### ISSUE TITLE
Cannot update Pointcloud realtime.

### ISSUE THREAD

**Issue by sanskar-sopho** [openMVG/openMVG#1019]
I want to use Sfm_Localization real-time, but it does not update point cloud. I also thought about IncrementalSfm for realtime localization but it doesn't work.

Is there any way of taking images from camera realtime instead of stored pictures in a folder?
Is the realtime localization module under development?

**Comment by rperrot** [comment]
Preamble : SLAM may not have same precision as actual pipelines (due to limited computation budget). 

What you want is realtime SLAM, we don't provide full SLAM support (ie: we don't do loop closure and model building) but only some kind of VO (Visual Odometry) for tracking of features across multiple frames , you can have a look at it here : 

https://github.com/openMVG/openMVG/tree/master/src/software/VO

We would enjoy having a full SLAM implementation, so feel free to contribute, it will be a big advance for the community.

**Comment by pmoulon** [comment]
Hi @sanskar-sopho,

> Is there any way of taking images from camera realtime instead of stored pictures in a folder?

Every binary in software are given in order to show how to use the underlying API:
- Feel free to modify the existing `openMVG_main_SfM_Localization` binary for your need.
You can easily change it in order to use a webcam, camera feed instead of the file from a directory and use `localizer.Localize(...)`.

> Is the realtime localization module under development?

We continue to make improvement:
- see WIP there https://github.com/openMVG/openMVG/issues/1009

As @rperrot said, on the other hand if you want a pure incremental SfM that does not have match before hand, it becomes related to SLAM.
- We don't have a SLAM backend yet but we would like to welcome anyone that would like to contribute and help on it.

**Comment by pmoulon** [comment]
Closed due to inactivity.
@sanskar-sopho
