### ISSUE TITLE
Limiting the number of threads used

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#1020]
Hi,

Is there a way to limit the number of threads that the openMVG binaries can use? For example, `openMVG_main_ComputeMatches` uses openMP for parallelization and occupies all available cores when run. Setting the `OMP_NUM_THREADS` environment variable doesn't seem to help. 

Thanks!

**Comment by pmoulon** [comment]
It must work.

Are you certain that you configure the OMP_NUM_THREADS variable correctly?

Can you tell which OS are you using?
Can you tell which parameter did you use for `openMVG_main_ComputeMatches`?

`export` or `set` must be the keyword to use.

**Comment by ssampang** [comment]
I verified that it was set by running `echo $OMP_NUM_THREADS` which printed 4. I'm running on Centos 7. This was what I called to run `ComputeMatches`: 
`/usr/bin/openMVG_main_ComputeMatches -i testJob/sfm_data.json -o testJob -g f -r 0.8 -n BRUTEFORCEHAMMING -f 1`. When I run this and observe progress with `htop`, I can see that all my cores are being used.

I set `OMP_NUM_THREADS` using the `export` keyword.

**Comment by ssampang** [comment]
Did some further investigation. It looks like `ComputeFeatures` adheres to `OMP_NUM_THREADS`. Looks like the problem is only with `ComputeMatches`

**Comment by pmoulon** [comment]
: So according your command line you are using the BRUTE_FORCE_MATCHER and so the problem could comes from here: https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/matcher_brute_force.hpp#L118

Since I'm using c++11 concurrency function there, I'm not sure that the `OMP_NUM_THREADS` will be taken into account (depending of the compilers c++ threading back end).

Please come back to me if you are able to isolate the problem.
