### ISSUE TITLE
[Question] Use of a calibrated stereo camera

### ISSUE THREAD

**Issue by chulminy** [openMVG/openMVG#1029]
Pierre 
I'm going to use images from a stereo camera and DSLR for 3D reconstruction. 
I will calibrate only stereo camera before collecting images. 
Since we knew the physical distance between right and left cameras in the stereo camera, we can make the constructed model on the physical scale. 
To do that, we need to make the calibrated parameters as constant.
It can make internal camera parameters as constant but I don't know how to fix the distance between the left and right cameras so as not to be tuned in the optimization step.

I found this and it seems to support what I'm going to do:
https://github.com/openMVG/openMVG/issues/580
Is there a way to do this experiment in the OpenMVG framework?
Thanks
Chul Min Yeum

**Comment by pmoulon** [comment]
Hi @chulminy 
Actual the master-develop branch does not support RIG.

- You can add a constraint in the BundleAdjustement to constraint the distance between the camera of your rig to be as close as your known baseline.

Or

- You can try https://github.com/openMVG/openMVG/issues/580 if the image from your camera rig are undistorted (pretty easy if you do a calibration step for your rig).

Or

- You can inject in the translation averaging step your known relative translation vector in order to constraint the rig cameras to be as close as your known distance.

**Comment by chulminy** [comment]
Thank you for the answer.  I will try that.

Chul Min
