### ISSUE TITLE
How to keep several  biedge connected  subgraphs  when the centers of images are available

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#1034]
The process named "Keep only the largest biedge connected subgraph" will  Keep only the largest biedge connected subgraph in the GlobalSfM and IncrementalSfM process.  While the center (gps coordinates) of the camera is available，the images with lower texture will be matched into several  disconnected subgraph and several of the largest biedge connected subgraphs shoud be kept.  
Anyway to resolve the problem.
Thanks.

**Comment by rperrot** [comment]
What is exactly your question ?

**Comment by whuaegeanse** [comment]
Images with poor texture will be matched into several connected subgraphs, while only the largest  subgraph will be kept after useing the function named "graph::CleanGraph_KeepLargestBiEdge_Nodes".
When the centers of images are not  known in advance such as knowing the GPS coordinates of the image，several of the largest  subgraph should be kept because of they sharing the same coordinate system.
So the question is how to keep several biedge connected subgraphs when the centers of images are available.

**Comment by pmoulon** [comment]
Note: - CleanGraph_KeepLargestBiEdge_Nodes is not used in the Incremental Pipeline.

I think your question is related to handling a scene where you have many disconnect graph. For the moment OpenMVG consider only the largest connected component for SfM. The BiEdged largest connected component is only used in the case of GlobalSfM since the loop constraints it detects is a requirements for GlobalSfM.

You can write a function that take as input a sfm_data and a matches file. You can then compute the various connected component and export the matches of the each connected component in a different match file.
Then you run the SfM pipeline of your choice on the produced matches file.
Then since your data are attached to GPS data you can merge each component in a single sfm_data file since they are all the same coordinate system. For the last task you can just create a sfm_data with all the poses and then triangulate the initial match file.

I already done a similar process in the past and it worked ok.

**Comment by whuaegeanse** [comment]
Thanks.
I will try it myself.

**Comment by pmoulon** [comment]
BTW:

- it could be useful to share back the binary that split a matches.X.Y file to a series of matches_COMPONENTID_SIZE.X.Y to the community.

- Then we can also think about making the match file a Incremental and Global SfM option so it will be easy for people to use such a scenario.

**Comment by pmoulon** [comment]
Now linked to https://github.com/openMVG/openMVG/pull/1135
