### ISSUE TITLE
ComputeFeatures Memory Usage

### ISSUE THREAD

**Issue by mchildsCO76** [openMVG/openMVG#1044]
I've having an issue on machines with 8 or 16GB of RAM with ComputeFeatures crashing after using all system memory on datasets with 1GB of JPG or more. I'm currently using all available cores (-1 to keep UI responsive). Is there a way to reduce the memory usage of ComputeFeatures similar to the cache parameter for ComputeMatches?

**Comment by rperrot** [comment]
The compute feature memory occupation depends on various parameters : 
- The size of the input image (Info : I can pass 21Mp images on a 16Gb mac without any issue, with some sets representing more than 6Gb - Since files are taken one at a time total size should not be an issue)
- The kind of feature you use (do you use SIFT or AKAZE ?)
- The preset you use (-p ULTRA gives you large memory usage, prefer -p NORMAL or -p HIGH)
- The usage or not of the -n option (If your having issues, do not use it)

**Comment by pmoulon** [comment]
Why do you not consider to make the parameter -n smaller?

**Comment by whuaegeanse** [comment]
Perhaps we can break an image into many blocks, and features be extracted in every block,   then the coordinates of features be made an offset with the topleft point coordinate of the block in the whole image. After using the above operation the features can be stored into file.

**Comment by mchildsCO76** [comment]
I have been able to run a few tests with different -n parameter values and noted the difference in memory usage. I will develop some heuristics based on the total input image size and the NORMAL/HIGH/ULTRA preset and automatically reduce the -n parameter value based on the available system memory so it can run without crashing if at all possible.

**Comment by mchildsCO76** [comment]
I wonder if it would be worth considering adding some kind of -n AUTO option that automatically reduces the -n value based on available system memory and the estimated memory usage? I'll do it externally for now.

**Comment by whuaegeanse** [comment]
When we make the parameter n smaller,  we can not make full use of the the cpu of the computer. But  when we make the parameter n bigger, we may do not have enough memory. I suppose the best way is break the image into many block and we can extract features in every block of the image.
We can add a function named `Describe2` and block size (width=2000, height=2000)  into the class named `Image_describer`.

**Comment by pmoulon** [comment]
The thing about memory estimation is that if you are running multiple process you can have high risk that the free memory estimation at a given time is not true in 10 sec....
But if you are using only one process and you are sure, you can precompute the used memory and compute the number of thread you can use.

If you are on Linux, you can use [parallel](https://www.gnu.org/software/parallel/man.html) and create a new binary that extract the features for only one image.

**Comment by mchildsCO76** [comment]
For my estimate I based it on a combination of the total system physical memory and the current available memory. Obviously you will typically have extra memory to page to on disk as well.

From my tests on HIGH it seems the extra max memory usage per thread added was approximately equal to the number of total pixels in the images. I compute a maximum target memory usage of the higher of 75% of the available physical memory and 25% of the total physical memory, with a floor of 2GB. The thread count to run is then calculated by dividing that by the total pixel count from all images and clamping to the range [1, # cores - 1].

I haven't run tests yet, but I guessed at heuristics for ULTRA as 3 times the memory of HIGH and NORMAL as 2/3rds the memory of HIGH.

This approach allows the thread count to scale based on system memory and should always be able to run if you don't fire up a bunch of other processes and use all of the system memory + page file.

I'm not sure of the internals of OpenMVG for memory handling, but in my code for things like image grids or other large collections of data I have a smart grid class that can switch to a memory mapped file when available memory is low. The data is addressable by row, with the minimum memory view being at least one row of data in size. Typically on 64-bit Windows if you do have to go to a memory-mapped file the entire thing can be memory-mapped as you have tons of address space, so you still work with a single pointer. But even on low-end systems you can work with huge volumes of data seamlessly (as long as your disk has space for the mem mapped files when needed).

**Comment by rperrot** [comment]
> From my tests on HIGH it seems the extra max memory usage per thread added was approximately equal to the number of total pixels in the images. 

With NORMAL and HIGH, the memory complexity is in O(n) where n is the number of pixel. But be careful there is a hidden constant (it should be at least 7n in the default setting - we build octave with slices, each pair of slice is subtracted, so we have in memory several time arrays of the size of the image). 

With ULTRA, the image is upscaled, so the number of pixel in the slice is 4times the number of pixel of a slice si 4 times the number of pixel of the input image. 

On modern OS, memory is compressed (OSX is a perfect example), but you don't know the exact compression scheme. That means that available memory is an information that is not so relevant. 

> I suppose the best way is break the image into many block and we can extract features in every block of the image.

That's not simple, because we usually don't work at image level but with pyramid of images.  Using pyramid on blocks of images is not the same thing as using pyramid on a single image. You must include borders to the blocks to ensure that the higher level of the pyramid covers the same region as the input image. 

That means for big pyramid lot's of extra data and many redondant computation. Moreover, with sift you have borders that could not be computed (some pixels around the image), because of the size of the filters. If you break image in blocks, you increase the data that is not computable, so it's not just a split in contiguous blocks that must be use but a split in overlapping blocks, resulting again in a high redundancy of the computation. While this strategy could helps using large images into low memory system, this may results in a very slow method. 

We can think about a hybrid block system (blocks would be at the processing of a slice), but it needs a serious study before coding it.
