### ISSUE TITLE
Merging various SfM_Data scenes?

### ISSUE THREAD

**Issue by Shangareer** [openMVG/openMVG#1047]
Hi,
I get about 20,000 images of a large scene, putting them in reconstruction all at once is too slow even though I give a sequenced matches file. Now I divide them into 5 parts and reconstruct them on 5 computer respectively. I master the methods of merging their result files "sfm_data.bin" and transforming their point clouds to a uniform coordinate, but the position of points have some deviations. I want to deal this problem with Bundle Adjustment.I'm not sure if the file  "sfm_data_BA_test.cpp" is for doing this, if yes, how to use it , if no, is their any module of OpenMVG to do this?

**Comment by pmoulon** [comment]
Hi,

If I understand well you want to merge many sfm_data scene.

-  Does your sfm_data scene share some camera positions?
I ask those question, because if you don't have common cameras or common 3d points between the various scenes, the merging and BA will not make them have a better fit since no constraints will be there between the 3d submaps.

If your sfm_data share some camera positions, you can compute a similarity transform and merge them.

- If your scene is too big, you can compute the matches on downsampled images.

**Comment by Shangareer** [comment]
My dataset is a loop scene of a street. I divide them into 3 parts as shown in the picture for example. There are common cameras between neighbouring point clouds and I have computed their transforming matrix with PCL. By transforming all point clouds to the coordinate of pointcloud_1, the result should be  Fig.1, but it turns out to be Fig.2. You can see that pointcloud_1 and pointcloud_2 are not closed. Can I use BA to solve this problem?
![question](https://user-images.githubusercontent.com/28132894/30214966-e4f54e1e-94e0-11e7-9d9c-2c0c90b3fad9.jpg)

**Comment by pmoulon** [comment]
1. FYI, you have also tools in OpenMVG to compute an affine transform and apply it to an existing sfm_data scene.
- see: https://github.com/openMVG/openMVG/blob/master/src/openMVG/geometry/rigid_transformation3D_srt.hpp#L20
- and https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_transform.hpp#L24

2. You can run the BA by providing as input the output of your registration.

3. I would advise you can merge the match file for your scene 1,2,3 and then run GlobalSfM. It should be quite fast even with 20,000 images. I mean the major blocking point you got was to run the matching. So since you done it, why not just merge the matches and run the SfM process on it.

**Comment by pmoulon** [comment]
@Shangareer  Any feedback?

**Comment by Shangareer** [comment]
Sorry for my tardy reply. In fact the matching step didn't take time because I assigned a file that contains pair lists like 1-2, 1-3, 2-3, 2-4, 3-4, 3-5. I tried to run GlobalSfM but the sfm_data.bin was not generated.

**Comment by pmoulon** [comment]
You can try to have more inter picture coverage.
OpenMVG provide you a tool to do that. You can use the `-v X` option on `main_ComputeMatches`. X the overlapping value you want. I would advise a value between 4 and 10. Since Global SfM requires at least image triplet the X value must be at least superior to 3.

So in your case you have sfm_data.bin since the SfM process have failed since no image triplet have been found.

**Comment by Shangareer** [comment]
Thanks, I will try it and reply you some days later.

**Comment by pmoulon** [comment]
@Shangareer Any feedback?
