### ISSUE TITLE
[Question] Scalable Modeling Solution with openMVG

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1071]
I have been using openMVS for modeling with openMVG.
openMVS works great till 60-70 images, but it crashes at Densepoint as soon as the number of images crosses 70. 
Is there a more scalable solution I can use with openMVG?

**Comment by pmoulon** [comment]
Please note that here the scalability problem is not coming from OpenMVG but from OpenMVS that cannot process huge dataset due to memory limits.

Solutions that you could try:
- Try to process your dataset with MVE dense surface computation (OpenMVG2MVE already existst)
- You can increase your RAM amount or swap RAM to process the dataset with OpenMVS or simple process the dataset with the subsampling option for the dense point computation and user larger image at the latter stage since it consumes less memory.
- You can cut the OpenMVG scene in cluster and process each cluster in OpenMVS. See usage of `main_ComputeClusters`.

BTW,
The best would be to implement and use "Scalable Surface Reconstruction from Point Clouds with Extreme Scale and Density Diversity", C. Mostegel, R. Prettenthaler, F. Fraundorfer and H. Bischof. CVPR 2017.

**Comment by Ntweat** [comment]
openMVG works like a charm,  I have tested it with 600+ images, never crashed. 
openMVS is crashing. I have a 32GB RAM, 64 GB SWAP, GTX1080Ti GPU, i7-7700K CPU. Still, openMVS just stops. 
1. MVE does not give complete surfaces.
2. I will see ```main_ComputeClusters``` . Is there a way to merge them later?

I will read the paper. 👍 Lets see.

**Comment by pmoulon** [comment]
2. No, you have to perform the merging on your side.

**Comment by ManishSahu53** [comment]
Hey @Ntweat, I was in a similar situation few days ago. I want to process large number of images (~10,000). So I first decided to process a subset of my dataset. Then proceed with the complete dataset. OpenMVG works very well. You should use clustering option in OpenMVG to divide your sfm_data.bin with number of parts.  You can easily create then dense point cloud in openMVS taking individual clusters. I then used points2grid tool to convert dense point cloud to DEM. I thought my memory and large dataset problem is solved but then I noticed that there are some variations in the DEM data where the individial point cloud meet. Intergrity of DEM is not maintain at the junction area. See the image below there are two values of DEM at same point. Ideally these should be same or minimun.

![image](https://user-images.githubusercontent.com/27155127/31053922-e0a65b14-a6c4-11e7-91dc-d1cb20ba3199.png)

**Comment by Ntweat** [comment]
Impressive @ManishSahu53 
I have a 32 GB RAM, 64GB swap, i7 7700K, 1080 Ti. RAM is not a problem. 
A problem which I do have is that I am trying to create an automated pipeline, give it any video or images and it gives you the model. No human intervention.

Does points2grid need human intervention?

**Comment by ManishSahu53** [comment]
@Ntweat  Points2grid is completely automated. No need for human Intervention. 
Can you tell why you had so much of swap? Will this large swap help in memory issue?

**Comment by Ntweat** [comment]
@ManishSahu53 Thanks a lot !! I will look into it. 
Answer to swap question: Nope, with so much RAM and GPU my machine is hardly able to utilize them fully. It has never gone to swap. I keep SWAP = 2xRAM just cause I have been using Linux since 2007 and that what I have been following.

**Comment by pmoulon** [comment]
Can we close the issue?

**Comment by Ntweat** [comment]
I havent been able to test it.
I will close it now, will reopen if needed
Thanks
