### ISSUE TITLE
Can using (roughly) accurate GPS priors increase runtime of IncrementalSFM?

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#1080]
Hi,

I'm using the modified version of @hcjghr's `openMVG_main_SfMInit_ImageListing` that allows providing GPS priors via a text file to add GPS priors to my `sfm_data.json`. I then run `openMVG_main_IncrementalSfM` with the `-P` option, and a video that took ~300 seconds without the priors is taking ~900 seconds when using the priors. Does this seem reasonable/plausible to you?

The images and GPS priors were obtained from a consumer drone. The priors look roughly accurate but obviously won't be very precise (especially with altitude). I just wanted to check in and see if this seems abnormal to any of you. I noticed in another issue @pmoulon mentioned that MVS doesn't like to operate in world coordinates. Would it help IncrementalSfM if I centered the GPS priors first?

**Comment by pmoulon** [comment]
Hi @ssampang,
Using GPS must not change too much the speed.
Since the feature graph is the same the time to process the dataset should be similar.

Did you know the accuracy of your GPS data?
- some values must be displayed at each BA iteration, can you share it the final accuracy fitting?

You can try to center GPS prior to see the impact.

If your graph is quite dense you can process your dataset with `openMVG_main_GlobalSfM -P`.

**Comment by ssampang** [comment]
Entire output of IncrementalSfM:
With GPS: https://gist.github.com/ssampang/f9f275338afeb5aa43e133dc8f24d2f5
Without GPS: https://gist.github.com/ssampang/54e694f80f529ae385685d8a4b4a7cbc

> Did you know the accuracy of your GPS data?

The GPS data was taken from a drone, so the precision will not be great, but the general shape of the flightpath is the same, and indeed looks the same when viewed in meshlab. Here are links to the [flightpath](https://drive.google.com/file/d/0B3YrWttrVZW7V0ZDMGpwME1VUTg/view?usp=sharing) and [outputted pointcloud with poses](https://drive.google.com/file/d/0B3YrWttrVZW7aWNGbFQ5S2dNSzQ/view?usp=sharing).

**Comment by pmoulon** [comment]
Can you make a fast test when your translate your GPS data to have one equal to 0 and see if you still have this undesirable effect (slowdown)?

**Comment by pmoulon** [comment]
From the log I see that the final accuracy of the GPS fitting is (If your unit is in meters, Does it looks like decent due to accuracy of onboard GPS? -> +- 5meters ):
```
Usable motion priors: 1
Pose prior statistics (user units):
 - Starting median fitting error: 4.74918
 - Final fitting error:
	 min: 0.457859
	 mean: 5.21711
	 median: 4.82716
	 max: 13.5301
```

Also from the LOG I see that BA is slower when we activate the GPS priors, between 2 or 6 times slower. The reason is due in part because we are adding constraint from camera position to be as close as possible to the GPS known position.

The `-P` option activate a non rigid GPS fitting. You can also have a rigid fitting if you need.
See here: https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#for-sfm-to-xyz-gps-registration

Since OpenMVG pipeline are quite flexible it could be also easy for your to think to this:
- perform a classic SfM (without GPS)
- then perform a BA on the resulting scene with non rigid GPS fitting.
This way only one BA step is added to your processing pipeline at the end of the process.

**Comment by ssampang** [comment]
Sure I'll test the translated GPS today. I don't particularly need a rigid fitting. My main motivations for using GPS priors are:
1) I thought it may accelerate the convergence of BA and essentially result in faster processing
2) Aid BA when the video is especially low quality, and may fail without GPS

Other than this, I would actually prefer to not rely too much on GPS in case it has errors.

**Comment by ssampang** [comment]
I have suspicions about bugs that I'd like to clear up before testing the translated GPS coordinates (because they may depend on the bugs). I will post results early next week.

**Comment by pmoulon** [comment]
Any new feedback?

**Comment by ssampang** [comment]
Sorry, I noticed odd behavior when using @hcjghr's branch, so I took the time to roll my own code that modifies `sfm_data.json` on its own after running `main_SfMInitImageListing`. With [this version](https://gist.github.com/ssampang/182f365f51ea8b848402a70819490898), `IncrementalSfM` still takes 916 seconds. This was after subtracting the location of the first camera from the locations of all cameras. Perhaps I need to normalize the scale as well?

**Comment by ssampang** [comment]
Okay, normalizing the scale fixes the issue! I can initialize with GPS coordinates and `IncrementalSfM` runs in the same amount of time now. I only tested it once, but `GlobalSfM` seems to run in 2/3 of the time. Unfortunately it generates a point cloud about 2/3 as dense as `IncrementalSfM` though.

**Comment by ssampang** [comment]
As mentioned in #1080, this issue was solved by scaling down the gps coordinates to have one camera centered at the origin and have the distance to the rest of the cameras normalized by the avg distance.

**Comment by pmoulon** [comment]
Thanks for the report.
We can think to add an option to normalize/un-normalize the scene during the BA.

**Comment by hcjghr** [comment]
Hi,

@ssampang can you elaborate a bit what kind of odd behavior did you notice? Also, you said that normalizing the scale helps. Do you have the code in any of the branches online so I can quickly test it as well?

thanks

**Comment by ssampang** [comment]
@hcjghr I had 147 images, and 147 sets of gps coordinates, but the code in your branch skipped the first image in my dataset when adding gps coordinates to `sfm_data.json`. After noticing this and realizing that I wanted to make some modifications to the gps coordinates (normalization), I thought it'd be faster to just roll my own version. Unfortunately, the code is mixed in with some of my company's proprietary code, so I can't share it. It's pretty simple though - here's the pseudocode:
```
def normalize(gps_coords):
  gps_0 = gps_coords[0]
  avg = 0
  for g in gps_coords:
    avg += magnitude( g - gps_0 )
  avg /= len(gps_coords)
  res = []
  for g in gps_coords:
    res.append( (g - gps_0)/avg )
  return res
```
