### ISSUE TITLE
simply a question:  performance and quality vs sony XZ1

### ISSUE THREAD

**Issue by albertVideo** [openMVG/openMVG#1084]
Hello,

May be this place is not the right place to ask such a question, and sorry for that, but i do not know a better place.

I am using for a while openMVG/openMVS and have done more than 20 3D reconstruction of people and object. it works very well and i am satisfied.

I have seen on some marketing stuffs that Sony recently launched the Xperia XZ1 with 3D reconstruction using the principles of photogrammetry. I am very impressed.

There is one thing i do not understand is how can they 3Dreconstruct so fast, in few minutes, and so well.  

For the performance: I have 4 cores i7 processor, 16GB memory  and i need between 30 minutes and 1 hour (to compare to the snapdragon proc including a GPU)

For the quality:  when i see their marketing stuff there is no need to retouch the 3D model/object.

Thank you for your attention and sorry if it is not the right place

**Comment by rperrot** [comment]
There are lots of things that helps to make things faster : 
- The camera is calibrated (camera intrinsics are all known in advance, so no refine is mandatory) ;
- Only one camera is supported (openMVG is far more general) ;
- The phone has predefined mode for reconstruction (this introduces some priors on the outcome and some optimization could be made based on this, for example) ;
- The underlying algorithms are not the same (features may not be as robust since scale is not relevant for example, and the whole reconstruction is not elaborated using the same requisites) ;
- The quality may not be pair with openMVG ;
- ... 

Maybe one of the method used in the phone for 3d face scanning rely on this work: 
http://lgg.epfl.ch/publications/2015/AvatarsSG/

**Comment by pmoulon** [comment]
As @rperrot said, the sony XZ1 app is designed to run only for one usage.

OpenMVG SfM is designed to work on unordered image sequence.
The sony XZ1 is designed to do SLAM with Inertial integration (SLAM + IMU sensor fusion). Since they know that every image is coming in a given order they can just perform feature tracking instead of feature matching.

So the main difference are:
- type of processing (sequence(ordered) vs unordered)
- complexity of feature matching (tracking vs matching)
  - OpenMVG have some experimental tool for tracking [here](https://www.youtube.com/watch?v=kJQqp0OHWQE)

Note that if you want to process your dataset faster with OpenMVG you can:
- reduce the image size to lower the number of feature per image.
- you can process the dataset as a ordered sequence by using the `-v` option on `main_ComputeMatches`.

So as a conclusion:
- we are trying our best to extend OpenMVG to fit most of the usage that the user can think about.
- we don't have a SLAM backend yet but feel free to help. (As I said we already made some sample for feature tracking).

**Comment by albertVideo** [comment]
Thank you for your  valuable information.
As i said i am greatly satisfied with openMVG/openMVS even if i am looking forward the gpu.

**Comment by pmoulon** [comment]
Feel free to help to bring more GPU.
Please note that preliminary work are there for GPU binary descriptor matching: https://github.com/openMVG/openMVG/commit/077e8391f7f0233e0e30ba120cdbc95b31982e13

**Comment by pmoulon** [comment]
Feel free to close the issue when you got your answer.

**Comment by albertVideo** [comment]
thank you, if i were able to provide GPU code, i would have done it a long long time ago
