### ISSUE TITLE
main_Localization is crashing when using single intrinsics and camera model other then `Pinhole_Intrinsic_Radial_K3`

### ISSUE THREAD

**Issue by tomas789** [openMVG/openMVG#1107]
When I build a reconstruction with camera model other then `Pinhole_Intrinsic_Radial_K3`, I cannot use "-s 1" single intrinsics flag in `main_Localization`. Problem is caused by [main_SfM_Localization.cpp:275](https://github.com/openMVG/openMVG/blob/master/src/software/Localization/main_SfM_Localization.cpp?utf8=✓#L275). Loaded camera model is `dynamic_cast`ed to `cameras::Pinhole_Intrinsic_Radial_K3` but it is not checked whether it does return `nullptr` or a valid pointer. It then crashes on [main_SfM_Localization.cpp:332](https://github.com/openMVG/openMVG/blob/master/src/software/Localization/main_SfM_Localization.cpp?utf8=✓#L332).

I would suggest at least failing nicely with error message. Or ideally, support all camera models.

**Comment by pmoulon** [comment]
Thanks for the report.
I will have a look to it soon and come back to you for testing ;-)

**Comment by pmoulon** [comment]
Hi @tomas789,

I updated the code in the develop branch.

- Now the code support all possible camera models if you are using the `-s` mode.

In the case of the sfm_data scene contains many camera model (fish eye + pinhole + spherical), it's not trivial to ask the user which camera type he want to register.

Note: By default the `unknown` intrinsic mode will continue to use a pinhole camera with K3 distortion. Feel free to do a PR in order to use any camera model that are compatible with the pinhole camera type.

Please test the branch and close the issue once you have validated the fix ;-)

**Comment by pmoulon** [comment]
@tomas789 Can you open an issue with the topic `[software] Add the ability to specify the camera model for main_Localization`?

I'm closing the issue since the reported problem is solved.
