### ISSUE TITLE
Cannot run make install with non-root user since EIGEN_INCLUDE_INSTALL_DIR has been renamed

### ISSUE THREAD

**Issue by luxigo** [openMVG/openMVG#1117]
Hi Pierre !

You are doing a great job, thanks again :-)

Looks like while updating Eigen something has been broken in cmake files and cmake tries to install it in the root directory.
```
CMake Error at third_party/eigen/Eigen/cmake_install.cmake:44 (file):
  file cannot create directory: /eigen3/Eigen.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  third_party/eigen/cmake_install.cmake:37 (include)
  third_party/cmake_install.cmake:65 (include)
  cmake_install.cmake:84 (include)
```
In this commit 0bad788ab3cb06b475fd3c12484e224d1ff7df3e EIGEN_INCLUDE_INSTALL_DIR has been renamed INCLUDE_INSTALL_DIR 

The real problem is probably elsewhere, but reverting to EIGEN_INCLUDE_INSTALL_DIR does the job as long backward compatibility is provided by eigen here:
https://github.com/openMVG/openMVG/blob/31c94e7ae83f7e8073b6fde915c85459bcd68414/src/third_party/eigen/CMakeLists.txt#L65

I would prefer to fix the real issue but as temporary workaround we got this.

Best regards,

Luc

**Comment by pmoulon** [comment]
Can you see if I fixed this or not in the develop branch?
I made this change: https://github.com/openMVG/openMVG/commit/0bad788ab3cb06b475fd3c12484e224d1ff7df3e#diff-3ae5324d418c334c9aa264ea200ffa9fL110

**Comment by luxigo** [comment]
I'm talking about the up to date develop branch.

This commit (0bad...) for which a link was included in my comment above is the commit where the renaming occurs.

Looks like somehow at install time an empty string is used instead

Probably a problem with Eigen cmake files, despite the "deprecation" message coming from them

I cannot not point it out better now.  5am, I give up.

As long as backward compatibility is provided by Eigen, it's a waste of time.

**Comment by srivathsanmurali** [comment]
Hi,
I also see this bug when I try to install OpenMVG.
I think this is because Eigen doesn't handle the Install directory with backward compatibility well.
When INCLUDE_INSTALL_DIR is set in
https://github.com/openMVG/openMVG/blob/e4b686a902dc9f70bd3589e27c1026c39d721558/src/third_party/CMakeLists.txt#L108-L112
it goes down a weird if clause inside the Eigen cmake config
https://github.com/openMVG/openMVG/blob/31c94e7ae83f7e8073b6fde915c85459bcd68414/src/third_party/eigen/CMakeLists.txt#L65-L86

Since INCLUDE_INSTALL_DIR is set, control goes to the else statement, where it is reset to ${CMAKE_INSTALL_INCLUDEDIR}/eigen3.
This breaks the OpenMVG's install.

I also recommend we should stick to using EIGEN_INCLUDE_INSTALL_DIR and not INCLUDE_INSTALL_DIR until eigen fixes this.

**Comment by pmoulon** [comment]
@https://github.com/openMVG/openMVG/pull/1118 Have been merged.
Thx for your additional feedback on this @srivathsanmurali ;-)

**Comment by AndresDuque** [comment]
I am having the same issue "INCLUDE_INSTALL_DIR must be relative to CMAKE_PREFIX_PATH" in Fedora 32 when using mingw64-cmake in my CI on GitLab. The install-dir I am getting is this one: /usr/x86_64-w64-mingw32/sys-root/mingw/include. Could it be an error of access rights?
