### ISSUE TITLE
Can't find .sln file

### ISSUE THREAD

**Issue by benjyvc** [openMVG/openMVG#1121]
Hello Pierre,

Here's a snip showing where I pointed CMake to for building binaries:
![image](https://user-images.githubusercontent.com/14839594/31855973-2b5ac54a-b684-11e7-83a9-fc3f3b970b12.png)
And here is what's in that directory:
![image](https://user-images.githubusercontent.com/14839594/31855982-56acf524-b684-11e7-9243-0367253b0384.png)
 Many thanks for your time!

**Comment by pmoulon** [comment]
Did you press` Generate`?

**Comment by benjyvc** [comment]
It's been too long a day, I didn't. Went off path with the instructions, now see it. Whew. Thank you!

**Comment by pmoulon** [comment]
No worries!

**Comment by benjyvc** [comment]
Pierre,

I opened the .sln into VS2015, saw progress bars, was awaiting something to happen that would allow me to "Change the target to Release", and got this screen:
![image](https://user-images.githubusercontent.com/14839594/31856030-aa951bf2-b685-11e7-9e81-b4bec0255b7c.png)

I have VS Community 2015, saw it was some version of 14, so in CMake I selected Visual Studio 14 2015. Am I getting this message because it's somehow linking to a commercial version? Sorry to open this up again.

**Comment by benjyvc** [comment]
Okay, think I sorted that out. I had to switch to Solution Explorer, hunted a bit and found Release as an option to default Debug. It's now building. Thanks again, especially on a Saturday!

**Comment by garimss** [comment]
![OPENMVG](https://user-images.githubusercontent.com/16250644/61278409-bc00da80-a7e6-11e9-9791-45f9cc51113a.png)

after it says succeed build. I get the following issue.

@benjyvc  how to did it work for you after successful build?

**Comment by pmoulon** [comment]
@rperrot Any idea of what's going on here?

**Comment by rperrot** [comment]
That's not an issue, the build was successful, but @garimss try to launch the ALL_BUILD project which does not contains any executable (it's a CMake special project). 

@garimss You just have to build the solution Ctrl+Maj+B and look at the "Output" tab at the bottom of the window. At the end of the process you have the number of correct build and the number of failed build. If everything is ok, the number of failed build should be 0.

**Comment by garimss** [comment]
Thank you @pmoulon and @rperrot. after compiling this pops up by itself and out put windows says Build: 91 succeeded, 0 failed, 0 up-to-date, 0 skipped.

Now how to start with SFM. Do I need to go to exe directly or have to run through command line or I will appreciate if you can share a link if there is any other getting started guide which I can refer other than the openMVG documentation!

I am just a beginner here and looking around to convert a 3d from a leg video from different angles.

Any help will be appreciated. Sorry for any inconvenience! Thanks again.

**Comment by garimss** [comment]
when I run sfm, I get the below error: also please see attached picture? What is the reason for this?
![2](https://user-images.githubusercontent.com/16250644/61354972-ebc2e780-a8a5-11e9-8f05-8a25c332bee1.png)


There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
5. Colorize Structure

The input SfM_Data file "D:\git_hub\ralph\openMVG\build\software\SfM\output\reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "D:\git_hub\ralph\openMVG\build\software\SfM\output\reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "D:\git_hub\ralph\openMVG\build\software\SfM\output\reconstruction_sequential/robust.bin" cannot be read.

**Comment by pmoulon** [comment]
OpenMVG is warning you about this `There is no defined intrinsic data in order to compute an essential matrix for the initial pair.`.

So basically your camera model is not recognized by OpenMVG. You can consider add your camera to the Camera sensor database or use the `-f FOCAL_IN_PIXEL` option on SfMInitImageListing.

Camera Sensor database: https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt

Computation of the Focal Length in pixels: https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata
Else you can approximate it by using -f `Value=max(w,h)*1.3`.
It will simulate the focal length for a 90 degree FoV camera.

**Comment by garimss** [comment]
@rperrot and & @pmoulon  Hi, I am wondering how to extract matched points and with coordinates. And also How to build tracks. Sorry for being demanding. I am just a newbie here. And trying to solve a 3d leg problem where I need to get exact matches and may be with few best matches and than have to extract the point information.

Also wondering is by using tracks I can visualize image by image matches. But not sure how do use the code.

There is no specific guideline given. I am curious to know the method to use the code given on https://openmvg.readthedocs.io/en/latest/openMVG/tracks/tracks/

Is this code needed to be include in .cpp files and build over and than run through SFM or just need to add this code in sequential or/& Global pipeline code.

I will appreciate your quick response. Thanks
