### ISSUE TITLE
How to input camera poses?

### ISSUE THREAD

**Issue by otepmong** [openMVG/openMVG#1130]
Hello,

We are trying to create a 3D object using OpenMVG/MVS using array of cameras in a fixed position.  We notice that the camera poses and orientation of the output mesh are dependent on the object being scanned.  Some artifacts were introduced due to error of the camera pose computed.  We thought that we can fix the artifacts and orientation of the output by inputting the camera poses from a known good scan.

Here is the experiment we tried so far.

1. Run through OpenMVG/MVS pipeline and output camera poses  (Pose3 class: two attribute: Mat3 rotation__; Vec3 center__;) calculated in Incremental_SfM to a file cameras.txt
2. Input cameras.txt and run through the same set of images.  We load the camera poses in main_SfMinit_ImageListing, bypass Incremental_SfM and  pass the poses along.

The both sparse cloud outputs look good, but the output mesh of the camera pose input does not.  It is a bit more bumpy see pictures below.

![compare_post1](https://user-images.githubusercontent.com/7981417/32145502-f3ba9daa-bc86-11e7-8275-84a75042bb33.jpg)
![compare_pose2](https://user-images.githubusercontent.com/7981417/32145503-f3d3bbb4-bc86-11e7-9560-2ffafb8c8fcd.jpg)

Perhaps, we are missing additional information needed to be input.  Would be happy to share the set of images and our hack code.  

Suggestions, please.    Thank you.

**Comment by yuyou** [comment]
It would be more helpful if you could show us the content of the cameras.txt and the camera mode defined in your pipeline.

**Comment by otepmong** [comment]
Hi Yuyou,

I am not aware of camera mode settings.  Where can I find the settings and what value I should I use?

 Attached is the camera file contains the calculated locations of the cameras (from the OpenMVG Pose structure), each row containing 13 numbers: camera #, camera center x, y, z, and camera rotation matrix R00, R01, R02, R10, R11, R12, R20, R21, R22. 

[cameras_0829.txt](https://github.com/openMVG/openMVG/files/1429293/cameras_0829.txt)

Here is the plot of the array of cameras.

![image](https://user-images.githubusercontent.com/7981417/32203599-8b40364c-bda1-11e7-8614-f6ed1fb99db8.png)

Appreciate any pointers.. Thank you.

**Comment by pmoulon** [comment]
Can you elaborate what have you done for 2?

Here some questions:
1- Did you compute with shared intrinsics or individuals intrinsics?

2. About your step too. I think you have done the following.
-  ComputeFeatures, and ComputeStructureFromKnownPoses with a previous sfm_data to get some camera poses and intrinsics.
  - Since ComputeStructureFromKnownPoses use only information from triplet the refinement cannot be optimal.
  - Did you know that for this step you can also triangulate a match file. So you will have more points and so the BA at this step will perform better. Seethe `-d` option (develop branch). https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeStructureFromKnownPoses.cpp#L93

I think the process is no perfect since:
1. the calibration from 1 is not optimal (the features certainly does not cover the whole image area and some imprecision remains for the poses and intrinsics)

Moreover you do not need to use a cameras.txt. You can export a previous sfm_data.bin to a sfm_data.json with camera view, intrinsics and poses information and use it with another image sequence.

**Comment by otepmong** [comment]
Hello Pierre,

I computed the individual intrinsics k in a separate step. 
1.  Then I use k in step 1.  (ImageListing, ComputeFeatures, ComputeMatches, IncrementalSfM ).  
       I wrote each camera position and rotation matrix to a file (cameras.txt) from IncrementalSfM.
2.  Using the same k intrinsics, cameras.txt, and same set of images in 1.  We run
(ImageListing, ComputeFeatures, ComputeMatches, GlobalSfM, ComputeStructureFromKnownPoses, openMVG2openMVS (and the rest of OpenMVS).  
We inject camera pose (cameras.txt) into ImageListing and pass the info along to ComputeStructureFromKnownPoses.

Can you clarify "triplet" information?  What does "BA" stand for?  

Should we bypass ComputeMatches and GlobalSfM for step 2?  We can try to turn on -d option to see if we get a better result.

Please let me know what option I can use to export sfm_data.bin to sfm_data.json and How to import it into the OpenMVG pipeline.  Currently we modified the code to do this.

Thank you.

**Comment by pmoulon** [comment]
> Can you clarify "triplet" information ?

A triplet is a sequence of three data. By default ComputeStructureFromKnownPoses keep only the 3d point that are seen by at least 3 cameras.

> What does "BA" stand for ?

Bundle Adjustment (the non linear step that move the camera parameters and the 3d points in order to reduce the reprojection error). This step is the process used to refine the scene.

**For the step 2 you can bypass the GlobalSfM process.**

Here how to do it.
So first suppose that you have made one calibration. So you have a sfm_data.bin with camera parameters (intrinsics, camera poses and 3d points) <- the result of any SfM process.

Then you want to use those camera poses for triangulating another image dataset (In your case you can do that since your camera rig is not moving). Here I suppose I processed a dataset called otepmong_scan_images_gold_top_reconstruction and that I want to use those camera poses for a dataset called otepmong_scan_images_hello_kitty_reconstruction
1. Extract the camera information to a json file
`
openMVG_main_ConvertSfM_DataFormat -i <PATH>/otepmong_scan_images_gold_top_reconstruction/reconstruction_sequential/sfm_data.bin -I -V -E -o <PATH>/otepmong_scan_images_hello_kitty_reconstruction/camera_poses.json
`

2. Edition of the image path (in order to make the new exported project handle the new image views)
You open the file camera_poses.json and edit the field `root_path` to point towards the new image dataset. i.e ->
`"root_path": "/media/pierre/otepmong_scan_images_gold_top/",` will be updated to
`"root_path": "/media/pierre/otepmong_scan_images_hello_kitty/",`

3. Computes some matches for the new scene and triangulate the matches
- Run ComputeFeatures by using the file <PATH>/otepmong_scan_images_hello_kitty_reconstruction/camera_poses.json as input
- Run ComputeMatches by using the file <PATH>/otepmong_scan_images_hello_kitty_reconstruction/camera_poses.json

4. Triangulate the computed matches
```
openMVG_main_ComputeStructureFromKnownPoses 
-i <PATH>/otepmong_scan_images_hello_kitty_reconstruction/camera_poses.json
-d -m <PATH>/otepmong_scan_images_hello_kitty/matches/ 
-f <PATH>/otepmong_scan_images_hello_kitty/matches/matches.f.bin 
-o <PATH>/otepmong_scan_images_hello_kitty/sfm_data_structure.bin
```

-> Tada... You obtained some 3d points without re-rerunning SequentialSfM or GlobalSfM ;-)
Only the matches and the triangulation of the matches have been done for the second dataset.


This step will allow you to jump from: 
![cameras00](https://user-images.githubusercontent.com/3235050/32644657-cb23552a-c597-11e7-9353-84fb282e5838.png)
![points01](https://user-images.githubusercontent.com/3235050/32644658-cb365b70-c597-11e7-81d8-631b6e9e6a2c.png)

Activating the option `-b` on `openMVG_main_ComputeStructureFromKnownPoses` allow to refine the camera parameters and 3d scene.

**Comment by yuyou** [comment]
@pmoulon It is clear. You should consider adding this as a new tutorial under the [doc](http://openmvg.readthedocs.io/en/latest/software/softwares/).

**Comment by pmoulon** [comment]
@yuyou The feature about using existing camera poses is already demonstrated in the tutorial_demo and the Sequential and Global python pipeline somehow.

We clearly need to enhance the documentation and samples ;-) but it takes time to do.

I will close the ticket due to inactivity. @otepmong Feel free to re-open the ticket if needed.
@yuyou Feel free to open a ticket about the documentation with some graphics in https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/ComputeStructureFromKnownPoses.rst
