### ISSUE TITLE
Wrong "id_intrinsic" ID in "sfm_data_expanded.json"

### ISSUE THREAD

**Issue by yuyou** [openMVG/openMVG#1132]
Hi

When using "`openMVG_main_SfM_Localization`" with the argument "`-s|--single_intrinsics`" to generate new "`sfm_data_expanded.json`" , the expected output would save the new "`id_pose`" but use the existing "`id_intrinsic`", as they share the same camera model. 

But the "develop" branch outputs wrong "id_intrinsic" (which should be "0" in the case of a single intrinsic).

```
  "id_intrinsic": 60,
  "id_pose": 60
```

**Comment by pmoulon** [comment]
You are right, thank you for the bug report.

I forgot to initialize the id_intrinsic if the option `bUseSingleIntrinsics` is true there https://github.com/openMVG/openMVG/blob/778daa5811017afec551aa9be1b2919393e80895/src/software/Localization/main_SfM_Localization.cpp#L417

This bug is fixed be https://github.com/openMVG/openMVG/commit/1da4833b3dfa1544c28396063826b010c2aedf3b

I initialize the `id_intrinsic` to the intrinsic id of the first view (since the user can have defined at another value than 0).

Can test the fix in the develop branch and close the issue when you have verified that the bug is fixed on your side too?

**Comment by yuyou** [comment]
Tested and the bug has fixed. Thanks.
