### ISSUE TITLE
[Question] SIFT parameters

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1149]
Is there a way to adjust the SIF parameters?
Like number of octaves, Sigma, Curvature threshold, etc.

**Comment by Ntweat** [comment]
Thanks.

I am still working on using high resolution images (4K)
I am trying to figure out what is going wrong in camera pose estimation. 
Colmap is giving more accurate results, but I am a fan and openMVG and want to stick to it.


Are there any papers I can refer to for feature matching? 
I found the paper on fast cascade hashing but not for the rest.

**Comment by pmoulon** [comment]
Thanks for your loyalty! It is appreciated ;-)

Did you look if Colmap is reducing your image resolution before feature extraction?

You can also share privately the dataset to me there openmvg-team[AT]googlegroups.com in order to let us understand what's going wrong.

**Comment by Ntweat** [comment]
I did. Default reduction in colmap is to 3200 but I disabled that and tried it, still, it worked. But there was a problem, false positives. 
I even gave colmap the same SIFT parameters as openMVG. 
Also, it depends on dataset too, some high res datasets openMVG performs better than colmap. 

The problems mentioned in https://github.com/openMVG/openMVG/issues/995 are also there. 
After exhaustive testing I feel that the problem is 2 folds.
1. Accurate camera tracks.
2. False positives. 

I will create a dataset and send it soon.

**Comment by Ntweat** [comment]
Thanks for your reply on https://github.com/colmap/colmap/issues/246 
Can I use exhaustive matching in openMVG ?

**Comment by pmoulon** [comment]
Posting here since I made a wrong post. @Ntweat can you remove this comments: https://github.com/colmap/colmap/issues/246#issuecomment-345089525

Exhaustive matching is the default mode in openMVG ->  Matching all the pairs.

So if you consider all the possibility if gives you a matrix.
But since we can ignore the diagonal and we suppose that matching is symmetric we process only the upper or lower diagonal.

0 1 2 3 4
0
1
2
3
4

Please take a look to the exported svg files in the matching directory.
All the tested pairs are exported.:
- putatives
![putativeadjacencymatrix](https://user-images.githubusercontent.com/3235050/32919867-28886a68-cadc-11e7-87e9-18ac9c49f449.jpg)
- pair kept after geometric filtering 
![geometricadjacencymatrix](https://user-images.githubusercontent.com/3235050/32919866-28702e94-cadc-11e7-9fcd-d5df49475049.jpg)

You can also visualize that by using the adjacency matrix viewer:
https://github.com/openMVG/openMVG/issues/831

**Comment by Ntweat** [comment]
Ok.
Sorry for this question but I saw that default matching method in openMVG is Fast Cascade Hashing. 
Is it same as Exhaustive matching?

**Comment by pmoulon** [comment]
It depends:
1. Exhaustive matching can be for the pair (compare all the possible image pair)
 - no vocabulary tree pair filtering
 - OpenMVG is using all the pair on one side of the square matrix, or you can it to compute less (video mode or provide your own pair indexes)
2. Exhaustive matching can be to compare all the descriptor (nearest neighbor retrieval without method that perform approximation)
 - Cascade Hashing is a approximate method, like ANN
 - Brute Force is a nearest neighbor search method that test every possibility but it is slower...

**Comment by Ntweat** [comment]
Can you tell me where the SIFT parameters are used (or how to pass custom ones)? 
I don't want to recompile openMVG everytime I use I want to tweak them?

**Comment by Ntweat** [comment]
Finally solved!!
I backtracked both colmap and openMVG to figure out what was happening.
The 2 change which fixed it were:
1. Assume different camera (cameras don't share intrensics)
2. Incremental SfM (Global SfM does not converge) 

Still would be nice to be able to control SIFT parameters as well

**Comment by pmoulon** [comment]
>Still would be nice to be able to control SIFT parameters as well

You can modify only the ComputeFeatures code in order to pass the desired SIFT params ;-). So only change the SIFT constructor parameters.
The default preset choice is an easy way to deal with 3 configuration for any feature detector. Note that most of the existing SfM library propose only to use SIFT.... OpenMVG can be used with any method.

> Incremental vs. Global SfM
It depends of the dataset (if your graph is with high degree, global SfM will work better, if your graph have tiny degree Incremental SfM is recommended)

> Shared vs not shared Intrinsics
You can choose to group or not Intrinsic with the `-g` option on SfMInit_ImageListing.

**Comment by Ntweat** [comment]
Incremental vs. Global SfM 

But why the same dataset on low res (1920 x 1080)  converges on global but does not when in 4K  (original images are 4K but I scaled them down)

**Comment by pmoulon** [comment]
Did you look to the matches graphs?

Else, As I said, if you share me the dataset, I would be happy to take a look to it!

**Comment by Ntweat** [comment]
I am doing some tests on the dataset want to be sure that there is difference before I send it.

**Comment by pmoulon** [comment]
Yep, no worries!

**Comment by Ntweat** [comment]
@pmoulon dataset sent

**Comment by Ntweat** [comment]
@pmoulon did you get a chance to look at the dataset?
