### ISSUE TITLE
close up with wide angle cameras

### ISSUE THREAD

**Issue by GuyNat** [openMVG/openMVG#1159]
Hello Mr Moulon,

Congratulations on the openMVG suite, it looks very interesting.

I am experimenting with the software to do a 3d reconstruction of a rather small area (35cm long by 15cm wide) using 4 aligned cameras (5MP with a wide angle of 130°). The 4 cameras are 8cm from the target so quite close.

The setup is roughly like this

TARGET TARGET
------------------------
c1     c2     c3     c4

The target used for now  is simply a flat carboard with random patterns.

In the best case (normal camera model -c 3) I get a third of the area that should be reconstructed and it is bended. Using the fish eye model (-c 5) I get nothing.

Also tried to undistort the images using OpenCV and feeding undistorded images to OpenMVG but this did not help either.

I can send the pictures if it helps.
Thank you
Guy

**Comment by pmoulon** [comment]
Using wide angle camera works better if you can provide the camera distortion setting as input.

Feel free to share your dataset in order to let us have a look.

For photogrammetry you must follow this check-list:
- does the intrinsic information is valid,
  - for autocalibration of large FoV camera you need a lot of images.
  - then you can reuse the calibration in the next reconstruction you will do.
- does my image have matches (check the produced svg files in matches for this purpose)
- do I used the appropriate pipeline (Incremental vs Global)

**Comment by GuyNat** [comment]
Thank you Pierre for the answer. Do you have an email to which I can send the dataset and the intrinsic information that I got from opencv calibration ?

**Comment by pmoulon** [comment]
You use this email: openmvg-team[AT]googlegroups.com

**Comment by GuyNat** [comment]
Hello, I did fix the issue. For the record and other users benefit here is what worked.

**Comment by pmoulon** [comment]
If you are using undistorted image you can even use the camera model 1, since you don't have any distortion in your image.

Do you mind close the ticket since we listed and tested some experiments.
