### ISSUE TITLE
[Question] Using fisheye images

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1165]
Hi 
I am trying to estimate camera poses using 12 fisheye images take from Samsung Gear 360

It does not converge in global and linear. 
I am using the camera model as 5 

Any help?

EDIT: Can globalsfm do fisheye?

**Comment by pmoulon** [comment]
Fish Eye images are tricky since they involves a lot of distortion and so the image correspondences are harder to build.
The best scenario if you want to use fish eye images, is to use an existing precalibration you made.
You can do that by doing a dataset with a lot of frames of a textured object.
Then you reuse this calibration and ComputeMatches will be able to use it to find more correspondences between the images.

BTW, since you are using a 360 camera, you can also do:
- SfM with the spherical images (supported in the coming OpenMVG v1.3 (develop branch))
- Or extract pinhole images from your 360 images and process them as usual with the pinhole camera model see [here](https://github.com/openMVG/openMVG/issues/621)

**Comment by Ntweat** [comment]
I will look forward to test OpenMVG 1.3
