### ISSUE TITLE
Question about incremental SFM for contiguous overlap

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#1166]
By looking at the code, I noticed that the incremental SFM algorithm consists of initially picking a pair of images, triangulating the 3D points, and then trying to resection the rest of the images based on whether any of the already triangulated features are visible in those images. 

In that case, would incremental SFM fail for contiguous overlap (such as the figure below: please excuse the really rough graphic!)? C1-C2 and C2-C3 have some overlap, but there is no overlap between C1 and C3, hence C3 cannot be resectioned into C1-C2 based on my understanding. Or am I missing a step somewhere?

![image](https://user-images.githubusercontent.com/2274262/33640368-c12883f2-d9f5-11e7-8e67-37fbd7216d15.png)

Thanks!

**Comment by pmoulon** [comment]
Cameras must have some overlap.
So in your case since C3 does not share any visibility with 3d points that can be triangulated by C1 and C2 incremental SfM will not work.

But often since the blue plane is not as close to the camera:
-  you will have more visibility and so you will be able to make some SfM.
- and since tracks are computed by transitivity, you can obtain some point in common between C1, C2, C3.

**Comment by saihv** [comment]
Got it, thank you! I agree that this would be very uncommon in a real life scenario, just wanted to clarify it anyway.
