### ISSUE TITLE
using ZED camera for 3D reconstruction

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1181]
Hi, I'm trying using ZED cameras for 3D dense reconstruction. I have 2 questions:
1. Can the depth information from ZED be used for openMVG reconstruction?  So far as I know, openMVG doesn't use any depth information, but can depth information be helpful at all?
2. openMVG does sparse reconstruction only, right? If I want to use the result of openMVG for dense reconstruction, what software would you suggest? 
Thank you very much!

**Comment by pmoulon** [comment]
1. You are right OpenMVG does not use any depth information.
2. OpenMVG perform only SfM. You can obtain sparse or more dense point cloud by playing with the PRESET option on main_ComputeFeatures. Then you can export the result to many dense reconstruction framework (CMPMVS/OpenMVS/PMVS/MVE/HPMVS) Here the doc https://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

The cannot advise one software or another without knowing your need (usage you want to do).

Feel free to contribute ideas or code in order to use RGBD images.

**Comment by squashking** [comment]
thank you very much!
