### ISSUE TITLE
Difference between Region and Feature

### ISSUE THREAD

**Issue by jakubcerveny** [openMVG/openMVG#1182]
Hi, 

I want to experiment with custom feature matching in an SfM scene, and I have a hard time understanding the meaning of "Regions", which are used in the SfM tools extensively. There is a Region_Provider, but also a Features_Provider, which one do I use to load and work with features and their descriptors? (I want to work with the descriptors directly). 

Thank you,
Jakub

**Comment by pmoulon** [comment]
Hi,

Regions is the abstract concept to cache the feature type and the descriptor type.

Then the SfM pipeline is using the abstract Region_Provider and and Features_Provider to load regions or features corresponding to some view of the sfm_data file.

Since you want to work with descriptor directly for matching purpose I would like suggest to you to take a look to the matching_image_collection and matching module.

Here an example to match two regions:
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/features_image_matching/describe_and_match.cpp
```
std::map<IndexT, std::unique_ptr<features::Regions>> regions_perImage;
  image_describer->Describe(imageL, regions_perImage[0]);
  image_describer->Describe(imageR, regions_perImage[1]);

//-- Perform matching -> find Nearest neighbor, filtered with Distance ratio
  matching::IndMatches vec_PutativeMatches;
  matching::DistanceRatioMatch(
    0.8, matching::BRUTE_FORCE_L2,
    *regions_perImage.at(0).get(),
    *regions_perImage.at(1).get(),
    vec_PutativeMatches);
```

Then for a collection of image you can take a look here:
The generic interface:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/Matcher.hpp#L31
The specialization: 
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/Matcher_Regions.hpp#L29
And the final implementation:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/regions_matcher.hpp#L137

So if you have a method that need all the feature at once you can look to the CascadeHashing implementation: https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/Cascade_Hashing_Matcher_Regions.hpp#L30

else you can take a look there where all method are used for pairwise evaluation
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/regions_matcher.cpp#L74

So the general idea is that you can inherit from Matcher and then access to the raw memory link to each regions descriptor.

**Comment by jakubcerveny** [comment]
Thank you! This is very helpful.

Jakub

**Comment by pmoulon** [comment]
I would like to find some time to extend the doc on it... Feel free to help since you dig into ;-)

**Comment by pmoulon** [comment]
@jakubcerveny Do you mind close the issue?

**Comment by jakubcerveny** [comment]
Closing, thanks again.
