### ISSUE TITLE
different focal length for openMVG_main_SfMInit_ImageListing

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1183]
Hi, If not all the views are from one camera, how to specify the focal length parameter for different views when using openMVG_main_SfMInit_ImageListing?

**Comment by ShikiGami** [comment]
From what I know, `openMVG_main_SfMInit_ImageListing` uses the exif data and the camera database `sensor_width_camera_database.txt`.
Basically all images should contain exif data with the name of the camera it was taken with, and a reference to the sensor width of that camera in the database.
I don't think it is possible to just manually choose a focal length, since the -f option would affect all images.

**Comment by squashking** [comment]
@ShikiGami Unfortunately the images I have do not contain EXIF data. They are captured by ZED cameras. And the ZED cameras do not all have the same focal length. Are there any methods to solve this problem? Thank you very much and merry Christmas!

**Comment by ShikiGami** [comment]
What comes to my mind as a solution is to manually insert multiple intrinsics into the sfm_data.json, and asign manually the corresponding intrensics ID to each camera.

**Comment by pmoulon** [comment]
The focal length of the ZED cameras should be close. You can still start with a common focal length and not grouped intrinsic and let the BA refine the value.

Or @ShikiGami said you can assign the intrinsic ID with an editing of the sfm_data.json file (by hand or thanks to a script).

**Comment by squashking** [comment]
@ShikiGami @pmoulon Thank you!
