### ISSUE TITLE
Spherical images and MVS

### ISSUE THREAD

**Issue by ShikiGami** [openMVG/openMVG#1189]
First of all, congratulations on the new version release, and thanks for adding so much needed support for spherical cameras in the Incremental SFM reconstruction tool.

I'm trying to migrate my current pipeline from the previous one for spherical photos, using the tool to extract rectilinear images from the spherical ones, but I've found some problems.

The first is that when using `openMVG_main_ComputeStructureFromKnownPoses` it seems to fail, since I get an empty robust file.

The second one is that if I try to export this to openMVS using the `openMVG_main_openMVG2openMVS` tool, it crashes.

I don't know if it is that these tools have not been updated to handle these kind of reconstructions, or if I'm doing something wrong.

I will be grateful for any kind of help.
Thanks.

**Comment by pmoulon** [comment]
Thank you for your kind words about the last release.

So actually spherical images can be handled in two ways:
- using directly the spherical images for SfM (MVS export will not work there, since no MVS framework support equirectangular images as input).
- split the spherical images into rectilinear image and process thoses images as regular pinhole images.

Can you tell me in which case `openMVG_main_ComputeStructureFromKnownPoses` fails (pinholes or equirectangular)?

`openMVG_main_openMVG2openMVS` will work only if you have pinhole images.
We can still write a tool that takes a SfM_data scene with Spherical images and create the corresponding SfM_data file with equirectangular images.

Hoping my message answer your questions.

**Comment by ShikiGami** [comment]
Thanks a lot for your answer.

> Can you tell me in which case openMVG_main_ComputeStructureFromKnownPoses fails (pinholes or equirectangular)?

It fails in equirectangular only. Using it with split rectilinear images works (although, there is a lot of noise, probably because of distortion)

>If we want extend the existing tools, we can write a tool that takes a SfM_data scene with Spherical images and create the corresponding SfM_data file with equirectangular images.

That sounds like an interesting proposition. My main problem when transforming equirectangular images into rectilinear images for the SfM -> MVS pipeline is that it creates a lot of noise in the robust reconstruction, and also because it takes a lot more resources. That's why I was kind of looking forward to be able to do SfM without splitting the images.

**Comment by pmoulon** [comment]
Please note that `openMVG_main_ComputeStructureFromKnownPoses` is an optional step.

> That sounds like an interesting proposition. My main problem when transforming equirectangular images into rectilinear images for the SfM -> MVS pipeline is that it creates a lot of noise in the robust reconstruction.

Here the problem does not comes from our side. Making a good robust MVS solution is very hard.

> That's why I was kind of looking forward to be able to do SfM without splitting the images.

We can still think about performing SfM with the spherical images and then export the scene for MVS with the conversion to pinholes images.

**Comment by pmoulon** [comment]
Now it is doable see here https://github.com/openMVG/Image_datasets/tree/master/360_dataset
