### ISSUE TITLE
Missing camera poses when reconstructing a large set of images

### ISSUE THREAD

**Issue by jyiyang** [openMVG/openMVG#1198]
Thanks for this great library! I encountered some problems when trying to use the openMVG pipeline to reconstruct a large set of images (total of 723 frames). The data is extracted from the fr1/rpy data from the [TUM RGB-D dataset](https://vision.in.tum.de/data/datasets/rgbd-dataset/download#), and I only used the color images.

The pipeline I used is as follows:
openMVG_main_SfMInit_ImageListing
openMVG_main_ComputeFeatures
openMVG_main_ComputeMatches
openMVG_main_GlobalSfM

I want to extract the camera poses for every given frame. However, I was only able to get 714/723 camera poses in the sfm_data.json file. It seems that there are some missing camera poses. My questions are as follows:

1. Would you offer a reason that might cause the missing camera poses? I have been looking at some issues related to degenerated frames when camera movements are small in IncrementalSfM, but since I am using GlobalSfM, this issue seems confusing to me. 

2. Is there a way to avoid missing/skipping frames in openMVG when using a large dataset? 

Best regards,
Jack

**Comment by pmoulon** [comment]
Hi @jyiyang 
I would say that the first thing to look at is the log of the different step of the process to understand when the image have been lost.

1. Check that `SfMInit_ImageListing` is listing all your images.
- 723 images should be listed at this stage.
2. Check image matching results (some graphs are log if you have Graphviz installed that allow to see the Connected Component):
- Images can be in a multiple CC since there is point feature connections between some images.
3. Check the SfM engine log:
- Global SfM use a BIEdge connected graph, so if some images are not linked in a triplet then can be discarded.

In order to enhance the number of connection in the image graph you can use the feature preset parameter on the binary `ComputeFeatures`. See the option `-p <NORMAL/HIGH/ULTRA>`. The default preset is NORMAL. I would advise you to try the preset HIGH on your dataset (Please use a new output directory, else the old computation will be reloaded).

Since only a tiny percentage of the images are missing I think those images have been discarded since they share less point features connections to the image dataset.

Regards.

**Comment by jyiyang** [comment]
Thank you for your quick reply! By taking a closer look at the output log, I noticed that the number of poses was decreased during bundle adjustment in the GlobalSfm step. Specifically, the following output shows a substantial decrease in the outlier removal:

...
Bundle Adjustment statistics (approximated RMSE):
 #views: 723
 #poses: 723
 #intrinsics: 1
 #tracks: 4623
 #residuals: 83926
 Initial RMSE: 1.64635
 Final RMSE: 1.61718
 Time (s): 285.042

Outlier removal (remaining #points):
	 initial structure size #3DPoints: 4623
		 pixel residual filter  #3DPoints: 4502
		 angular filter         #3DPoints: 1649
Point_cloud cleaning:
	 #3DPoints: 1470

Bundle Adjustment statistics (approximated RMSE):
 #views: 723
 #poses: 564
 #intrinsics: 1
 #tracks: 1470
 #residuals: 35664
 Initial RMSE: 0.910509
 Final RMSE: 0.718482
 Time (s): 130.571

Would you show me if there is a quick way to preserve the outliers after BA, just for the sake of keeping all the frame-to-pose correspondence intact?

Thanks!
Jack

**Comment by jyiyang** [comment]
Got it, I just comment out the part related to outlier removal in this [file](https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/global/sfm_global_engine_relative_motions.cpp#L481).

**Comment by rperrot** [comment]
Maybe it's a threshold issue with values near the threshold. I don't think it's a good practice to remove the code execution. You may encounter noise issues. 

@pmoulon Could we set some parameters of the outlier removal at the cmdline in order to help users like @jyiyang for some specific cases ?

**Comment by pmoulon** [comment]
The dataset contains a lot of blurry image, so first I would like to understand which part of the dataset is removed and then took some action.

**Comment by NikolausDemmel** [comment]
Just as a side note: The images TUM RGBD benchmark are from a Kinect and thus rolling shutter, which also might contribute to high residuals and thus removal as outliers.
