### ISSUE TITLE
format of image coordinates in bundle.rd.out 

### ISSUE THREAD

**Issue by ccastilloro** [openMVG/openMVG#1202]
Hi, everyone! I´m new in the forum. I´m starting to use OpenMVG. Congratulations, it is excellent!
I´m writing because I´m interested in knowing which format has the bundle.rd.out file created before the dense matching with CMVS. I have 2 main questions:
1. On the origin of the image coordinates
The thing is it seems to me that the image coordinates of a tie point in one image do not follow bundler´s convention considering the center of the image the origin of the coordinates. Bundler´s website:
 _The pixel positions are floating point numbers in a coordinate system where the origin is the center of the image, the x-axis increases to the right, and the y-axis increases towards the top of the image. Thus, (-w/2, -h/2) is the lower-left corner of the image, and (w/2, h/2) is the top-right corner (where w and h are the width and height of the image)._ 
When I check the file, none of the image coordinates are negative. So I suppose when OpenMVG creates the file maybe is following a different format.
2. Distorted/Undistorted coordinates
My second question is whether this image coordinates included in bundle.rd.out correspond to distorted or undistorted images.
Thanks a lot for the help in advance.
All the best,
Carlos

**Comment by pmoulon** [comment]
Hi,
1. You are right, perhaps the features coordinates position in the image are not right. Hopefully PMVS/CMVS only use the 3d point position.

2. OpenMVG supports more complex camera model than Bundler and so we always export the undistorted image coordinates and so we export a classic Pinhole camera equivalent.
See the IsPinhole and the cast to get the Pinhole camera equivalent: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2PMVS.cpp#L270

Looking forward your help to fix the inconsistencies.
As you will understand the conversion of the sfm_data.bin file from OpenMVG to json is more powerful than the bundle.rd.out since the OpenMVG file format allow to support any type of intrinsic.

**Comment by ccastilloro** [comment]
Thanks, Pierre, very useful! Yes, I think the coordinates are not right. OK, CMVS does not use them.

1. So I understand that on exporting the structure, the image observations for a tie point in one camera are undistorted? I´m interested in calculating the image residuals (distance between the image projection and the undistorted observation). Example:
 ###  _"key": 0,
            "value": {
                "X": [
                    -0.7929758202563443,
                    -1.3651349332692525,
                    1.385454143600874
                ],
                "observations": [
                    {
                        "key": 0,
                        "value": {
                            "id_feat": 418,
                            "x": [
                                1273.3499755859376,
                                38.0432014465332-------> distorted or undistorted image coordinates in camera 0?
                            ]_

I would think that this is distorted because it is the same value I found in the 418 feature of this camera in the features file. Or are the features observations already undistorted? When I apply the pinhole model with these vaues (x = K * (R * X + t)), I get high residuals, that´s what I also thinks they are distorted.

2. If the observations were distorted, a further question would be: Is there any documentation on the equations of the different camera models (radial, fisheye) to determine the undistorted coordiantes? E.g: for fisheye:
fisheye": [
                            0.04647707292936867,
                            0.012705821842060796,
                            -0.002733209475033692,
                            -0.001202994593773855
                        ]
How can I see the equations where these parameters are applied?

Thanks a lot for the help,
Carlos

**Comment by pmoulon** [comment]
I would advise you to take a look at the code so this way you understand what is done and which data is exported.

You will see here that for bundler we export the feature position (so image domain with distortion)
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2PMVS.cpp#L308

In order to view some stats about the residual I would advise you to take a look to the exported file:
SfMReconstruction_Report.html
Example for one dataset:
![image](https://user-images.githubusercontent.com/3235050/34922571-a8161472-f946-11e7-818f-52b9812b3baa.png)

Else you can see how use the OpenMVG camera model to compute the residual values:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_report.hpp#L49

> How can I see the equations where these parameters are applied?

I would advise you to look to the code and the function add_disto and remove_disto.
i.e: https://github.com/openMVG/openMVG/blob/master/src/openMVG/cameras/Camera_Pinhole_Fisheye.hpp#L86

**Comment by ccastilloro** [comment]
Thanks a lot, Pierre. Impressive! Yes, I will check the code indeed. Sorry for the simple questions, little by little I´m getting more familiar with OpenVMG and github.
Thank you for the patience.
Cheers,
Carlos

**Comment by pmoulon** [comment]
No worries, there is no simple questions.
Feel free to close or re-open the issue according your need.
