### ISSUE TITLE
Invalid input image graph for global SfM error

### ISSUE THREAD

**Issue by ccastilloro** [openMVG/openMVG#1209]
Hi, I found a problem with Global SfM (probably with Compute_Matches since matches.e is empty).

- It´s not working even using ULTRA option in Compute-Matches. I attach images (just a tiny example).
- The camera is from a smart-phone. I included it in the sensor file:
bq-Aquaris M5;4.80
![img_20170210_100053](https://user-images.githubusercontent.com/35308827/34938029-18b940d2-f9e7-11e7-80cf-ee98bd6f53b8.jpg)
![img_20170210_100058](https://user-images.githubusercontent.com/35308827/34938031-18db23a0-f9e7-11e7-8675-6080cc71f7ab.jpg)
![img_20170210_100103](https://user-images.githubusercontent.com/35308827/34938032-18f9b9fa-f9e7-11e7-84aa-12cc6eb74865.jpg)

Below the command window:
 _SfMInit_ImageListing report: 
listed #File(s): 3 
usable #File(s) listed in sfm_data: 3 
usable #Intrinsic(s) listed in sfm_data: 0 
--describerMethod SIFT 
--upright 0 
--describerPreset ULTRA 
--force 1 
--numThreads 0 
 
 
- EXTRACT FEATURES - 
0%   10   20   30   40   50   60   70   80   90   100% 
|----|----|----|----|----|----|----|----|----|----| 
*************************************************** 
Task done in (s): 57 

Optional parameters: 
--force 1 
--ratio 0.8 
--geometric_model e 
--video_mode_matching -1 
--pair_list  
--nearest_matching_method AUTO 
--guided_matching 0 
--cache_size unlimited 
 
- Regions Loading - 
0%   10   20   30   40   50   60   70   80   90   100% 
|----|----|----|----|----|----|----|----|----|----| 
*************************************************** 
 
 - PUTATIVE MATCHES -  
Use: exhaustive pairwise matching 
Using FAST_CASCADE_HASHING_L2 matcher 
Using the OPENMP thread interface 
 
- Matching - 
0%   10   20   30   40   50   60   70   80   90   100% 
|----|----|----|----|----|----|----|----|----|----| 
*************************************************** 
Task (Regions Matching) done in (s): 175 
"neato" no se reconoce como un comando interno o externo, 
programa o archivo por lotes ejecutable. 
 
- Geometric filtering - 
0%   10   20   30   40   50   60   70   80   90   100% 
|----|----|----|----|----|----|----|----|----|----| 
********************************** 
****************** 
* 
Task done in (s): 0 
 
 Export Adjacency Matrix of the pairwise's geometric matches 
"neato" no se reconoce como un comando interno o externo, 
programa o archivo por lotes ejecutable. 
 
----------------------------------------------------------- 
Global Structure from Motion: 
----------------------------------------------------------- 
Open Source implementation of the paper: 
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion." 
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013. 
------------------------------------------------------------ 
 - Features Loading - 
0%   10   20   30   40   50   60   70   80   90   100% 
|----|----|----|----|----|----|----|----|----|----| 
*************************************************** 
 CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0 
Invalid input image graph for global SfM_ 

I don´t know what I´m doing wrong. Any help?

Thanks a lot!

**Comment by whuaegeanse** [comment]
Please try ANN_L2 matcher.

**Comment by pmoulon** [comment]
The reason that the reconstruction failed is because you don't have intrinsic data for your images:
`usable #Intrinsic(s) listed in sfm_data: 0`

So I think the name you add in the camera sensor database is not right.

You can either provide an approximate focal length or add your camera in the OpenMVG camera sensor width database by adding `Aquaris M5; 4.8`

On my side I tried this:
- to provide an approximate focal length `-f 4160`
- the preset HIGH for the feature extraction
-  the sequential sfm pipeline
Since your image, object does not have a lot of features using the feature preset and the sequential SfM is recommend.

I obtain the reconstruction of the floor:
![snapshot00](https://user-images.githubusercontent.com/3235050/34958880-a9acaa1a-f9e8-11e7-9d80-463434d06492.png)

The robust triangulation step makes some point appears on the object (but not too much, too few texture):
![snapshot00](https://user-images.githubusercontent.com/3235050/34959036-56e0d760-f9e9-11e7-9241-3b55f4fad0b5.png)

**Comment by ccastilloro** [comment]
Thanks! Pierre, you were right. I corrected the camera name in the sensor file (no need to include the 'make', only the model) and set the HIGH option (with the default, it didn´t) and everything is working fine, even in GlobalSfm mode. I suppose the thread can be close.
Thanks again!
