### ISSUE TITLE
OpenMVG2openMVS

### ISSUE THREAD

**Issue by MesHeritage** [openMVG/openMVG#1211]
Hello,

I have an issue with the export from MVG to MVS and cannot figure out the problem. I saw a previous issue related to that and I am not sure if it's still the case (update in headers) but other people do not seem to block on that. I am using release version for both. I compiled the release for MVG but I used the one available for MVS.

When I process the command, the export goes well, files are created.
Then I used the densification command for MVS and it crashes.

Never had this issue when going through the "interface visualSFM" with the nvm file. 
If I export MVG to NVM and use the interface, it works (Just huge waste of space and time).

I tried to redownloaded the release, to follow the same command that available pipelines but still not working.
Is it an update I missed for the export or can it be an issue with a command or file name?

Thanks!

**Comment by rperrot** [comment]
I think the issue is more related to openMVS than openMVG. OpenMVS is known to have some memory issues (you cannot use large scenes with large images). Maybe you could have a look at the clustering approach : 
- you split the scene into clusters (using openMVG_main_ComputeClusters executable) ;
- you export each clusters into an openMVS project ;
- finally you can run openMVS on each clusters (with some luck each of them could fit into memory).

**Comment by pmoulon** [comment]
The issue is certainly in the mvs data format.
`openMVG2openMVS` was updated in OpenMVG v1.3 to export to the last OpenMVS release format.
See we are using version 2 -> https://github.com/openMVG/openMVG/blob/master/src/software/SfM/InterfaceMVS.h#L12
The same as here -> https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Interface.h

Which version of OpenMVG and OpenMVS are you using?

**Comment by MesHeritage** [comment]
Indeed, version issue. While checking it I found the problem but don't really understand why.
I downloaded and compiled openMVG after the last update, I though I had the last version. But I download your release of 1.3 just now and use the export from it. It seems to work.

Not sure where the problem came from but I might stick to download your own release next update to be sure!

Thanks for the help! Have a nice day.
