### ISSUE TITLE
How to recover 2d-3d correspondences?

### ISSUE THREAD

**Issue by AIBluefisher** [openMVG/openMVG#1212]
Hi, @pmoulon 

I meet a problem while using openMVG. I want to get the 2d-3d correspondences, only sfm_data.json and matches.f.txt are all I have after reconstruction completed. Is there any effective way to recover the 2d-3d correspondences? The recovered data structures may be **_Hasp_Map<IndexT, Pair<vector<Observation, vector<Vector3d>>>  _** 

Thank you very much!

**Comment by AIBluefisher** [comment]
Maybe I didn't express my intention clearly. 
Actually, I divided a scene into several parts, every part is reconstructed by ac-sfm, then I want to align several reconstruction subsets by finding 3D-3D correspondences, which are same 3d points but have different coordinate representations as they are reconstructed in different local coordinate systems. The 3D-3D correspondence and all the data I need can be represented by a triplet **<cameraId, Observation, Point3d>**. With only sfm_data and feature correspondences are known, I find it is not easy to find these 3D-3D correspondences, so I want to find 2D-3D correspondences first, the data structure can be represented as **Hasp_Map<IndexT, Pair<vector<Observation, vector>> >**, IndexT represents the index of image/camera, thus by I can find 3D-3D correspondences by feature matches.
It's a little complicated. Is there any more efficient way?

**Comment by pmoulon** [comment]
You can think in various ways:
1. perform sfm where many views are in overlap, so this way you can register each reconstruction since they share some common 3d camera poses.

Or
1. Perform many reconstruction, and then find the common putative 3D points coordinates.
I would do the following: Try to see if a 2d feature map many 3d points.
For this I would use `Hasp_Map<ViewId, vector<Pair<ObservationId,Point3d>>>`
So in order to find the Point3d that belong to the same ObservationId I would use a sort operation on all the entry of the Hash_Map and an equal range with a lambda on the ObservationId (to get all thePoint3d that map the same cam,ObservationId).

I don't know if my message is clear.

**Comment by AIBluefisher** [comment]
It's quite clear. The two approaches could reach different reconstruction results, I will implement both to check which one is better. And I have implement part of the first approach you depict above, since reconstruct several little parts can be much faster than reconstruct the whole parts once when datasets are large enough. I will commit my code to openMVG of this implementation when all algorithms are completed.
