### ISSUE TITLE
Provide external matches

### ISSUE THREAD

**Issue by MatillaMartin** [openMVG/openMVG#1228]
I would like to provide precomputed matches to the IncrementalSFM instead of using the ComputeFeature and ComputeMatches. Is there any direct way?

Thank you!

**Comment by pmoulon** [comment]
You have to export your data to the OpenMVG feature and matches file format.
If should be easy according the OpenMVG api.
1- You need to generate some files:
  - *.feat (the feature position).
  - matches.perso.txt/bin (your matches).
  - export or reuse an existing `image_describer.json` (tell to OpenMVG which type of feature the *.feat file contains).
2- Populate from your match data:
 - PairWiseMatches (the corresponding feature index per image pair) and save it.
 - Export your feature position in IMAGE_NAME.feat files (create SIFT_Regions and add your point data in it and export it do disk)
 - Call OpenMVGComputeFeatures in order to generate the `image_describer.json` (This file is read to know which feature type the *.feat contains) or copy paste an existing one.
2 - Run OpenMVG SfM data and specify the match file to use (can be a bin or a txt file).

**Comment by MatillaMartin** [comment]
Perfect! I followed your steps and it works perfectly!

On a side note:
Working on this, I created a new feature type. Its a PointFeature, and as a describer I have an ID for each point, so its a `Scalar_Regions<PointFeature, int, 1>`
Everything loads correctly, but during the matching it fails to match a few features (lets say 3/20). It is really strange, because the matching is just checking that the ID is the same on both features (distance between describers is 0).
I ended up creating the matches.f.txt file externally, with a simple bruteforce check, but I think its worth noting this issue, in case there is a small bug in the matching module.

**Comment by pmoulon** [comment]
Great, which matcher did you use?
I would be interested to know what going on and fix the issue if there is one.

**Comment by MatillaMartin** [comment]
I ran it in AUTO mode, so `FAST_CASCADE_HASHING_L2 matcher`

**Comment by pmoulon** [comment]
The `FAST_CASCADE_HASHING_L2` is optimized for descriptor that can be divided in chunk (so their length must be longer than 1). I'm even surprised that it worked in your setting ;-)

Can you try to run the BruteForce matcher or the ANN_L2?

But as you said if you can create by yourself the match file it is nice too.

**Comment by pmoulon** [comment]
@MatillaMartin Any new feedback?
Can you please close the issue?

**Comment by MatillaMartin** [comment]
Sure, I will close it!
I will try with BruteForce matcher as soon as I can, and will update :)

**Comment by ableade** [comment]
I am also trying to use precomputed matches from my image set. Where can i find information on the data file format expected for matches? regards
