### ISSUE TITLE
GlobalSfM and non-zero lens-shift camera?

### ISSUE THREAD

**Issue by jakubcerveny** [openMVG/openMVG#1243]
Dear Pierre,

I was wondering if the Global SfM algorithm correctly supports cameras that have a lens shift by design, as I'm having trouble reconstructing a dataset like that.

My dataset consists of images from 5 aerial cameras. The nadir camera has no lens shift but the principal point of the four oblique cameras is shifted in X by about 15% of the image width. This is due to the design of the sensor (UltraCam Osprey). I do specify these shifts in the input sfm_data.json. The reconstructed pointcloud however contains multiple layers, as if views from different cameras didn't connect well. The problem appears right in the initial structure of the global pipeline and never goes away completely. I was wondering if it could be because of the lens shifts, since I have other nadir/oblique datasets that have 5 standard cameras and these reconstruct just perfectly.

Thank you,
Jakub Cerveny

**Comment by pmoulon** [comment]
It should be able to use any existing pre-calibration.
The artifact you speak about make me think about a BA artifact (wrong intrinsic refinement).
Here the step I would like you to test:
1. I would make a fast trial with the Incremental SfM just to see the output of it.
2. Depending of the results of Incremental SfM we could see if the BA is having trouble to refine the intrinsics. If it is the case, we can fix the intrinsics for the SfM process and perform only a BA with intrinsic refinement on the complete scene.

If the lens shift is constant, you can also certainly start with setting the principal point at the middle part of the image and hope that the BA will recover the shift when you will have more image.

**Comment by jakubcerveny** [comment]
I did some more experiments. I imported good precalibration from a different reconstruction and tried again both global and incremental SfM. It seems global SfM is still pretty unstable, especially in the presence of obliques. Nadir only reconstruction works but breaks into several components. Incremental is more stable but takes a long time and still has some multi-surfaces when obliques are present. The only thing that seems to work well is nadir-only incremental reconstruction. I was wondering what would be your opinion on the following method:

1. do incremental reconstruction of nadir views only (this is reasonably fast and works),
2. resect all obliques on the nadir reconstruction (each oblique separately),
3. do a final BA on everything.

Would you say this is worth trying?

Thank you,
Jakub

**Comment by pmoulon** [comment]
@jakubcerveny Since Global SfM is using only triplet of images and tracks of length 3 in order to compute the relative translations it is possible that in your case this is not the best setting. I mean having oblique et and nadir will not leads to strong matches between the two "angle" acquisition.

-> Did you take a look to the graph or the adjacency matrix after the geometric filtering?
- You will see the two CC with few links between them I think.

Your pipe 1,2,3 could work and you could give it a try. It should be easy to test:
1- do incremental SfM with nadir view
2- try to localize the nadir images https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/localization/localization.rst
3. see the output...

You can also test the new WIP incremental pipeline pushed there with your full image set https://github.com/openMVG/openMVG/issues/1241

Matching oblique and nadir image is often tricky. I know that some method try to wrap the oblique to match the nadir image and obtain more matches since the image have been "flattened". So one other solution could be to use SIFT for the nadir and use ASIFT feature extraction for the oblique and let the matching run.

**Comment by jakubcerveny** [comment]
Thank you Pierre!
