### ISSUE TITLE
is the world reference coordiante system randomly chosen?

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1248]
I have a few sets of images for the same scene. I did SFM using OpenMVG and got the output camera poses. I then plot the world origin together with the pointcloud data and found it is at different positions for different datasets. And it is not at the center of one of the images (or camera center). So I'm curious, is the world reference coordinate system randomly chosen?
I have attached one of the output point cloud file. The camera positions are in green, and the world origin is shown in red. Thank you!
[cloud_and_poses_color.ply.zip](https://github.com/openMVG/openMVG/files/1783668/cloud_and_poses_color.ply.zip)

**Comment by happyfrank** [comment]
As @pmoulon said

> As I said, during the process, at one time a camera is set with identity transform and then BA will move the scene and so the entire scene will move.
> 
> -> If you want every time to have one camera with identity transform you can apply a pose.inverse() to the scene and set one camera as identity.

If you want to have a given fix coordinates system you must use GCP (Ground Control Points, or GPS position for your images).

Regarding GCP: See the help http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

Regarding GPS:See the help http://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/?highlight=GPS

**Comment by squashking** [comment]
@happyfrank sorry, maybe I didn't make my question clear, I don't want to have a fix coordinates system, what I want is just to know, for a given output camera poses from OpenMVG, how the world reference is determined/chosen? Randomly or something else?

**Comment by happyfrank** [comment]
Randomly. Because the step "compute features" was randomly.

**Comment by squashking** [comment]
@happyfrank Do you mean that the world origin was chosen to be at a random feature point? What about the xyz axes?

**Comment by happyfrank** [comment]
That's not what I mean.  During the BA step the scene will change. 
You can see your result initialPair.ply. it's upright. Because It doesn't through BA step.

**Comment by pmoulon** [comment]
As I said, https://github.com/openMVG/openMVG/issues/1247, the first coordinates system set the camera with Y up, Z in front and the first camera with an Identity transform. Then the Bundle Adjustment make the camera move in order to decrease the reprojection error of the 3d points. In this step all the scene is moving a bit and so the first camera will not longer be with an Identity transform and this is not a problem.

- Since the SfM process is using threading you can obtain different results between various run. If you want reproducible results, you can set one thread (set OMP_NUM_THREADS=1) and run the toolchain, you will see that you obtain exactly the same results every time.

- As I said, if you want, every time, fix one camera to be Identity, you can do this as a post process by applying a transform to the scene (The inverse pose of the camera of your choice).

**Comment by squashking** [comment]
@pmoulon @happyfrank  Thank you so much for the answers! Now I understand.

**Comment by squashking** [comment]
@pmoulon Hi Pierre, just one more question. in your above answer, you wrote "the first coordinates system set the camera with Y up, Z in front ", this seems not the convention for camera coordinates system. To my knowledge, Y is usually pointing down. Can you please confirm? Thank you very much!

**Comment by pmoulon** [comment]
Y is down in the camera coordinates system, but Y is up in the camera pose.

**Comment by squashking** [comment]
@pmoulon  I'm sorry I'm confused. What do you mean by "Y is up in the camera pose"? To my understanding, camera pose is just a rotation matrix and a translation vector. do you mean there is a camera coordinates system and a camera pose coordinates system? What is the relation between the Y in camera coordinates system and the Y in camera pose then? Thank you very much!
