### ISSUE TITLE
Missing stlplus dependencies

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1289]
When I changed stlplus to build the shared lib instead of a static lib:
```
-add_library(stlplus ${LIBSLTPLUS_SRCS})
+add_library(stlplus SHARED ${LIBSLTPLUS_SRCS})
```
build began to fail due to missing ```stlplus``` dependencies for these libs/executables:
```
ui_openMVG_control_points_registration
ui_openMVG_MatchesViewer
ui_openMVG_MatchesViewer
openMVG_main_ComputeClusters
openMVG_main_SplitMatchFileIntoMatchFiles
openMVG_main_ComputeFeatures_OpenCV
openMVG_main_SfMInit_ImageListing
openMVG_main_ConvertList
openMVG_main_SfM_Localization
```
also in examples.

Could you please fix those?

I changed stlplus to be a shared library for the FreeBSD port, because on FreeBSD static libraries are discouraged. Installed objects should be shared libraries to avoid excessive copying of binary code.

Please also consider to have a cmake option to turn stlplus into a shared library (since ```stlplus``` project itself builds libraries with completely different names, so there can't be any conflict.

**Comment by pmoulon** [comment]
Which branch did you tried (master or develop)?

I made partial fixes recently in the develop branch but it is possible that I missed some libraries:
https://github.com/openMVG/openMVG/commit/4d1b16f12ba472c6fc572be7b3ee1f855a93176c

**Comment by yurivict** [comment]
This is devel, rev d9563130

I suggest you just make stlplus respect general cmake settings for static vs. shared libs.

**Comment by pmoulon** [comment]
Hi @yurivict 

I worked on some points you shown to me in the branch called `develop_cmake_fixes`
https://github.com/openMVG/openMVG/commits/develop_cmake_fix

I think I fixed most of the problem.

I managed to compile the project with an ubuntu LXDE with clang 6.0:
1. Setup all the external libraries:
  - jpeg, tiff. png, flann, ceres, eigen, lemon, cereal
2. Compile OpenMVG and set the path for the 3rd party library (to avoid OpenMVG to setup them):
`CC=/usr/bin/clang-6.0 CXX=/usr/bin/clang++-6.0 cmake ../openMVG/src/ -DOpenMVG_BUILD_SHARED=ON -DCEREAL_INCLUDE_DIR_HINTS=/usr/include/cereal -DLEMON_INCLUDE_DIR_HINTS=/usr/include/lemon -DCOINUTILS_INCLUDE_DIR_HINTS=/usr/include/coin -DCLP_INCLUDE_DIR_HINTS=/usr/include/coin -DOSI_INCLUDE_DIR_HINTS=/usr/include/coin -DOpenMVG_BUILD_TESTS=ON -DTARGET_ARCHITECTURE=generic`

In my case I got the following (notice everything is listed as external):
```
-- CEREAL: (external)
-- EIGEN: 3.3.4 (internal)
-- CERES: 1.13.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.8 (external)
-- LIBPNG: 1.6.34 (external)
-- LIBJPEG (external)
-- CLP: 1.16.11 (external)
-- COINUTILS: 2.10.14 (external)
-- OSI: 0.107.9 (external)
-- LEMON: 1.3.1 (external)
```

3. Assert that the compilation is running and that the test are running ok
- `ctest -j8`

4. If everything builds ok, you can remove the `-DOpenMVG_BUILD_SHARED=ON` from your compilation command line and run `make install`.

4.a. If you have `***Exception Illegal` issue. It's because of some optimization run by default in the cmake. You can deactivate the line `AutodetectHostArchitecture() OptimizeForArchitecture()` here: https://github.com/openMVG/openMVG/blob/develop_cmake_fixes/src/CMakeLists.txt#L109. You can now recompile and everything will run fine.

Regarding your point:
> general cmake settings for static vs. shared libs.

I'm using the cmake recommendations:
- BUILD_SHARED_LIBS can be set using -DOpenMVG_BUILD_SHARED=ON and most of the target does not use any `STATIC` or `SHARED` keyword, so they are building according the user request.
- https://cmake.org/cmake/help/v3.0/command/add_library.html
  ` If no type is given explicitly the type is STATIC or SHARED based on whether the current value of the variable BUILD_SHARED_LIBS is ON. `

Thx you for your feedback on the last change I made.

I was not able to reproduce the missing `stlplus` link error. But I'm eager to help on this.

**Comment by yurivict** [comment]
> BUILD_SHARED_LIBS can be set using -DOpenMVG_BUILD_SHARED=ON and most of the target does not use any STATIC or SHARED keyword, so they are building according the user request.

I also use ```-DOpenMVG_BUILD_SHARED=ON```, but stlplus still builds as a static library, because you are overriding ```BUILD_SHARED_LIBS``` for the third party libs. I had to add the word SHARED, then it builds the shared library, and the build fails because of the missing dependencies.

**Comment by pmoulon** [comment]
Despite it's running ok in my VM, the current `develop_cmake_fixes` does not run in the CI (Travis, AppVeyor). I'm investigating...

**Comment by pmoulon** [comment]
Classic build now run back to normal: https://travis-ci.org/openMVG/openMVG/builds/365988171

So this branch should be ok for your to test a build with pre-installed libraries:
- flann, eigen, ceres,cereal, tiff, jpg, png, lemon, osi-clp.
