### ISSUE TITLE
ComputeStructureFromKnownPoses not work for ground-truth calibration data

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1311]
Hi, I feed openMVG_main_ComputeStructureFromKnownPoses with ground-truth camera poses and got very poor reconstruction results. But if I feed it with the poses I got from IncrementalSfM then it works quite well. I compare the ground-truth poses and the ones I got from IncrementalSfM and find that the latter is scaled up (I know this is normal for OpenMVG). My question is: how can I use my ground-truth camera poses in OpenMVG?

**Comment by pmoulon** [comment]
Note by default the `openMVG_main_ComputeStructureFromKnownPoses` binary triangulate features only if they are visible by 3 views. If you want all the matches triangulated you have to set your match file as an argument.

See here: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeStructureFromKnownPoses.cpp#L93

`-d -f <PATH>/matches.f.bin -i X -o X -f X`

**Comment by squashking** [comment]
@pmoulon I did exactly as what you said, i.e., direct triangulation from the matches.f.bin file. I just would like to confirm: can I use my ground-truth poses (calibrated using patterns) in OpenMVG? I see the poses generated by OpenMVG is a scaled version of the ground-truth poses. Does the scaling matter?  Thank you very much!

**Comment by pmoulon** [comment]
Scaled does not matter.
I have made a lot of triangulation of scene where I got the camera poses from other sources (calibration of GT files) and it worked great.

Be sure to visualize the camera location and orientation using exportCameraFrustum in order to check that you have provided the right data.

**Comment by squashking** [comment]
@pmoulon I compared the intrinsics estimated by openMVG and the ground-truth, and found that the estimated instrinsic values are quite far from the ground-truth, e.g., the estimated focal length is almost 20% larger than the ground-truth. But strangely, the 3D reconstruction still seems to be working fine. Is this phenomenon normal? and why? Thanks.

**Comment by pmoulon** [comment]
Since we are running bundle adjustment some parameters can compensate each other.
If you want you can tell OpenMVG to do not refine the intrinsic by using `-f NONE` or simply choose which parameter you want to refine, i.e you can set the FOCAL-LENGTH to constant by using `-f ADJUST_PRINCIPAL_POINT|ADJUST_DISTORTION`.

**Comment by squashking** [comment]
@pmoulon I tried fixing the ground-truth intrinsics when runing IncrementalSFM, but I got camera poses which are very different from the ground-truth (you can see the attached image). The cameras are strictly mounted in a straight line, but the poses I got from InrementalSFM are very different. However, if I do not keep the intrinsics fixed as the ground-truth, I can get camera poses closer to the ground-truth poses. This is not understandable since using ground-truth intrinsics is supposed to improve the results, right? Could you please explain a little about it? Thank you very much!

![snapshot00](https://user-images.githubusercontent.com/34270290/41325035-74c2f0d8-6efb-11e8-8255-034ffc71b7b0.png)

**Comment by Poutsh** [comment]
Hi @squashking ,

I was wondering if you solved your problem because I'm facing a very similar situation right now. I want to use my GT poses from my camera and use ComputeStructureFromKnownPoses but I get very poor results too, even with the -d option. And as you say, I get a satisfying result using IncrementalSfM poses.

Did you find something or did you end up using IncrementalSfM instead of your poses?

Thank you in advance.

**Comment by liming0791** [comment]
@squashking Have you solved your problem ? I have similar problem with ComputeStructureFromKnownPoses.

**Comment by squashking** [comment]
@Poutsh @liming0791 ComputeStructureFromKnownPoses should work. You probably misused some parameters if IncrementalSfM works but ComputeStructureFromKnownPoses fails.

**Comment by liming0791** [comment]
> @Poutsh @liming0791 ComputeStructureFromKnownPoses should work. You probably misused some parameters if IncrementalSfM works but ComputeStructureFromKnownPoses fails.

For Example what parameters ? How about your parameters with ComputeStructureFromKnownPoses ?
