### ISSUE TITLE
Given sparse point cloud information and camera pose, can I get sfm_data.json or sfm_data.bin?

### ISSUE THREAD

**Issue by TianQi-777** [openMVG/openMVG#1334]
Hey @pmoulon, 
My research work is SLAM/SFM. Now my partner has obtained sparse target point clouds(.ply) and accurate poses through the SLAM method. Can I convert it to sfm_data.json or sfm_data.bin format for subsequent processing? What should I do?
Looking forward to your reply.

**Comment by TianQi-777** [comment]
There is another question. If my focal length is 12.9599 mm, how much should I enter for -f?
For example:
$ openMVG_main_SfMInit_ImageListing -f 1295.99?
or $ openMVG_main_SfMInit_ImageListing -f 12.9599?

**Comment by pmoulon** [comment]
>  Now my partner has obtained sparse target point clouds(.ply) and accurate poses through the SLAM method. Can I convert it to sfm_data.json.
-  Sure, you can use the OpenMVG API, to create the views (image information and link to pose ids and intrinsic id), the camera intrinsic and the cameras poses. You can also add the 3D points and 2d observations of them that you have.
  - In order to visualize your progress on this you can use the ConvertSfMDataFormat (`-i sfm_data.json -o sfm_data.ply`) and load the PLY to see if your camera and 3d point are at the right positions.

The Focal Length that you must use must be in pixels.  See here for the computation: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L355

**Comment by TianQi-777** [comment]
OK, thank you for your reply：）
