### ISSUE TITLE
Hello! How can i get pose estimation before BA?

### ISSUE THREAD

**Issue by raehyuk** [openMVG/openMVG#1364]
Hello!
Thanks for this wonderful code.
I would like to get the pose estimation before BA. I think that would be some results after openMVG_main_ComputeMatches since this is right before openMVG_main_IncrementalSfM which conduct BA . But I'm not sure which file contains pose estimation .

**Comment by pmoulon** [comment]
BA is only one step of the SfM pipeline.
You must be aware that the incremental SfM pipeline is running multiple BA since it adds images in a sequential manner and you need to minimize error accumulation to register the remaining images.

On the other side, the global SfM pipeline is running only BA at the end since it estimate all the position of the camera at the same time (motion averaging).

Camera pose estimation are contained in the sfm_data.bin or sfm_data.json file. You can convert from one ext (bin<->json) by using the binary ConvertSfmDataFormat.

If you want the scene on your desk before BA, you can just save the sfm_data scene just before the `Adjust ` function (BA) is called.

Incremental SfM BA:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L145
Just add before the loop:
```
Save(sfm_data_, stlplus::create_filespec(sOut_directory_, os.str(), ".json"), ESfM_Data(ALL));
```

Global SfM BA:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/global/sfm_global_engine_relative_motions.cpp#L150
Just add before this line:
```
Save(sfm_data_, stlplus::create_filespec(sOut_directory_, os.str(), ".json"), ESfM_Data(ALL));
```

**Comment by raehyuk** [comment]
Thanks a lot! I added 
Save(sfm_data_, stlplus::create_filespec(sOut_directory_, os.str(), ".json"), ESfM_Data(ALL)); 
at https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L145
like this
do
      {
        Save(sfm_data_, stlplus::create_filespec(sOut_directory_, os.str(), ".json"), ESfM_Data(ALL)); 
        BundleAdjustment();
      }
After going through all the pipeline steps. (ImageListing -> ComputeFeatures -> ComputeMatches -> IncrementalSfM -> ComputeSfM_DataColor -> ComputeStructureFromKnownPoses) 

I tried ConvertSfmDataFormat(from sfm_data.bin to sfm_data.json) to get extrinsics and it was successful. Is this camera pose before BA?
I am afraid that sfm_data.bin was overwritten with data after BA.

**Comment by raehyuk** [comment]
Oh I think it worked. After modifying code I extracted extrinsic from sfm_data.bin and it was different from original .
Thanks !
