### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [openMVG/openMVG#1365]
Would you like to [replace any double quotes](https://github.com/openMVG/openMVG/blob/ca2a20718453cee3bd60f8daeaa07697123289f0/src/openMVG/cameras/Camera_Pinhole.hpp#L14 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by rperrot** [comment]
> "How do you think about to avoid “a duplicated file search” here?"

Search is not duplicated, what the sentense means is that if there is a special tool in the compiler to handle "" it is used, if not it fall back to <> inclusion.

> "Would you like to restrict the searched directories for header files of your software?"

That's a consequence of using "". That's what I said to be "the habits" of what we did. 

But I think I've just understood your question : you mean rewriting the #includes when openMVG is used after an install step ? (in that case #includes should indeed be <>).

**Comment by elfring** [comment]
>you mean rewriting the #includes when openMVG is used after an install step ?

Yes. - Or also at other stages of the software development process?


>(in that case #includes should indeed be <>)

Thanks for your understanding in this direction.

-----

There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by elfring** [comment]
>Absolutely not.

Would anybody dare to measure possible differences for run time characteristics there?


>…, it is used mainly to distinguish between our code and others libraries, …

I try to increase the distinction between versions for files which can be installed and which are in development (or in a questionable update status) also for this software library.

**Comment by rperrot** [comment]
> Would anybody dare to measure possible differences for run time characteristics there?

It's not possible because it depends on many things that we don't manage (compiler internals, OS, I/O access). There is no impact on performance since other compiler stages (preprocessor, compilation, optimization, link, ...) are far more costly than the search of file even on the slowest I/O file. 

> I try to increase the distinction between versions for files which can be installed and which are in development (or in a questionable update status) also for this software library.

The file that are installed are defined in the INSTALL() process of the cmakefiles, not defined using the #include directive.

**Comment by elfring** [comment]
>It's not possible because it depends on many things that we don't manage

[Corresponding measurements of software behaviour](https://en.wikipedia.org/wiki/Software_performance_testing "Description for performance testing") can become very challenging.
I would expect that it should be quicker to perform a file search only once (instead of letting a search attempt fail before).


>The file that are installed are defined …

* How do you think about to achieve that angle brackets should be used for include statements in header files which refer to installed software components?
* Do you need a software build option to select the file inclusion from other directories (with potentially less trust)?

**Comment by rperrot** [comment]
>I would expect that it should be quicker to perform a file search only once (instead of letting a search attempt fail before).

Maybe but searching a file for a limited set of directory is really fast. And as I said before, searching file may took less than a second for the whole compilation stage and the whole compilation is much much longer (in a matter of minutes). So we may not spend time on rewriting things to improve something that has no impact for users§/devs. Even more it may reduce readability that is one of the goal of the library. 

> How do you think about to achieve that angle brackets should be used for include statements in header files which refer to installed software components?

As I said before that would only be the only reason to rewrite things. However this may need a scripting process to rewrite things in headers because it doesn't have same meaning for build dir than for install dir. Moreother as tested on many platforms the CMakeLists tools generate code and inclusion directive that make installation transparent to the user. 

>Do you need a software build option to select the file inclusion from other directories (with potentially less trust)?

It was not needing during all the development process of openMVG so far, so it may not be needed. 

I don't understand exactly your question. Did you encounter any issue with inclusion stage of openMVG in other projects ? Are your question really a question, or a more philosophical debate ? 

Development of feature inside openMVG takes a long time, if there are potential benefit of making arge change in the structure of openMVG it may be motivated with **strong needs** that fit inside the project (readability, stability, ...). You are the first one that ask for that question and you seem to ask the same question on many projects inside github (that doesn't say your question is useless, but we won't have to spend time on long and unproductive debate). Many devs answer you with almost the same answer as I did.

**Comment by rperrot** [comment]
@pmoulon 

This is spam, you could delete this post (cf https://github.com/mfem/mfem/issues/559#issuecomment-408515537)

**Comment by elfring** [comment]
>As I said before that would only be the only reason to rewrite things.

Thanks that you can agree to such an aspect.


>However this may need a scripting process to rewrite things in headers because it doesn't have same meaning for build dir than for install dir.

It depends.

* Do you insist to use quotes in include statements which refer to components from development (or test) versions of your own software library?
* Can angle brackets be eventually always used for inclusion of files from this library?


>CMakeLists tools generate code and inclusion directive that make installation transparent to the user.

Does the CMake software installation support change any include statements?


>Are your question really a question,

Yes. - I am trying to adjust specific development concerns.


>or a more philosophical debate ?

You might get such an impression when your current mood does not fit to aspects for which I am trying to increase the software development attention.

**Comment by pmoulon** [comment]
Feel free to make a PR if you want.
I'm closing the debate since a similar post is going around Github and labeled as spam.

**Comment by elfring** [comment]
Will your software library be installed with the desired file inclusion style?
