### ISSUE TITLE
FLANN matcher for binary feature

### ISSUE THREAD

**Issue by happyfrank** [openMVG/openMVG#1375]
Dear @pmoulon I have extracted the orb feature points with the computer feature opencv. I tried the BF HANMING matching effect very well, but the speed is a bit slow. 
So I want to use FLANN HAMMING to match the binary feature of orb. Will this speed be faster? Will the effect be similar?
By the way. How should I do this? FLANN is a third party of openMVG, But I didn't see where the FLANN matching were used. 
Sorry I see ANN_L2. but this is just for the scalar feature. So How can I modify it and change it to match binary feature.

Thanks.

**Comment by RemoteSensingFrank** [comment]
maybe  you can  consider siftgpu to  speed up.  In     my work i add siftgpu combine with openmvg.发自我的华为手机-------- 原始邮件 --------主题：[openMVG/openMVG] FLANN matcher for binary feature (#1375)发件人：Frank Liu 收件人：openMVG/openMVG 抄送：Subscribed Dear @pmoulon I have extracted the orb feature points with the computer feature opencv. I tried the BF HANMING matching effect very well, but the speed is a bit slow.
So I want to use FLANN HAMMING to match the binary feature of orb. Will this speed be faster? Will the effect be similar?
By the way. How should I do this? FLANN is a third party of openMVG, But I didn't see where the FLANN matching were used.
Thanks.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openMVG/openMVG","title":"openMVG/openMVG","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/openMVG/openMVG"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"FLANN matcher for binary feature (#1375)"}],"action":{"name":"View Issue","url":"https://github.com/openMVG/openMVG/issues/1375"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openMVG/openMVG/issues/1375",
"url": "https://github.com/openMVG/openMVG/issues/1375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "FLANN matcher for binary feature (#1375)",
"sections": [
{
"text": "",
"activityTitle": "**Frank Liu**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@happyfrank",
"facts": [
{
"name": "Repository: ",
"value": "openMVG/openMVG"
},
{
"name": "Issue #: ",
"value": 1375
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"openMVG/openMVG\",\n\"issueId\": 1375,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"openMVG/openMVG\",\n\"issueId\": 1375\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/openMVG/openMVG/issues/1375"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 370039490\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by happyfrank** [comment]
@RemoteSensingFrank Thanks for you reply. But I want build openmvg to mobile phone, it can't use GPU.

**Comment by pmoulon** [comment]
@happyfrank You can use the existing engine to match binary feature (BruteForce hamming).
Using FLANN and his LSH matcher could work but on a mobile phone it would be slower than the brute force method approach.

Also to speed up the existing code you can add a NEON specialization for the Hamming metric so you will be able to use vectorization to compute the bitcount in a faster way.

**Comment by pmoulon** [comment]
In order to test the HAMMING matcher you can just use this function
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/features_image_matching/describe_and_match.cpp#L116

and you specify `BRUTE_FORCE_HAMMING`

**Comment by happyfrank** [comment]
@pmoulon Thanks. Now I‘m testing this one.[FLANN::HierarhicalClustering](https://github.com/openMVG/openMVG/issues/32#issuecomment-34949156)
If everything goes well, I should get the result tomorrow.

**Comment by pmoulon** [comment]
Did you got interesting results?

**Comment by csp256** [comment]
There is a branch with GPU brute force binary descriptor matching implementation that gets >100 billion comparisons per second. https://github.com/mdaiter/openMVG

There is also a snippet available here: https://github.com/komrad36/CUDAK2NN

If you don't have a GPU try: https://github.com/komrad36/K2NN

If you find a faster matcher let me know.

**Comment by pmoulon** [comment]
The GPU hamming matcher is already integrated in this branch (you can test it): https://github.com/openMVG/openMVG/tree/develop_koral 

From my test K2NN is not as fast as just using popcnt for small batches (10K features).

**Comment by happyfrank** [comment]
Dear @pmoulon, recently I'm very busy. I will test it after fews days. Sorry for reply late.

**Comment by happyfrank** [comment]
Dear @pmoulon, as you said.FLANN  LSH matcher it slower than the brute force method approach on mobile phone.
And FLANN::HierarhicalClustering's result not better than BruteForce hamming.
Now I'm close this question.

**Comment by pmoulon** [comment]
Thx for having ran the experiment and sharing the have found the same outcome ;-)
