### ISSUE TITLE
minMaxMeanMedian calculation speed improvement

### ISSUE THREAD

**Issue by mitjap** [openMVG/openMVG#1398]
When looking at  https://github.com/openMVG/openMVG/blob/835f1e585377a55d4143548fa9181438f5d23889/src/openMVG/numeric/numeric.h#L364

I noticed there is room for speed improvement. Instead of `std::sort` we could use `std::nth_element` which has linear time complexity.

```
std::vector<Type> vec_val( begin, end );
auto middle = vec_val.begin(); std::advance(middle, vec_val.size() / 2);

std::nth_element(vec_val.begin(), middle, vec_val.end());
std::nth_element(vec_val.begin(), vec_val.begin(), middle);
std::nth_element(middle, vec_val.end(), vec_val.end());

min = vec_val.front();
max = vec_val.back();
median = *middle;
```

I'd make PR but I don't have the time at the moment.

**Comment by mitjap** [comment]
There are other places in library where we could benefit from replacing `std::sort` with `std::nth_element`.

**Comment by pmoulon** [comment]
Thx @mitjap 
Yeah I know, I have made a very naive implementation...
Thx for the proposal.
We could also certainly replace the two last `nth_element` with `min_element` and `max_element` in the adequate range.

**Comment by pmoulon** [comment]
Thx you @mitjap for the suggestion. 
Fixed by https://github.com/openMVG/openMVG/commit/e41d6cd1d8355c066b793d7e275168c3daab1e17

I used `min_element` and `max_element` for min and max search in the half_range in order to just look for the elements without using any sorting routine (a scan should be faster than the nth_element)

I also added a unit test for the function ;-)
