### ISSUE TITLE
Different match results between PAIR_FROM_FILE and PAIR_EXHAUSTIVE?

### ISSUE THREAD

**Issue by AIBluefisher** [openMVG/openMVG#1402]
Hi, @pmoulon 

I'm using openMVG to do feature matching. I perform two different types of matching approaches, one performs matching with ```PAIR_EXHAUSTIVE``` option, and the other is ```PAIR_FROM_FILE```. With the option of PAIR_FROM_FILE, I provide some files for matching, for example, If I have 6 images, from 0 to 5, and I divide them into 3 groups, where 0 and 1 in the same group, and 2 and 3 in the same group, 4 and 5 in the same group, then I generate the matches pairs with the order: (0, 1), (2, 3), (4, 5), (0, 2), (0,3), (1, 2), (1, 3), (0, 4), (0, 5), (1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5).
I compare the matching result of the two different types, and I find they are different. As I think, the matching results should not be relative to the order of matches pairs. Can you tell me what's wrong?

Thank you very much!

**Comment by pmoulon** [comment]
The results could be different due to the random number generation used during the process.
-> Can you tell us which matching method are you using?
-> Can you tell us if the matching are different at the putative stage or at the geometric matching stage?

- If you have some time and in order to investigate this you can set one thread and run both and see. 
 See the environment variable`OMP_NUM_THREADS`.

**Comment by AIBluefisher** [comment]
OK, I will make an investigate in detail and give answers to the questions above.
