### ISSUE TITLE
Inner loop of Batch SfM

### ISSUE THREAD

**Issue by imkaywu** [openMVG/openMVG#1421]
Hello Dr. Moulon, 

Thanks for sharing this new SfM engine. I read the original paper and found that there is an inner loop that repeatedly performs triangulation and BA until convergence, which is not the case in your implementation. I was wondering if this is an intentional design since the single triangulation is able to result in sufficient tracks being triangulated, or a potential bug?

thanks,
Kai

**Comment by rjanvier** [comment]
Dear Kai Wu,
The Original paper perform triangulation -> **track selection** -> truncated BA until "convergence". The "convergence" term of Cui et al. refer to the fact that jaccard index of tracks ids previously selected and currently selected should be > 0.9.
Here, in the current pipeline, we do not have the track selection step, so we do not really have to check this "convergence" like in the paper. So it's not a bug, even if I agree we could maybe add an extra Triangulation + BA for early batch in the pipeline because it would not be so costly and result in more tracks and also potentially earlier view registration. But making 2 full triangulation and 2 BA each round would really degrade run time in further steps (with let say > 200 cameras)  another alternative would be a more classic  scheme like this "Triangulation -> **local** BA -> triangulation -> **Global** BA".

About the track selection method, If you want to test it, I have implemented this kind of approach in a separate branch (but I need to update it since I had polished it so far) few remarks about it.
- It is not necessarily faster in early round of this SfM pipeline (let say less than 300 images) since running loops of triangulation + selection + BA is not so cheap. 
- It could be unstable in these early round of the pipeline because in the selection formulation, the authors did not take into account the the spreading of tie-points over the sensors frame so it could lead to degenerate evaluation of intrinsics during the BA if selected points are not well spread. 
- The track selection framework favor long tracks, as a result it could also favor unstable far away points seen by a lot of cameras.
