### ISSUE TITLE
Using fisheye images (UAV)

### ISSUE THREAD

**Issue by s-wtnb** [openMVG/openMVG#1423]
I have pictures of fisheye camera shot by UAV.
When processing it (with fish eye arguments) with OpenMVG, the point clouds is **NOT** flat.
Is there a way to make it flat like [this](https://github.com/openMVG/openMVG/issues/423#issuecomment-194876281)?

I reduced the image size to 1/4 while keeping the exif info to shorten processing time.
Is this a problem?

[1/4 size Image files link(69.94MB)](https://1.bitsend.jp/download/28bab8125000e57882a0e1adfd012736.html?setLang=en)
[Original size Image files link(960.42MB)](https://1.bitsend.jp/download/32c831dba367e7157ec70f3a02160180.html?setLang=en)
<br><br>
sensor_width_camera_database.txt(added)
FC6310R;13.2

(non GPS)
```
openMVG_main_SfMInit_ImageListing.exe -i -o -d sensor_width_camera_database.txt -c 5
openMVG_main_ComputeFeatures.exe -i -o -m AKAZE_FLOAT -n 7
openMVG_main_ComputeMatches.exe -i -o
openMVG_main_IncrementalSfM.exe -i -m -o -c 5
openMVG_main_ComputeSfM_DataColor -i -o 
```
![sfm1](https://user-images.githubusercontent.com/25291845/47481905-01a00080-d870-11e8-942d-1d4d1c86d357.jpg)
-> not flat(no GPS info, the top and bottom are reversed)
<br><br>
(rigid GPS)
```
openMVG_main_geodesy_registration_to_gps_position -i -o
openMVG_main_ComputeSfM_DataColor -i -o 
```
![sfm2](https://user-images.githubusercontent.com/25291845/47481917-0b296880-d870-11e8-948c-70781123bcfb.jpg)
-> not flat and camera position is wrong(oblique)
<br><br>
(non-rigid GPS)
```
openMVG_main_SfMInit_ImageListing.exe -i -o -d sensor_width_camera_database.txt -c 5 -P
openMVG_main_ComputeFeatures.exe -i -o -m AKAZE_FLOAT -n 7
openMVG_main_ListMatchingPairs.exe -i -o -G -n 12
openMVG_main_ComputeMatches.exe -i -o -l
openMVG_main_IncrementalSfM.exe -i -m -o -c 5 -P
```
![sfm3](https://user-images.githubusercontent.com/25291845/47481923-11b7e000-d870-11e8-802f-99bded4b56b4.jpg)
-> no pointcloud and camera position is wrong(oblique)
<br><br>

OS:Windows10
OpenMVG: v1.3 "Yellowtail" [ReleaseV1.3.Yellowtail.WindowsBinaries_VS2015.zip](https://github.com/openMVG/openMVG/releases/download/v1.3/ReleaseV1.3.Yellowtail.WindowsBinaries_VS2015.zip)

**Comment by rjanvier** [comment]
Hi,
the doming/bending effect is due to the fact you are trying to evaluate a very complex model of distortion on a quasi flat surface without much priors... so translation and rotation are compensating for distortion.
To tackle this kind of issue you can either inject a pre computed calibration, or add GCP but if you can't do that it's very important to start with a good initial pair. 
![calorifere_complet](https://user-images.githubusercontent.com/1537100/47610009-11c00780-da4b-11e8-9994-d4c634248fc4.jpg)
Here I choose the DJI_0125 and DJI_0127 because they contains a bit of relief (the buildings) to quicly have a not so bad estimation of the distortion parameters.. I  modified other parameters but tell me first if it's good by using these pairs.

**Comment by s-wtnb** [comment]
good result!
Please tell me all parameters you set up.

**Comment by s-wtnb** [comment]
`openMVG_main_IncrementalSfM -i -m -o -P -a DJI_0125.jpg -b DJI_0127.jpg`
The result after setting the initial pair and executing IncrementalSfM is shown below.
![sfm4](https://user-images.githubusercontent.com/25291845/47687301-f90a4a00-dc22-11e8-8f2a-a4fa764c0d6f.jpg)
thanks

**Comment by rjanvier** [comment]
it looks like you didn't use priors her (I can' see the blue dots)
some other tricks
- if your altitude is estimated with pure GPS signal you have to down weight the Z components of your priors (see the `-W` option in `openMVG_main_SfMInit_ImageListing `)
- in this specific case, because the features on the fields could yields some ambiguous results, you can use orthographic essential in `openMVG_main_ComputeMatches` (`-g o`) and use  `-M` option to point to this match file in `openMVG_main_IncrementalSfM`
- You can try to use sift descriptor instead of AKAZE

**Comment by pmoulon** [comment]
As you see [here "Critical Configurations For Radial Distortion Self-Calibration"](http://ccwu.me/file/radial.pdf) this problem is well know in the literature.

What we advise is:
- if possible do a two altitudes fly in order to help Bundle Adjustment to infer the right distortion factors.
- or pre-calibrate the distortion and send it to OpenMVG.

**Comment by rjanvier** [comment]
You could also refer to papers from Vincent Tournardre et al. who made some very extensive study of the problem:
for example
https://www.researchgate.net/publication/283184189_UAV_LINEAR_PHOTOGRAMMETRY
for full bibiliography see here https://www.researchgate.net/profile/Vincent_Tournadre

**Comment by s-wtnb** [comment]
thx!
I will try it with argument, and read papers.
