### ISSUE TITLE
Better model quality with "worse images"

### ISSUE THREAD

**Issue by gmiguelr87** [openMVG/openMVG#1427]
Hello,

I have a doubt that I am not able to understand, I hope you can guide me.
I don't understand why if I use a set of high resolution images 6000x4000 px I end up getting a dense point cloud (with mvs) that is of worse quality than if I use the same images in the same conditions, but reduced resolution to 3000x2000 px.

Any idea?
Thank you

**Comment by pmoulon** [comment]
Hi @gmiguelr87 ,

Can you elaborate a bit more?
- can you share the residual statistics you obtain at the end of your SfM process for the both resolution?
-> You can also look to the SfM_Report and share them here.

From what you say, I cannot say if the issue is coming from OpenMVG (SfM) or from the MVS pipeline your are using.

**Comment by pmoulon** [comment]
@gmiguelr87 any new comment?

**Comment by gmiguelr87** [comment]
Hi @pmoulon !

Sorry for the delay in responding, I was away for a while. Leave me some time and I recover the information of both cases (high resolution and low resolution).

Thank you so much!
