### ISSUE TITLE
RANSAC implementation instead of AC-RANSAC

### ISSUE THREAD

**Issue by zharr** [openMVG/openMVG#1428]
Hi I am trying to modify SfM to use Ransac instead of ac-Ransac in camera pose estimation. If that is too complicated, specifically I would like to keep the threshold for this estimation constant instead of calculating it each time. I have been looking in sfm_robust_model_estimation.cpp and robust_estimator_ACRansac.hpp to start, but was wondering the best way to go about this.

Thanks

**Comment by pmoulon** [comment]
Hi @zharr,

1. You should be aware that you can specify an upper bound accuracy for AC_Ransac. See [here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/robust_estimation/robust_estimator_ACRansac.hpp#L319)
2. In order to understand how to use the API for RANSAC and AC-RANSAC I would advise you to take a look to: https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_estimation_tutorial/robust_estimation_tutorial_homography.cpp and then do your customization. We could think one day about abstracting the Robust_Estimator or make it configurable via a ENUM.
