### ISSUE TITLE
[question] Different focal length in x and y direction

### ISSUE THREAD

**Issue by wilee74** [openMVG/openMVG#1442]
Hi,

First of all, thank you for this great work!
I have a question about the pinhole camera model. As far as I understood, for all models, you consider that fx = fy. Do you think we could have better accuracy with fx not necessarily equal to fy?

Thanks in advance

**Comment by avkudr** [comment]
@pmoulon, actually, if you think that it may improve the accuracy, I would like to develop the corresponding class, make some tests and a PR then

**Comment by wilee74** [comment]
@pmoulon, actually, if you think that it may improve the accuracy, I would like to develop the corresponding class, make some tests and a PR then

**Comment by pmoulon** [comment]
Sorry for the late reply.
Assuming square pixel is mostly ok and I don't think it will make a drastic change for calibration.
For me, it's always better to share as much parameter as you can in order to stabilize BA estimation and refinement.

Feel free to implement your camera model and test it and make a PR once you made your experiment.
Tell us if you need some guidance or not.
