### ISSUE TITLE
How to find common observations in different scenes?

### ISSUE THREAD

**Issue by AIBluefisher** [openMVG/openMVG#1483]
Hi, @pmoulon 

Since I have many different sub-scenes with common images, I want to **register them into one global coordinate system**. It' not difficult to implement it by using these common images to find a rigid similarity transform. But if I want to ***find the similarity transform with common 3D landmarks***, how can I find these common landmarks between every two sub-scenes? Below is what I tried, but there may be something wrong...

The data structure of landmarks is ```using Landmarks = Hash_Map<IndexT, Landmark>;```, and the ```IndexT``` represents their ```trackId```. The data structure of tracks is ```typedef std::map<size_t, submapTrack> STLMapTracks;``` Since I have global tracks, I can find the common observations
by their ```trackId```: the ```landmark``` with a same ```trackId``` should be a 3D correspondence. So, the code for finding common observations should like:
```C++
 void FindCommonObservations(const SfM_Data& sfm_data1, 
                             const SfM_Data& sfm_data2,
                             std::vector<Eigen::Vector3d>& observations1,
                             std::vector<Eigen::Vector3d>& observations2)
{
    Landmarks landmarks1 = sfm_data1.GetLandmarks(), landmarks2 = sfm_data2.GetLandmarks();
    for (auto it1 = landmarks1.begin(); it1 != landmarks1.end(); ++it1) {
        int trackid = it1->first;
        auto it2 = landmarks2.find(trackid);
        if (it2 != landmarks2.end()) {
            observations1.push_back(it1->second.X);
            observations2.push_back(it2->second.X);
        }
    }
}
```
I can't register the sub-scenes into the global coordinate system properly with the common observations. 
The code for finding similarity transform is same for common images and common observations. Is there anything wrong with my code for finding common observations?

The problem is not an issue strictly speaking, maybe it's more proper to communicate by e-mail.

**Comment by pmoulon** [comment]
If you have common image, I would look to find the Views that have the same image name and then use the Pose center of those views to perform a rigid registration.

If you want to rely on image features and 3D structure points, you can find the common tracks, by looking if a track shares the same Feature Id and View Name. Since the view name is not accessible in the Landmark observations directly, you will have to map the ViewId to the ViewName.

So if you have >= common images between your reconstruction, I would advise you to use, image position based registration.
If you have <=2 common images I would advise you to use, landmark base fusion.

Hoping it is explicit enough.
We can work on some tutorial or sample together to share those feature to the whole OpenMVG community if you want.

**Comment by AIBluefisher** [comment]
I agree with you, and it's what i'm doing to using landmark base fusion when the number of common images is not enough. But I still have questions:
(1) Once I have the common tracks, is it necessary to check the viewId and featureId? Since two landmarks that located in different sub-scenes with the same trackId are be triangulated by different features in different views.
(2) Check the featureId and viewId for each landmark is time consuming, because one landmark has many observations - that's why I want to find the common 3D points with track.

Moreover, the algorithms and these features are under developing, i'm quite willing to share them to the community.
