### ISSUE TITLE
Reading match.f.bin file

### ISSUE THREAD

**Issue by nils-hamel** [openMVG/openMVG#1493]
Hi @pmoulon  !

I have a question about the match.f/e.bin file. Is there a way to read it or to convert it into a readable format (ASCII) ?

We need to be able to extract the connected images as they are presented in the GeometricAdjacencyMatrix.svg file.

The goal would be to be able to extract a full pair_list file out of the match.f/e.bin file.

Is there a better way to do it rather than reading the XML code of the GeometricAdjacencyMatrix.svg file ?

Thanks for your help !

**Comment by pmoulon** [comment]
You can either use OpenMVG API, or save the match file in ASCII (by changing the file extension to `txt` rather than bin).

Option 1. Use the OpenMVG API to read the match files:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/indMatch_utils.hpp

Option 2. Change the bin to txt here -> https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L177

**Comment by pmoulon** [comment]
PS: in the future, this PR will export pairs to a file directly https://github.com/openMVG/openMVG/pull/1486

**Comment by nils-hamel** [comment]
Ok thanks !
