### ISSUE TITLE
openMVG result compare to PIX4D  

### ISSUE THREAD

**Issue by dhcpp** [openMVG/openMVG#1523]
Hi, PR!  I take 244 images to reconstructed model by ``openMVG_main_GlobalSfM``. The result is seem very nice.But  when I compared it to PIX4D's reuslt and GPS , I have meet some trouble

I used [evo](https://github.com/MichaelGrupp/evo) to comapre result: ``evo_ape  tum sfm_data.txt gps_data.txt  --plot``. 

```
APE w.r.t. translation part (m)
(not aligned)

max	0.353191
mean	0.112080
median	0.088031
min	0.014647
rmse	0.133896
sse	4.374447
std	0.073254
```

This below figure show that trajectory and error between GlobalSfM  and GPS(UTM)
![Screenshot from 2019-05-17 10-58-11](https://user-images.githubusercontent.com/39484220/57901391-8cd9f580-7897-11e9-952b-84b30aff0ddb.png)

Q1 : How to optimize z direction error ?

``evo_traj  tum sfm_data.txt pix4d_pose.txt gps_data.txt  --plot``
![Screenshot from 2019-05-17 11-06-19](https://user-images.githubusercontent.com/39484220/57901401-982d2100-7897-11e9-9260-33a81ad4b2b6.png)

Q2 : I get rotation matrix R  by extracted sfm_data.json(after BA) , then I transform R to degree. The roll degree is -179.xxx or 179.xxx, and PIX4D roll degree is 0.0xxx or -0.0xxx.
openMVG and [PIX4D](https://support.pix4d.com/hc/en-us/articles/202558969-How-are-defined-omega-phi-kappa) rotation system have any diffrence?

![Screenshot from 2019-05-17 11-34-23](https://user-images.githubusercontent.com/39484220/57901440-cad71980-7897-11e9-8760-55f98a06b4a6.png)

**Comment by pmoulon** [comment]
Thank you for sharing the result of the experiment.
Please note that by default the weight for registration to GPS data are the same for X,Y,Z. You can customize the weights in the toolchain see [here](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L162).
It could explain why Pix4D is better in Z (since they could use a different weighting for X,Y and Z).

Q2. There is various way to decompose a matrix to roll, pitch, yaw. Seems like you have 180 flip, it could be to an axis decomposition sign error. So I would not worry about that, data seems consistent.

**Comment by dhcpp** [comment]
With your help, I have deal with question2 by flip roll 180 degree.

However I reset the GPS weight {0.8,0.8,1.4} {0.9,0.9,1.2} {1.0,1.0,1.5} ..., and the Z direction error has not been greatly reduced. Why does the adjustment weight not improve the accuracy?

What is the general setting of the GPS weight value? Is there a paper or topic that study GPS constraints?

**Comment by pmoulon** [comment]
Since we don't know how Pix4D is doing the GPS registration I would try the following:
- Perform SfM without GPS info
- Perform SfM without GPS info and perform rigid registration
- Perform SfM with GPS info (adaptive registration)

and compare the three results.

Regarding the weight, you can drastically change the scale and go with a larger factor 4x, 10x,... between X,Y and Z.

There is not so much paper about GPS constraint as I'm aware of, and it's a pity.

**Comment by whuaegeanse** [comment]
Here is a link to the paper named [Incremental Fusion of Structure-from-Motion and GPS using Constrained Bundle Adjustments](https://hal.archives-ouvertes.fr/hal-01635480/document) .

**Comment by dhcpp** [comment]
@pmoulon , I tried the bigger weight you said, but it's no work. And results as following:
```
x1y1z1		0.09690036651137357

x1y1z4		0.10840349184043943

x1y1z10		0.13486428692602678  

x2y2z2		0.09752854566860329

x0y0z1		0.09758104536960409

x5y5z10		0.11571477942430312

x10y10z10	0.1426713273098102

x0y0z0		0.09766691212253317
```

**Comment by dhcpp** [comment]
@whuaegeanse THX, ; )
