### ISSUE TITLE
Strange Problems of using Panorama image and Spherical camera model

### ISSUE THREAD

**Issue by iamwangyabin** [openMVG/openMVG#1525]
When I follow the guide from [here](https://github.com/openMVG/Image_datasets/tree/master/360_dataset) to handle my data [here](https://github.com/iamwangyabin/Panorama_Data) 
I found that the X and Y of the camera poses are right but the Z corridinate is wrong ,  just as shown:
The red point is Cmaera pose which is computed by OpenMVG  
The yello point is the ground truth coordinate of camera pose which is got by some kind measurment
The blue line indicate the correspondence 
![2019-02-22 18-14-39屏幕截图](https://user-images.githubusercontent.com/38123329/57999768-2825d180-7b09-11e9-87c0-5002f7889d94.png)
As shown , The Z coordinate is wrong and I think it is not because of scale problem. 
![3](https://user-images.githubusercontent.com/38123329/57999857-7b981f80-7b09-11e9-8805-3f7fb45ceffb.png)
![2](https://user-images.githubusercontent.com/38123329/57999815-51466200-7b09-11e9-883b-46e987542e50.png)
The X and Y just OK!
My picture shown as:

![PIC_20190420_164407](https://user-images.githubusercontent.com/38123329/58000297-ec8c0700-7b0a-11e9-92b4-b10a27262b6c.jpg)

I try other feature and match methods but the best result is SIFT, I think it maybe because of the BundleAdjustment which push camera to fit wrong tracks

**Comment by pmoulon** [comment]
Depending of the baseline distance, the motion will be more or less accurate.
I believe the error could be reduced if you take images with less distance.
It could be also due to drift or wrong matches association due to repetitive feature along the floors of the building.
If you know that all your camera are on the same plane, you can add a constraint at the end, move the camera with all the same Z info and perform a BA again.

**Comment by iamwangyabin** [comment]
Sorry for that , last week I also try some other SFM tools (such as openSFM) and many parameters, they show the same results......... and OpenMVG even show the best results! 
thanks a lot @pmoulon
