### ISSUE TITLE
can't calculate density point

### ISSUE THREAD

**Issue by yokoshou** [openMVG/openMVG#1540]
Help me.
I tried to make density point cloud by openMVG+openMVS,but it dosn't work.
In case I tried with image data with exif,it works well.(photo by smartphone)
However, when I tried without exif data,openMVS can't output .ply file.(photo by web cam)
 
I can't understand What is the problem.
I did openMVG_main_SfMInit_ImageListing -f X option.

Any advices?

[log_openMVS.txt](https://github.com/openMVG/openMVG/files/3264071/log_openMVS.txt)

**Comment by yokoshou** [comment]
All log and dataset .
[images.zip](https://github.com/openMVG/openMVG/files/3264101/images.zip)
[All_log.txt](https://github.com/openMVG/openMVG/files/3264111/All_log.txt)

**Comment by pmoulon** [comment]
If your image does not have EXIF data you need to provide a initial focal guess.
You can provide the Focal Length value to SfMInit_ImageListing with the `-f` option.
The focal length can be approximated as `-f 1.2*max(w,h)` so for you `-f 2304`

**Comment by pmoulon** [comment]
Also reading your log, it seems that OpenMVG made a ok job (please take a look to the file cloud_and_poses.ply to see if the camera path and the structure look ok, but OpenMVS did not succeeded to make a dense point cloud)

Since your object does not have a lot of texture I would advise you to add `openMVG_main_ComputeFeatures.exe -p HIGH` and use `-n X` with X the number of thread you want.

Finally, you are using OpenMVG compiled in debug, you will have better performance with a version compiled in RELEASE mode.

**Comment by yokoshou** [comment]
Thank you for some advices pierre.
I tried to do all you wrote,but result was same.
OpenMVS didn't output .ply file.

Can I ask you any other advices??
or should I ask this to OpenMVS developer??

**Comment by pmoulon** [comment]
1. I would recommend you to try to have sharper image
2. Using  background with a lot of texture could help SfM and MVS (newspaper)
