### ISSUE TITLE
Changing images halfway

### ISSUE THREAD

**Issue by Edward334** [openMVG/openMVG#1565]
Hi, 

I have a more a somewhat theoretical question than an issue, if I'm in the wrong place to ask this, I apologize: I am using a collection of images of an object to do 3D reconstruction using OpenMVG and OpenMVS, and also I have edited images of the same object. For example, let's say the colors are inverted, the contrast is enhanced, a Sobel filter is applied and stuff like that. Obviously, the better model is built upon the the original images. 

Now, my question is: In which point during the entire MVG+MVS pipeline it is best to replace the original images with the edited ones ? I can think of two options: either right after the SfM or right before Texturing in OpenMVS (using undistorted pictures if necessary)

Thanks, and again, I'm sorry if it's the wrong place to ask this.

**Comment by pmoulon** [comment]
Hi,
I would say it depends of your objects, but in order to account for distortion, you want OpenMVG to undistort your images.

If the distortion is very small, you could replace the images inplace, but I would not advise this since this is not very generic.

So.
1. I would create a folder with your original imagery and one with your corrected imagery.
2. I would duplicate your sfm_data.bin and export it to json with ConvertSfmData.
3. I would update the exported sfm_data.json and update the working path to point towards your RGB image
4. You have now a way to export either the original imagery or the modified imagery to OpenMVS and play with it.

**Comment by Edward334** [comment]
Thank for your answer, will give it a try and come back with some feedback if you're interested.

**Comment by pmoulon** [comment]
Sure. I would be happy to hear your feedback.

**Comment by Edward334** [comment]
Hi, got distracted for a while and forgot to reply: Thanks for the solution, worked like a charm !

**Comment by pmoulon** [comment]
Glad to hear!
