### ISSUE TITLE
Final Output coming like attached. How can I get more clean output

### ISSUE THREAD

**Issue by garimss** [openMVG/openMVG#1592]
I am not getting clear output. final result showing too much noise and even its missing detail on target object as well

Any suggestions for me to try again. Also visualsfm not giving complete 3d output without any noise on it.

![LEG](https://user-images.githubusercontent.com/16250644/63503811-ca879380-c502-11e9-8c24-fe96baeb00d4.png)

**Comment by garimss** [comment]
@pmoulon any suggestions sir for this result. what are the options I should try to improve this.

Thank you so much for being so nice to all of us who are asking for help and suggestions. You are awesome.

**Comment by pmoulon** [comment]
Photogrammetry can provides some nice results if you have the right settings.

1. I would try to ensure the subject is not moving
2. I would use a tripod to ensure sharp images (are you using a cell phone of a DSLR?)
3. I would project a pattern on the patient leg in order to add more features. Skin is texture-less for SIFT... or you can draw some points, lines on the leg (see [here](http://arc-team-open-research.blogspot.com/2013/09/scanning-face-in-3d-with-photos.html) and [here](https://goo.gl/aYh6rm)).

Let me know if this is working better.

Linking https://github.com/openMVG/openMVG/issues/799
