### ISSUE TITLE
What the parameter settings on Tanks and Temples multi-view data set?

### ISSUE THREAD

**Issue by PengYao1988** [openMVG/openMVG#1612]
Dear Researchers,
     While I am implementing OpenMVG+OpenMVS on 'Tanks and Temples' multi-view data set, I found that the results on the leaderboard which have used OpenMVG (e.g. OpenMVG+OpenMVS, OpenMVG+PMVS, OpenMVG+SMVS) are all set a same parameter (image scale factor = 2). Do anyone know where to set 'image scale factor' in OpenMVG, or it just a pre-processing on input multi-view images?

**Comment by pmoulon** [comment]
I never run myself an evaluation on 'Tanks and Temples', can you see on the leaderboard who ran the experiments?

I would assume it was a pre-processing.

**Comment by elliestath** [comment]
Hey, I actually encountered problems in calculating the poses for some of the datasets in Tanks and Temples too.
I used a standard SfM pipeline I commonly used for such projects but few of them, e.g. the Palace of the Advanced dataset.
The steps I used:

```
 openMVG_main_SfMInit_ImageListing -i /images/ -d ../../../../../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o . -c 3
    openMVG_main_ComputeFeatures -i sfm_data.json -o ./matches -m SIFT -f 1 
    openMVG_main_ComputeMatches -i sfm_data.json -o ./matches/matches.bin -f 1 -n ANNL2 (I also tried HNSWL2)
    openMVG_main_GeometricFilter -i sfm_data.json -m ./matches/matches.bin -g f -o ./matches/matches.f.bin
    openMVG_main_SfM -i sfm_data.json -m ./matches/ -M ./matches/matches.f.bin -o ./out_Incremental_Reconstruction --sfm_engine INCREMENTAL
```

Like this it calculates most of the poses (around 90%) but I would like to calculate all of them. The same happens for e.g. Auditorium dataset. If you have any ideas on better parameters, I would be grateful! Thanks!

**Comment by pmoulon** [comment]
@elliestath  some datasets could be tricky and need more features.
Some tips:
- I would suggest using HNSWL2 (faster and more accurate than ANNL2)
- You could try to add `-p HIGH` to the computeFeatures line and see if it helps, it is possible that some image pair are rejected due to a lack of matches, and detecting more feature per image could help.

Another issue could be that some images does not have a focal prior since the camera model is not in the SensorDB of OpenMVG. COLMAP is using a default focal multiplier...
We have an experimental branch replicating this behavior here https://github.com/openMVG/openMVG/commit/3b5e2aed4f8e8f06ff08abd4a816b410dc379b32 that you can eventually try

Keep us update if it helps!

**Comment by pmoulon** [comment]
@PengYao1988 I assume the 'image scale factor' was a parameter for OpenMVS (using half-size images to speed up processing)
