### ISSUE TITLE
Reconstruction with the stellar parameter of the incremental sfm2.

### ISSUE THREAD

**Issue by Livan89** [openMVG/openMVG#1613]
Hi.

I have a problem that is happening to me more and more often. When generating the sparse with the incremental_sfm2, the results change if I reprocess the same model, that is, I can generate a model with the same set of images, without changing anything, just generate, finish and regenerate and the results are different . The most interesting thing is that the .feat and .desc are generated exactly the same, the same happens with the Compute_matches files, however the results in the sfm2 change. Does the stellar parameter have any random selection components? I have looked at the detail and it does not seem to me, but something happens for this change. Please help. Regards.

**Comment by pmoulon** [comment]
There is some random number generated in various steps for the Ransac evaluation.
If you run OpenMVG with a single thread you will have reproducible results. But when you are using it with multiple thread we cannot guarantee reproducibility since the latency will be different at every iteration and so some operations are performed in different order.
