### ISSUE TITLE
[Question] Using openMVG as third party library in visual studio

### ISSUE THREAD

**Issue by ziyuedang** [openMVG/openMVG#1614]
Dear contributors,

I am trying to develop my own project using some parts of the openMVG libraries and I'm using Visual Studio 2015 under windows. 

I followed the instructions in https://github.com/openMVG/openMVG/blob/master/BUILD.md and built the static libraries. 

My question is: Is it possible to use visual studio IDE instead of cmake to include the library directories? Since some third party libraries are used in openMVG functions (e.g., eigen), 3rd party libraries have their own directories that need to be included in the project property sheet as well.  I have tried to brute force adding the directories one by one but that doesn't seem very efficient. Wondering if there's something I'm doing wrong or is there a better way of achieving this.

Any help would be appreciated, thank you!

**Comment by pmoulon** [comment]
It would be more efficient to use CMAKE since it will bring for you all the dependencies.
Nothing is stopping you to generate a pattern from an existing CMake import and then copy-paste what matters for you (includes, libs, compilation flags).

Sidenote: CMake has been created to cancel all manual operations in IDEs that could lead to a mistake and to help us, developer, to focus more on the code than dependencies.
