### ISSUE TITLE
indMatch.hpp file suggestion

### ISSUE THREAD

**Issue by GabrielMachine** [openMVG/openMVG#1618]
"Hello!
I  would like to report a suggestion in indMatch.hpp file. I was studying the OpenMVG for my final course project and I found in this file three friend bool operators. As far as I know these friend tokens are used when you have encapsulated  data in the class, but the data that is pretented to get these functions are public. I've also tested if removing this friend operator in the class would affect the code itself, however it does not affect and OpenMVG builds and runs as usual. So, I propose that  you remove the friend token. If desired, I can provide a pull request."

**Comment by GabrielMachine** [comment]
I forgot to mention witch lines should be altered. the lines are line 29, line 33 and line38

**Comment by pmoulon** [comment]
Thank you @GabrielMachine for your feedback.
You are right, the `friend` keyword is not needed since the object `IndMatch` is a `struct` and so I can have direct access to the struct member by using functions.
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/indMatch.hpp#L29

Feel free to do a PR starting from develop branch and propose the PR to OpenMVG::develop branch. Thank you.

Perhaps I made the same mistake in some other structure. Feel free to make a search and see if we can fix some other operator ;-)

Feel free to explain what did you achieve with OpenMVG for your final course project or share any screenshot of nice reconstruction you made here ;-)

**Comment by GabrielMachine** [comment]
I'm having an issue to send the pull request for the openMVG origin. It gives me the message "remote: Permission to openMVG/openMVG.git denied to GabrielMachine." . Could you provide me an way to solve this issue?

**Comment by pmoulon** [comment]
You need to start from a FORK see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by GabrielMachine** [comment]
I know this is doesn't seem urgent, but I am proposing what I feel could be the correct way for improving the API: I replaced the position of the operators to non-member  inline functions external to the struct and built it again and it worked.

See my new PR. I don't mean to bother but if you feel this should be done, I will do the same for all files and keep updating the PR until you feel it is OK.

Thank you.
