### ISSUE TITLE
Counting SIFT features

### ISSUE THREAD

**Issue by rockokw** [openMVG/openMVG#1637]
Hello,

Based on the [feature.hpp](https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/feature.hpp#L146) code and comments I see in https://github.com/openMVG/openMVG/issues/1558, it appears I can use the number of lines in an image's feat file to count the number of SIFT features detected in that image. I'm writing some Python scripts to do some quick analysis, so I wanted to verify that I'm not missing anything.

Thanks

**Comment by pmoulon** [comment]
Yes, you have the right assumption.

**Comment by rockokw** [comment]
Do you think something like this would be useful for OpenMVG? 
![notredame_bigsfm](https://user-images.githubusercontent.com/5362581/68715517-37458380-0570-11ea-9fc2-56c6251875d0.png)

**Comment by pmoulon** [comment]
Sure, feel free to make a PR, we can then add it, in `openMVG/softwares/SfM/Statistics/ListFeatureCountHistogram.py`
We can later consider to add other tools to export statistics on the View/Matching graphs.

We can also consider adding this visual to the SfM report since OpenMVG has already ability to export histogram data as SVGs.

**Comment by rockokw** [comment]
Is there a reason you called it ListFeatureCountHistogram.py as opposed to just FeatureCountHistogram.py?
