### ISSUE TITLE
three-camera sfm, locking two camera poses & intrinsics?

### ISSUE THREAD

**Issue by antithing** [openMVG/openMVG#1708]
Hi, and thank you for making this code available.

My problem is this:

I have three cameras, two are a pre calibrated stereo pair, the other is a different camera, resolution and intrinsic matrix.

I need to find the transform of the third camera relative to the other two.

When I run the `openMVG_sample_multiview_robustEssential_ba` example on either two of the images, I get an incorrect result. (translation between the two cameras is very wrong, 3d points are incorrect).

When i try to run the `SfM_GlobalPipeline.py` on the images, I get the following:

```
Invalid input image graph for global SfM
5. Colorize Structure
The input SfM_Data file "D:\frames\out\reconstruction_global/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses
The input SfM_Data file "D:\frames\out\reconstruction_global/sfm_data.bin" cannot be read.
The input SfM_Data file "D:\frames\out\reconstruction_global/robust.bin" cannot be read.
```

Is this because i need to pass intrinsics in? I have intrinsics for the stereo pair two of the cameras. Where do I pass in the intrinsic data?
Also, is there any examples for running Global SFM using c++ without Python?

Thanks!

Thanks

**Comment by pmoulon** [comment]
1. Yes intrinsics are important data, the knowledge of the focal length will allow computing better Essential matrices

2. Yes you can call OpenMVG binaries directly (the python scripts are here to show you how to chain the binary and make people's life easier). Most of our pro users don't use the python scripts.

3. For your specific case, 2 cameras with the same intrinsic and another camera.
I would call SfMInitImageListing -g 0 -f 1
-> then edit the sfm_data.json to add your intrinsic parameter per camera, you can also make 2 view share the same intrinsic Id to handle the calibrated stereo pair
-> then run the pipeline (features, matches, SfM)


Since you want to know the location of the third camera, I would to the following:
- setup your calibration (intrinsic and extrinsics in sfm_data.json)
- triangulate some points
- then localize your 3rd camera

If you want help us mock up a tutorial about this I would be happy to help if you can share any data.

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
