### ISSUE TITLE
GlobalSfM is ineffictive

### ISSUE THREAD

**Issue by Lsz-20** [openMVG/openMVG#1710]
I'm using -g h
IncrementalSfM can get the desired results，but when I run the same data  with GlobalSfM，it's 'cloud_and_poses.py' has less points.
How can you get the desired results with GlobalSfM?
Thanks

**Comment by pmoulon** [comment]
Using homography matches is not the best to do SfM, or else you must be sure that your object is planar.

The Global SfM is not as robust as IncrementalSfM. So for some scenes, it could fail due to too much outlier contamination.

GlobalSfM works best when you give as input your camera parameter (right focal length value and distortion value) that you can copy paste in the sfm_data.json from a calibration done previously with Incremental SfM for example.

**Comment by Lsz-20** [comment]
Thanks for your help.I'll try it
