### ISSUE TITLE
 openMVG_main_ComputeFeatures multi threading 

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1730]
Hi,

I am running OpenMVG pipeline with around 350 images in a 16-core machine. openMVG_main_ComputeFeatures setting is as below
```
--describerMethod AKAZE_FLOAT
--upright 0
--describerPreset HIGH
--force 0
--numThreads 0
```
My understanding is --numThreads 0 is for max_thread right?

But I observed the CPU usage is not always utilizing the full 16 cores. Most of the time it is only using 1 CPU as below.

![Screenshot 2020-05-01 at 9 58 07 AM](https://user-images.githubusercontent.com/8738486/80791634-8f118e80-8b92-11ea-9dc9-ed0c43fed258.png)

May I know is this by design or it is related to the feature I choose?  Shall I explicitly input the numThread?

Thanks

**Comment by rperrot** [comment]
Did you compile with openMP activated ? Some of the parts are mono-thread, some are multithreads. AKAZE computation is mainly mono-thread (due to the nature of the diffusion process). 

The --numThread corresponds to multiple computation at once (ie: multiple images are described in parallel). However if you don't have openMP enabled this is not used. (That's the case on macOS with apple compiler).

**Comment by rperrot** [comment]
Note: if you use --numThreads = 0 this forces using the maximum of threads available.

**Comment by YouYue123** [comment]
Thanks for the explanation!

**Comment by YouYue123** [comment]
Thanks for the reply and explanation.

Yes. I compiled the source with openMP activated. Thanks for explaining --numThread
