### ISSUE TITLE
Spherical camera with GlobalSFM

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1731]
Hi I am trying to run GlobalSFM with a set of spherical camera images with the suggested pipeline here https://github.com/openMVG/Image_datasets/tree/master/360_dataset

But I always have a problem with translation and rotation averaging. But I could get good result with Incremental SFM. I understand from other related issues that GlobalSFM works with the assumption of calibrated camera intrinsic. But for spherical camera, the intrinsic is fixed

Any suggestion on how to run GlobalSFM on Spherical camera in a better way?

**Comment by pmoulon** [comment]
For the moment the GlobalSfM pipeline is working only with Rectilinear camera due to the way that the triplet configuration is handled for robust translation.
We can change this later in the future.
I would advise you to use the Incremental SfM pipeline for the moment with Spherical images.
Tips for speed are:
- video matching if you know that your frame are contiguous (-v X) on ComputeMatches
- and use -n X to multithreaded as much as you can feature extraction on ComputeFeatures

**Comment by pmoulon** [comment]
We also have now a faster filter for spherical images `-g u` on ComputeMatches that will work nicely if your images are upright.

**Comment by YouYue123** [comment]
Hi @pmoulon  thanks for the information. Is "-g u" included in the latest release v1.5 Coho Salmon?

**Comment by rperrot** [comment]
It's in the develop branch, since commit 50f70be12f3cf5196f55e7e772f801e179e80ceb

**Comment by YouYue123** [comment]
Thanks @rperrot
