### ISSUE TITLE
Not all images have been reconstructed

### ISSUE THREAD

**Issue by qingjiuling** [openMVG/openMVG#1801]
Hi.
I took ten pictures at the same time and place with the same camera, but only three of them were identified pose during reconstruction. How can I solve this problem?
eg:
Dataset info:
#views: 10
#poses: 3

**Comment by rperrot** [comment]
There are multiple issues that could explain the situation. One of them is that overlapping between images is not enough. 

If your confident with the overlaping, you could try to perform feature extraction at a highest level (use -p ULTRA option of the  openMVG_main_ComputeMatches executable).

If this does not succeed, this may be due to the object/scene that you're trying to reconstruct that is not adapted to the method (moving or non rigid object, glossy, transparent or textureless object) or some failure with the capture system (blur, excessive distortion).

**Comment by qingjiuling** [comment]
Thank you very much.
