### ISSUE TITLE
How to calculate 3d coordinates of one point using sfm_data.bin

### ISSUE THREAD

**Issue by Techhooli** [openMVG/openMVG#1821]
When after globalsfm or incrementalsfm, the sfm_data.bin can be obtained. But, if one pair of cooresponding image points is provided, how to calculate it's 3d coordinates. I have search some code sources such as triangulation.cpp. However, I have no idea. I think it's very easy to achieve it ... Someone can help me? Thx.

**Comment by Techhooli** [comment]
I means that that pair of cooresponding points is provided artificially. Maybe they are not the obvious feature points which can not be extracted by sift algorithm. However, we are interested in their 3D coordinates. Traditionally, when the interior and exterior orientation parameters of cameras are known,  the 3D coordinates can be calculated by triangulation. From triangulation,cpp, too many types of triangulation method are provided. I dont know if these different methods can generate different results? which one is best? Or there have been a softwate or sample can solve this triangulation problem?

**Comment by Techhooli** [comment]
And OpenMVS use triangulation to generate dense point cloud. Do you know if some MVS libraries still optimize the camera parameters? Maybe these MVS libraries just finish the dense matching and triangulation...  So sorry, I am the new one in this region. So glad to obtain some answers.

**Comment by Techhooli** [comment]
@pmoulon  Hey, sorry to bother you. If you have time, give me some advices, thx.

**Comment by pmoulon** [comment]
In order to triangulate points, you can use the SFM_Data triangulation engine.
Every correspondence in the sfm_data will be triangulated (estimation of the position of the 3d points).
To triangulate, what you need is know camera poses and camera intrinsic and some correspondences.

There is various example that shows triangulation in practice from OpenMVG codebase:
- samples https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/multiview_robust_essential/robust_essential.cpp ->https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/multiview_robust_essential/robust_essential.cpp#L198
- Sfm_data triangulation Blind or Robust https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data_triangulation_test.cpp#L42

Unfortunately, there is no MVS project that refines the camera parameters as OpenSource, as I'm aware of.

**Comment by Techhooli** [comment]
Thank you. I will do it as your suggestions.
