### ISSUE TITLE
Understanding the Pose3

### ISSUE THREAD

**Issue by uupks** [openMVG/openMVG#1835]
I'm trying to understand a little bit more about the  Pose3 structure. There are 2 questions :

1. Does the rotation matrix in Pose3 describe how to transform points in world coordinates to camera coordinates ? 

2. Why can multipliy two rotation matrix directly when composition of poses ? 
    ```
    /**
    * @brief Composition of poses
    * @param P a Pose
    * @return Composition of current pose and parameter pose
    */
    Pose3 operator * ( const Pose3& P ) const
    {
      return {rotation_ * P.rotation_,
              P.center_ + P.rotation_.transpose() * center_};
    }
    ```
    Isn't it R12 = R1 * R2.transpose() ?

Thanks !

**Comment by LiXin97** [comment]
First, as I can see, `rotation_` means `iRj`, is a rotation matrix transform from j coordinates to i coordinates. When the a Pose3 mean a pose from world to camera, it dose mean rotation from world coordinates to camera coordinates.

For the second question, The class `Pose3` is a class describe the rotation and translation from one coordinates (origin) to another coordinates (result). When two Pose3 variables multiple, the first Pose3's origin coordinates and the second Pose3's result coordinates must be same. Otherwise, the result of multiplication will have no practical significance.

We assume the first Pose3 is `iPj`, the second Pose3 is `jPk`.  When `iPj` `*` `jPk`, we want to get the Pose3 `iPk`. The first `iPj.rotation_` means `iRj`, and the second `jPk.rotation_` means `jRk`. So the result rotation is `iRk`.

**Comment by uupks** [comment]
Thanks for your reply

> For the second question, The class `Pose3` is a class describe the rotation and translation from one coordinates (origin) to another coordinates (result). When two Pose3 variables multiple, the first Pose3's origin coordinates and the second Pose3's result coordinates must be same. Otherwise, the result of multiplication will have no practical significance.
> 
> We assume the first Pose3 is `iPj`, the second Pose3 is `jPk`. When `iPj` `*` `jPk`, we want to get the Pose3 `iPk`. The first `iPj.rotation_` means `iRj`, and the second `jPk.rotation_` means `jRk`. So the result rotation is `iRk`.

// iRw means rotation from word coordinate to i coordinate
Pose3 pose_i(iRw, 0);
// jRw means rotation from word coordinate to j coordinate
Pose3 pose_j(jRw, 0);
// If we want compute pose j w.r.t pose i, we need
pose_i(pose_j.inverse())

Am i right?

**Comment by LiXin97** [comment]
sorry, I don't know what's your mean. 

> pose_i(pose_j.inverse()) ???

Do you want to get `iPj` ? 
`iPw` `*` `jPw`.inverse() = `iPj`.

**Comment by uupks** [comment]
> sorry, I don't know what's your mean.
> 
> > pose_i(pose_j.inverse()) ???
> 
> Do you want to get `iPj` ?
> `iPw` `*` `jPw`.inverse() = `iPj`.

yes, that's what i mean.

I misunderstood the Pose3 before, thanks for your patience !
