### ISSUE TITLE
Different results from the same input

### ISSUE THREAD

**Issue by Atlas-Li** [openMVG/openMVG#1840]
Hi,

    First of all, thank openMVG for your contribution.
    In the process of running, I encountered some problems: 
    -1. When I run multiple times with the same data and inputting the same parameters, the displacement and rotation of the results are different. Is this because of Bundle Adjustment? Is there any way to avoid these offsets? 
    -2. When I extracted the main body of the photos, only the background content was reconstructed. The result obtained was not only the displacement and the rotation was changing, but even the overall shape also became larger. I guess it was because the focal length was adjusted during the BA process. In view of this problem, is there any way to avoid it?
    Thank you!

**Comment by rperrot** [comment]
Hi, 

the reconstruction process uses random init and that's why result can be different from one run to another one. However results should not be so different (only minor changes), so I think there's an other issue. 

1. Try to increase the quality of the features (use -p HIGH or -p ULTRA in the openMVG_main_ComputeMatches executable) ;
2. Make sure your subject is "usable" (low textured, highly specular or transparent subjects are difficult to impossible) ;
3. Make sure your capture is correct : provide enough coverture (same parts should be visible from multiple images), avoid blurred images, avoid only translation motion (try to mix rotation/translation/zoom) ;
4. Try to force sfm process to optimize only some parameters (see the option -f in one of the sfm process executable).

If it's possible, give us one image set that exhibit your issue in order to test.

**Comment by Atlas-Li** [comment]
Thank you for your reply. 

Can you please give me your email address?
Thanks.
