### ISSUE TITLE
Can you stop IncrementalSfM2 from changing the extrinsic data if you have known poses?

### ISSUE THREAD

**Issue by Hiltona99** [openMVG/openMVG#1851]
I am trying to reuse extrinsics obtained from running the algorithm on the previous frames. Currently I am using IncrementalSfM2 as I am not too sure how to implement computeStructureFromKnownPoses into the pipeline. If you have any guide to that I would appreciate it. Anyway, here is how I am using incremenetal

Approach: 

1. openMVG_main_SfMInit_ImageListing
2. openMVG_main_ComputeFeatures
3. openMVG_main_ComputeMatches
4. My own script to inject extrinsics from previous run
4. openMVG_main_IncrementalSfM2 (using -S EXISTING_POSE)

Here are the json files before and after the incremental step. 
[sfm_data_before_after.zip](https://github.com/openMVG/openMVG/files/5899912/sfm_data_before_after.zip)

In these files, the after.json is only different from before.json by a small margin but it is enough to make the .ply files have different rotation/translations. I really need these to be the same.

**Comment by pmoulon** [comment]
If you want to keep the rotation/translation unchanged you can use `computeStructureFromKnownPoses` binary with a match file.
Adding the option to keep the camera pose constant could be easy but just not implemented yet.

**Comment by Hiltona99** [comment]
Ah I see, thank you @pmoulon. I have one more question then. I wish to eventually pass this to OpenMVS and I used `computeStructureFromKnownPoses`, but later on I receive an error in OpenMVS's DenisfyPointCloud stating "error: empty initial point-cloud". So, how can I use `computeStructureFromKnownPoses` and still export to OpenMVS? Currently I run these steps:

1. `openMVG_main_SfMInit_ImageListing`
2. `openMVG_main_ComputeFeatures`
3. `openMVG_main_ComputeMatches`
4. My own script to inject extrinsics from previous run into sfm_data.json file
5. Convert edited .json to .bin
5. `computeStructureFromKnownPoses`
6. `openmvg_main_OPENMVG2openMVS`
7. OpenMVS DensifyPointCloud

I must be missing/misusing something in these steps I am doing so anything you can tell me is much appreciated.

**Comment by pmoulon** [comment]
I would check that you used the right sfm_data file at `openmvg_main_OPENMVG2openMVS` and that you have 3D point in it.
You can use the `ConvertSfMDataFormat` to convert a sfm_data.bin to sfm_data.ply and view it in Meshlab or CloudCompare (so this was you can see where the camera are and where the structure(3d points) exists)

**Comment by pmoulon** [comment]
We can also work together to add the option to keep the camera constant in the BA for `openMVG_main_IncrementalSfM2`

**Comment by pmoulon** [comment]
I'm working on a proposal where you can control if poses are refined or not in BA for openMVG_main_IncrementalSfM2 by adding this to the command line:
```
[-e|--refineExtrinsics] Extrinsic parameters refinement option
	 ADJUST_ALL -> refine all existing parameters (default) 
	 NONE -> extrinsic parameters are held as constant
```
i.e:
- Telling the engine to refine extrinsic parameters:
`openMVG_main_IncrementalSfM2 -i ./software/SfM/tutorial_out/reconstruction_sequential/sfm_data.bin -m ./software/SfM/tutorial_out/matches/ -M ./software/SfM/tutorial_out/matches/matches.f.bin -o ./software/SfM/tutorial_out/reconstruction_sequential_tri -e "ADJUST_ALL"`

```
...
INFO: [sfm_data_BA_ceres.cpp:496] 
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 6393
 #residuals: 45082
 Initial RMSE: 0.333301
 Final RMSE: 0.310087
 Time (s): 0.295474
...
```

- Telling the engine to **do not** refine extrinsic parameters:
`openMVG_main_IncrementalSfM2 -i ./software/SfM/tutorial_out/reconstruction_sequential/sfm_data.bin -m ./software/SfM/tutorial_out/matches/ -M ./software/SfM/tutorial_out/matches/matches.f.bin -o ./software/SfM/tutorial_out/reconstruction_sequential_tri -e "NONE"`

```
...
INFO: [sfm_data_BA_ceres.cpp:496] 
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 6393
 #residuals: 45082
 Initial RMSE: 0.333301
 Final RMSE: 0.311078
 Time (s): 0.134851 
...
```

As you can see the BA was faster for the second call since pose were not considered in the BA optimization ;-)

**Comment by pmoulon** [comment]
@Hiltona99 you can test the feature in the branch `develop_2.0_fixed_extrinsics_in_ba`

**Comment by Hiltona99** [comment]
@pmoulon Sorry for the late response. Thank you for implementing this feature, I am grateful. I am trying to test the feature in the brach `develop_2.0_fixed_extrinsics_in_ba` but I am encountering things I have not seen before in the main branch that is causing me some trouble. 

The first problem is `openMVG_main_ComputeMatches` requires a --pair_list input that is not generated by either of the previous steps `openMVG_main_ComputeFeatures` or `openMVG_main_SfMInit_ImageListing`. I tried running `openMVG_main_ListMatchingPairs` on a previous run's sfm_data.bin to get the information which allowed the program to proceed. Let me know if that is correct.

The second problem is `openMVG_main_IncrementalSfM2`  is giving this error: `Invalid matches file.` I assume this is because I do not pass the  `-M ./software/SfM/tutorial_out/matches/matches.f.bin` argument you had. How did you obtain the matches.f.bin file?

**Comment by pmoulon** [comment]
Yep they are minor things that have changed in the 2_0 branch (running `openMVG_main_ListMatchingPairs` is now generating the pair that will be used for matching in order to make the pipeline more flexible)

To obtain the matches.f.bin file you can run `ComputeMatches`

**Comment by Atlas-Li** [comment]
@pmoulon 
For this new branch, openMVG_main_ComputeMatches doesn't create "matches.f.bin" file. 

The command I typed was: 
openMVG_main_ComputeMatches -i [dir/sfm_data.json] -p [dir/pair_list.txt] -o [dir/] -n HNSWL2 -r .8

Was there anything wrong?

Thank you

**Comment by pmoulon** [comment]
@Atlas-Li The pipeline has been adjusted here https://github.com/openMVG/openMVG/blob/develop_2.0_fixed_extrinsics_in_ba/src/software/SfM/SfM_SequentialPipeline.py.in#L62
Can you share any log?

**Comment by Atlas-Li** [comment]
@pmoulon Thank you for your update. I've followed the above link step by step, when I do 

openMVG_main_GeometricFilter -i /home/lab250/Desktop/2.8/new_branch/fg_out/matches/sfm_data.json -m /home/lab250/Desktop/2.8/new_branch/fg_out/matches/matches.putative.bin  -g -f -o /home/lab250/Desktop/2.8/new_branch/fg_out/matches/matches.f.bin

System was showing:

 You called : 
openMVG_main_GeometricFilter
--input_file:        /home/lab250/Desktop/2.8/new_branch/fg_out/matches/sfm_data.json
--matches:           /home/lab250/Desktop/2.8/new_branch/fg_out/matches/matches.putative.bin
--output_file:       /home/lab250/Desktop/2.8/new_branch/fg_out/matches/matches.f.bin
Optional parameters: 
--input_pairs        
--output_pairs       
--force              false
--geometric_model    -f
--guided_matching    0
--cache_size         unlimited
Unknown geometric model

But I cannot find "openMVG_main_GeometricFilter" tool on website, so I'm confused about "Unknown geometric model" mean, and how do I solve this?

**Comment by Atlas-Li** [comment]
The above issue was solved by replacing "-g -f". But I have met a new problem that when I do the "DensifyPointCloud" in openMVS, it showed "reference image   0 has not enough images in view", I also attached log file of this. Do you have any idea where I did wrong? Or how do solve this problem?

Very grateful.
[DensifyPointCloud-2102081922538C935B.log](https://github.com/openMVG/openMVG/files/5948690/DensifyPointCloud-2102081922538C935B.log)

**Comment by Atlas-Li** [comment]
@pmoulon After I have done some experiments, I found that it might because openMVG_main_IncrementalSfM2 didn't generate enough 3-D points. However, openMVG_main_IncrementalSfM does, is that possible to let openMVG_main_IncrementalSfM also has the ability to control the extrinsics? 

I have tried to adjust the source code of openMVG_main_IncrementalSfM a little bit followed the updates in openMVG_main_IncrementalSfM2 you provided, but it still changed the extrinsics.

**Comment by Atlas-Li** [comment]
@pmoulon 
Within this new branch, I have tried to update **src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp** and **src/software/SfM/main_IncrementalSfM.cpp** followed what you have updated in **src/openMVG/sfm/pipelines/sequential/sequential_SfM2.cpp** and **src/software/SfM/main_IncrementalSfM2.cpp**.

But the thing is even I added Extrinsic_refinement_options etc. into the source code of **sequential_SfM.cpp** and **main_IncrementalSfM.cpp**, the reconstruction result still updated the extrinsic automatically. I was wondering is there anything else I should modify in the source code in order to let the tool **openMVG_main_IncrementalSfM** control the extrinsic?

In the new branch, **src/openMVG/cameras/Cameras_Common_command_line_helper.hpp**, **src/openMVG/sfm/pipelines/sfm_engine.hpp**, and **src/openMVG/sfm/sfm_data_BA.hpp** were already updated, so I didn't change anything in these three source files.

Very grateful!

**Comment by pmoulon** [comment]
Solved by merging https://github.com/openMVG/openMVG/commit/cfeff2dcf9298fe4dcff111478e45de79f4db484
