### ISSUE TITLE
incrementalSfM for spherical camera

### ISSUE THREAD

**Issue by manurare** [openMVG/openMVG#1886]
Hi,

I am trying to make `SfM_SequentialPipeline.py` work with a spherical camera model. While I can indicate a spherical model in `openMVG_main_SfMInit_ImageListing` I can't do it in `openMVG_main_IncrementalSfM`:https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/software/SfM/main_IncrementalSfM.cpp#L111

How should I proceed to perform incremental SfM with an spherical model. Isn't there a way to get the point cloud out of `sfm_data.bin` where only extrinsics are depicted without intrinsics?

Thanks!

**Comment by pmoulon** [comment]
As you can see [here](https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm) you need to specify the camera model for the camera for SfMInit and then you can run the chain as it is (since a spherical camera model will already be set for all your images).

Note that it is something necessary to extract more point per images by using the `-p HIGH` to overcome the panoramic image distortion a bit more for feature matching.

See [here](https://github.com/openMVG/Image_datasets/tree/master/360_dataset) to play with some data that we are sharing

**Comment by manurare** [comment]
Thanks very much for the answer, that solved my problem! Another question that I have is: if I want to project the generated point cloud to a specific camera. How can I know the visible points in that pose? Is there any generated file during SfM that keeps track of visibility in each frame?

**Comment by manurare** [comment]
Sorry. I just got it. My bad
