### ISSUE TITLE
Localization module: Total poses found: 0/0

### ISSUE THREAD

**Issue by AshritR** [openMVG/openMVG#1920]
I'm new around here and I'm trying to use the localization module. I was able to successfully generate sfm data from an image dataset (not 360) but when I try to localize, I get this output:

```
-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------


- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Init retrieval database ...
Retrieval database initialized with:
#landmarks: 3829
#descriptors: 19572
 Total poses found : 0/0
```

I'm using an image for the dataset itself for the query. I even tried using the entire dataset but I get the same output. I tried one of the official datasets as well (ImageDataset_SceauxCastle). Please look into this

**Comment by AshritR** [comment]
I'm on Windows and these are the commands I used

`python SfM_GlobalPipeline.py D:\Ashrit\openMVG\dataset\RoomMap\Exterior\images D:\Ashrit\openMVG\dataset\RoomMap\Exterior\output`

`openMVG_main_SfM_Localization.exe -i D:\Ashrit\openMVG\dataset\RoomMap\Exterior\output\reconstruction_global\sfm_data.bin -m D:\Ashrit\openMVG\dataset\RoomMap\Exterior\output\matches -o D:\Ashrit\openMVG\dataset\RoomMap\Exterior\output\localization_matches -q D:\Ashrit\openMVG\dataset\RoomMap\Exterior\images`

**Comment by pmoulon** [comment]
Seems like it is a regression. I will try to debug and come back to you.
Thank you for reporting the issue

**Comment by pmoulon** [comment]
Found the issue: Since each image should have a different image name, if you reuse the same input, we automatically discard them. See here: https://github.com/openMVG/openMVG/blob/develop/src/software/Localization/main_SfM_Localization.cpp#L275

Try to copy your images to a different folder and rename them and its gonna work...
I tried with SceauxCastle and it worked
```
SfM::localization => try with image: 100_7100_.JPG
SfM::localization => try with image: 100_7110_ (2).JPG
SfM::localization => try with image: 100_7110_ (5).JPG
SfM::localization => try with image: 100_7110_ (10).JPG
SfM::localization => try with image: 100_7110_ (6).JPG
SfM::localization => try with image: 100_7110_ (4).JPG
SfM::localization => try with image: 100_7110_ (1).JPG
SfM::localization => try with image: 100_7110_ (3).JPG
...
--
 Used motion prior: 0
 Total poses found : 11/11
```

I will update the code with a warning, if this happen (if some image name are identical -> display a warning)

**Comment by AshritR** [comment]
Oh I see. Thanks for pointing it out. In the documentation page: https://openmvg.readthedocs.io/en/latest/software/localization/localization

1. The description for the query image directory argument mentions that the directory can also contain the images from the initial reconstruction. I misinterpreted as though the exact dataset can be used for the query.
2. The example command uses the same file name for the query as the one in the dataset.

This led to a little confusion in my case and I believe explicitly mentioning in the documentation that a reused input will be automatically discarded might prevent such confusion. Thanks again for helping out!

**Comment by pmoulon** [comment]
Haha, documentation can definitively be improved, We are checking the image names, because somehow from a pipeline perspective it does not make sense to re-localize the exact same image... but I agree that in some case it is something that you would like to do (i.e testing).

Also it is most likely that we updated the code, and not the doc later on...

We are happy to help and provide support, without support (even if there is some delay), there is no community ;-)

Please share any fun experiment you do with us, with screenshot and performance (success or failures XD)
