### ISSUE TITLE
Big images SFM slow

### ISSUE THREAD

**Issue by WF946773243** [openMVG/openMVG#1925]
I have a set of DJI Phantom 4 RTK images (17,000), using OpenMVG for global SFM, the speed is very slow, is there any way to speed up the processing?Thank you for your reply

**Comment by qingzhengzhuma** [comment]
1. use gpu to do feature detecting and matching.
2. decrease 3d points number in global ba.
3. try to provide good initial pose and intrinsic value as possible.

**Comment by pmoulon** [comment]
To speed up image matching you can use GPS priors (since you have RTK, you will have very accurate priors)
- https://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/

Your image graph will most likely be less dense and should be processed much faster.
You can also limit the number of points per images using the -premptive matching option...

There is no secret, a lot of images is involving more complex graph and so take more time.
FYI: IncrementalSfM2 should be much faster than IncrementalSfM1

If your camera is calibrated you could also leverage this and set the camera has fixed for the SfM steps.
1. Calibrate your camera on a subset of image
2. Copy paste your camera calib from this small scene to you large scene and process the large dataset with fixed intrinsics.

Let's continue the discussion here, and use your dataset as `speed` test for various options...
I can provide more command lines options detail in the coming days

**Comment by WF946773243** [comment]
@qingzhengzhuma How to decrease 3d points number in global ba?

**Comment by WF946773243** [comment]
@pmoulon GPS priors has been used for image matching. In order to use the camera pose prior(Pitch/Yaw/Roll), How to convert Pitch, Yaw and Roll in the image into the rotation matrix of openMVG?

**Comment by pmoulon** [comment]
For rotations, it depends on the convention of your data, I believe you will have like 9 combinations to test and you can use ExportCameraFrustum to visualize and test if you have the right one.

Decrease 3d points number in BA (either you update the code and randomly sample some) or you use the 'Preemptive' matching functionality to get fewer points per images
=> https://github.com/openMVG/openMVG/blob/develop_2.0/src/software/SfM/main_ComputeMatches.cpp#L69
Use `--preemptive_feature_count X`  on ComputeMatches
X would be the number of feature we would keep per images (starting from the largest scale keypoints)

**Comment by pmoulon** [comment]
Closing due to lack of feedback, feel free to re-open as needed
