### ISSUE TITLE
About global translation and global rotation

### ISSUE THREAD

**Issue by qwh9896** [openMVG/openMVG#1986]
We note that openmvg provides two different global rotation(ROTATION_AVERAGING_L1,ROTATION_AVERAGING_L2)
 and three different global translation (TRANSLATION_AVERAGING_L1,TRANSLATION_AVERAGING_L2_DISTANCE_CHORDAL,TRANSLATION_AVERAGING_SOFTL1)processing methods. At the same time, we note that in the global rotation phase, openmvg uses L2 by default instead of L1. However, during the test, we note that L1 provides ultra-high processing efficiency compared with L2. Therefore, we want to know, What is the reason why openmvg adopted L2 and abandoned L1? At the same time, we also want to know the difference between the three processing methods provided in the global translation processing stage?We note that openmvg provides two different global rotation and three different global translation processing methods. At the **same** time, we note that in the global rotation phase, openmvg uses L2 by default instead of L1. However, during the test, we note that L1 provides ultra-high processing efficiency compared with L2. Therefore, we want to know, What is the reason why openmvg adopted L2 and abandoned L1? At the same time, we also want to know the difference between the three processing methods provided in the global translation processing stage?

**Comment by pmoulon** [comment]
OpenMVG goal is to provide a flexible pipeline that people can play with and customize.
As you have noted we gladly provide various solvers for rotation and translation averaging.

- We didn't abandon any solution, we just make them available to users.

We choose to keep ROTATION_AVERAGING_L2 and TRANSLATION_AVERAGING_SOFTL1 since on our tests they provide the most stable results.
If you care about speed you can choose to leverage ROTATION_AVERAGING_L1.

Regarding the difference between the method, we believe we have cited the relevant paper in the implementation code.
But here a brief description:
TRANSLATION_AVERAGING_L1 -> Linear Programming optimization (convex optimization)
TRANSLATION_AVERAGING_L2_DISTANCE_CHORDAL -> Non-Linear solver (see paper)
TRANSLATION_AVERAGING_SOFTL1 -> Adaptation of TRANSLATION_AVERAGING_L1 to a Non Linear Solver

**Comment by pmoulon** [comment]
Any feedback?
