### ISSUE TITLE
[SIFT] Descriptor is not using multiple threads

### ISSUE THREAD

**Issue by rmbrualla** [openMVG/openMVG#203]
Hi,

I'm not being able to use the sift descriptor in a way that parallelizes. Either if I run it single threaded, I don't see it using multiple processors,if I run it inside a #pragma omp parallel for, it still does not parallelize as it has a sort of mutex inside. The configuration I'm using has the VL_THREADS_POSIX defined. Is anyone else observing this behaviour?

Thanks!

Ricardo

**Comment by pmoulon** [comment]
@rmbrualla I have made a fast implementation.
Could you tell me if you have done something similar on your side?

**Comment by rmbrualla** [comment]
Hi Pierre,

I did something slightly different. Once you update vlfeat, you can remove
the calls to vl_constructor/destructor and then you can add an openmp
parallel for around the all, i.e., process many images in parallel, but
parallelizing inside the function, as you did, might be a better option.

I wonder if you'll see the same problems if several threads are computing
the sift descriptors. Not sure if it is a common use case though.

Ricardo

**Comment by pmoulon** [comment]
I have preferred parallelize this way, since computing SIFT on multiple image at the same time can be very memory consuming. So perhaps only computing the descriptor is a bit slower rather than computing multiple image at the same time, but we do not risk a memory overflow.

There is not problem computing the descriptor in parallel since there is no memory allocation in vlfeat description, but you must update the gradient first.
