### ISSUE TITLE
Computing SfM on reduced observations

### ISSUE THREAD

**Issue by 3XH6R** [openMVG/openMVG#2050]
Testing different command combinations to speed up processing for general datasets.

Saw https://github.com/openMVG/openMVG/issues/888#issuecomment-296872507 cropping features/descriptors in image_describer.
Would it be possible to extract the first/largest/interesting `n` amount of features during feature extraction instead of cropping afterwards?

![image](https://user-images.githubusercontent.com/32020441/163909460-0310c739-79fc-4031-91d3-cf965b938d14.png)

**Comment by pmoulon** [comment]
Using the option https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/software/SfM/main_ComputeMatches.cpp#L69 should allow you to specific to keep X feature per images (for the moment the selection is based on scale).

For the moment we have preferred keep all the features, since they are important for matching and establishing reliable tracks.
To speed up, you can have two approach:
- filter the feature per images (and eventually bucketing the image to keep features evenly along the image)
- or filter the tracks before running a BundleAdjustment (again this is a selection problem, but easier to solve)

Some software also create feature reduction by downscaling images (and rescale accordingly feature position or focal length)

**Comment by 3XH6R** [comment]
Does [-P|--preemptive_feature_count] export modified feature and descriptor files or only a pair file?
Would it be possible to add a pair limiter and keep images that didn't meet the set limit?

**Comment by 3XH6R** [comment]
Would pre-emptive exporting modified features and descriptors with known matching keypoints worsen reliable tracks for SfM?

**Comment by pmoulon** [comment]
Please @3XH6R do not change the Title or Initial message after the fact since our user will not be able to understand in the discussion thread...
