### ISSUE TITLE
how can I use internal eigen and ceres?

### ISSUE THREAD

**Issue by pengxutao** [openMVG/openMVG#2144]
Hello, I had installed eigen and ceres on my computer before, and when I run `cmake -DCMAKE_BUILD_TYPE=RELEASE ../openMVG/src/`, I found openMVG use the eigen and ceres I installed before, rather than bundled eigen and ceres in "openMVG/src/third_party":
```-- CEREAL: (internal)
-- EIGEN:  (external)
-- CERES: 2.0.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.34 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/xuzhi/pengxutao/openMVG/openMVG_Build
```
the eigen and ceres are external, but their version are not same as openMVG bundled library in "openMVG/src/third_party", so how can I use internal eigen and ceres? thank you very much.

**Comment by pmoulon** [comment]
You can hide the find_package,
Hide this line https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L304
and this line https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L288

**Comment by alLiucb** [comment]
@pmoulon 

> You can hide the find_package, Hide this line https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L304 and this line https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L288



Hey, it’s been a few years since your answer and the project’s `CMakeLists.txt` has changed. Now you only need to comment out line [[293](https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L293)](https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L293).

I just wanted to leave this note here so future readers know exactly which line to modify.
