### ISSUE TITLE
Compiling in Windows

### ISSUE THREAD

**Issue by duis** [openMVG/openMVG#221]
I am trying to compile the libraries via VS 2010 Express. I get errors and at the end build fails.

========== Build: 28 succeeded, 33 failed, 0 up-to-date, 0 skipped ==========

I get errors like that;

LINK : fatal error LNK1181: cannot open input file '..\..\third_party\jpeg\Release\jpeg.lib'

LINK : fatal error LNK1181: cannot open input file 
'..\..\openMVG\multiview\Release\openMVG_multiview.lib'

I am clearly doing something wrong but i don't know what it is. Any suggestions?

**Comment by pmoulon** [comment]
Can you send the complete log (or share it thanks to a GIST).
We cannot see compile error here.

**Comment by duis** [comment]
This is what i get from normal verbosity level of project build output.

https://gist.github.com/duis/9d6da22adb2d43c1009c

**Comment by pmoulon** [comment]
Seems there is a problem with a third party.
I think you have download an archive of the project, rather than using GIT.

Please follow the rules defined here to ensure that you have the third_party libraries that are obtained thanks the git submodule functionnality.
https://github.com/openMVG/openMVG/blob/master/BUILD#L17

I think, actually, your directory openMVG/src/dependencies is empty in your case.

**Comment by duis** [comment]
Sorry for delayed answer. I used git here is the output.

https://gist.github.com/duis/7d0751ddaaea0fa17760
