### ISSUE TITLE
[Question] OpenMVG with a motor-controlled turntable

### ISSUE THREAD

**Issue by f-dy** [openMVG/openMVG#2212]
I was looking for a method do to SfM on turntable sequences, where the object is strictly rigid (not plants as in https://github.com/openMVG/openMVG/issues/2007) and the step size between two pictures is constant (not random as in https://github.com/openMVG/openMVG/issues/2202).

In this case, there is only one set of extrinsics to estimate (R,t between the first and second camera, because the motion is the same in the whole sequence), and a single set of intrinsics since there is just one camera.

Pierre @pmoulon, do you think that's a situation that OpenMVG could help solving? All photogrammetry software work fine with textured objects (eg [this](https://agisoft.freshdesk.com/support/solutions/articles/31000163268-turntable-capturing-scenario-and-processing-workflow)), but struggle on turntable shots with more difficult objects. Reducing the set of parameters to the bare minimum (5 extrinsics, 3 or more intrinsics) should help a lot, but we would probably have to use a good initialization and guided matching.

**Comment by pmoulon** [comment]
Hi

Seems like a situation that would be good for global SfM pipeline. Since from the relative pose you can compute you would extract the average rotation. 

Another trick that is useful for turntable set is to find ways to have tracks on object rather than background. People are often adding texture below the object with newspaper or a coded target. 

Using coded target could help for direct absolute pose camera estimation or registration

Maybe segment anything could help to segment the object and then we could run some more dense tracking like loftr if your object does not have so much texture.

Let me know if you find my comment useful and I would be happy to continue the discussion here and learn more about your typical dataset.

**Comment by pmoulon** [comment]
Closing issue due to lack of feedback, feel free to reopen if needed
