### ISSUE TITLE
ui_openMVG_control_points_registration and GPS registration

### ISSUE THREAD

**Issue by maazraan** [openMVG/openMVG#2239]
Firstly, i generated a point cloud using global pipeline and then called openMVG_main_geodesy_registration_to_gps_position i.e. GPS and the outcome was as good as expected. Later I tried to make it more accurate by using the ui_openMVG_control_points_registration, I used it and although the point cloud was georeferenced but the point cloud had too much noise in it. So I did GPS registration first and thenui_openMVG_registration thinking that it will generate a noise free point cloud but instead it gave this error:Control Point cannot be triangulated (not in front of the cameras).Please help me out.

**Comment by pmoulon** [comment]
By noisy point cloud what do you mean?
Could be a visualization issue?

**Comment by maazraan** [comment]
Thanks for the reply,
I mean too many points were out of cloud's plane and I visualized it in different softwares. My main aim is to use georeferencing after gps_registration.

**Comment by maazraan** [comment]
Any updates??

**Comment by 4CJ7T** [comment]
Ground control points are used for ridged transformation of the scene and are not utilized during structure from motion. Depending on the accuracy of the gps coordinates you may need to adjust weights.

**Comment by 4CJ7T** [comment]
@pmoulon, would it be plausible to use ground control points to refine poses?

**Comment by maazraan** [comment]
Thanks for the reply, from what i can understand, i should add weights during the GPS correction which can be done by using them as arguments in Geodesy function, but can you please tell me that how can I adjust weights automatically.

**Comment by mikec-bmg** [comment]
Did you ever receive help on the 'not in front of the cameras' issue from control point registration? Several years ago we noticed that the exact same GCPs when passed into the code used in ui_openMVG_control_points_registration would result in several being reported as 'not in front of the cameras'. In OpenMVG 1.2, they processed correctly, then after that they would not.

I'm trying to dig in to this now so that we can use newer OpenMVG, but just wondered if you had found a solution.
