### ISSUE TITLE
Use camera poses as initial start points

### ISSUE THREAD

**Issue by mojovski** [openMVG/openMVG#246]
Is there a way to use existing camera poses (R|t) for the incremental or global SfM?
I receive poses from a SLAM framework, which I would like to use as starting points for the BA optimization (willing to contribute if not supported yet).

Also: How can I align the trajectory to a ground truth trajectory so I can compare the results with an existing ground truth 3D model?

Thanks alot in advance!!

**Comment by FreakTheMighty** [comment]
In response to you second question:

I've used the `superimposition_matrix` function from [this very handy python module] (http://www.lfd.uci.edu/~gohlke/code/transformations.py.html) for alignment problems. Also, I'm sure [Point Cloud Library](http://pointclouds.org/) has an alignment algorithm.

**Comment by mojovski** [comment]
Thank you! As for the alignment issue, I guess I will try simple ways via CloudCompare or Meshlab first.

Looking forward for a response regarding the first, most exciting, question. :)

**Comment by pmoulon** [comment]
Hi @mojovski,
Thanks for your interest about the library.

Regarding the first question:
- it's a feature that I want to add in the next release (I think we can start to work on it, next week).
  - That's why I'm working hard on the next SfM_Data container https://github.com/openMVG/openMVG/issues/232 that will ease data exchange and new binary writing.

Regarding your second one.
- aligning to a ground truth trajectory, nothing more easy than computing a similarity transform between the two corresponding point cloud => https://github.com/openMVG/openMVG/blob/3a93c9be8d2b87b25bc7dd60a42129cca9299d38/src/openMVG/geometry/rigid_transformation3D_srt_test.cpp#L32

PS: I'm working also on a GT comparison to existing dataset here:
https://github.com/openMVG/SfM_quality_evaluation

**Comment by mojovski** [comment]
Thank you, these are great news! I will have a look on the code and come back on this next week.

**Comment by pmoulon** [comment]
@mojovski 
This issue will be a first start to do what you want:
https://github.com/openMVG/openMVG/issues/262
You will be able to load existing camera poses & some provide pair index to provide image visibility information. The process infer automatically which 3D point can be robustly triangulated.
Calling BA at the end of this process will be just a matter of adding two lines ;-)

**Comment by mojovski** [comment]
Thank you very much! :) I will update you here on my progress.

**Comment by pmoulon** [comment]
@mojovski It's now possible.
Once you have create your scene description (a sfm_data.json file) you can use the ComputeStructureFromKnownPoses binary to triangulate features tracks.
http://openmvg.readthedocs.org/en/latest/software/SfM/ComputeStructureFromKnownPoses/

You will just have to put a bigger threshold and perform a BA on the result.
