### ISSUE TITLE
Intermediate files generated during the reconstruction

### ISSUE THREAD

**Issue by fabiencastan** [openMVG/openMVG#299]
What is the rule for the generation of the intermediate files: `00000000_Resection.ply`?

The number of cameras added is not linear sometimes 7 new cameras, sometimes 1 new camera, etc.
The code is here, but it seems to be for each new camera...
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L104

**Comment by pmoulon** [comment]
The number of added cameras can differ each time:

The number of cameras that will be tried for resection are computed in the function FindImagesWithPossibleResection.

The simplest rules to make the reconstruction grow is to add one image at a time, but it's time consuming since it involves to perform BA at each step.

In order to minimize the number of BA this function can return many images.
It computes for the remaining images (the one that have no pose) the coverage of putatives 2d-3d correspondences count and keep the best ones according the following rules.
```
// Estimate the image on which we could compute a resection safely
// -> We first find the camera with the greatest number of matches
//     with the current 3D existing 3D point => M
// -> Then add any camera with at least 0.75M matches.
```
The numbering of the PLY files is incremented by each calling of new images slot addition.
Hoping it's sufficiently detailed.

**Comment by fabiencastan** [comment]
Ok, I see. Thanks!
