### ISSUE TITLE
Minor issues when using as an external cmake library

### ISSUE THREAD

**Issue by icoderaven** [openMVG/openMVG#330]
1. Coin related libraries are added to the OPENMVG_LIBRARIES environment variable even if the project has not been built with them -llib_OsiClpSolver -llib_CoinUtils -llib_Osi -llib_clp. Hacked away by commenting them out in install/share/openMVG/cmake/OpenMVGConfig.cmake

2. FLANN, nonFree and Software headers are not added in the install prefix.

**Comment by pmoulon** [comment]
Dear @icoderaven 
Thanks for your comments.

1. I don't understand why you want to remove the Coin related libraries, since they are needed by some OpenMVG core component (Linfinity  geometry problem solvers).

2. The last commit must fix it. Thanks for saw that point.
Regarding the software headers, they will not be distributed, since those header are link to some application they do not have to be distributed.

Can you tell me if the last commit in the develop branch solve the issue you have encounter?

Thanks.

**Comment by pmoulon** [comment]
@icoderaven can you tell me if this commit solve the issue?

**Comment by icoderaven** [comment]
I apologize but I'm travelling for the next three weeks, but will let you
know as soon as I get back!

**Comment by pmoulon** [comment]
Any feedback on this issue?

**Comment by icoderaven** [comment]
Just got back! I shall report within two days (Immediate demo deadlines!)

**Comment by pmoulon** [comment]
No problem ;-) It was just a ping to keep the thread alive

**Comment by icoderaven** [comment]
Just checked, and no, this didn't work

a. For the nonFree headers, the code expects the vl/ and the descriptor file to be in nonFree/sift/ rather than in just nonFree/. This should just be a minor fix in src/nonFree/sift/CMakeLists.txt, so I think something like

DESTINATION include/openMVG_dependencies/nonFree/sift

b. At the time of linking, I cannot find -llib_OsiClpSolver, -llib_CoinUtils, -llib_Osi, -llib_clp. Since you said that these libraries are required, I guess they need to be added to the install prefix?

**Comment by pmoulon** [comment]
Thanks for your feedback.
Be sure to use the last develop branch.

Which file do you try to compile/include produce you an error?

@cbalint13 and I and other people that want to join are working on improving the usage of OpenMVG as a third party library. see https://github.com/openMVG/openMVG/pull/346

**Comment by icoderaven** [comment]
I have a separate CMake build project, where I am trying to pull in the MVG library. My includes are 

#include "openMVG/sfm/sfm.hpp"
#include "openMVG/system/timer.hpp"

#include "third_party/cmdLine/cmdLine.h"
#include "third_party/stlplus3/filesystemSimplified/file_system.hpp"

#include "openMVG/image/image.hpp"
#include "openMVG/features/features.hpp"
#include "openMVG/matching/matcher_brute_force.hpp"
#include "openMVG/matching/matcher_kdtree_flann.hpp"
#include "openMVG/matching/matching_filters.hpp"
#include "openMVG_dependencies/nonFree/sift/SIFT_describer.hpp"

**Comment by pmoulon** [comment]
I will try to handle this the coming week.

**Comment by pmoulon** [comment]
Sorry for the late answer, but I have handle your request. Now is better than never.
=> Notice that you have to remove the **openMVG_dependencies** since it is already in the ${OPENMVG_INCLUDE_DIRS}

```
#include "openMVG/sfm/sfm.hpp"
#include "openMVG/system/timer.hpp"

#include "third_party/cmdLine/cmdLine.h"
#include "third_party/stlplus3/filesystemSimplified/file_system.hpp"

#include "openMVG/image/image.hpp"
#include "openMVG/features/features.hpp"
#include "openMVG/matching/matcher_brute_force.hpp"
#include "openMVG/matching/matcher_kdtree_flann.hpp"
#include "openMVG/matching/matching_filters.hpp"
#include "nonFree/sift/SIFT_describer.hpp"

int main(int argc, char **argv)
{
...
}
```

Please consider also add the SIFT library dependencies to your binary. Since it's a nonfree library it is not self contained in the ${OPENMVG_LIBRARIES} variable.
```
TARGET_LINK_LIBRARIES(main ${OPENMVG_LIBRARIES} vlsift)
```

Thanks to tell me if it works also for you.
=> Please consider the develop branch.
