### ISSUE TITLE
[software] SfMInit_ImageListing (images with empty Brand/Model field)

### ISSUE THREAD

**Issue by flm8620** [openMVG/openMVG#336]
Hi,
I put some jpeg without EXIF for input of "openMVG_main_SfMInit_ImageListing"
And one exception caught
=>
```
In exif, getModel() throw 'std::out_of_range'   what():  basic_string::erase
```
I think it's because in getModel():

std::string getModel() const
    {
      std::string smodel = exifInfo_.Model;
      // remove leading and trailing spaces
      smodel.erase(0, smodel.find_first_not_of(' '));
      smodel.erase(smodel.find_last_not_of(' '));
      return smodel;
    }

smodel is an empty string, and find_first_not_of(' ') returns string::npos.

**Comment by pmoulon** [comment]
Hi,
Can you share the image openmvg-team[AT]googlegroups.com in order to let me find and fix the issue?

**Comment by flm8620** [comment]
I have sent the image to openmvg-team[AT]googlegroups.com.

**Comment by pmoulon** [comment]
Thanks,
The error happens because the image have been edited by Photoshop.
This make some exif field empty (focal, camera maker...)
If you know your focal length and if it is fixed for all the image you can specified it:
- See here how to compute it by hand: http://openmvg.readthedocs.org/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata

I will take a look soon to make this type of image does not generate an error.
Thanks for the reporting.
PS: perhaps you can also mention to Photoshop to keep the initial EXIF data when saving.
=> Nice to see Coriolis meeting room again ;-)

**Comment by flm8620** [comment]
Thanks! In fact i have already set k matrix for images. And it works very well. We have compare the result of OpenMVG with the position of camera from lidar. And for a scene about 4~6 meter, the error of camera position is 1~9mm. There are also other factors which influence the error. We will finish our intership at 18 juillet, and we will give you a feedback of our test.
Leman FENG
Laila ZOUAKI

**Comment by pmoulon** [comment]
I will see with Pascal if we can make a session of debriefing all together.

**Comment by pmoulon** [comment]
Thanks for the image sharing.
It have help to detect three problems:
- a possible crash in getModel & getBrand function in case of empty string.
- if an image have no valid Brand & Model (Focal) field I must define the corresponding view to have an unknown intrinsic id.
- images with undefined intrinsic must remains with an undefined intrinsic (even in group mode)

**Comment by pmoulon** [comment]
@flm8620 The last commit in the develop branch must solves the problem.
:+1: Your issue helps me to detect two other problems ;-)
Looking forward to meet you soon.

Please close the issue if the changes looks and works fine for you too.
