### ISSUE TITLE
ComputeStructureFromKnownPoses  Segmentation Fault Core Dumped

### ISSUE THREAD

**Issue by priyanshuchandra** [openMVG/openMVG#338]
Hey, I am running the pipeline on different datasets. In some, it shows Segmentation Fault (Core Dumped) in Compute pairwise fundamental guided matching of ComputeStructureFromKnownPoses. 
Can you help me out, why is it so in some of the datasets. What might be the possible defect in Dataset? 
Thanks in advance! :)

**Comment by pmoulon** [comment]
Hi,
Perhaps the problem comes from the multithread environnement.
In order to check, Can you try to set your OpenMP thread count variable to 1 and rerun your experiment on your dataset?
set OMP_NUM_THREADS=1
The process will run slowly but with this test we will be able to check if the issue comes from parallelism or an other cause.

**Comment by pmoulon** [comment]
@priyanshuchandra , Any feedback following the suggestions?

**Comment by pmoulon** [comment]
No feedback... I close the issue.
