### ISSUE TITLE
SfM_Output missing

### ISSUE THREAD

**Issue by mojovski** [openMVG/openMVG#342]
Hi Pierre,
recently the project files for VisualSFM are not constructed anymore. Previously, I have used them to create an MVE-Scene. Is it possible to reactivate the SfM_Output in incremental or global BA?

Thanks alot!

**Comment by pmoulon** [comment]
Hi,
Since openMVG supports now different camera types we cannot export a SfM_Output converter... or we could export it only if the camera type is the RadialK3.
I don't understand why you have mentionned VisualSfM...
I would prefer to write a clean MVE ASCII export, like the existing converter (PMVS, CMPMVS...)

**Comment by pmoulon** [comment]
I close it, since this part will be covered by https://github.com/openMVG/openMVG/issues/325
