### ISSUE TITLE
Why do main_GlobalSfM/main_IncrementalSfM prescribe the geometric model used for matching?

### ISSUE THREAD

**Issue by LMescheder** [openMVG/openMVG#347]
Hi,
first thanks for all the work you put into creating this amazing open source library. While using it, I wondered why the two programs for sfm prescribe the geometric model for the matching (`main_GlobalSfM` wants me to use the essential matrix, `main_IncrementalSfM` the fundamental matrix). Indeed, I had issues getting the global method to work with matching based on the essential matrix (I assume this is due to inaccuracies in my intrinsics?), but using the fundamental matrix instead and changing the source code of `main_GlobalSfM` so that it looks for `matches.f.txt` instead of `matches.e.txt` made it work.

Wouldn't it make much more sense then to ask for the precise match file instead of the match dir as the `-m` parameter?

**Comment by pmoulon** [comment]
Hi,

Thanks for your kind word about OpenMVG.
Using approximate intrinsic make sometimes pure essential matrix estimation results worst than the pure fundamental matrix estimation.
That's why in your case if your use the matches.f.txt you have a better results.
Please note that you can use -g f option on main_ComputeMatches rename the file to matches.e.txt and run main_GlobalSfM without changing it's code.

The main idea of -m option is to specify the directory in which features are saved, and not directly point towards the matches.X.txt file, so fell free to rename the matches.f.txt file just after calling main_ComputeMatches during the time we find a nice solution.
