### ISSUE TITLE
NO sensor Width Database

### ISSUE THREAD

**Issue by seanXYZ** [openMVG/openMVG#370]
When I use the tool openMVG_main_SfMInit_ImageListing, I am surprised  by the parameter -d , because no sensor data input for visualSFM. 

Usage: openMVG_main_SfMInit_ImageListing
[-i|--imageDirectory]
[-d|--sensorWidthDatabase]
[-o|--outputDirectory]
[-f|--focal] (pixels)
[-k|--intrinsics] Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"
[-c|--camera_model] Camera model type:
	 1: Pinhole
	 2: Pinhole radial 1
	 3: Pinhole radial 3 (default)
[-g|--group_camera_model]
	 0-> each view have it's own camera intrinsic parameters,
	 1-> (default) view can share some camera intrinsic parameters

If I have not got sensor width database for my camera, Can I use openMVG to compute SFM ? HOW ? all the picture is captured by a same camera, I can get Camera matrix using OpenCV, Can I use  -f or -k  instead the sensor width data?

**Comment by pmoulon** [comment]
Hi @seanXYZ 
VisualSfM have made the choice to use fictional focal length value.
In OpenMVG the sensor_size can be used to compute a close to reality pixels focal length. When you have accurate value it's better to use them. That's why you can use the database of sensor width as an option. https://github.com/openMVG/openMVG/blob/master/src/software/SfM/cameraSensorWidth/cameraGenerated.txt

BTW, if you have images that have been captured by the same camera and same focal length you can set the pixel focal in this two way:
- the focal length in pixel manually using the -f option with the focal length in pixels. 
- the entire K matrix with the -k option

http://openmvg.readthedocs.org/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata

If you prefer the VisualSfM way that use fictional focal length you can take a look here, to have a GUESS option:
https://github.com/kaben/openMVG/commit/2b99f50f23c70c54afddac5b904e59f80925209f

**Comment by seanXYZ** [comment]
Thank you for your reply!  Actually, my images captured by a IP-camera(fixed focal length ) on my UAV. There is  no exif data, just YUV420 stream after decode. But, I got the K matrix through OpenCV.
So,  I would like to use -f option or -k option !
Thank you again ~

**Comment by pmoulon** [comment]
If you use the -f option the principal point will be set at middle of the image and let be refined by BA in the SfM process.
If your principal point is a bit far from the sensor you can use this constraint at the start by using the -K.

So, first, I would recommend to a simple test with the -f option.

**Comment by seanXYZ** [comment]
I have already tried both, Thank you a lot ~
but the result is not good, maybe the overlap between images is  a little small.
BTW, I want some data you have tested, Where can I download ?

**Comment by pmoulon** [comment]
Please note that you have binaries to export the detected/matched features:
=> openMVG_main_exportKeypoints
=> openMVG_main_exportMatches

You can use the tutorial in 
```
$ cd .../openMVG_Build/software/SfM
$ python tutorial_demo.py
```
It will checkout this dataset and run the toolchain:
https://github.com/openMVG/ImageDataset_SceauxCastle

Else you have high resolution datasets here:
https://github.com/rperrot/ReconstructionDataSet

If you need more help or investigation about your image dataset you share it here:
openmvg-team[AT]googlegroups.com

**Comment by seanXYZ** [comment]
Thank you ~ 
you are really kind~

**Comment by pmoulon** [comment]
I close the issue since answers to your questions have been provided.
