### ISSUE TITLE
Is mixing heterogeneous image sets advisable?

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#380]
Does `OpenMVG` handle image sets from different cameras gracefully?  Are there any problems associated with different input image sizes and 90^ rotations?

I've built [a tall tripod](http://www.insightdigital.org/entry/index.php?option=com_content&view=article&id=144&Itemid=437) to shoot photo matrices.  The main benefits of this uniform photo coverage close to a wall are:  stable view angles for SfM reconstruction and good coverage for occlusions, as shown below (side/front views):
![image](https://cloud.githubusercontent.com/assets/5424003/9559919/0f5c7654-4db3-11e5-857b-c417307e8899.png)
Alongside the regular array of photos taken with one camera, above, you'll also see many other photos, taken from the ground using another camera.

A secondary photo collection is helpful, of course, to increase the number of photographs covering the subject.  However, it's common enough for differences in camera intrinsics to create artifacts in a resulting isosurface.  Here's an example where mixing two photo sets as input to a `MVE` reconstruction yields noise at surface boundaries:

![image](https://cloud.githubusercontent.com/assets/5424003/9560043/62bd610c-4db6-11e5-987f-0f8f59eccc04.png)

In the example above, I believe the high-frequency 'dust' artifacts in the hieroglyphs are a result of a slight delta between reconstructions from two input photo sets / cameras.  View the above image at 100% (click twice) to see the artifacts more clearly.

Can anyone comment on the robustness of mixing heterogeneous image sets in `OpenMVG` or offer their experiences?

**Comment by pmoulon** [comment]
Hi @KevinCain,
First of all, thanks for the sharing and congrats for this amazing capture.

OpenMVG is able to deal with heterogeneous images and camera model, I have tested it on many scenes from here https://github.com/rperrot/ReconstructionDataSet that have various focal length.

I agree that it seems that there is some noise in the final reconstruction but it seems that picture registration is correct. I don't know yet if the error comes from the registration (openMVG) or from the dense reconstruction (MVE).

OpenMVG by default cluster the view in intrinsic groups regarding their optical properties. Perhaps this clustering creates tiny artefact in your scene (see -g option on SfMInit_ImageListing that is be default to true).

I would suggest this series of test in order to understand what is happening:
- re-run SfMInit with the -g 0 option. Rerun only the SfM part (since matches must not changes). Rerun MVEexporter and MVE.
If not change (the error is on another place)
- SfM + MVE with Landscape orientated images only (so remove all the images related to the bottom rows and the images shoot far from the wall) => to detects if error comes from portrait/landscape image mixing.
- SfM + MVE with landscape and portrait images orientated images only   => to detect if the far images create the noise

From the registration we saw that some picture where shoot with only a rotation motion (far away pictures). This 'rotation only' motion is not so good for 3D, since it does not involve parallax.

I invite you to continue the technical dicussion on openmvg-team[AT]googlegroups.com

**Comment by pmoulon** [comment]
Long time without new answer to this thread.
I just want to add that now we can run ComputeStructureFromKnownPoses with the -b option that will do a new BundleAdjustment on the triangulated geometry. It can helps to fix tiny misalignement.
