### ISSUE TITLE
Building openMVG in shared mode fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by LMescheder** [openMVG/openMVG#403]
Building openMVG (develop branch) with `-DBUILD_SHARED_LIBS=true` and `-DCMAKE_BUILD_TYPE=RELEASE` on Ubuntu 15.04 fails with the following error message:

```[ 87%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_sample_robustEssential
../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::system::Timer::elapsed() const'
../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::system::Timer::Timer()'
collect2: error: ld returned 1 exit status
openMVG_Samples/robust_essential/CMakeFiles/openMVG_sample_robustEssential.dir/build.make:116: recipe for target 'Linux-x86_64-RELEASE/openMVG_sample_robustEssential' failed
make[2]: *** [Linux-x86_64-RELEASE/openMVG_sample_robustEssential] Error 1
CMakeFiles/Makefile2:3401: recipe for target 'openMVG_Samples/robust_essential/CMakeFiles/openMVG_sample_robustEssential.dir/all' failed
make[1]: *** [openMVG_Samples/robust_essential/CMakeFiles/openMVG_sample_robustEssential.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by pmoulon** [comment]
Thanks for your feedback.
This build mode '-DBUILD_SHARED_LIBS=true' is experimental and I will be happy to help you on that point.

The message you obtain is strange since openmvg_system is asked in the dependecies here
https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/robust_essential/CMakeLists.txt#L8

You can try two options:
- move openmvg_system below openmvg_sfm here https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/robust_essential/CMakeLists.txt#L8

or

- add openmvg_system as a dependencies of openmvg_sfm https://github.com/openMVG/openMVG/blob/develop/src/openMVG/multiview/CMakeLists.txt#L31

Can you tell help if it helps?

**Comment by pmoulon** [comment]
I think you also forgot to enable this: -DOpenMVG_BUILD_SHARED=ON

**Comment by pmoulon** [comment]
@LMescheder 
Here the fix.
Can you tell me if it's ok for you too?

Using -DOpenMVG_BUILD_SHARED=ON only must be sufficient

**Comment by LMescheder** [comment]
Great, now it works. Thanks for the quick help!
