### ISSUE TITLE
Evaluating openMVG

### ISSUE THREAD

**Issue by alperaydemir** [openMVG/openMVG#404]
I'm trying to evaluate openMVG.

I've tried SfM_GlobalPipeline.py on images that I've collected (with no exif data) and even for the simplest images, the pipeline seems to fail. The images are somewhat distorted with a 4mm lens which can be one reason. Do the images have to have exif data, or else, how can one input intrinscis (and extrinsics) of cameras from the command line?

**Comment by pmoulon** [comment]
The Global pipeline need the approximate focal length of the image.
If you know the focal and the sensor size see here how to compute the focal in pixels http://openmvg.readthedocs.org/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata

If you don't know your sensor size, you can use as an approximation fpix = 1.2 * max(w,h)

In order to set it for the whole image set use the -f option on main_SfMInit_ImageListing
You can edit the SfM_GlobalPipeline.py and add "-f", "YourValue" to the command line.

Regarding usage of OpenMVS on the result:
you can compile openMVG, install it locally and use it in OpenMVS. So you can directly import the produced sfm_data.json with the InterfaceOpenMVG2 binary.

If you want to use the .baf format you must use openMVG_main_ConvertSfM_DataFormat.

**Comment by alperaydemir** [comment]
Thanks Pierre. I tried the `-f` option as you said but didn't help so much.

One data point is, looking at the .svg files, while there seems to be an adequate amount of putative matches, there's almost no geometric matches to be found, later on getting the error GlobalSfM:: Rotation Averaging failure!`

**Comment by pmoulon** [comment]
You can try to extract more SIFT keypoints per image.
Try to use the -p HIGH option on main_ComputeFeatures (please delete your old .feat and .desc and matches.X or use the -f 1 to force recomputation on main_ComputeFeatures & main_ComputeMatches else it will reload old files)

**Comment by pmoulon** [comment]
Any new feedback?

**Comment by alperaydemir** [comment]
Using the ULTRA function and `AKAZE_FLOAT` I managed to get better results.
I'd need to dive in more though to understand with visualizations of matches etc. to see why HIGH is not sufficient.

I consider this question answered, thanks!

**Comment by pmoulon** [comment]
relative point correspondences is a crucial point in SfM ;-)
Thanks for your feedback.
