### ISSUE TITLE
SfM: main_ComputeMatches with anything but -g e (f or h) results in Invalid matches file

### ISSUE THREAD

**Issue by mad-de** [openMVG/openMVG#408]
When using a different setting for -g with "openMVG_main_ComputeMatches" (f or h), results in error: "Invalid matches file"

Code:
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-r", "0.8", "-g", "f"] )
pMatches.wait()

**Comment by pmoulon** [comment]
It because you modify the script that are made to run a specific toolchain.

-g f (fundamental matrix filtering) => matches.f.txt => Sequential/Incremental SfM
-g e (essential matrix filtering) => matches.e.txt => GlobalSfM
-g h (homography filtering) => matches.h.txt

As you see each SfM pipeline expects a specific matches.X.txt file.
If you want try the one from matches.f.txt in GlobalSfM, rename it to matches.e.txt and everything will run fine.

**Comment by mad-de** [comment]
thanks for the help!
