### ISSUE TITLE
Cascade hashing licensing

### ISSUE THREAD

**Issue by donlk** [openMVG/openMVG#410]
Hey folks!
I noticed some time ago the Cascade hashing module was rewritten and moved to the internal structure from the nonFree section. Does this mean the current implementation is under MPL2 as well? As far as i recall, the algorithm is patented and free only for research. If so, should'n it be placed under nonFree?

thanks,
Andrew

**Comment by pmoulon** [comment]
Hi,
Actually cascade hashing is not patented.
Only the initial author code have a restriction for research only due to it's license.
Since the code have been totally rewritten from scratch there is problem of concurrency with the original code and the new licence of the code.
Note also that there is adaptation to make it support various descriptor types.

**Comment by donlk** [comment]
So that means using the module is not covering the main conception of this paper?
PCT/CN2014/076474

**Comment by pmoulon** [comment]
I was not aware of the patent request.
If I read well the patent request is still pending and not yet accepted.
