### ISSUE TITLE
[cameras] Add a fish-eye distortion model

### ISSUE THREAD

**Issue by ORNis** [openMVG/openMVG#423]
- [x] Add a simple fish-eye distortion model for a full frame fish-eye
- [x] Document and write tests for it
- [ ] Push a nice example somewhere

**Comment by stephane-lb** [comment]
Hi Ornis,

Looks really interesting ! Do you think that will work with the Google Jump Project ;-)

May the force be with you,

Stephane

**Comment by pmoulon** [comment]
It must work with 'fisheye' ActionCamera content.
So with some images acquired by the GoogleJump camera rig at multiple position.
Do you some go pro image sequence scenes we can test?

**Comment by stephane-lb** [comment]
Hi Pierre, 

Thanks for your quick answer.
I will make some this week-end and I will upload them for you.

Have a good week-end,

Stephane

**Comment by ORNis** [comment]
Thank you Stephane,
it would be really helpfull.
Romain

**Comment by stephane-lb** [comment]
Hi, 

Just made an update I have 2 actions cameras one is a go pro hero 4 black and the second one is a DareTang H9. I have to do some footage asap, and these are my first steps in photogrammetry, so I am looking of something to acquire which would be diffuse enough to provide a good dataset.

The second thing which is bad is the light. I am living in London and I am afraid the pictures would be too dark ... 

I will find a solution and then I will post again.

Have a great day,

Stéphane

**Comment by pmoulon** [comment]
Don't hesitate to share any dataset.
We will make experiments on them and see what is happening...

**Comment by pmoulon** [comment]
@stephane-lb Did you got the time to capture some datasets?

**Comment by ORNis** [comment]
I will try to do one small dataset next week.

**Comment by pmoulon** [comment]
@ORNis That would be very kind and a screenshot of the reconstruction could provide a nice demo images for the future release.

**Comment by igorti** [comment]
I have some UAV imagery over agriculture fields collected with GoPro 4 Silver. Would that help you?

**Comment by pmoulon** [comment]
@igorti Yes it can. Can share it on the Google Group or by emailing me?
Every fisheye like images can help to test the feature.

**Comment by igorti** [comment]
@pmoulon Great! I sent you an email.

**Comment by pmoulon** [comment]
@igorti Thanks I will try to make some run on this dataset within the week ;-)

**Comment by ORNis** [comment]
Sorry @pmoulon I was pretty busy fighting with 3D models this week ;).
I was planning this, https://fr.wikipedia.org/wiki/Basilique_Notre-Dame_de_Cl%C3%A9ry-Saint-Andr%C3%A9#/media/File:ClerySaintAndre02.jpg 
of course, not the full church but a small subset.

**Comment by pmoulon** [comment]
Thanks @ORNis ;-)

**Comment by stephane-lb** [comment]
Salut :-)

I am really sorry for the delay, I was not  well organised.
You could find some files here : vps.digital-lab.fr/Gopro.zip .
( Upload in progress, should be ok in 5 min )

Hope that will help !

Stephane

**Comment by pmoulon** [comment]
Thanks @stephane-lb 
The more dataset we have the better support we could provide.
For the moment datasets provided by @igorti and @fabiencastan clearly show that the camera model is working fine.
For one dataset provided by @pyp22, results was not satisfactory, but I think it is due to scene complexity... (I did not investigate on it yet).
Will try to provide feedback on those tests next week.

**Comment by stephane-lb** [comment]
@pmoulon If you need other kind of datasets ( for example if something wrong on this one), like stereo go pro or anything like that let me know. Now that the day are longer, I will be able to find enough light to capture things.

**Comment by pmoulon** [comment]
@stephane-lb 
Don't know why but the focal length field of your images are set to 0.
Will suppose that the focal was 5.0 or 3.0 mm.
I don't know if you shoot in narrow/medium or ultra wide mode...

**Comment by stephane-lb** [comment]
@pmoulon that was shooter in wide mode ( Sorry - did not know all this modes before )

**Comment by pmoulon** [comment]
@stephane-lb  No problem, we are all in the process of learning to use this new kind of action cameras

**Comment by pyp22** [comment]
Hi guys! 
Ast the weather calmed down I've planned to shoot this WE using my brand new samyang-8mm-f-3-5-umc-fish-eye-cs-ii-lens. I will upload scenes on my git dataset.

**Comment by pyp22** [comment]
See https://github.com/pyp22/datasets/tree/master/fisheye/Perros-Guirec_St_Nicolas%20Church for test i've done this WE.

Regards

PY

**Comment by pmoulon** [comment]
Thanks to @igorti and other (@pyp22, @ORNis)
The fisheye camera model have been validated as ok.

here some results on a dataset from @igorti (UAV dataset with a HERO4 Silver GoPro camera)

Resulting reconstruction with the Pinhole Radial 3 default camera model. We see the curved effect over camera position and ground => Distortion & Translation compensate each other).
![image](https://cloud.githubusercontent.com/assets/3235050/13672549/9f3ff05a-e6d5-11e5-8675-363465f79ffd.png)

Resulting reconstruction with the new Fisheye camera model. We see that the camera path & ground looks flat ;-)
![image](https://cloud.githubusercontent.com/assets/3235050/13672605/dc5489ba-e6d5-11e5-800a-8660f979f685.png)

Thanks @ORNis for this nice contribution.

Another validation was the large scale test about mixing camera model (Fisheye & Radial3) from @ORNis : 
![image](https://cloud.githubusercontent.com/assets/3235050/13672676/1b5899f8-e6d6-11e5-97f6-ecdf75bdcf0d.png)

**Comment by pyp22** [comment]
Great job guys! Thanks a lot!

**Comment by igorti** [comment]
Thanks for your effort! I did more tests on other GoPro and modified Canon S110 imagery  and the results were as good!

Would it be possible to somehow automatically detect fisheye camera model so that it wouldn't require manually providing this parameter?

**Comment by ORNis** [comment]
@igorti I'm afraid there is nothing in exif data that could help.

**Comment by pmoulon** [comment]
@igorti What you can do is a fast script that given some EIXF will configure the camera type as fish eye. Or even better if you have fixed focal length, use a previous calibration ;-)

**Comment by ORNis** [comment]
Pierre is right, you can do scripts or modification to openMVG based on a priori knowledge of your gears (it's the way I proceed myself, I put a threshold ~15mm). 
The mean of my previous message is that AFAIK we cannot do something fully generalist, automatic and robust based only on exif data (as for example, very short focal lengths exist for non-fisheye lenses too and regex matching for variants of the "fish-eye" string can fail for some lenses).

**Comment by fabiencastan** [comment]
Even if there is no robust way to do it, maybe using "fisheye" distortion **by default** for short focal length makes more sense than using "radial3" in all cases, isn't it?

**Comment by ORNis** [comment]
It's up to you @fabiencastan.I fear it can be a misanderstood feature.

**Comment by mshafiei** [comment]
Hello,
Unfortunately I didn't find any relative forum to ask this so I resort to ask it here.
I'm using a fisheye camera with FOV a bit less than 180 degrees. But I get too much outliers in the output such that the structures are hardly visible.

The camera is recording on 30 fps, there is a slow and broad translation, and the surface is highly textured.

I'm using -r 0.6 and -p HIGH for the SIFT features, the distortion coefficients and camera parameters are computed in OpenCV and then fed into OpenMVG. But even the outlier_removed outputs are so noisy.

**Comment by pmoulon** [comment]
Hi @mshafiei 
Thanks for your feedback.
I think your problem is related to not only the camera model but also from the scene acquisition.
I mean when you are using a video like acquisition, a lot of outlier can be kept even with epipolar filtering because the motion is along the epipolar line.

Here a list of think that you can check:

**1. camera model**
Are you sure you are using the openMVG FishEye camera model?
-> SfMInit with the -c 5 option
Are you sure that the camera model parameter are the same in the OpenCV model and in the OpenMVG one.

**Feature tracking:**
For the tracking issue, since you motion is very small from one frame to another you can model the point correspondence filtering to a point to point error metric, instead of using a point to line error metric. It means that you can use ```-g h``` instead of ```-g f``` or ```-g e``` in the main_ComputeMatches. Then you rename the matches.h.bin to matches.f/e.txt depending of the SfM pipeline you are using later on.
=> Else you can build your feature correspondences by using a a local feature tracker, like KLT (see the openMVG/openCV sample: see here https://plus.google.com/108029268028983704703/posts/6cX8yudfxmZ

Often the outlier tracks are short tracks, you can easily go along the structure and delete short tracks (those of length 2,3,4)... and you will see that the structure will appear more clearly

So as conclusion:
I suggest you to use the homography constrained putative matches filter in order to limit the wrong point association along the motion of your camera.
If you want exchange more about your dataset you can email me or send here a tiny sequences openmvg-team[AT]googlegroups.com

Please keep us informed about your test regarding the suggestions.
