### ISSUE TITLE
robust_essential_spherical + pipeline

### ISSUE THREAD

**Issue by FreakTheMighty** [openMVG/openMVG#433]
I'm curious what it will take (if it hasn't already been done) to integrate the spherical solver into the global or sequential pipelines?

**Comment by pmoulon** [comment]
Hi @FreakTheMighty,
Adding spherical camera must not be so hard but the problem is that it's not so easy for everyone to produce a large collection of spherical images of a place.

Using spherical images make the matching more complex, since the image distortion due to the projection make SIFT matching harder.

here you will find how to compute the relative pose between two spherical panorama.
https://github.com/openMVG/openMVG/tree/master/src/openMVG_Samples/robust_essential_spherical

**Comment by FreakTheMighty** [comment]
@pmoulon we have access to a [theta](https://theta360.com/en/), so it has gotten a lot easier for us take spherical images. I'm looking forward to testing the `robust_essential_spherical` sample with a pair of real images.

Looking forward, it would be very cool to apply this to a video or image sequence from the theta.

**Comment by FreakTheMighty** [comment]
@pmoulon if you're interested, here is a small series of photos using the theta https://goo.gl/photos/rWideVQwKn6rUYFB7

When I have a chance I'll play around with the sample you've provided.

**Comment by stuartpb** [comment]
Is https://github.com/openMVG/openMVG/tree/master/src/openMVG_Samples/robust_essential_spherical the path to the above-linked samples (which now yields a 404 error)?

**Comment by pmoulon** [comment]
The name was changed but the sample is still here https://github.com/openMVG/openMVG/tree/master/src/openMVG_Samples/multiview_robust_essential_spherical
