### ISSUE TITLE
openmvg_main_openMVG2MESHLAB not working?

### ISSUE THREAD

**Issue by solty91** [openMVG/openMVG#457]
Hi, 

Thanks for the amazing library. 

I am not too familiar with meshlab but know that it can render textures on top of reconstructed point clouds. I have used your SfM pipeline successfully and am aware of the ply files that are present too, but when I run openmvg2meshlab, the output mlp file contains nothing useful. Am I missing someting?

Secondly, following https://github.com/openMVG/openMVG/issues/185 about converting to pmvs, I downloaded the CMVS-PMVS binaries but the "Usage of the binaries" link you mention in the Readme,txt points to a non-existent page in terms of how to use pmvs. I am therefore not able to call on the pmvs2 executable. 

Thanks in advance!

**Comment by pyp22** [comment]
Hi @solty91,
About openmvg2meshlab, can you share the scene ? That might help ;)

You might be interrested in this Python script (commented) you can tweak & modify to suit your needs: 

https://github.com/pyp22/NuxSFM-2.0/tree/master/stable/computer-vision/mvg2pmvs

Regards

PY

**Comment by pmoulon** [comment]
Hi @solty91 
Thanks for your comment about OpenMVG.

The idea of openmvg2meshlab is just to generate a project file to be able to load some camera raster and the calibration point cloud in Meshlab.
So if you have a mesh, or compute a mesh from the point cloud, you can use meshlab raster projection function to compute a texture.

In order to use PMVS, you have first to export the scene to PMVS
https://openmvg.readthedocs.org/en/latest/software/MVS/PMVS/
And then to run the PMVS (CMVS) tools on the exported file.
See the Python script from @pyp22 for more details.

You can also use OpenMVS:
https://plus.google.com/108029268028983704703/posts/W3AoZxZTLTo

Everything is explained here
https://openmvg.readthedocs.org/en/latest/software/MVS/MVS/

**Comment by pmoulon** [comment]
@solty91 Any feedback?
