### ISSUE TITLE
unexpected results occasionally

### ISSUE THREAD

**Issue by avanindra** [openMVG/openMVG#471]
Hi ,

I am trying to understand OpenMVG. I have some datasets on which I run the openmvg pipeline. The problem I am facing is , sometimes the pipeline gives good and very accurate results , but other times on the same data set , it completely fails. The cameras I get looks like lying on bunch of straight lines. The cameras have focal lengths from exif. I want to understand at which stage actually the problem is occurring. My ultimate goal is to run global sfm pipeline on my own supplied tracks. But first I want to make sure that openmvg runs consistently on all of my datasets. I am testing the openmvg on all the three platforms , windows( vs2013 ) , mac( clang ) and linux( gcc ) and at least on mac and linux I face the same issue. 

I cloned the master and dev versions and tested on both of them.  I am running the pipeline with default settings , with sift features ( HIGH and ULTRA modes ). 

What could be the reason for this?...

I would really appreciate any help.

Regards,

Avanindra

**Comment by pmoulon** [comment]
Hi @avanindra,

It would be interesting that I can investigate a bit with you on your problematic dataset.
If the dataset is not too big you can share it to me at openmvg-team[AT]googlegroups.com

I think to two potential problems:
1. The initial solution is good but the BA make the scene so small that the PLY file and float discretisation make the camera and scene as straight line.
=> In order to see if the problem comes from this points you can look to the PLY file produced during the reconstruction (Be sure that you are looking on a reconstruction that have failed):
a. check the PLY file in that order and tell me when you see some lines...
cameraPath_translation_averaging.ply
initial_structure.ply
structure_00_refine_T_Xi.ply
structure_01_refine_RT_Xi.ply
structure_02_refine_KRT_Xi.ply
structure_03_outlier_removed.ply

If all the file looks ok all the time,
2. The problem can be due to some robust model estimation that sometimes works sometimes not. I think that sometimes some false relative motions remains and are not removed and so it makes the reconstruction fail.

But I think that 1. is the situation you will face.
The first files will look ok and the last will make the straight lines appears.

BTW, you can share here the reconstruction log, when it succeed and when it fails.
Perhaps I will see something from it.

**Comment by avanindra** [comment]
Forgive me if the question is stupid. How do I share the dataset at openmvg-team[AT]googlegroups.com?... 

Also I checked the four files you mentioned. They all contain points spreading towards infinity.

**Comment by avanindra** [comment]
![screenshot from 2016-02-04 23 58 10](https://cloud.githubusercontent.com/assets/2970678/12825364/f214703a-cb9b-11e5-9919-9f8ab92a35ba.png)
![screenshot from 2016-02-04 23 59 16](https://cloud.githubusercontent.com/assets/2970678/12825368/f58e71ac-cb9b-11e5-82a1-711c8727772d.png)

[openmvg_output.zip](https://github.com/openMVG/openMVG/files/118000/openmvg_output.zip)


I have attched two screen shots for initial_structure.ply and structure_00_refine_T_Xi.ply.

I have also uploaded all the output files you mentioned.

I looked closely the final ply file. It does appear to be discretized.

**Comment by avanindra** [comment]
here is the dataset , I just uploaded it on github:
https://github.com/avanindra/PhotogrammetryDataSets

**Comment by pmoulon** [comment]
Thanks I will look to it ASAP (in the coming days).
I definitively think that it's the BA that make the scene so small that saving the scene in float discretize too much the result.

**Comment by sweeneychris** [comment]
@pmoulon In Theia, I have a normalization function that can be called on reconstructions to avoid this. Basically, you compute the marginal median of point positions (i.e., median of each dimension) and move the origin of the reconstruction to this point. Then, you scale the reconstruction so that the average distance from each point to the new origin is something like 100 (or any value you choose).

**Comment by pmoulon** [comment]
Thanks @sweeneychris for the suggestion. By points, Did you mean 3D points or camera positions?
Another solution can be to normalize such that the minimal depth of any 3D point is superior to a given value.

**Comment by sweeneychris** [comment]
I usually normalize the reconstruction based only on the 3D points since those are the primary interest in most cases.

**Comment by pmoulon** [comment]
@avanindra 
The problem is a scaling issue.
Will try to have a more in depth look in the coming weeks.

**Comment by avanindra** [comment]
@pmoulon 

I copied code from global sfm pipeline in a single main.cpp , and removed all the codes and check which were not needed. Following are settings I am using:

Feature detector : SIFT
Feature matcher:  fast Cascade hasher 
match filter : fundamental matrix
global sfm: rotation averaging L1 , translation soft l1

I am noticing a lot of unexpectedness in results. At time it would align all the images , other time the pipeline would filter almost half or 3 quarter of the cameras. And the results are consistent on multiple data sets. All my datasets have rich textures , incremental pipelines run smoothly on them. They have reliable focal lengths from exif.

The model estimators should not have this kind of drastic effects on camera estimation and I am bit doubtful that it is due to model estimators , because I also fed filtered matches from my custom pipeline and got similar unexpected results.

I also notice the cardinality of camera edges before input to rotation averaging , they only vary slightly in each run. And in almost all the cases it is the rotation averaging which filters out all the cameras.  

I can upload the code , if you want to check it if I am missing something in the code itself. 

The only thing I want is to openMVG perform consistently on datasets with reliable exifs. 

thank you for looking into the issue.

**Comment by pmoulon** [comment]
@avanindra thanks for your dedication in order to help to understand what is happening.

In order to understand at which step the process discard some your images can you look to some statistics between different run:
a. The mean and median rotation error => "Statistics about rotation triplets:"
b. The number of triplets and the number of estimated ones: "#Relative translations estimates ... computed from ..."

We must see if the big difference is at step a or b.

**Comment by sweeneychris** [comment]
@pmoulon The statistics you've asked for should provide good detail for analysis. But I wanted to point out that my L1-IRLS rotation solver is much more stable after I switched to using an ADMM implementation for the L1 step. The interior point method I was using before was sometimes unstable for large scale dataset

**Comment by pmoulon** [comment]
@sweeneychris Thanks for your pointer and feedback.
I admit that I use all the time the L2 rotation averaging + L2 non linear refinement. It provides decent results.
I was thinking since many month to add a new L1 solver to OpenMVG (and you are right ADMM is a good candidate. Better than the interior point - L1magic).
I think I will rewrite L1-IRLS to use it.

**Comment by sweeneychris** [comment]
Feel free to use my ADMM L1 solver. It is basically a port of the one from this page: http://web.stanford.edu/~boyd/papers/admm/

The beauty of ADMM is that it is so simple to implement (way more simple than interior point method) and it converges to a "good" solution very quickly.

**Comment by avanindra** [comment]
@pmoulon <https://github.com/pmoulon>

Hi ,

I would put this thread on hold , as I am bit on clock right now. As soon
as I get some free time , I would report detail of openmvg run. I would
very much like to see this through.

Thanks for the replies.

Regards,

Avanindra

**Comment by pmoulon** [comment]
@avanindra Results must be more stable now in the develop branch.

**Comment by avanindra** [comment]
Hi,

I did extensive testing with develop branch and I confirm that the global sfm results are quite stable. Specially for large number of photos ( even when focal lengths are unknown ) , I tested upto 650 photographs and found results quite good. Though translation averaging get slower quickly for larger number photographs.

The SFM fails in case the scene has repetitive structures , it produces noisy results in those cases. And I haven't found any work around for those , so if you can give any recommendation  , I would highly appreciate it.

**Comment by pmoulon** [comment]
Thanks for coming back and sharing your experience feedback.
I'm happy to hear that results are now more stable for your datasets.

You can try to augment the minimum track length in order to avoid short track that must be more contaminated.

SfM with repetitive structure is still a real challenge.
And there is plenty of paper that try to tackle the problem:
What can missing correspondences tell us about 3D structure and motion? IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2008. Preprint (PDF)
http://research.microsoft.com/pubs/147401/roberts-cvpr11.pdf
http://people.inf.ethz.ch/acohen/papers/cohenCVPR12.pdf
https://www.cs.unc.edu/~jheinly/publications/eccv2014-heinly.pdf
