### ISSUE TITLE
openmvg_main_openMVG2PMVS can't export gray images

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#482]
In main_ComputeFeatures.cpp, image object is declared with gray Image.While in main_openMVG2PMVS.cpp , image object is declared with RGBImage. In this situation, the original images in gray type cannot be exported.

**Comment by pmoulon** [comment]
I don't remember if PMVS support gray image.
BTW, we can update openMVG2PMVS to support gray image as well.
Would you try to make a PR for this?

**Comment by ORNis** [comment]
No it does not support it. at least the original version.

**Comment by pmoulon** [comment]
You are right, PMVS support only COLOR images as input
https://github.com/pmoulon/CMVS-PMVS/blob/master/program/base/image/image.cc#L520

But we can make main_openMVG2PMVS.cpp read the gray image and export it as a graycolor one (GRAY => RGB with the same values).

**Comment by ORNis** [comment]
From my experience, in dense correlation phase, working with higher dynamic can improve the result... it can be helpful but the improvement is not dramatic. As  stated by @pmoulon tone mapping is a good way to get informations from highlights and dark areas, it can be critical in some configurations.

**Comment by whuaegeanse** [comment]
Thanks.

**Comment by pmoulon** [comment]
You closed this issue with no conclusion.
Do you consider it is not necessary to realize the proposed fix (if an image is gray, openMVG2PMVS will export a RGB gray image)?

**Comment by whuaegeanse** [comment]
I have fixed this small issue. Because of being not  familiar with github, I cannot make a pull request.
The way to fix the issue is as follow:
In  file: image_io.hpp
template<>
 inline int ReadImage(const char * path, Image<RGBColor> * im)
-    return 0;
+  if (res == 1 && depth == 1)
+  {
+	  //-- Must convert Gray to RGB
+	  std::vector<unsigned char> ptrGrayColor(ptr.size()*3);
+	  for (int i = 0; i < h; ++i)
+	  {
+		  unsigned char *pRowGrayColor = &ptrGrayColor[i*w*3];
+		  unsigned char *pRow = &ptr[i*w];
+		  for (int j = 0; j < w; ++j)
+		  {
+			  pRowGrayColor[j * 3] = pRow[j];
+			  pRowGrayColor[j * 3 + 1] = pRow[j];
+			  pRowGrayColor[j * 3 + 2] = pRow[j];
+		  }
+	  }
+	  RGBColor * ptrCol = (RGBColor*)&ptrGrayColor[0];
+	  Image<RGBColor> rgbaColIm;
+	  (*im) = Eigen::Map<Image<RGBColor>::Base>(ptrCol, h, w);
+  }
+  else
+	  return 0;

**Comment by pmoulon** [comment]
Ok, so when you read a gray image you force the pixel to be the same.
Your modification can be applied here:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io.hpp#L140

The existing behavior was done to show to the user that he tries to read an image that have less pixel depth that the one he needs.
Will think if we integrate or not this modification. Since everytime you want read image you will multiply by three the needed memory.

**Comment by whuaegeanse** [comment]
Thanks for your quick reply. 
Yes, it's necessary to integrate this modification. When  processing big images such as  aerial image, I suppose that GDAL will be a good solution for image IO.

**Comment by iskandervito** [comment]
Dear
I have similar issue when trying to export to PMVS format. I run the  openMVG_main_openMVG2PMVS with gray JPEG image and I got this message : Empty JPEG image (DNL not supported).
![error_openmvg2pmvs](https://cloud.githubusercontent.com/assets/14975338/22522292/57947e72-e8bb-11e6-8e2c-6c55bb159e11.png)

I think this issue is related to what was explained in the previous comment.
Do you forsee an update of a fix for this issue or should we apply the workaround explained by whuaegeanse.

Thanks
Iskander

**Comment by pmoulon** [comment]
@iskandervito You can take inspiration here https://github.com/openMVG/openMVG/commit/4e442333f537064c2fb96440e7d09af0860ee0a8 in order to modify openMVG_main_openMVG2PMVS to be able to use this binary with gray image.
1. If color image reading fails
2. try to read a gray based image
