### ISSUE TITLE
Question on coordinate system of output points

### ISSUE THREAD

**Issue by vfdev-5** [openMVG/openMVG#501]
What are the units and the coordinate system of the output points from reconstruction procedure? For example, in a robust.ply file there are points and camera coordinates. How can we interpret these values : how defined 3D zero point and what are the units? 

Thank you in advance fot the answer and for sharing this project as opensource !
Cheers

**Comment by pmoulon** [comment]
Thanks for your interest towards OpenMVG.

The reconstruction is up to a scale and a translation to the true measurements.
You can rescale & set an origin to the reconstruction by using the GCP (Ground Control Points):
http://openmvg.readthedocs.org/en/latest/software/ui/SfM/control_points_registration/GCP/

Later simpler tools will certainly be develop in order to ease set a known origin & scale.
