### ISSUE TITLE
"stdint.h" shoud be included in file tbmr_test.cpp and rand_sampling.hpp

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#541]
uint8_t will not be treated as a known type unless the file  "stdint.h" be included.
When building in visual studio 2013, errors occurs.

**Comment by pmoulon** [comment]
does it works if you include ```#include <cstdint>```?

**Comment by whuaegeanse** [comment]
I suppose that it works. I use  #include <stdint.h>.

**Comment by rperrot** [comment]
<cstdint> is C++, stdint.h is C. Prefer <cstdint> 

@pmoulon Just looking at the standard, we should test if uint8_t is availlable because it is said to be optionnal (uint_least8_t is mandatory, and may be prefered, because of it's availability but it's size may not be constant between platforms, arrrg !). This is not a big issue since unit8_t is available on gcc/clang/msvc but with exotic platform, this may cause some trouble. (maybe we can stay as it is).

**Comment by pmoulon** [comment]
Since build is ok in the VisualStudio Continuous integration, I'm closing the issue.
Feel free to reopen, if you have any other questions.
