### ISSUE TITLE
Using OpenMVG for human body measurement

### ISSUE THREAD

**Issue by gbrault** [openMVG/openMVG#548]
Hello,

thanks to let this software open source first!

I am just wondering if one could use your software to build 3D models of people?

How many cameras would be needed to do a 3D Scan in a raisonnable time?

Thx

**Comment by pmoulon** [comment]
Hi,
Thanks for your kind words about OpenMVG.

You can use photogrammetry software to build 3D models of people.
You must be aware that often you need high resolution images to capture the body details (since the skin and often some clothes does not have plenty of texture that is required for feature detection & matching across the images).

You can see some body scanner here http://www.pi3dscan.com/ that is made from Raspberry pi camera cluster. There is many camera and they use a projector in order to help the picture registration.
Often people use a lot of synchronized camera https://www.google.fr/search?q=photogrammetry+body&espv=2&biw=1920&bih=962&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjprMjrvL7MAhXEBywKHQ2BDXAQsAQIJA

here you have some tips to enhance the results on faces
http://3dcienciasaude.com.br/blog/?p=70

The idea regarding the number of camera, is that you must have each part of the subject you want to catpure in at least 3 picture, in the pixel ratio you want (the area of your model covered by the pixel sensor is the limit you can reach).

Hoping it helps.

**Comment by gbrault** [comment]
Thx for the advise!
