### ISSUE TITLE
While running SfM_SequentialPipeline.py or SfM_GlobalPipeline.py smf_data.bin and robust.bin files not being created.

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#559]
Hello, I'm a bit new at this and have tried to run SfM_SequentialPipeline.py and SfM_GlobalPipeline.py on a fresh install and both fail to create smf_data.bin and robust.bin.  The following errors come up.

> There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
> 5. Colorize Structure
> 
> The input SfM_Data file "/home/user/Pictures/MVGProject/reconstruction_sequential/sfm_data.bin" cannot be read.
> 6. Structure from Known Poses (robust triangulation)
> Compute Structure from the provided poses
> 
> The input SfM_Data file "/home/user/Pictures/MVGProject/reconstruction_sequential/sfm_data.bin" cannot be read.
> 
> The input SfM_Data file "/home/user/Pictures/MVGProject/reconstruction_sequential/robust.bin" cannot be read.
> 

Is there a way I can find out what's causing this?  I need the .bin files for use in openMVS.

**Comment by whuaegeanse** [comment]
The camera of the input images does not exist in the file "sensor_width_camera_database.txt". There are two ways to resolve the problem:
1. add option focal length like this : 
`pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params], "-f", "3500")`;
2. add the camera info to the camera db file:sensor_width_camera_database.txt;

**Comment by jpwhitney** [comment]
Thanks for the quick reply!
Your explanation was very helpful.  I ended up adding exif data to my files with exiftool as they did not have any model or focal length information.
I am using these as more of a test of concept than as an actual project, but in the future it'll likely be useful to add the camera sensor info to the "sensor_width_camera_database.txt" file as you mentioned in your comment above.
@whuaegeanse

**Comment by pmoulon** [comment]
I close the issue, since the solution was provided by the community.

**Comment by joshuajano** [comment]
Dear Mr. Pierre
Thank you for help, because i have solved with the issue and when i launched "ctest --output-on-failure -j", i got output like this:
      Start  1: openMVG_test_Camera_Pinhole
 1/80 Test  #1: openMVG_test_Camera_Pinhole ..............................   Passed    0.16 sec
      Start  2: openMVG_test_Camera_Pinhole_Radial
 2/80 Test  #2: openMVG_test_Camera_Pinhole_Radial .......................   Passed    1.46 sec
      Start  3: openMVG_test_Camera_Pinhole_Brown
 3/80 Test  #3: openMVG_test_Camera_Pinhole_Brown ........................   Passed    0.46 sec
      Start  4: openMVG_test_Camera_Pinhole_Fisheye
 4/80 Test  #4: openMVG_test_Camera_Pinhole_Fisheye ......................   Passed    0.67 sec
      Start  5: openMVG_test_Camera_Spherical
 5/80 Test  #5: openMVG_test_Camera_Spherical ............................   Passed    0.51 sec
      Start  6: openMVG_test_Camera_Subset_Parametrization
 6/80 Test  #6: openMVG_test_Camera_Subset_Parametrization ...............   Passed    0.13 sec
      Start  7: openMVG_test_Camera_IO
 7/80 Test  #7: openMVG_test_Camera_IO ...................................   Passed    0.05 sec
      Start  8: openMVG_test_exif_IO
 8/80 Test  #8: openMVG_test_exif_IO .....................................   Passed    0.08 sec
      Start  9: openMVG_test_ParseDatabase
 9/80 Test  #9: openMVG_test_ParseDatabase ...............................   Passed    0.07 sec
      Start 10: openMVG_test_features
10/80 Test #10: openMVG_test_features ....................................   Passed    0.02 sec
      Start 11: openMVG_test_image_describer
11/80 Test #11: openMVG_test_image_describer .............................   Passed    0.05 sec
      Start 12: openMVG_test_akaze
12/80 Test #12: openMVG_test_akaze .......................................   Passed    0.96 sec
      Start 13: openMVG_test_mser
13/80 Test #13: openMVG_test_mser ........................................   Passed    0.25 sec
      Start 14: openMVG_test_sift
14/80 Test #14: openMVG_test_sift ........................................   Passed    0.39 sec
      Start 15: openMVG_test_tbmr
15/80 Test #15: openMVG_test_tbmr ........................................   Passed    0.11 sec
      Start 16: openMVG_graph_test_connectedComponent
16/80 Test #16: openMVG_graph_test_connectedComponent ....................   Passed    0.04 sec
      Start 17: openMVG_graph_test_triplet_finder
17/80 Test #17: openMVG_graph_test_triplet_finder ........................   Passed    0.01 sec
      Start 18: openMVG_test_image
18/80 Test #18: openMVG_test_image .......................................   Passed    0.01 sec
      Start 19: openMVG_test_image_drawing
19/80 Test #19: openMVG_test_image_drawing ...............................   Passed    0.02 sec
      Start 20: openMVG_test_image_integral
20/80 Test #20: openMVG_test_image_integral ..............................   Passed    0.04 sec
      Start 21: openMVG_test_image_io
21/80 Test #21: openMVG_test_image_io ....................................   Passed    0.19 sec
      Start 22: openMVG_test_image_filtering
22/80 Test #22: openMVG_test_image_filtering .............................   Passed    0.14 sec
      Start 23: openMVG_test_image_resampling
23/80 Test #23: openMVG_test_image_resampling ............................   Passed    7.09 sec
      Start 24: openMVG_test_linearProgramming
24/80 Test #24: openMVG_test_linearProgramming ...........................   Passed    0.22 sec
      Start 25: openMVG_lInftyCV_test_triangulation
25/80 Test #25: openMVG_lInftyCV_test_triangulation ......................   Passed    0.39 sec
      Start 26: openMVG_lInftyCV_test_resection
26/80 Test #26: openMVG_lInftyCV_test_resection ..........................   Passed    0.26 sec
      Start 27: openMVG_lInftyCV_test_resection_robust
27/80 Test #27: openMVG_lInftyCV_test_resection_robust ...................   Passed    2.16 sec
      Start 28: openMVG_lInftyCV_test_global_translations_fromTriplets
28/80 Test #28: openMVG_lInftyCV_test_global_translations_fromTriplets ...   Passed    0.26 sec
      Start 29: openMVG_lInftyCV_test_global_translations_fromTij
29/80 Test #29: openMVG_lInftyCV_test_global_translations_fromTij ........   Passed    0.30 sec
      Start 30: openMVG_lInftyCV_test_tijsAndXis
30/80 Test #30: openMVG_lInftyCV_test_tijsAndXis .........................   Passed    0.38 sec
      Start 31: openMVG_lInftyCV_test_tijsAndXis_outlier
31/80 Test #31: openMVG_lInftyCV_test_tijsAndXis_outlier .................   Passed    0.33 sec
      Start 32: openMVG_geodesy_test_geodesy
32/80 Test #32: openMVG_geodesy_test_geodesy .............................   Passed    0.01 sec
      Start 33: openMVG_test_convex_hull
33/80 Test #33: openMVG_test_convex_hull .................................   Passed    0.01 sec
      Start 34: openMVG_test_rigid_transformation3D_srt
34/80 Test #34: openMVG_test_rigid_transformation3D_srt ..................   Passed    0.05 sec
      Start 35: openMVG_test_plane_estimation_kernel
35/80 Test #35: openMVG_test_plane_estimation_kernel .....................   Passed    0.03 sec
      Start 36: openMVG_test_half_space_intersection
36/80 Test #36: openMVG_test_half_space_intersection .....................   Passed    0.29 sec
      Start 37: openMVG_test_frustum_intersection
37/80 Test #37: openMVG_test_frustum_intersection ........................   Passed    0.37 sec
      Start 38: openMVG_test_frustum_box_intersection
38/80 Test #38: openMVG_test_frustum_box_intersection ....................   Passed    0.46 sec
      Start 39: openMVG_test_matching
39/80 Test #39: openMVG_test_matching ....................................   Passed    0.05 sec
      Start 40: openMVG_test_matching_filters
40/80 Test #40: openMVG_test_matching_filters ............................   Passed    0.01 sec
      Start 41: openMVG_test_indMatch
41/80 Test #41: openMVG_test_indMatch ....................................   Passed    0.03 sec
      Start 42: openMVG_test_metric
42/80 Test #42: openMVG_test_metric ......................................   Passed    0.01 sec
      Start 43: openMVG_test_Pair_Builder
43/80 Test #43: openMVG_test_Pair_Builder ................................   Passed    0.02 sec
      Start 44: openMVG_test_triangulation
44/80 Test #44: openMVG_test_triangulation ...............................   Passed    0.02 sec
      Start 45: openMVG_test_triangulation_nview
45/80 Test #45: openMVG_test_triangulation_nview .........................   Passed    0.06 sec
      Start 46: openMVG_test_solver_affine
46/80 Test #46: openMVG_test_solver_affine ...............................   Passed    0.01 sec
      Start 47: openMVG_test_solver_essential_eight_point
47/80 Test #47: openMVG_test_solver_essential_eight_point ................   Passed    0.03 sec
      Start 48: openMVG_test_solver_essential_five_point
48/80 Test #48: openMVG_test_solver_essential_five_point .................   Passed    0.08 sec
      Start 49: openMVG_test_solver_essential_three_point
49/80 Test #49: openMVG_test_solver_essential_three_point ................   Passed    0.00 sec
      Start 50: openMVG_test_solver_fundamental_kernel
50/80 Test #50: openMVG_test_solver_fundamental_kernel ...................   Passed    0.01 sec
      Start 51: openMVG_test_solver_homography_kernel
51/80 Test #51: openMVG_test_solver_homography_kernel ....................   Passed    0.03 sec
      Start 52: openMVG_test_solver_resection_kernel
52/80 Test #52: openMVG_test_solver_resection_kernel .....................   Passed    0.06 sec
      Start 53: openMVG_test_solver_translation_knownRotation_kernel
53/80 Test #53: openMVG_test_solver_translation_knownRotation_kernel .....   Passed    0.03 sec
      Start 54: openMVG_test_rotation_averaging
54/80 Test #54: openMVG_test_rotation_averaging ..........................   Passed    0.16 sec
      Start 55: openMVG_test_translation_averaging
55/80 Test #55: openMVG_test_translation_averaging .......................   Passed    0.21 sec
      Start 56: openMVG_test_extract_columns
56/80 Test #56: openMVG_test_extract_columns .............................   Passed    0.00 sec
      Start 57: openMVG_test_numeric
57/80 Test #57: openMVG_test_numeric .....................................   Passed    0.02 sec
      Start 58: openMVG_test_poly
58/80 Test #58: openMVG_test_poly ........................................   Passed    0.02 sec
      Start 59: openMVG_test_lm
59/80 Test #59: openMVG_test_lm ..........................................   Passed    0.02 sec
      Start 60: openMVG_test_l1_solver
60/80 Test #60: openMVG_test_l1_solver ...................................   Passed    0.13 sec
      Start 61: openMVG_test_rand_sampling
61/80 Test #61: openMVG_test_rand_sampling ...............................   Passed    0.00 sec
      Start 62: openMVG_test_robust_estimator_lineKernel
62/80 Test #62: openMVG_test_robust_estimator_lineKernel .................   Passed    0.00 sec
      Start 63: openMVG_test_robust_estimator_MaxConsensus
63/80 Test #63: openMVG_test_robust_estimator_MaxConsensus ...............   Passed    0.06 sec
      Start 64: openMVG_test_robust_estimator_Ransac
64/80 Test #64: openMVG_test_robust_estimator_Ransac .....................   Passed    0.01 sec
      Start 65: openMVG_test_robust_estimator_ACRansac
65/80 Test #65: openMVG_test_robust_estimator_ACRansac ...................   Passed    0.22 sec
      Start 66: openMVG_test_gms_filter
66/80 Test #66: openMVG_test_gms_filter ..................................   Passed    0.01 sec
      Start 67: openMVG_test_tracks
67/80 Test #67: openMVG_test_tracks ......................................   Passed    0.03 sec
      Start 68: openMVG_test_global_quantile_gain_offset_alignment
68/80 Test #68: openMVG_test_global_quantile_gain_offset_alignment .......   Passed    0.22 sec
      Start 69: openMVG_test_progress
69/80 Test #69: openMVG_test_progress ....................................   Passed    0.05 sec
      Start 70: openMVG_test_sfm_data_io
70/80 Test #70: openMVG_test_sfm_data_io .................................   Passed    0.13 sec
      Start 71: openMVG_test_sfm_data_BA
71/80 Test #71: openMVG_test_sfm_data_BA .................................   Passed    0.27 sec
      Start 72: openMVG_test_sfm_data_utils
72/80 Test #72: openMVG_test_sfm_data_utils ..............................   Passed    0.02 sec
      Start 73: openMVG_test_sfm_data_filters
73/80 Test #73: openMVG_test_sfm_data_filters ............................   Passed    0.05 sec
      Start 74: openMVG_test_sfm_data_graph_utils
74/80 Test #74: openMVG_test_sfm_data_graph_utils ........................   Passed    0.06 sec
      Start 75: openMVG_test_global_SfM
75/80 Test #75: openMVG_test_global_SfM ..................................   Passed    2.30 sec
      Start 76: openMVG_test_sequential_SfM
76/80 Test #76: openMVG_test_sequential_SfM ..............................   Passed    0.51 sec
      Start 77: openMVG_test_sequential_SfM2
77/80 Test #77: openMVG_test_sequential_SfM2 .............................   Passed    0.34 sec
      Start 78: openMVG_test_stellar_SfM
78/80 Test #78: openMVG_test_stellar_SfM .................................   Passed    0.32 sec
      Start 79: openMVG_test_split
79/80 Test #79: openMVG_test_split .......................................   Passed    0.01 sec
      Start 80: openMVG_test_dynamic_bitset
80/80 Test #80: openMVG_test_dynamic_bitset ..............................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 80

Total Test time (real) =  24.33 sec

**Comment by joshuajano** [comment]
But now, i am trying to run this code "python SfM_SequentialPipeline.py [full path image directory] [resulting directory]".  At the end, i got the same error as https://github.com/openMVG/openMVG/issues/1218 and i have tried the solution, but the error is still the same.
1. Intrinsics analysis
 You called : 
/home/joshuajano/openMVG_Build/Linux-x86_64-release/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/joshuajano/ReconstructionDataSet/EchillaisChurch/
--sensorWidthDatabase /home/joshuajano/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/joshuajano/Desktop/Output_image/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 353
usable #File(s) listed in sfm_data: 353
usable #Intrinsic(s) listed in sfm_data: 39
2. Compute features
 You called : 
/home/joshuajano/openMVG_Build/Linux-x86_64-release/openMVG_main_ComputeFeatures
--input_file /home/joshuajano/Desktop/Output_image/matches/sfm_data.json
--outdir /home/joshuajano/Desktop/Output_image/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
3. Compute matches
 You called : 
/home/joshuajano/openMVG_Build/Linux-x86_64-release/openMVG_main_ComputeMatches
--input_file /home/joshuajano/Desktop/Output_image/matches/sfm_data.json
--out_dir /home/joshuajano/Desktop/Output_image/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
	 PREVIOUS RESULTS LOADED; #pair: 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 0
 Images Id: 

------------------
TrackLength, Occurrence

5. Colorize Structure

The input SfM_Data file "/home/joshuajano/Desktop/Output_image/reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/home/joshuajano/Desktop/Output_image/reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "/home/joshuajano/Desktop/Output_image/reconstruction_sequential/robust.bin" cannot be read.

**Comment by saibeidex1** [comment]
There is no defined intrinsic data in order to compute an essential matrix for the initial pair
这个问题是因为图片的属性里没有带相机的参数，后来用官网下载的带相机参数的图片后，这个问题就好了。

**Comment by friendship1** [comment]
https://github.com/openMVG/openMVG/issues/559#issuecomment-219625095
> The camera of the input images does not exist in the file "sensor_width_camera_database.txt". There are two ways to resolve the problem:
> 
> 1. add option focal length like this :
>    `pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params], "-f", "3500")`;
> 2. add the camera info to the camera db file:sensor_width_camera_database.txt;

I think first there is a minor typo.
  `pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-f", "3500"])`
this is right one.
