### ISSUE TITLE
SfM problem: two cameras position can't be too close ?

### ISSUE THREAD

**Issue by ACWrong** [openMVG/openMVG#567]
Hi,
    I try to reconstruction from a video. I got the some frames and found that if the camera positions are too close then neither incremental / global SfM algorithm cannot get the result. Why ?
Thanks.

**Comment by pmoulon** [comment]
When camera are very close, the motion does not allow triangulation (since there is only a rotational motion)?

But if you have some motion and during your motion there is a lot of camera at the same place it is not a problem.

As the word Structure from Motion tell it, we need camera motion to guess the scene structure point.

**Comment by ACWrong** [comment]
Thank you very much!
