### ISSUE TITLE
Is it possible to use openMVG to build 3d model of room?

### ISSUE THREAD

**Issue by UlfR** [openMVG/openMVG#574]
Hi, openMVG Team,

could i use openMVG to build model of room?
 If so, what are best params for focal width, ComputeFeatures, ComputeMatches?

**Comment by pmoulon** [comment]
Hi @UlfR 
You can use it, but you will need some textured walls in order to establish features matches between adjacent pictures.

I recommend to use a short focal length (that will provide you a larger FoV).
I.E: You can use GoPro in still picture capture (shoot automatically all seconds) while you are moving and so use the FishEye camera model in OpenMVG.
- ComputeFeatures -> Set the preset to HIGH or ULTRA in order to extract more features and so enable more matches between images pairs. (use the -n option to extract features for many image at once)
- ComputeMatches -> No particular settings, run ANNL2 matcher can provide more matches but it is slower.

If the room is textured you can obtain results similar to https://goo.gl/photos/r7fEgd6Hobftw9MC6

Don't hesitate to share your experiments with us.

**Comment by UlfR** [comment]
@pmoulon, thanks for your answer! Are any advices about the best point of shooting? From corners, center,  doorway?

**Comment by pmoulon** [comment]
You must avoid rotating around a single point.
The best is to shoot from the maximum distance.

A path like the following  + some convergent view for each wall can be sufficient.
![image](https://cloud.githubusercontent.com/assets/3235050/16041708/4157e9f4-3237-11e6-94de-dd8a857360fa.png)

Adding some panorama like sequence can help for image registration:
![image](https://cloud.githubusercontent.com/assets/3235050/16041757/8602c2b8-3237-11e6-9717-f8451a424034.png)

**Comment by UlfR** [comment]
Thanks a lot!
