### ISSUE TITLE
GoPro SFM Problem

### ISSUE THREAD

**Issue by shuguohui** [openMVG/openMVG#578]
here is my gopro dataset(HERO3+ Black Edition).

https://github.com/shuguohui/SFM-Datasets/tree/master/GroPro/minibus

i use openmvg default config,bug can't get the correct result,i check the match result and find the match-pairs is too little.
graph 1 {
node [shape=circle]
  n16
  n15
  n14
  n13
  n12
  n11
  n10
  n9
  n8
  n7
  n6
  n5
  n4
  n3
  n2
  n1
  n0
  n3 --  n2
  n4 --  n2
  n6 --  n5
  n7 --  n6
  n10 --  n8
  n10 --  n9
  n11 --  n10
  n12 --  n8
  n12 --  n9
  n12 --  n10
  n12 --  n11
  n13 --  n12
  n14 --  n8
  n14 --  n9
  n15 --  n7
  n15 --  n8
  n16 --  n8
  n16 --  n15
}

btw, the photoscan software can got the correct result.so i think the image itself has no problem

**Comment by pmoulon** [comment]
Hi @shuguohui,

Thank you for the dataset sharing.
Here the explanation and the road to a successful reconstruction.

1. The camera model you are using is not defined in the OpenMVG camera database.
Please add the following line in your https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt file
```
HERO3+ Black Edition;5.75
```
So a valid initial focal length will be provided in order to perform SfM.

2. GoPro camera have large FoV and so it's better to use a FishEye like camera model
To do so, you can use the ```-c 5``` option on the openMVG_main_SfMInit_ImageListing binary.

3. Run the incremental pipeline and you will have 15 images calibrated from 17 (incremental pipeline).

![image](https://cloud.githubusercontent.com/assets/3235050/16187269/95cbd6e8-36cf-11e6-954f-900b0a834441.png)

Have fun

**Comment by shuguohui** [comment]
hi @pmoulon
in sensor_width_database/sensor_width_camera_database.txt file, i add HERO3+ Black Edition;6.39,not 5.75(as the focallength in photoscan is 1733)
I use -c 5 option on the openMVG_main_SfMInit_ImageListing
And ComputeFeatures ,Set the preset to HIGH 
but i can't get the correct result,
i try again use HERO3+ Black Edition;5.75 now

**Comment by shuguohui** [comment]
hi @pmoulon,
can you share your all the SFM pipeline results for me,i compare my results and your results,hope to find the problem why i can't get the correct result.
i use HERO3+ Black Edition;5.75 also get the incorrect result.
my email is : shuguohui@gmail.com

thank you very much

**Comment by pmoulon** [comment]
Did you obtain a better result with 5.75?

**Comment by pmoulon** [comment]
Any news?

**Comment by shuguohui** [comment]
hi @pmoulon，
I‘m sorry for feedback so late，i found that develop branch can got the correct result，but master branch got  incorrect result。I compare the results and found that the problem is in ComputeMatch step， the "\src\openMVG\robust_estimation\robust_estimator_ACRansac.hpp"  in master branch, at line 422:
if (!bACRansacMode && nIter > nIterReserve*2)
          nIter = 0;
this codes cause the problem,when nIter = 0, the estimation loop will break and return inliers zero

**Comment by pmoulon** [comment]
Thanks for the detailed feedback and see that the develop branch is giving you better results (meaning that the project is evolving in the right way ;-) ).

You can safely use the develop branch for your tests.
Will close the issue when the ```HERO3+ Black Edition;6.2``` will be added to the camera sensor size db.

See why for the 6.2 there http://www.kolor.com/wiki-en/action/view/Autopano_Video_-_Focal_length_and_field_of_view

**Comment by pmoulon** [comment]
I'm closing the issue since the database has been updated and any problems have been discussed with solution.
Thank you @shuguohui
