### ISSUE TITLE
How to auto detect the failed cases?

### ISSUE THREAD

**Issue by gesong1982** [openMVG/openMVG#579]
Hi,

Thank you for providing the this open source. I made lots of nice 3D model by using this nice library. However in some cases, I got inaccurate results. I am wondering, except checking it by eyes, is there any way I can evaluate the results automatically or any scores can tell me the reconstruction is failed? 

Thank you very much.

Song

**Comment by pmoulon** [comment]
Hi @gesong1982 
Thank for your kind feedback about the library.

Regarding checking the inaccuracy, you can check many points:
- how much pictures from the total dataset are registered,
- how is the distribution of the re-projection residual,
- how much of points are triangul-able (from the total possible count)

If you have some problematic dataset, we can have a look to try to improve the registration.
We must see if it's a feature matching issue => feature presets (NORMAL|HIGH|ULTRA),
or a geometry issue (intrinsic or extrinsic) => use a known distortion.

Feel free to share any dataset on openmvg-team[AT]googlegroups.com

**Comment by gesong1982** [comment]
Hi @pmoulon 

Thank you very much for your quick reply. The images I used are sampled from a video and I use sequential mode during the matching. I do not have any prior knowledge about the intrinsic and distortion parameters of the camera. I just estimate the focal length based on the image resolution (1.2*max(w,h)).  And in most time openMVG works well, nice work! However when using large number of high resolution images SfM+MVS is really time consuming, I try to detect the failed case as early as possible to save time. I am really interested in your suggestions, do you mind providing more details about how can I obtain the re-projection residual and the number of points are triangul-able?

Thanks again and I appreciate your time.

**Comment by pmoulon** [comment]
The scene where you have problem are perhaps scene where the matching is not working fine in sequential mode. Have you tried on those scene the default matching mode (exhaustive), just for a check?

In the output reconstruction directory, you have a file called SfMReconstruction_Report.html, for each view you have the residual information.

For the number of triangul-able point it would be required to write some code.
- load the scene,
- compute the tracks (keep only length 3 more more robustness),
- perform a robust triangulation,
- compute the number of rejection.

**Comment by gesong1982** [comment]
I attached the SfM report below. Cloud you please show me which value I need focus on or how to analysis the residual information. I will try the reconstruction again by using the exhaustive matching mode. 
[SFM report_.pdf](https://github.com/openMVG/openMVG/files/328501/SFM.report_.pdf)

Thanks.

**Comment by pmoulon** [comment]
In this case the report is not very informative.
The found camera geometry seems to be decent but do not reflect the ground truth.
What about the RMSE you obtain on your other scenes?
  - Here you have ```SfM Scene RMSE: 0.612987```

**Comment by gesong1982** [comment]
SfM Scene RMSE: 0.612987 (generate two layers on one corner of the scene)
SfM Scene RMSE: 0.702826
SfM Scene RMSE: 0.71953
SfM Scene RMSE: 0.68984
SfM Scene RMSE: 0.627075

Several RMSE examples show above, the first one has problem with two layers, for the others work well. By using the exhaustive matching mode, it work well but take 3x longer than sequential mode.

**Comment by pmoulon** [comment]
The two layer is due to the fact that some feature have not been tracked correctly, or that they have been cut by the SfM process.
If you want perform a fast matching, you can perform a exhaustive matching at a lower resolution, then use the found pairs as a list to perform the full frame matching. So the first run will determine image similarity and then you will compute at higher scale only the required pairs.

Which type of camera & image resolution are you using?

**Comment by gesong1982** [comment]
The camera should be the DJI Drone camera & current resolution is 1920*1080 for quick test, also have 4K videos. 
Basically running time is not the big issue for me, the accuracy is most important for me. So I may use exhaustive matching, and will try your suggestion to see if I can obtain comparable results by using the exhaustive matching on original resolution.

**Comment by pmoulon** [comment]
@gesong1982 
- I don't know which is the FoV of the DJI camera. But perhaps on some scene the openMVG FishEye camera model can help.
If the accuracy is the most important for you I would you like to suggest to use the exhaustive matching in order to keep all the loops that can be computed from the images links.
Then if the time is an issue, I would suggest to use a two iteration process, one with thumbnail to detect the image similarity (interesting pair to match), then launch the full res matching of the selected pairs.

Additionally, if you have some GPS metadata you can limit the matching to a neighborhood...

**Comment by gesong1982** [comment]
@pmoulon 

Thank you for you kind suggestions, will try them. Really appreciate your time. You can close this issue.
