### ISSUE TITLE
[Pipeline] multi image input

### ISSUE THREAD

**Issue by codeDilemma** [openMVG/openMVG#606]
1. What is the best pipeline to reconstruct from multi image input? I have seen the code for openMVG_sample_multiview_robustEssential but this input is only stereo.

2. Is there any official forum for OpenMVG to ask questions?

**Comment by pmoulon** [comment]
Hi @codeDilemma 
1. You can handle multi image input in OpenMVG.
SfM related binaries are located in software. Samples are more for demonstrating OpenMVG multiview core.
You can either run the Incremental or the Global SfM pipeline.
It depends on your image coverage and the size of the dataset and the time you want to wait in order to obtain your results.
In order to run the SfM pipeline in an easy way there is python script that are exported:
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

2. You can ask question here or on te googlegroup https://github.com/openMVG/openMVG#contact

**Comment by pmoulon** [comment]
The actual code is able to process a directory of images and save the final reconstruction as ply already.
You can customize it as many place, feel free to go through and see what you want to update.

The camera_file_params is used to have "good" approximate pixel focal length.
You can use the option -f X (with X the known pixel focal length), it will configure the same focal length for all your image.

For the moment I prefer to let the user aware of the fact that having accurate intrinsic data help the SfM process.
But you can easily change the SfMInit_Image_Listing binary in order to suppose a given FoV and so set for example 1.2*max(w,h) as an approximate pixel focal length for your test.

**Comment by pmoulon** [comment]
Feel free to reopen, if you have any other questions.

**Comment by codeDilemma** [comment]
Everything is fine and could be closed.

Last question: I am not able to open RGBA with

openMVG::image::Image<openMVG::image::RGBAColor> image_rgba;
const bool check = ReadImage(filename.c_str(), &image_rgba); //everytime false

Is this bug fixed?

**Comment by pmoulon** [comment]
RGBA color writing & reading is working:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io_test.cpp#L41

I think you are trying to read an image that does not have 4 channels.
Your input image must have 4 channels.
So if your image does not have 4 channels this is not a bug, but the normal behavior (input image cannot be interpreted as a 4 channel image).
