### ISSUE TITLE
3D to 2D correspondences

### ISSUE THREAD

**Issue by chuqiaodev** [openMVG/openMVG#635]
Hi @pmoulon,

I am wondering may I obtain the 3D to 2D correspondence, e.g. for each 3D point in ply file, how do I know which images it mapping from, furthermore which 2D features it corresponding to, in any kind of outputs? Look forward to your reply. Thanks.

**Comment by pmoulon** [comment]
This information is saved in the SfM_Data file.
You have for each landmark (the 3D point) & the list of observations ( image id, feat id + 2d point position).

You can to see it convert the sfm_data.bin file to json with the binary ConvertSfMDataFormat -i sfm_data.bin -o sfm_data.json

Then go to the field structure and you will see something like:
```
{
            "key": 284,
            "value": {
                "X": [
                    -0.24015136192931139,
                    0.19104019857230972,
                    1.7391606695043016
                ],
                "observations": [
                    {
                        "key": 3,
                        "value": {
                            "id_feat": 2280,
                            "x": [
                                998.177978515625,
                                711.64599609375
                            ]
                        }
                    },
                    {
                        "key": 4,
                        "value": {
                            "id_feat": 1904,
                            "x": [
                                1070,
                                849.77197265625
                            ]
                        }
                    },
                    {
                        "key": 6,
                        "value": {
                            "id_feat": 2160,
                            "x": [
                                1137.550048828125,
                                650.25
                            ]
                        }
                    }
                ]
            }
        },
```

In order to use this information in your own format, you can either parse the json file or use OpenMVG as a third_party project inside your program and directly use the .bin sfm_data scene and use OpenMVG data structures and objects.

Saw that you also ask the question for MVE. Each SfM library list this info since keeping the mapping is important to compute the reprojection error (residual) information

**Comment by chuqiaodev** [comment]
Thanks to quick reply, by running openMVG_main_ComputeStructureFromKnownPoses will create robust.bin file, what is the difference between sfm_data.bin and robust.bin?

**Comment by pmoulon** [comment]
robust.bin is the tracks that are computed by using guided matching (track that have at least 3 image observation).
sfm_data.json is the result of the SfM pipeline (so only pairwise matches that does not have been computed by using guided matching).
I invite you to take a look at the doc to better understand the algorithm
https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeStructureFromKnownPoses/

**Comment by chuqiaodev** [comment]
Thanks @pmoulon.
