### ISSUE TITLE
Estimation from parallel cameras

### ISSUE THREAD

**Issue by ogrex** [openMVG/openMVG#637]
I'm trying to estimate shape with camera parameters given. The cameras are all in a plane. I added camera extrinsic parameters(rotation and center)  in sfm_data.json. But there is no point generated after doing feature computing and main_ComputeStructureFromKnownPosition. 
So I traced the computation and found the reason lies in function GuidedMatching_Fundamental_Fast:
1, ep2 would become NaN after divided by its third element which is 0.
2, function line_to_endPoints would always return false because epipolar line is parallel to image(so the parameters of line have a 0 element).
So parallel case is not supported by OpenMVG?

**Comment by pmoulon** [comment]
Thank @ogrex for the feedback.
Feel free to update the code in order to support your case.

What you can try also is to compute your tracks and directly run the Robust triangulation framework.

**Comment by ogrex** [comment]
Thank you for your quick reply. 
In the part of GuidedMatching_Fundamental_Fast, why is ep2 normalized and why does line_to_endPoints ignore the case that line have a zero element.

**Comment by pmoulon** [comment]
Here the link towards the problematic line for your case (it will help other to understand which part of the code we are talking about)
https://github.com/openMVG/openMVG/blob/master/src/openMVG/robust_estimation/guided_matching.hpp#L315

I suggest you to use GuidedMatching instead of GuidedMatching_Fundamental_Fast .
You can activate it here
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/structure_from_known_poses/structure_estimator.cpp#L119

Adding a define will activate it:
```
#define EXHAUSTIVE_MATCHING 1
```

**Comment by pmoulon** [comment]
@ogrex Does it helps?

**Comment by ogrex** [comment]
Thanks for your answer. After using EXHAUSTIVE_MATCHING, the sparse point cloud is generated. But the result is not as good as expected because a lot of noise points are generated.
![te](https://cloud.githubusercontent.com/assets/11294306/19065166/e0abee3e-8a4c-11e6-9c2d-f16143891a3e.png)

**Comment by pmoulon** [comment]
Ok, but the real shape is there.
The noise can comes from triangulation with too tiny angles or bad corresponding point.

**Comment by pmoulon** [comment]
@ogrex Any additional feedback?

**Comment by pmoulon** [comment]
Closed due to user inactivity.
