### ISSUE TITLE
All your samples seem to be missing...well, samples

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#639]
* [Your `openMVG_Samples` directory here on Github](https://github.com/openMVG/openMVG/tree/master/src/openMVG_Samples)
* [Your **Samples** page from RTD](https://openmvg.readthedocs.io/en/latest/openMVG_Samples/openMVG_Samples/)

Am I missing something?!? I don't see any actual *examples* as to how to use this (seemingly magnificent!) tool! If I'm mistaken, and just not looking in the right place, please point me in the right direction!

At the end of the day, I'm just looking for documentation as to how to use OpenMVG/MVS.

**Comment by pmoulon** [comment]
@zharvey-welltok 
- Samples

You must activate the compilation of the samples in order to be able to run them https://github.com/openMVG/openMVG/blob/master/BUILD#L59
```
-DOpenMVG_BUILD_EXAMPLES=ON
```
Samples demonstrate how to use each features in a given context. In order to run them just launch the binary.

- Regarding the SfM side.

You must look to this part of the doc 
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/

You have python script that launch the toolchain for you on an image directory:
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

- Regarding connection to existing MVS framework

http://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - I'll follow all of these suggestions.

Quick question - any suggested reading for newcomers wishing to understand the CV techniques/algorithms used by this library?

**Comment by pmoulon** [comment]
I would advise you take a look to https://github.com/openMVG/awesome_3DReconstruction_list

The OpenMVG SfM pipelines are explained in the paper of the readme.
https://github.com/openMVG/openMVG/blob/master/README.md#citations

**Comment by zharvey-welltok** [comment]
👍
