### ISSUE TITLE
Lots of failed tests during build

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#642]
I am following the [steps to compile/build](https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD) OpenMVG on a Mac (El Capitan 10.11.5). I followed the first set of steps and had correct/successful output for each one:

```
$ git clone --recursive https://github.com/openMVG/openMVG.git
$ cd openMVG
$ ls
 AUTHORS BUILD  docs  logo  README  src  ...
$ cd ..
$ mkdir openMVG_Build
$ cd openMVG_Build
```

But when I went to run the following command:

    cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" . ../openMVG/src/

I got confusing build output and can't tell whethere or not it succeeded.

On one hand the command finishes with the following output:

```
** OpenMVG version: 1.0.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- EIGEN: 3.2.8 (internal)
-- CERES: 1.11.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF:  (internal)
-- LIBPNG:  (internal)
-- LIBJPEG (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zac.harvey/thelab/openMVG_Build
```

...but on the other hand, [I get **a lot** of failing tests](https://gist.github.com/zharvey-welltok/0484b392572330bbeafdc2fdcde84358).

Can someone help me determine what the source of these failures were, and how they relate to the overall build health/success?

**Comment by pmoulon** [comment]
The test are only related on OpenMP detection for your compiler.
So the failure test only tell you that OpenMP cannot be used.
You can compile and use OpenMVG without OpenMP (but you will not use it a its full speed).

You can perform make and play with the binaries.

@rperrot can perhaps provide more info about OpenMP support on MacOs.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon 👍 - I was able to run `tutorial_demp.py` without any problems!

**Comment by rperrot** [comment]
@zharvey-welltok 

That's not strictly speaking an error ; openMVG can be used without OpenMP (as @pmoulon said, you will only use 1 core/thread for processing), theses messages only tells you that after trying all combination of OpenMP flag none of them succeed. 

If you really want to use OpenMP on OS X, you must use another version of clang (the one provided by OS X does not support it). I tested with success clang-3.8 and 3.9 (3.7 also works but with special care, I don't recommend it) using macports here is how : 
- First install clang-3.8 (or 3.9 using macports ) : sudo port install clang-3.8 (or clang-3.9)
- When you configure your cmake project, just tell you which compiler you want : 
```
CC=clang-mp-3.8 CXX=clang++-mp-3.8 cmake -DCMAKE_BUILD_TYPE=Release . ../openMVG/src 
```

Unfortunately with that solution, you cannot use the Xcode generator (-G Xcode) since it force using the system clang. 

Note : this has only been tested on OS X El Capitan and previous (not in Sierra).
