### ISSUE TITLE
Understanding OpenMVG features

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#654]
I have just read the [features page](https://openmvg.readthedocs.io/en/latest/openMVG/features/features/) in your docs and have a few questions about it:

1. What is the difference between a **Feature** vs. a **Descriptor** vs. a **Vector**? It *sounds* like a Feature is represented in the code by a Vector, but then I'm still unsure as to how a Feature relates to a Descriptor.
2. I see there are "Point-Based Features", but are there any other types of Features? For instance, perhaps there are Vector-based, etc.?
3. What does the "SIO" in `SIOPointFeature` stand for?
4. What's the relationship between Feature and location/(x,y) coordinates? I see that `SIOPointFeatures` store position/scale/orientation as (x,y,s,o), but wouldn't (x,y) be a specific coordinate/pixel in the image? If so, how does a pixel have scale or orientation?
5. Do *all* SIFT descriptors have to be 128-bit? If not, then what factors typically determine descriptor size?

Thanks!

**Comment by pmoulon** [comment]
1. Feature describe the localization in the image, while the descriptor is the description around the point of interest (the feature).
2. For the moment I consider only Point based feature, but we can think about handle line based feature later on.
3. SIO => Scale Invariant & Orientation. So an SIOPointFeature is a point in which we add scale and orientation information.
4. X,Y is in the image domain. orientation describe the dominant gradient within the region. The scale depicts the local size of the point. Since the scale is specific to the scale space used by the feature detection method they are not exactly the same for SIFT & AKAZE.
5. SIFT is a 128 values base descriptor. It can be 128 uchar, or 128 float. Default settings setup a 128 uchar descriptor.

**Comment by zharvey-welltok** [comment]
Ahh, this is starting to make sense :-) - thanks!

Here's a picture to use as an example:

![aceventura1](https://cloud.githubusercontent.com/assets/20440748/19561520/ff68b576-96a6-11e6-9bc2-cca2ef0d490a.jpg)

* In the picture above, can you give me an example of what one Feature might be, and what its Descriptor would look like?
* When you say "*orientation describe the dominant gradient within the region...*", what do you mean by dominant "gradient"? A change in colors/shade from one section of the image to the other (so basically, line detection)? Or something else?

Thanks again!

**Comment by pmoulon** [comment]
I invite you to take a look to the code sample and to run them.
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/features_siftPutativeMatches/siftmatch.cpp

You can for example run:
./Linux-x86_64-RELEASE/openMVG_sample_describe_and_match -t SIFT

and see on your disk:

![01_features](https://cloud.githubusercontent.com/assets/3235050/19561800/52051c10-96da-11e6-9f8f-b46bc3aecb75.jpg)

For the orientation, I forward you to read the feature detection paper (SIFT or AKAZE).

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - closed!
