### ISSUE TITLE
ComputeMatches appears to be failing

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#666]
I am running a set of images (frames from a MP4 video) through a pipeline of 4 OpenMVG tools:

1. `openMVG_main_SfMInit_ImageListing`; then
2. `openMVG_main_ComputeFeatures`; then
3. `openMVG_main_ComputeMatches`; then
4. `openMVG_main_GlobalSfM` (I have also tried `openMVG_main_IncrementalSfM`)

When I run the first three commands (up to and including `ComputeMatches`) I get console output that indicates they have ran successfully. However when I run `GlobalSfM` I get:

```
-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0

Cardinal of nodes: 0
Cardinal of edges: 0

Invalid input image graph for global SfM
```

And when I try `IncrementalSfM` instead of global, I get:

```
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.
```

The commands that I ran as well as the console output for those commands [can be found in this gist](https://gist.github.com/hotmeatballsoup/c5688cd9c759dbca87ae375c33bcf187).

I have created a [Github repo for troubleshooting this](https://github.com/hotmeatballsoup/3drecon-troubleshooting) which has the following directories of interest:

* [`basementtoy/samples`](https://github.com/hotmeatballsoup/3drecon-troubleshooting/tree/master/basementtoy/samples) - the directory where you can find all the images I'm feeding into `openMVG_main_SfMInit_ImageListing` as input; and
* [`basementtoy/matches`](https://github.com/hotmeatballsoup/3drecon-troubleshooting/tree/master/basementtoy/matches) - the directory where you can find all the output generated by the first 3 commands; and
* [`basementtoy/recon`](https://github.com/hotmeatballsoup/3drecon-troubleshooting/tree/master/basementtoy/recon) - the directory where either `GlobalSfM` or `IncrementalSfM` should be generating their reconstruction output to

In the past I've run into these "*Invalid input image graph for global SfM*" errors with `GlobalSfM` because I wasn't using enough photos/images, and there wasn't sufficient overlap between each photo to produce a graph. However, as you can see, I'm using 40+ images taken from all angles around the object (a toy sitting on the floor of my basement; hence all the "`basementtoy` names).

**Can anyone spot why either `ComputeMatches`, `GlobalSfM` or `IncrementalSfm` are failing?**

**Comment by pmoulon** [comment]
The reason of failure is simple, you does not have intrinsic camera information: (the intrinsic id is set to undefined)
see here: https://github.com/hotmeatballsoup/3drecon-troubleshooting/blob/master/basementtoy/matches/sfm_data.json#L16

You must always check that you have valid intrinsic for some images!

In your case you can provide the focal value by using the -f option on main_SfMInit_ImageListing

Since your frame was exported from a video there is EXIF data that OpenMVG can infer to compute the focal lenght, so you must provide it by hand.

A focal value like -f 1.2*1920 => -f 2304 should be run fine.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - however explicitly setting `-f 2304` results with view's `id_intrinsic` being set to zero (0)! So SfM (Global and Incremental) is still failing, I *believe* because `id_intrinsic = 0` for **all** views.

It looks like `focal` is computed [by this formula](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L255). To me this means that `exifReader->getFocal()` is resolving to `0` and forcing `focal` to compute to `0`, however [there is a check for that](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L241) right above it, so I'm not sure why setting `-f 2304` on the command line is resulting with `focal` being calculated as `0`...any thoughts?

I updated the gist and the 3drecon-troubleshooting repo with new info after setting `-f 2304` if it helps. Thanks again, enormously!

**Comment by pmoulon** [comment]
Having ```id_intrinsic = 0``` for all view is the normal behavior.
It means that all the view are sharing the same camera model parameter that are listed in the intrinsic part of the json file.

In order to check the focal value you have you can check it in the json file.

As you see here the focal value is well set to 2304:
https://github.com/hotmeatballsoup/3drecon-troubleshooting/blob/master/basementtoy/matches/sfm_data.json#L754

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon, **but SfM is still failing with the same messages as above**, even with `-f 2304` set on ImageListing.

Is there anything else wrong with the images, their EXIF data, the arguments to any of the various OpenMVG tools, or anything else that you can spot? This is a total blocker for me!

**Comment by pmoulon** [comment]
I have already processed some dataset where the frames cames from video (as you have done it).

And I showned to you, I was able to find some corresponding pair after the geometric filtering.

So I think it's just a matter of compilation or launching, please erase the output directory (matches) and relaunch your commands.

**Comment by zharvey-welltok** [comment]
OK @pmoulon I am starting to see what you mean. **I believe I am having a compilation issue**, because each time I run my SfM pipeline **I am completely deleting and recreating the entire directory structure!**

To help me confirm that I have a compilation issue (and not an issue with my images or the arguments I'm passing in to each of the command-line tools), I have done the following:

* I created a new directory called `testsfm/` and gave it the following directory structure:
    * `testsfm/frames` -> placed 21 JPG images in here (as my inputs)
    * `testsfm/matches` -> working directory where each tool will look for (and generate) files/info
    * `testsfm/recon` -> output dir for SfM (Global and Incremental alike)
* Then I ran my pipeline (ImageListing -> ComputeFeatures -> ComputeMatches -> GlobalSfM)
* Again, I get the "*Invalid input image graph for global SfM*" error after GlobalSfM runs
* I copied my entire terminal window into a file and saved it under `testsfm/console-output.txt`. This file contains the exact commands that were used to process my 21 images.
* I then uploaded this `testsfm/` directory to [my troubleshooting repo](https://github.com/hotmeatballsoup/3drecon-troubleshooting) and updated the `README` to show steps to reproduce (basically everything I've written here above)

Please, if you ( @pmoulon ) or anyone else has a few minutes to help me troubleshoot, I would be enormously appreciative!!!

I would be interested if someone could:

1. Clone my repo
2. If necessary, delete all the contents of `testsfm/matches` and `testsfm/recon` so you are starting on a "clean slate"
3. Use `testsfm/console-output.txt` to run my SfM pipeline with the *exact* same commands that I used
4. Confirm if Global SfM fails for you as well. If it does, then this indicates an issue with my images or the arguments I'm passing into the tools. **But, if GlobalSfM works for you, then this indicates a compilation/system issue on my end.** Knowing which one of these is the case will help me enormously in debugging here. I would also ask that if GlobalSfM works for you, that you push your versions of `testsfm/matches` and `testsfm/recon` so that I can compare them with my version.

Thanks enormously for any help here!!!

**Comment by pmoulon** [comment]
@zharvey-welltok I made some experiment and took a look to your images:

**Here some notes for your basementtoy dataset:**

1. you have some images that are very blurry and so it does not help in order to make the feature matching connect the neighboor images (I would suggest you to move more slowly or use something to stabilize your camera while turning around the object (perhaps a rolling chair))

2. since there is many images that are blurry, I ran the sequential pipeline on your images, the toolchain was running fine, but I was only able to calibrate a subsample of your image
=> (20/44) with SIFT HIGH
=> (/44) with AKAZE_FLOAT HIGH ANNL2 (akaze works better with blurry images)

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/20034651/23ee724a-a382-11e6-92f9-610e0e2c925c.png)

The result looks quite close to the reality. But I would recommend you to find a way to enhance your image capture protocol.

**Here some notes for your testsfm dataset:**

My first remark is going on taking a look to the log, and we can read "image020" model "DSC-HX5V" doesn't exist in the database" => So, as I said, before, please check that your image view intrinsic is well configurated before running a dataset!!

Since you have no intrinsic, the essential matrix match filter will not work and produce an empty graph. Then global SfM will have an empty graph as input and so will be able to do nothing.

Once your camera added to the database ```DSC-HX5V;6.1```. I dont know why the SONY camera model cannot be read from those images... Btw, I ran sequential pipeline and I obtained:

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/20034684/19ab8492-a384-11e6-8eb4-eba5fc0a83f7.png)

So your problem for this dataset was again about the camera intrinsics ;-)

PS: I processed with AKAZE_FLOAT HIGH ANNL2, Global SfM was also running fine.
=> SIFT HIGH is running nice also for sequential and global.

Here the result of the global SfM pipeline

![snapshot_global01](https://cloud.githubusercontent.com/assets/3235050/20034697/a3b933aa-a384-11e6-9dff-8aaca114894f.png)

**Comment by pmoulon** [comment]
I'm closing this issue since it was a was a solved problem => the problem was that with your images the automatic intrinsic initialization failed (since the camera was not in the database).

Problem can be solved by added your camera model to the sensor database or by providing the focal value manuallly to SfMInit_ImageListing;

**Comment by zharvey-welltok** [comment]
Sorry @pmoulon I've been swamped at work and was hoping to come back to this today or tomorrow. To be clear, I am very confident this is a system/compilation issue, as I was able to get the pipeline working on a different machine (VM) using the exact same commands.

I just haven't had a chance to investigate yet, but I will soon.

**Comment by zharvey-welltok** [comment]
Hi @pmoulon I would like to re-open this issue if you don't mind. I'm sorry I disappeared for almost a week, but work is very busy for me and I had to put my hobby projects on hiatus.

I'd like to focus on my "`basementtoy`" project, because I am *still* seeing `ComputeMatches` fail for me, even after following your advise to try `AKAZE_FLOAT` instead of `SIFT` due to blurry images.

I have updated my troubleshooting repo on GitHub to show the latest issue. If you follow the exact instructions below, you will see that the pipeline fails at `IncrementalSfM`:

1. `cd ~`
2. Clone/pull my [3drecon-troubleshooting repo](https://github.com/hotmeatballsoup/3drecon-troubleshooting)
3. `mkdir -p basementtoy/frames`
4. `mkdir basementtoy/matches`
5. `mkdir basementtoy/recon`
6. `cp 3drecon-troubleshooting/basementtoy/frames/* basementtoy/frames`
7. $sensorDB=/path/to/your/sensor_width_camera_database.txt
7. `openMVG_main_SfMInit_ImageListing -i basementtoy/frames -o basementtoy/matches -d $sensorDB -c 3 -f 2304`
8. `openMVG_main_ComputeFeatures -i basementtoy/matches/sfm_data.json -o basementtoy/matches -m AKAZE_FLOAT -f 1 -p ULTRA`
9. `openMVG_main_ComputeMatches -i basementtoy/matches/sfm_data.json -o basementtoy/matches -r 0.8 -g e`
10. `openMVG_main_IncrementalSfM -i basementtoy/matches/sfm_data.json -m basementtoy/matches -o basementtoy/recon`

When you run the last command (`IncrementalSfm`) it should fail with the following output:

```
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.
```

The `3drecon-troubleshooting/basementtoy/matches` directory contains everything that my OpenMVG installation produced for those 4 pipeline commands; might be helpful for troubleshooting.

If you can reproduce this, can you help me figure out why `IncrementalSfm` is failing?

**And, if you are *not* able to reproduce this, using the *exact* same commands above on the *exact* same images, then the only things I can see as being the culprits are:**

* **Operating system** : I'm running this on Ubuntu 14.04; or
* **Dependencies** : perhaps OpenMVG requires version X of some dependency but my Ubuntu machine is using version Y; or
* **Compilation** : Maybe something is going wrong during my compilation, failing silently, and thus doesn't operate correctly at runtime; or
* **Branch** : I'm using the `master` branch build for OpenMVG, are you?

Also, if you're not able to reproduce this, would you mind sharing:

1. Your system info (OS & version)
2. Branch/build info (`master`, `develop`, etc.)
3. Specific dependencies OpenMVG depends on (libraries and packages) that are not apart of the openMVG project/repo
4. Your `basementtoy/matches` directory (feel free to push a feature branch to my repo and put in a PR so that I can compare)

Again, sorry to keep harping on the same subject here, I'm sure you're getting tired of this (!), but am really starting to think this is something system/dependency/compile related.

Thanks again *enormously*!

**Comment by pmoulon** [comment]
Hi.
Since you are using the sequential pipeline please use option -g f on main_ComputeMatches and everything will run fine.

-g e is mostly used for global SfM.

**Comment by zharvey-welltok** [comment]
Hey, you're right, @pmoulon - `-g f` worked spectacularly - **thank you!**
