### ISSUE TITLE
[geodesy] Theoretical background

### ISSUE THREAD

**Issue by rommuell** [openMVG/openMVG#670]
Hi,
I'm interested in the theoretical background of using odometry data as non rigid prior during BA (incremental SfM). Could you recommend any paper or literature to review, so that I can understand how you integrate the odometry information? Thanks!

Best, 
Roman

**Comment by pmoulon** [comment]
Hi,

**The implementation of integration to odometry information does not follow a particular paper:**

- for the non rigid prior we just fit the existing camera poses to the GPS poses in a rigid way and then let the BA adjust in a non rigid way (adding constraint that minimize the SfM camera poses to the fixed GPS position)
- in order to be robust to outlier GPS position I'm using a robust norm with a factor that depends of the quality of the rigid fitting.

Hoping it helps a bit.
**You're welcome to test the existing WIP approach, to provide feedback and try to extend it if it does not fit your needs**.

You can read more in the WIP documentation there:
https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst#non-rigid-registration-adaptive-registration-sfm
=> At the end you will find ready to use command line for the depicted branch

**Regarding the theoritical background I would like to recommend these ones:**

- Fusion of GPS and Structure-from-Motion using Constrained Bundle Adjustments
  - http://maxime.lhuillier.free.fr/pCvpr11.pdf

- Benefit of Rigorous Modeling of GPS in Combined AT/GPS/IMU−Bundle Block Adjustment
  - http://www.geopp.de/pdf/geopp_gip_oeepe_p.pdf

- INTEGRATION OF RAW GPS MEASUREMENTS INTO A BUNDLE ADJUSTMENT
  - http://www.isprs.org/proceedings/XXXV/congress/comm4/papers/477.pdf

**Comment by weblucas** [comment]
Nice material. I will also try out soon.

**Comment by rommuell** [comment]
Thank you very much for your support!

**Comment by pmoulon** [comment]
You're welcome, feel free to test the WIP feature and come back with comment here.
Or close the issue if the provided answer was good.

**Comment by zharvey-welltok** [comment]
Hi @pmoulon just curious - what is meant by the word "rigorous" here (e.g. *rigorous* modeling, *rigorous* GPS, etc.). I know what "rigorous" means (as an English word!) but not sure what it implies in the context of SfM.

**Comment by pmoulon** [comment]
By rigorous they mean use GPS data in the right way (modeling the sensor error as close a possible)

**Comment by zharvey-welltok** [comment]
Makes sense, thanks @pmoulon!

**Comment by pmoulon** [comment]
@rommuell Can you please close the issue if you got the answer to your questions?
