### ISSUE TITLE
openMVG + VS2013 build error

### ISSUE THREAD

**Issue by json87** [openMVG/openMVG#676]
Hi, 
  thanks very much for providing the excellent SfM tools. Recently, I have pull the latest source code and build it under vs2013 on windows 7 x64 platform. However, the project named "openMVG_system" could not pass built process and some errors have been reported as following.  After search these errors, some conflicts maybe existed between C99  and C++11 (http://stackoverflow.com/questions/25561677/intmax-max-was-not-declared-in-this-scope).

![1](https://cloud.githubusercontent.com/assets/17582213/20255704/c28d32a8-aa79-11e6-8fe1-074a8c503abd.png)

**Comment by whuaegeanse** [comment]
Use Visual studio 2015 instead.

**Comment by pmoulon** [comment]
Please use VisualStudio as advised in BUILD file

**Comment by pmoulon** [comment]
@json87 Any feedback?

**Comment by json87** [comment]
yes, I am testing the solution under vs2013. I would give my feedback later today. @pmoulon

**Comment by json87** [comment]
good news! I have successfully built openMVG with VS 2013 under windows 7 platform. The errors listed above could be dealt by adding one macro definition in the CMakeFileList.txt in the src folder. I am a freshman for openMVG. then further tests have not been conducted.  @pmoulon 

IF (WIN32)
  ADD_DEFINITIONS(-DNOMINMAX)
  ADD_DEFINITIONS(-DVC_EXTRALEAN)
  IF (MSVC)
    ADD_DEFINITIONS(/bigobj)
    **_ADD_DEFINITIONS(-D__STDC_LIMIT_MACROS)_**
  ENDIF (MSVC)
ENDIF (WIN32)

**Comment by pmoulon** [comment]
You must try to build everything (including enable the unit test and samples in the cmakelist)
and then test the run-test target to ensure that OpenMVG will work as it must for your compiler and machine.

**Comment by json87** [comment]
yes, openMVG core libraries, samples and  main apps have been compiled successfuly! 




jiangsan870211@whu.edu.cn
 
From: Pierre Moulon
Date: 2016-11-18 09:35
To: openMVG/openMVG
CC: json87; Mention
Subject: Re: [openMVG/openMVG] openMVG + VS2013 build error (#676)
You must try to build everything (including enable the unit test and samples in the cmakelist)
and then test the run-test target to ensure that OpenMVG will work as it must for your compiler and machine.

**Comment by pmoulon** [comment]
Did you checked that unit test was running fine?

**Comment by robin32205** [comment]
Hello all, I am trying to do the same thing in vs2013, and get the error message:
> CMake Error at cameras/CMakeLists.txt:2 (UNIT_TEST):
>   Unknown CMake command "UNIT_TEST".

unfortunately, i got the same message with 2015. how can I fix it?

my platform is windows 10 x64

**Comment by pmoulon** [comment]
@robin32205 Using VS2015 is advised in order to have a full C++11 feature support. https://github.com/openMVG/openMVG/blob/master/BUILD#L23

@robin32205 Can you show the full cmake log?
Continuous integration on VS2015 was ok for v1.1 as you see here https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.302

**Comment by robin32205** [comment]
Hi, please check the attachment for info, thank you!


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年1月23日 上午 11:43
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] openMVG + VS2013 build error (#676)


@robin32205<https://github.com/robin32205> Using VS2015 is advised in order to have a full C++11 feature support. https://github.com/openMVG/openMVG/blob/master/BUILD#L23

@robin32205<https://github.com/robin32205> Can you show the full cmake log?
Continuous integration on VS2015 was ok for v1.1 as you see here https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.302

**Comment by pmoulon** [comment]
Please use the github online interface for dropping attachment.

**Comment by TheDoubleB** [comment]
I've had the same issue building on VS2013, so I made VS2013-specific minimal intrusion changes. openMVG builds in its entirety, including unit tests, and unit tests run without errors.

As it is our need, we will be maintaining VS2013 compatibility the foreseeable future on our branch at:
https://github.com/modriplanetdoo/openMVG/tree/vs2013

**Comment by pmoulon** [comment]
I'm closing the issue since various solution have been provided:
1. using VS2015 (the recommended windows based compiler)
2. using an OpenMVG fork that provide VS2013 support
