### ISSUE TITLE
openMVG_main_openMVG2MVE2

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#690]
![image](https://cloud.githubusercontent.com/assets/15321725/20780619/575d5990-b7b7-11e6-942d-d52273ecfe2c.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20780629/69f1cc9e-b7b7-11e6-82f5-684216c52d31.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20780639/742fb392-b7b7-11e6-9f0a-7d8c44d598f7.png)
When I run the command in the dos,the program can not generate view_xxx_mve,undistorted png and thumbnail.png in the views

**Comment by pmoulon** [comment]
You must provide a sfm_data file that have been produced by the SfM binaries (Incremental or Global).
Something like sfm_data.bin in reconstruction directories.

Since in your case your have provided as input a sfm_data file that does not have any camera poses inside it, the exporter export nothing.

**Comment by jingzibelieve** [comment]
oh,I konw!
