### ISSUE TITLE
What if too many images and can not load all descriptors? 

### ISSUE THREAD

**Issue by HUSTyanchao** [openMVG/openMVG#699]
There are too images in my image set and my PC has 8G memory. It could not load all descriptor files at a time. Is this any option to load the descriptor file dynamically? Or partition the image set in to multiple groups to handle the limited memory case?

**Comment by pmoulon** [comment]
Hi,

You can use the WIP **cache feature** in the branch develop_regions_provider_cache.
This branch add a region cache system that allow you to specify the maximal number of region(descriptors) that will be load in ram.

Please add the -c X option on main_ComputeMatches. X is the max number of regions that will be loaded in memory. Please use a number that is not too small else, the process will be too slow (thread will wait each other). Using a number like thread_count * 6 must be fine. Use something like 100 if you don't know which value you can set.

https://github.com/openMVG/openMVG/blob/develop_regions_provider_cache/src/software/SfM/main_ComputeMatches.cpp#L90

Please, tell me if it works fine, since this is a WIP feature.

```
git checkout develop_regions_provider_cache
git submodule init
git submodule update
// redo cmake and build
// add the -c 100 option to your python script to launch the toolchain
```

**Comment by HUSTyanchao** [comment]
@pmoulon  
Hi, thank you for your reply. I have tried it, however it did not work at all. Is it only applicable to some specific hardware?

**Comment by pmoulon** [comment]
No it must work for all platform.
Which OS do you have?
Which command lines have you used?
Does the process was killed at the same time as previously?

**Comment by HUSTyanchao** [comment]
@pmoulon 
It is Ubuntu 14.04 64-bit. 
I use **main_ComputeMatches -i <sfm_data.json folder> -o <matches> -c 1000** since there are 8000 images. I think it is killed at the same time as previously. However the progress bar did not show the current progress as before but the machine was still running. I waited for a long time like previously then the process was killed.

**Comment by pmoulon** [comment]
Ok, So if the progress bar does not show a long time, it's because the cache is working, => regions will be loaded on demand.

Can you check if the process is killed for a memory reason or for another reason?

I would like to help more but we must understand where the crash is happening, Any chance you can  run it in debug mode with gdb to catch the error, or print more info during the matching to identify the problematic pair?

I think that at a point the internal stored matches are larger than your ram can support and so the process was killed.

**Comment by pmoulon** [comment]
You close the issue since the cache option worked or because of another reason?

**Comment by HUSTyanchao** [comment]
Well, I think it worked. Thanks for your kind help.
