### ISSUE TITLE
what may lead reconstruction failure ?

### ISSUE THREAD

**Issue by overwatch3d** [openMVG/openMVG#701]
I try to use openMVG as the first step of reconstructing the 3D scene of a video game.  A screenshot video was captured while walking through in the game scene; and then converted to a list of images ( 960 x 526): ( available at dropbox: https://www.dropbox.com/sh/6whikq9vmpvqnm2/AABw4Bm4tMqO-QmLoNWak7zya?dl=0). For camera intrinsics,  I estimated the focal length = 381.809 from known horizontal-fov=103.  

I followed the OpenMVG SfM pipelines.  Steps 1, 2, 3, were fine. But both the two methods in the 4th step failed as shown in the Reconstruction_Report.html .  Why ?  Please could you give me some advice ?

By the way, I also tried ORB-SLAM method.  It can track the camera poses quite well at most of time, but the tracking is always lost when a pure rotation happens which is quite usual in game. I expect the offline SfM method like openMVG can avoid this issue, can it ?

**Comment by pmoulon** [comment]
I would like to suggest to use a larger focal length (something like 1.1 8 max(w,h))
Then since your image are masked for a large part it's not the best case for SfM. I think you have used mask in order to hide some HUD information.

PS: 
- which focal did you used for ORB-SLAM?

- there is a tracking sample in OpenMVG see a demo there https://www.youtube.com/watch?v=kJQqp0OHWQE perhaps this method would be able to find more stable matched.

**Comment by pmoulon** [comment]
@overwatch3d Any feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity.
