### ISSUE TITLE
Segfault with Eigen 3.3.1

### ISSUE THREAD

**Issue by bjornpiltz** [openMVG/openMVG#703]
I tested openMVG with my Linux 64 bit GCC setup, where I have Eigen 3.3.1 and Ceres 1.12 installed and make test fails with the following output:

```
The following tests FAILED:
	  8 - openMVG_test_features (SEGFAULT)
	 19 - openMVG_lInftyCV_test_triangulation (SEGFAULT)
	 21 - openMVG_lInftyCV_test_resection_robust (SEGFAULT)
	 37 - openMVG_test_triangulation_nview (SEGFAULT)
	 43 - openMVG_test_solver_resection_kernel (SEGFAULT)
	 62 - openMVG_test_sequential_SfM (SEGFAULT)
	 63 - openMVG_test_global_SfM (SEGFAULT)
```

They all seem related to [Using fixed size Eigen objects in STL containers](https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html)
I can fix all but one with the attached patch. `openMVG_test_global_SfM` needs further investigation.
[eigen_aligned.patch.txt](https://github.com/openMVG/openMVG/files/655173/eigen_aligned.patch.txt)

**Comment by pmoulon** [comment]
Thank you, I will try to investigate about it next week.

**Comment by pmoulon** [comment]
I made a fast try and I got some segfault too.
It's certainly due to some change regarding the alignement [here](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1348).
I would like to understand exactly what changes in Eigen are causing this error.
Updating a minor Eigen version must not make the code crash...

In your case did you use the new [find-package](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1319) Eigen3?

**Comment by bjornpiltz** [comment]
No, I didn't change any source code. I just specified the location of Eigen with:
```
-DEIGEN_INCLUDE_DIR_HINTS=/usr/share/include/eigen3
-DCERES_DIR_HINTS=/usr/local/lib/cmake/Ceres
```
I don't think it matters, though. EIGEN3_DEFINITIONS is still empty, right?

**Comment by pmoulon** [comment]
Did you made a try with clang?

**Comment by bjornpiltz** [comment]
Same segfaults and an additional problem

```
Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_BA_ceres.cpp.o
In file included from /openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:8:
In file included from /openMVG/src/openMVG/sfm/sfm_data_BA_ceres_camera_functor.hpp:11:
In file included from /usr/local/include/ceres/ceres.h:37:
In file included from /usr/local/include/ceres/autodiff_cost_function.h:132:
In file included from /usr/local/include/ceres/internal/autodiff.h:145:
/usr/local/include/ceres/jet.h:251:3: error: requested alignment is less than minimum alignment of 32 for type 'Eigen::Matrix<double, 12, 1, kAlignHint>'
  alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;
  ^
/usr/local/include/ceres/internal/autodiff.h:232:34: note: in instantiation of template class 'ceres::Jet<double, 12>' requested here
    FixedArray<JetT, (256 * 7) / sizeof(JetT)> x(
                                 ^
```

Seems related to the alignment changes.

**Comment by pmoulon** [comment]
I have most of the test running on my side too.

Following your diff, I added this:
EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION(openMVG::trifocal::kernel::TrifocalTensorModel) to the file triplet_tijsAndXis_kernel.hpp

I think also that it would be valuable to consider to extend EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION to deal with initializer list in order to smooth support.

There is still a problem with openMVG_test_translation_averaging

**Comment by pmoulon** [comment]
Just a note:
@bjornpiltz Seems like other Ceres user have detected Eigen related error too
https://github.com/ceres-solver/ceres-solver/issues/251

**Comment by bjornpiltz** [comment]
Just a heads up: There is a bug in Eigen <=3.3.1 which makes EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION fail on MSVC 2015 x64 when AVX is enabled. See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1389.

**Comment by pmoulon** [comment]
Does this fix is working for you?
https://bitbucket.org/eigen/eigen/commits/29f0625a5c72/

**Comment by bjornpiltz** [comment]
Yes.

**Comment by pmoulon** [comment]
@bjornpiltz Did you tried the last Eigen version 3.3.3?
Seems like there is a release each month now ;-)

We must discuss again about collaborate on some features ;-)
Feel free to @mail me or to join openmvg.slack.com
