### ISSUE TITLE
Is sequential or global more accurate?

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#714]
I understand the basics of each algorithm however it is not clear what the difference in the final products will be as a result.

Are there some basic guidelines on when to use each?

I have read elsewhere that global is quicker but sequential is more accurate.  Is this the case with openMVG?

**Comment by pmoulon** [comment]
Global SfM is better for scene that have large image overlap.
Sequential SfM is better for scene with scene that have poor image overlap.

- global SfM is faster than sequential SfM since it avoid the usage of multiple Ba steps and can perform more steps in parallel.

By nature GlobalSfM distributes the error along the image graph more evently and so it tends to be more accurate for all the dataset. As the paper (Moulon Pierre, Monasse Pascal and Marlet Renaud. ICCV 2013. Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion.) show it, Global SfM can be better for a lot of dataset (in term of speed and accuracy).

GlobalSfM in a general way does not like to have a image graph that is corrupted by a large count of  outliers (false image matching) while sequential can deal better with such graphs.

So there is not clear answer:
- depending of your time budget and knowledge about your dataset you can decide to use one or the other method.

**Comment by jpwhitney** [comment]
Thanks, that does help somewhat to guide my thinking in this regard.

A small follow up question is how to tell if outliers are present that may corrupt GlobalSfm?
