### ISSUE TITLE
[VisualStudio] Build - CMake

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#723]
I have downloaded the OpenMVG source and am trying to install via CMake.

1. I followed the instructions in the read me.
2. Set the source path to openMVG-master/src/
3. Set a build path
4. I get the following CMake error

CMake Error at CMakeLists.txt:82 (message):
  

   submodule(s) are missing, please update your repository:
    > git submodule update -i

5. I have downloaded git for Windows but not sure how to use it to download the missing submodules.

Any advice please

Regards,

Alan

**Comment by pmoulon** [comment]
Hi @bigakoz 
You need to open the git terminal in windows (right click open a git termine here)
Then you do
```
Getting the sources:
$ git clone --recursive https://github.com/openMVG/openMVG.git
or
$ git clone https://github.com/openMVG/openMVG.git
$ cd openMVG
$ git submodule init
$ git submodule update
```
and then you run cmake.
When you use the direct github download it does not checkout the submodule dependencies.

**Comment by bigakoz** [comment]
Thanks Pierre,

I have made a bit of progress but am missing a lot of the dependecies. I 
tried compiling with VisualSudio but a lot of errors due to the missing 
dependencies.

 From CMake configure:

Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)

Could NOT find Wget (missing: WGET_EXECUTABLE)

Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)

Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR 
GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")

Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)

Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY 
COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY 
COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY 
COIN_OSI_CLP_LIBRARY)

Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)


Plus the following was not found by CMake

1. I don't have Blas. is this required ?

2. CLP

3. COIN Utils

4. Flann Lib

5. Jpeg lib

6. Lemon lib

7. Mosek missing

8. OSI lib

9. Tiff missing

10. Zlib missing

Any tips on finding the missing files.


Alan

**Comment by bigakoz** [comment]
Pierre,

I have managed to make some progress. I have updated my compiler to"Visual Studio Community 2015" and am now able to compile after a very frustrating day ! Looks like the missing dependencies get compiled anyway or don't make any difference.

Anyway my latest problem is the OpenMVG library is compiling some of the DLL's but is not generating lib files which means the libraries that depend on "openMVG_numeric.lib" for example won't compile.

Any tips as I thought lib creation  was a flag in my old compiler but can't find a flag in 2015. The web says i need to add DEF files but that seems like a lot of extra work.

I also had to add math.h to numeric.h as there wasn't  a #define for M_PI in the original source.

Regards,

Alan

**Comment by pmoulon** [comment]
@bigakoz 
I'm sorry that the build is not a piece of cake for you.

OpenMVG can use some library as internal or external mode. On windows the major part of the library are used in internal mode since they are not detected on the system.

OpenMVG must compile without modification on VS2015 (since the build is tested on continous integration).

Do you compile in release?
By default OpenMVG compile stative files => so .lib files.
If you are building dll it's because you have chosen the option build_shared in cmake.

**Comment by bigakoz** [comment]
Yes turning into a drama. I am recompiling all my libraries to be compatatble with the new compiler (boost, glog, gflags, ceres) so a bit of an ordeal.

I will have another crack at OpenMVG soon once I sort myself out again

**Comment by bigakoz** [comment]
I will try your tip about build_shared when I get back onto and advise whether I have had success.

**Comment by pmoulon** [comment]
It must compile if you start from scratch.

CMake at the end must show a message like this one:
```
EIGEN: 3.2.8 (internal)
CERES: 1.11.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.15.11 (internal)
COINUTILS: 2.9.3 (internal)
OSI: 0.106.10 (internal)
LEMON: 1.3 (internal)

Configuring done
Generating done
```

**Comment by bigakoz** [comment]
Thanks Pierre,

I started from scratch with the new compiler and it worked first time.

I got in a pickle because I have many existing libraries on my machine compiled with the old compiler and when I tried to recompile them again there was many linking issues. I am not u to speed on Cmake so ended up with a mess.

This issue is closed and perhaps I should start a new thread.

Anyway I will explain what i am trying to do

I am doing my masters in underwater photogrammetry and was making reasonable progress. but after lookking at some of your software from OpenMVG looks like I don't need to re-invent the wheel.

So I am looking for the following.
1. Basic Sfm
2. Sfm that uses existing pose information
3. extend this to include further observation types by adding more observation types to the bundle adjustment. For instance a distance constraint could be added between two cameras that where mounted together. 

As well as generating 3D models this can be used to precisely position subsea vehicles (ROV's)  that would be  cheap way to navigate (replace expensive INS). An upward set of cameras could also track an ROV relative to the hull of a vessel (in shallow water). 

Your software seems to provide most of what I am looking for.
 
My questions are:
1. Do you have any example datasets and examples of how you call the various s/w programs
2. What camera coordinate system do you use ? OpenCV uses a X +ve to the right Y+ve down and Z +ve towards the image. I want to uses a photogrammtric system X +ve to the right Y+ve upand Z -ve towards the image. Is this possible ?

Regards,

Alan

**Comment by pmoulon** [comment]
1. OpenMVG is doing SfM, it provides an incremental and a global pipeline. Since you are manipulating underwater image, I think that incremental SfM will work better.

2. Can you explain it more. OpenMVG have a localization mode that allow to localize a sequence of image into an existing reconstruction. But it does not extend the scene yet.
Perhaps you mean to use some existing relative poses that are known between some camera (rigid camera rig acquisition).

3. It would be easy to add a distance constraint inside the existing BundleAdjustment wrapper.

Now for you your questions:

1. There is this tiny sample https://github.com/openMVG/ImageDataset_SceauxCastle that you can play with. Read here in order to understand how to launch the python script that will launch the different OpenMVG binaries for you https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

2. Z+ in front of the camera, X+ right
https://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/

**Comment by bigakoz** [comment]
Thanks Pierre,

I have openMVG working now and the results are excellent.

I have reprocessed a data set that was processed with commercial photogrammetry software and your results look better. I get an overall RMS 0.44 pixels whereas the photogrammetry s/w achieved 066 pixels.

With regards to 2.

In the case where the camera exterior orientation (Extrinsics) is known (or approximately known) can this be introduced into the adjustment. For instance in aerial photogrametry the photo centres have a priori values from GPS processing and onboard motion sensors. In a subsea environment camera centre information is also known but would not be of a very high accuracy but would be useful to get the solution into a mapping grid.

In order to introduce additional observations (like a distance contraint) or known dimensions in an image (say a known distance on known structure) it will be required to get the model into a real coordinate system. I notice you have a function called openMVG_main_geodesy_registration_to_gps_position which does I assume via a similarity transformation.

Its not a big deal if it is not possible as a similarity transformation and manipulating the point cloud is also a viable alternative. I would to have a look at the PCL library next which is probably the way to go.

Thanks for all your help and your excellent software. 

Alan

**Comment by pmoulon** [comment]
Hi @bigakoz 
Thank for your comments, happy to hear that OpenMVG is working great on your dataset.

OpenMVG toolchain can now support external position for all or some images. This contraint is used for the BundleAdjustment.
Actually the GPS position is read from the exif and converted to a XYZ position and then used by the pipeline.

Here the first draft documentation about it
https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#non-rigid-registration-adaptive-registration-sfm

You can easily modify the SfMInit_ImageListing application in order to handle your positional XYZ metadata and run the chain with the option to use the pose priors.

I'm adding @hcjghr to the discussion thread since you can have some interesting discussion together ;-)

**Comment by bigakoz** [comment]
Thanks Pierre,

I may close this thread as it is probably off topic and start a new one.

**Comment by pmoulon** [comment]
Thanks, you can close this thread and we will continue to discuss in the new one
