### ISSUE TITLE
Underwater Photogrammetry

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#725]
Pierre,

I have moved our discussion to a new thread.

To summarize.
1. I am doing my masters in underwater photogrammetry and would like to make use of the openMVG library as it appears to be an excellent piece of software and does a lot of what I am looking for.

Features I am interested.
1. Adding known camera extrinsics parameters.

Under vehicle will generally have some kind of positioning onboard that will provide a position and orientation for each image capture. However the quality will generally be poor (around the metre level) so introducing this informaation would require a weighting strategy.

2. Adding Ground Control Information

Seabed information is also sometimes available in the form of a DTM which again may be of variable quaility. A method to introduce this is required. The vertical component is important but the horizontal coordinate is not that critical as the vertical value doesn't change much over a surface. So matching a detected feature and interpoling a vertical ground control value form the DTM would work.

Equipment is available that combines scanners mounted with the cameras. High precision scan (for DTM) data is acquired concurrently. I would like to look at combining this data into the bundle adjustement.

3. Rigid camera mounting.

Often more than one camera is used and these multiple cameras are rigidly installed on a subsea vehicle.

It would be useful to add a constraint for the relative orientation of multiple cameras. I would see this being a calibration process prior to conducting a full data acquiistion process.

4. Adding known object geometry.

In precise subsea work structures are often surveyed precisely in a fabrication yard and then installed subsea. Connecting pipework between structures needs to be measured in-situ and the fabricated on shore and then installed.

What would be useful is to be able to introduce the survey of the structure into the bundle adjustment.

5. Error analysis and Correllation of parameters.

Determination of the uncertainty of the quaility of the model is obviously very important. Therefore  a weighted solution is required when using different parameter types.

I will be looking at whether the variance/covariance matrix is generated from the bundle adjustment. This in turn can be converted into a correllation matrix on selected parameters. For instance many intrinsic parameters can be solved but analysis of the correllation matrix will determine whether solving all is valid (check parameters that become highly correllated with others)

These are my plans and not sure whether it is all possible but will give it a go.  I obviously don't want to re-invent the wheel so if OpenMVG has some of these features already would be fantastic.

Thanks again for all your excellent work on this library

Alan

**Comment by pmoulon** [comment]
@bigakoz, Alan,

Here a by topic answer

1. Adding known camera extrinsics parameters.

-> You can already add and use camera pose priors (camera center position). The default option is actually loading GPS XYZ position in ECEF, but you can customize the binary to load your data and set a weight for each image. You can then use this Position prior data to filter out some pair for the matching and then to guide the SfM process to be georegistered and as closest as possible as your data priors.

2. Adding Ground Control Information

-> You can use Control Points (so link some image observations to some known 3D data observations). This feature is already implemented.
http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

3. Rigid camera mounting.

-> There is a WIP branch in order to support calibrated camera rig. See here for some results https://github.com/openMVG/openMVG/issues/580
-> I would like to add a tool to perform a kind of rig autocalibration by using the results of SfM on the unstructured images sets.

4. Adding known object geometry.

This topic can be linked to GCP data.

5. Error analysis and Correlation of parameters.

You are more than welcome to extend the actual BA interface to compute and export the uncertainty of the parameters. See http://ceres-solver.org/nnls_solving.html?highlight=covariance#_CPPv2N5ceres10Covariance7ComputeERK6vectorI4pairIPKdPKdEEP7Problem
@hcjghr Can perhaps also provide some feedback on this topic.

**Comment by bigakoz** [comment]
Thanks Pierre for you comprehensive reply.

Quick Question.

How do you create "create_points_registration" in CMake. I can see the files in the src directory but I can seem to create it in the build directory. I have tried most of the flags in CMake without success

**Comment by bigakoz** [comment]
Pierre,

Another quick question.

I don't want to start modifying any of the openMVG library for my own purposes.

However, I would like to write a small program that will do the following.
1. Convert the bundle adjustment (assuming is in ECEF) to projected coordinates. With optional of doing datum transformations.

Clearly ECEF should be used for the bundle adjustment as earth curvature errors would be introduced by using projected coordinates. However for practical use of the results I need to get the model back onto a projection.
2. Export the model points, intrinsics and extrinsics into my own formats. 

What piece of code best to look at to understand the openMVG data format and ways of accessing the data.

Regards,

Alan

**Comment by pmoulon** [comment]
In order to compile "create_points_registration" you must have QT installed. See here QT4 is required https://github.com/openMVG/openMVG/blob/master/src/software/CMakeLists.txt#L14

Regarding how to transform an existing scene:
- you will need to read the SfM scene (read a SfM_Data file)
  - 
```
 SfM_Data sfm_data;
  if (!Load(sfm_data, sSfM_Data_Filename_In, ESfM_Data(ALL)))
  {
    std::cerr << std::endl
      << "The input SfM_Data file \"" << sSfM_Data_Filename_In << "\" cannot be read." << std::endl;
    return EXIT_FAILURE;
  }
```
- then you need to  compute the transformation you want to apply (ECEF to your coordinate system)
 - here I cannot help you must do it
- then apply the transformation
  - you can use the existing Similarity transform
```
//--
      // Apply the found transformation as a 3D Similarity transformation matrix // S * R * X + t
      //--

      const openMVG::geometry::Similarity3 sim(geometry::Pose3(R, -R.transpose() * t/S), S);
      openMVG::sfm::ApplySimilarity(sim, m_doc._sfm_data);
```
- then export the data to your format or use the JSON exporter and read the data you need.

```
// Export the SfM_Data scene in the expected format
  if (Save(
    sfm_data,
    sSfM_Data_Filename_Out.c_str(),
    ESfM_Data(ALL)))
  {
    return EXIT_SUCCESS;
  }
  else
  {
    std::cerr << std::endl
      << "An error occured while trying to save \"" << sSfM_Data_Filename_Out << "\"." << std::endl;
    return EXIT_FAILURE;
  }
```
If you want do your own exporter you can take a look at the stored data here (ex. here the PLY export https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_io_ply.hpp)

Regards

**Comment by bigakoz** [comment]
Thanks Pierre,

I have playing with the transformation based on your "usage of GPS Priors" on the website.

1. I have injected latitude,longitude,Altitude into the imagery using exiv2. This is data is from a photogrammetric solution so the information is accurate
2. I then use the "-P" flag in openMVG_main_SfMInit_ImageListing.
3. create a pair list file with  openMVG_main_ListMatchingPairs
4. Compute matches with openMVG_main_ComputeMatches and the match file.
5. I then run openMVG_main_IncrementalSfM   with the "-P" flag
or run openMVG_main_geodesy_registration_to_gps_position   with "-P" not used.

This all appears to work fine with the similarity solution looking sensible and the bundle adjustment also producing RMSE at the sub  pixel level.

I am running the MVE pipeline and find I can generate a model with MVE when I don't using Pose Prior information but can't when I do.

When I look at the exports from openMVG_main_openMVG2MVE2  for preparation to create a 3D model I notice some issues.
1. All the model point coordinates look sensible
2. The Camera translation for each camera do not look realistic and look to be out by many 1000's of metres.

Can you suggest anything that I am doing wrong ?

**Comment by bigakoz** [comment]
I have a bit more of a look at this and probably need an explanation.

I notice that in that the pose returned in      const Pose3 pose = sfm_data.GetPoseOrDie(view);

Has a translation part and a pose centre part.  

The pose centre (from debugging) is the coordinate for the camera centre. I am nlot sure what the translation part represents.

I would have expected that the rotation and translation would have been about the camera not some other coordinate system.

Could you please explain how this works ?

**Comment by pmoulon** [comment]
Happy to see that your preliminary test regarding the Pose prior work as expected.

Here some comments regarding your question:

The camera pose is stored as world pose 3D point => C => t = -R C
R:R: the rotation of the camera to the world frame,
t:t: the translation of the camera. t is not the position of the camera. It is the position of the origin of the world coordinate system expressed in coordinates of the camera-centred coordinate system.

I used this convention since it's simpler to manipulate world coordinates (point position that you can use directly to display the camera position).


Regarding the error for ```openMVG_main_openMVG2MVE2``` notice that since your are using geodesic coordinates, all camera position can be large and so if we don't handle the camera position with the full double precision, all position can look the same.

See here the modification I done in order to export full double precision to be sure to export the data as it is:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_io_ply.hpp#L58

Please add the same line to the MVE exporter and I think you will not longer have problem in MVE.

Please be also aware that often MVS framework does not like to have very large coordinates for the cameras (often re-normalize the scene is required (mean translation to be 0 & median width to be 1)).

**Comment by bigakoz** [comment]
Thanks Pierre,

I have made the changes you suggested but still knot working. I will need to check my Pythin script to see if the problem is on my side.

In fact it is not a real issue for me as the bundle adjustment is working correctly and I intend to write a transformation on the output file (.PLY) anyway to be able to transform onto datums other that WGS84.

What is the transformation from the world frame back to the camera. That is I would like to output the coordinates and rotations for the camera. I assume the rotations need to be rotated around the X axis to be in a omega,phi,kappa (pitch,roll,yaw) system.

I am making good progress with openMVG and just need to trying out the ground control registration to have a full working system.

For your information the RMSE results from openMVG are better than the results on my test project that was using commercial photogrammetry software.

One suggestion however have you considered adding refraction to your Intrinsics model ? This would enable full photogrammetric capability to airbourne acquisition and is quite simple to impement
Regards,

Alan

**Comment by bigakoz** [comment]
Pierre,

I am trying to use 'ui_openMVG_control_points_registration'

In release mode it crashes when I try and load a  "*.bin" files and in debug mode it won't load up as it is looking for MSVCR100d.dll and MSVCP100d.dll.

I am using Visual Studio 2015 and my suspicion is that either:
1. It is related to my QT installation (I am using version 4.8) and that it was compiled with an older version of the run time libraries.
or
2. I have compiled the openMVG and the program using /MT (static linking) rather than with /MD.
   - This was required when I tried to install openMVS which only worked with static linking.

Any suggestions

**Comment by bigakoz** [comment]
Pierre,

I am going to download the QT source and compile under VS2015.

The missing DLL's indicate that QT4.8 has been compiled with an older version VS2010 which will explain the crash. Unless you have another explanation.

**Comment by pmoulon** [comment]
I think it's good to use the same compile for every library you are using.
Good luck with the QT compilation, Take a while, but it will certainly be worth it.

**Comment by bigakoz** [comment]
Thanks Pierre,

Its proving much harder than I anticipated. I can compile QT but is seems to be missing some files in order for CMake to create ui_openMVG_control_points_registration ! I am ready to change tack on this.

I any case I will probably need to write my own version of this in my project and add some other features.

As a tempory fix !
1. I have a file of image coordinates of my targets
2. I have a file of model coordinates matching the image targets.

What lines in ui_openMVG_control_points_registration are used to inject this data into the bin file in order to do the registration. Unfortunately I can't run a debug version to step through your code.

Alan

**Comment by pmoulon** [comment]
@bigakoz 
You must add controlpoints datat inside the SfM_Data structure, see here https://github.com/openMVG/openMVG/blob/master/src/software/ui/SfM/control_points_registration/GraphicsMainWindow.cpp#L92

You must update the 3D position of the landmark and the list of its observation.

**Comment by pmoulon** [comment]
@bigakoz Any feedback about the last question (using rigid registration)?

**Comment by bigakoz** [comment]
Pierre,

I have been taking a break over the last week or so.

My intention is to write an interface for openMVG in windows.
1. Add configuration control for all the various options via interfaces.
2. Convert your UI into windows so I have more precise control over picking the points.
3. Write my own similarity transformation. I want to control the weighting as a lot of the control will only have height and my survey control (3D) may have variable quality.

I hopefully will be able to port this across and understand the data formats better.

I will keep you posted.

**Comment by pmoulon** [comment]
Hi @bigakoz 
Please note that some existing UI made in QT are Windows compatible.

For sure the community is looking to have GUI and have started some project here or there:
- https://github.com/open-anatomy/SfM_gui_for_openMVG
- http://www.regard3d.org/

PS: Be free to ask to join openmvg.slack.com
