### ISSUE TITLE
openMVG_lInftyCV_test_resection_robust failing

### ISSUE THREAD

**Issue by sgielkens** [openMVG/openMVG#740]
Hello Pierre,

I am building openMVG 1.1 for Fedora 25. It builds without problems (as always) but the 'make test' fails now. It concerns test openMVG_lInftyCV_test_resection_robust. The log message is:
```
<begin_output>
Command: "/builddir/build/BUILD/openMVG-1.1/build/Linux-x86_64-RELEASE/openMVG_lInftyCV_test_resection_robust"
Directory: /builddir/build/BUILD/openMVG-1.1/build/openMVG/linearProgramming/lInfinityCV
"openMVG_lInftyCV_test_resection_robust" start time: Jan 22 22:57 CET
Output:
----------------------------------------------------------

 Launching Test : 43Resection_L_Infinity_Robust_OneOutlier_Test

openMVG_lInftyCV_test_resection_robust: ClpSimplexDual.cpp:3216: int ClpSimplexDual::changeBounds(int, CoinIndexedVector*, double&): Assertion `!("should not 
be here")' failed.
<end of output>
Test time =   0.07 sec
----------------------------------------------------------
Test Failed.
<end_output>
```

I have disabled for cmake: -DOpenMVG_USE_OCVSIFT=OFF. Reason is missing header files in Fedora. I would like to give more details if necessary. What should I do or provide to give a better clue?

By the way, I am very curious about the new GPS functionality!

With kind regards,  Serge GIELKENS

**Comment by sgielkens** [comment]
I now see the ugly bold face. Result of the dashes (------) in the output. Do not pay attention to it, I did not mean to attract attention.

**Comment by pmoulon** [comment]
@sgielkens I have updated your post you can use the markdown command for code.

Did you run the test in release or debug?
Can you tell me if you are using OSI/CLP as internal or external library?

Since your error does not point to the same assertion in the current master version
https://github.com/openMVG-thirdparty/osi_clp/blob/master/Clp/src/ClpSimplexDual.cpp#L3216

On my configuration I have (cmake output)
```
-- CLP: 1.15.10 (external)
-- COINUTILS: 2.9.15 (external)
-- OSI: 0.106.9 (external)
-- LEMON: 1.3.1 (external)
```

**Comment by sgielkens** [comment]
Hello Pierre,

Thanks for the quick response!  I ran the tests in release mode. I will also do a debug build.

I use the system components as much as possible. Also the OSI/CLP libraries are external. These are my versions from the cmake output:

```
-- CLP: 1.16.10 (external)
-- COINUTILS: 2.10.13 (external)
-- OSI: 0.107.8 (external)
-- LEMON: 1.3.1 (external)
```

**Comment by pmoulon** [comment]
Seems like you have a more recent version of CLP/COINUTILS/OSI than the one that are supported by default by OpenMVG.
So the but could be due to a regression in the COIN project or an API change.
Since the linear programming component are not used in the SfM pipeline I would not worry for your experiments. But if you use OpenMVG as a third_party and use the LInfinityCV I would like to investigate with you what is happening.

Having only one test failing is strange, since some other unit test use also the Linear Programming CLP wrapper.

**Comment by sgielkens** [comment]
Hello Pierre,

Thank you for your reply. For your information: the debug build results in exactly the same error.

I do not use openMVG or LInfinityCV explicitly. However, I use openMVG to build openMVS. I have no clue if it has implications for that. I will build openMVS and see what happens.

With kind regards,  Serge

**Comment by pmoulon** [comment]
In your case it will not have side effects.
Thank you for the debug compile and check.

Will try to update the internal CLP/COINUTILS/OSI when I will have some time and try to see what is going on.

**Comment by pmoulon** [comment]
@sgielkens 
I made some more test
=> Update locally to 
```
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: 0.107.8 (internal)
```
And then run the test.
I fall inside an error also for 
```
./openMVG_lInftyCV_test_resection_robust


 Launching Test : 43Resection_L_Infinity_Robust_OneOutlier_Test

Assertion failed: (!("should not be here")), function changeBounds, file /Users/pierrem/Documents/Dev/github_clean/openMVG/src/dependencies/osi_clp/Clp/src/ClpSimplexDual.cpp, line 3216.
Abort trap: 6
```

If I comment in the line ```CoinAssert(!("should not be here"));``` in ```ClpSimplexDual.cpp``` file the test is running ok. So I don't know if the error is due to an error on my side (bad API usage), or in a wrong misjudgment in the OSI/CLP API.

**Comment by sgielkens** [comment]
Hello Pierre,

Thanks for your further investigation! Do I understand correctly that you commented out the assertion to check whether the test finishes successfully?

I did today a quick test to check if the SfM pipeline works without problems regardless of the failing test. It works indeed :-) I also successfully compiled openMVS. I have to check, yet, if it works correctly.

With kind regards,  Serge GIELKENS

**Comment by pmoulon** [comment]
Yes, you understand right, I commented out the assertion in the CLP code and the test is running fine again.

BTW, the message that appears just above the CoinAssert is not very informative
```
// set non basic free variables to fake bounds
// I don't think we should ever get here
CoinAssert(!("should not be here"));
```

**Moreover I think this assert is a regression, since you can see in the CLP official trunk, now the assert is a comment!**
https://github.com/coin-or/Clp/blob/master/Clp/src/ClpSimplexDual.cpp#L3232

**Comment by sgielkens** [comment]
Hi Pierre,

Thank you for your quick answers and communicating this upstream!

Regards,  Serge GIELKENS

**Comment by pmoulon** [comment]
@sgielkens Can you close the issue now that we know the problem is coming (for your case) from the coin_or installation and not OpenMVG.

Note that the next version will use update to date Osi-cpl code.
See https://github.com/openMVG/openMVG/issues/792

**Comment by sgielkens** [comment]
Hi Pierre,

My apologies. That slipped my mind.

Kind regards,   Serge

**Comment by pmoulon** [comment]
No worries, Thx.
Looking forward your next issue ;-)
