### ISSUE TITLE
How to merge scenes with common images? 

### ISSUE THREAD

**Issue by pogilon** [openMVG/openMVG#764]
I have 2 scenes with common images. How can I merge these scenes using OpenMVG? I would really appreciate any input and recommendations!

**Comment by pmoulon** [comment]
You should compute the rigid transform to align them.
To do so, you can compute the 7DoF rigid transform between the two reconstruction by providing the corresponding camera position, and then apply the transform to the reconstruction.

1. List the corresponding camera center in two array (at least 3 cameras)
2. Compute the transform
3. Apply the transform to te reconstruction to make it be in the same coordinate system

Here you will see the code snippet used for rigid GPS registration (robust or non robust):
https://github.com/openMVG/openMVG/blob/master/src/software/Geodesy/registration_to_exif_gps_position.cpp#L150

If you want we can work on a new software in order to do it and so this feature will be available for everyone.

**Comment by pmoulon** [comment]
@pogilon Any feedback?

**Comment by pmoulon** [comment]
Closing since no feedback was provided...
