### ISSUE TITLE
How to use examples in openMVG with xcode ?

### ISSUE THREAD

**Issue by siddharthsrivastava** [openMVG/openMVG#772]
Hi, 

I have compiled openMVG master on Mac OSX with Xcode support. I was wondering how can I execute the samples ?

I have tried with command line where it shows "cannot execute binary file" while when I run with xcode some dependencies are missing (it rebuilds the entire code)

For example, XCode gives the following error while executing (build and run) any sample from within it:

> file:///3dmodel/openMVG/openMVG/src/third_party/ceres-solver/internal/ceres/gmock_gtest_all.cc: warning: Missing file: /Users/siddharthsrivastava/Documents/3dmodel/openMVG/openMVG/src/third_party/ceres-solver/internal/ceres/gmock_gtest_all.cc is missing from working copy

Is there a step by step guide or a cheatsheet for learning to use openMVG with XCode ?

**Comment by pmoulon** [comment]
Can you explain me which sample you are trying to run?
```
openMVG_sample_cameras_undistoBrown
openMVG_sample_multiview_robustEssential_ba
openMVG_sample_features_affine
openMVG_sample_multiview_robustEssential_spherical
openMVG_sample_features_kvld
openMVG_sample_multiview_robustFundamental
openMVG_sample_features_siftPutative
openMVG_sample_multiview_robustFundamental_guided
openMVG_sample_geodesy_show_exif_gps_position
openMVG_sample_multiview_robustHomography
openMVG_sample_image_matching
openMVG_sample_pano_converter
openMVG_sample_main_features_repeatability_dataset
openMVG_sample_robustHomography_guided
openMVG_sample_multiview_robustEssential
openMVG_sample_robust_estimation_Homography
```

Then for SfM i would advise you to use:
https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

**Comment by siddharthsrivastava** [comment]
thanks

**Comment by siddharthsrivastava** [comment]
Hi, I executed the tutorial Sfm sequential pipeline. It works well with the demo dataset. But when Itry with other dataset i.e. the one from  [SFMEdu](http://vision.princeton.edu/courses/SFMedu/) consisting of 5 images. But the pipeline fails with the following error:

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.

> 
> 5. Colorize Structure
> 
> The input SfM_Data file "/3dmodel/30D/output15/reconstruction_sequential/sfm_data.bin" cannot be read.
> 6. Structure from Known Poses (robust triangulation)
> Compute Structure from the provided poses
> 
> The input SfM_Data file "/3dmodel/30D/output15/reconstruction_sequential/sfm_data.bin" cannot be read.
> 
> The input SfM_Data file "/3dmodel/30D/output15/reconstruction_sequential/robust.bin" cannot be read.

Since SFMEdu is able to generate a 3D model (which I believe is inferior to the pipeline in openMVG), is there any specific type of images which I should be using (orientation etc) ?

**Comment by pmoulon** [comment]
OpenMVG is able to recover valid poses for this model (you must ensure that you have valid intrinsic image data).
1. images have no exif data
2. I compute an approximal focal length according this formula -f = 1.1*max(w,h)
3. I send to SfMInit_ImageListing -f 704
4. It works (since valid intrinsic data have been set)

See the log of SfMInit_ImageListing with -i .../SfMEdu/SFMedu2/SFMedu2/images/

=> first run (notice the 0 for the number of intrinsics)
SfMInit_ImageListing report:
listed #File(s): 7
usable #File(s) listed in sfm_data: 5
usable #Intrinsic(s) listed in sfm_data: **0**

=> second run ith the -f X option (notice the 1 for the number of intrinsics)
SfMInit_ImageListing report:
listed #File(s): 7
usable #File(s) listed in sfm_data: 5
usable #Intrinsic(s) listed in sfm_data: **1**

Default reconstruction:
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/22767641/23376348-ee7d-11e6-962e-6b11c6740471.png)

Then I switched to AKAZE_FLOAT with HIGH preset and ANNL2 descriptor matcher in order to have more matches per image pair and I obtain the following:
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/22767686/5395645e-ee7d-11e6-8d64-d7a4c529171d.png)

**Comment by pmoulon** [comment]
@siddharthsrivastava Can you please close the issue?

**Comment by siddharthsrivastava** [comment]
thanks. It works well
