### ISSUE TITLE
Question :  How to compute the PMVS parameter:  level

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#783]
Hello Pierre,

Is there an algo or even a rule of thumb to calculate the value of the level parameter of pmvs (the first line of the PMVS/pmvs_option.txt file)  ?

The parameter's description (http://www.di.ens.fr/pmvs/documentation.html) is clear. But i what need to know/feell is how much time i have to wait ?
I guess such a rule should depend of the image size and number of processor.

Thank you
Alvaro

**Comment by pmoulon** [comment]
Hi @alvaro562003 there is no specific rules for the value of level since the level parameter only tells if you want to use image downsampling or not.
So the larger the level value is, the faster the process will run, but the simplest the scene will be.

If you need more feedback I would recommend you to take a look to https://github.com/alexlocher/hpmvs
In order to use this project on some OpenMVG scene you can use the main_openMVG2NVM binary ;-)

**Comment by pmoulon** [comment]
@alvaro562003 Any feedback?

**Comment by alvaro562003** [comment]
Sorry, i forgot this question. 
I am impressed by the Alex Locher's project. 
In my case, i prefer to wait few minutes till the end.
Thank ou
