### ISSUE TITLE
Using the camera database

### ISSUE THREAD

**Issue by Jlowzow** [openMVG/openMVG#790]
Hi.
openMVG_main_SfMInit_ImageListing is unable to recognise the camera "FC300S", even though I added it to my database file.csv, and specifying the file with the -d option. changing filename to .txt makes no difference.
Any idea to what I am doing wrong?

Sidenote, i am unable to find sensor data for DJI FC6310, will not specifiying sensor sise degrade the result much?

**Comment by pmoulon** [comment]
HI @Jlowzow 
Your FC300S camera must be recognized since it is registered here
https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt#L678

Please note that OpenMVG have its own camera database. The csv file https://github.com/openMVG/CameraSensorSizeDatabase is here to share knowledge to other project and to the community.

Regarding the DJI FC6310, I would like to recommend you to provide a focal guess to the OpenMVG toolchain and see how it goes. You can specific the pixel focal length to the ```main_SfMInit_ImageListing``` binary by using the ```-f X``` option.
Just replace the X value by this computation: 1.1 * max(imageWidth, imageHeight).

**Comment by Jlowzow** [comment]
Hmm, not sure what is happening: I downloaded the updated version of the database. (I made the pull request to put in FC300S into the database)

`ls`
http://ix.io/nxH

`openMVG_main_SfMInit_ImageListing -i . -d sensor_width_camera_database.txt -o matches/`

will output
`DJI_0079" model "FC300S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

DJI_0080" model "FC300S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

DJI_0081" model "FC300S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

DJI_0082" model "FC300S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

DJI_0083" model "FC300S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
`

It looks like searches with the filename as key (droping .jpg) in the database. Which is why it does not find the camera model.
The lookup should be with "DJI" not "DJI_0220".

I will build openMVG again and retry.

**Comment by pmoulon** [comment]
Hi @Jlowzow 
Your camera must be recognized out of the box since it is shipped in the camera database see here
https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt#L678

The keyword that is look for in the database is "FC300S", the DJI_00XX that you saw is the image view filename.

Please be sure to use the database that is given with the OpenMVG project and not the one from https://github.com/openMVG/CameraSensorSizeDatabase

**Comment by pmoulon** [comment]
@Jlowzow Did the proposed solution fixed your problem?

**Comment by Jlowzow** [comment]
No, sorry. But I want to do more testing before i claim that this is a bug. Will try with another dataset.

**Comment by pmoulon** [comment]
@Jlowzow Any more feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity.

**Comment by Narayan999** [comment]
Hi.
How can I add  logitech hd pro webcam c920 to opemMVg camera database. I have attached the sample picture for reference.
Thank you.
![picture](https://user-images.githubusercontent.com/23073493/34599140-3840ff5e-f234-11e7-8f7a-0222165642d6.jpg)

**Comment by pmoulon** [comment]
1. You have to check if your image have some EXIF data that depicts the camera model and its focal length.
To do so -> Does the binary `main_SfMInit_ImageListing` says something about your image. If the image does have the required EXIF info but not found in the camera database a message is displayed (`XXXXX doesn't exist in the database. Please consider add your camera model and sensor width in the database.`). Else the camera does not have the required EXIF data and so I advise you to look to the following step 2.

2. The simplest way for you to use your image for unknown source it to provide to the pipeline an approximate focal length that will be refined by the Bundle Adjustment step during the SfM process.
To do so you can use the `-f` option on the `main_SfMInit_ImageListing` binary. As parameter for this option you can use the rules `1.2 * max(w,h)`. In your case a good value will be 3648*1.2 = 4377. So just add `-f 4377` to the command line for `main_SfMInit_ImageListing` and you will be good to go.

**Comment by yolingen23** [comment]
Hi, I am using a Gopro Black 7 camera. My camera is not in exif / sensor_width_database / sensor_width_camera_database.txt. How do I add my camera to this file? The EXIF file shows focal length 3.0 mm, width 4000, height 3000.I also calibrated my camera in matlab. I have all the calibration data.

**Comment by rockokw** [comment]
All you have to do is add a line containing the sensor width to sensor_width_camera_database.txt
For example, I have a Pixel 3 with a sensor width of 5.76mm so I added the following line to the file:
`Pixel 3;5.76`
The name you use should be the same as the Model in the EXIF data.

**Comment by yolingen23** [comment]
![Screenshot from 2019-12-07 02-15-34](https://user-images.githubusercontent.com/48957011/70353411-59d07100-187e-11ea-9ef3-64e34eb18181.png)

first of all thank you for your return.
I have entered the "sensor_width_camera_database.txt" camera's model and senor width into the txt file in the openmvg folder as mentioned, and the attached image shows the error I received on the code.my original openmvg file is installed in the opt file. I wonder if it calls from there when it's running the program. Otherwise, the openmvg program that is installed in Desktop is running. Because I just added the txt file in the openMVG folder in Desktop.

**Comment by rockokw** [comment]
Your change looks fine. That error message is because openmvg is trying to load that file as an image for some reason. Can you trying starting the process again with a fresh, clean image listing?

**Comment by yolingen23** [comment]
thank u very much @rockokw  . i process again with new image folder. i fixed. 
as another question;
I also calibrated my photos in opencv and want to use the values in the k matrix. how can I do that in openmvg?

**Comment by rockokw** [comment]
For the camera intrinsic data, I believe you can edit the sfm_data.json file manually or play around with the arguments to openMVG_main_SfMInit_ImageListing. 
See: https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/

It might be a good idea to open a new issue at some point, if this doesn't work.

**Comment by pmoulon** [comment]
@yolingen23 
If you want to use your own calibration there is two ways:
- From SfMInit_ImageListing by using -f `YOUR_FOCAL_VALUE_FROM_YOUR_CALIBRATION`
or
- Use SfMInit_ImageListing with the camera model you need
- Then you can edit the sfm_data.json and update your camera parameter (using python or your favorite GUI)
- Then you run the rest of the pipeline (features, matches, sfm). Note that the matche stage will use the distortion factor your input to find better matches.

Notice also that the GoPro cameras could have various FoV settings, so your calibration will be only valid for a single fov setting.

**Comment by yolingen23** [comment]
Thank you very much for your help. I'm newbie. I want to get camera coordinates using OpenMVG. What should I do for this? Can you briefly tell me how to get coordinates?

**Comment by pmoulon** [comment]
For this you have to run the SfM pipeline and then convert the sfm_data.bin to sfm_data.json using SfMDataConverter and then look for the camera poses `poses`. You will have the pose defined as rotation and center.

**Comment by yolingen23** [comment]
5. Optional further processing and 5. Optional further processing (3rd party) required?

**Comment by yolingen23** [comment]
The sensor Dimensions 6.17 mm x 4.63 mm. I want to implement this option (`From SfMInit_ImageListing by using -f YOUR_FOCAL_VALUE_FROM_YOUR_CALIBRATION`). For this (max (4000 * 3000) * 3 mm) /6.17) If I apply the formula -f 1944.89 do I have to write ? @pmoulon

**Comment by pmoulon** [comment]
Yes, you can run with an approximate focal by using `-f 1944.89` or use the accurate one you found with calibrating your camera `-f 1119.6`

Distortion factor should be retrieve and approximated by BA.

**Comment by yolingen23** [comment]
How can I make it happen. I did not get it `Distortion factor should be retrieve and approximated by BA.

` Do I also need to do the steps after the Global Sfm step to get the camera coordinate

**Comment by pmoulon** [comment]
Please create a thread link to your issue, here we don't speak anymore about the camera database.
What I meant is that the SFM process and the BA run in this process will refine the input camera model you provide.
