### ISSUE TITLE
Use of dynamic_cast with Regions

### ISSUE THREAD

**Issue by hugbed** [openMVG/openMVG#797]
Hi,

I was looking at the [robust estimation tutorial homography](https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_estimation_tutorial/robust_estimation_tutorial_homography.cpp) and couldn't help but notice the use of a dynamic_cast to a derived class (`SIFT_Region`) to retrieve function members such as `Descriptors`. 

Wouldn't there be an alternative to `dynamic_cast` since in a real-time applications, the non-deterministic dynamic casts could be problematic? From what I have learned, dynamic casts are used sometimes because the interface cannot correctly represent the implementation (maybe I'm wrong). Maybe the Image_describer could be templated with its corresponding `Regions` type, e.g., `SIFT_Image_describer ` could derive from `Image_describer<SIFT_Regions>` and use the templated type as region.

I don't know if it's just me but it feels weird to use dynamic_cast as a standard way to use an interface.

For example in Image_describer (c++ pseudo-code):

```cpp
template <class RegionType = features::Region>
class Image_describer
{
  // ...
}
```

And SIFT_Image_describer:

```cpp
template <class RegionType = SIFT_Regions>
class SIFT_Image_describer<RegionType>: Image_describer<RegionType>
{
  // ...
}
```

There could be different template specialization for different region types to replace the switch cases in the implementation. However, this seems like much work and would change the current interface...

Something like that could render the Region type available at compilation so the `dynamic_cast` would not be necessary would be great:

```cpp
std::unique_ptr<Image_describer<SIFT_Regions>> image_describer
    (new SIFT_Image_describer(SIFT_Image_describer::Params(-1)));
std::map<IndexT, std::unique_ptr<SIFT_Regions> > regions_perImage;
image_describer->Describe(imageL, regions_perImage[0]);
image_describer->Describe(imageR, regions_perImage[1]);

SIFT_Regions *regions = regions_perImage.at(0).get();
```

I'm not sure about how this could be implemented but I would like your opinion on the matter!

Thank you.

**Comment by pmoulon** [comment]
Hi @hugbed 
Thank your for your feedback. Here my answer.

1. I have choose the design to be as abstract as possible because for example a single Image_Describer can return various regions type and the major point is that I would like to write generic code.

If you take as example the AKAZE_Image_describer ([here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/image_describer_akaze.hpp#L109))
You will see that it can return ```AKAZE_Float_Regions```, ```AKAZE_Liop_Regions``` or ```AKAZE_Binary_Regions``` depending of the choice of the description method.

2. I choose the fact that the Image_describer is not storing the regions type for another interesting outcome, we can change easily the Image_describer allocation and the rest of the code will continue to work.

3. We can use the Image_describer as parameter of function and class without trouble. In your case we will have to use template everywhere.

```
  std::unique_ptr<Image_describer> image_describer(
   //new SIFT_Image_describer);
   new AKAZE_Image_describer); // Here with one line I can use a different region type
  std::map<IndexT, std::unique_ptr<features::Regions> > regions_perImage;
  image_describer->Describe(imageL, regions_perImage[0]);
```
In your case the type is stored in the "mother" class and so if I want to switch to AKAZE I have to change the region type in many places.
```
std::unique_ptr<Image_describer<SIFT_Regions>> image_describer
    (new SIFT_Image_describer(SIFT_Image_describer::Params(-1)));
std::map<IndexT, std::unique_ptr<SIFT_Regions> > regions_perImage;
image_describer->Describe(imageL, regions_perImage[0]);
image_describer->Describe(imageR, regions_perImage[1]);
```

See here for a concrete example (perhaps you took an example that I have not made generic yet ... due to time reason):
https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/openMVG_Samples/features_image_matching/describe_and_match.cpp#L62
```
using namespace openMVG::features;
  std::shared_ptr<Image_describer> image_describer;
  if (sImage_describer_type == "SIFT")
    image_describer = std::make_shared<SIFT_Image_describer>
      (SIFT_Image_describer::Params());
  else if (sImage_describer_type == "AKAZE")
    image_describer = std::make_shared<AKAZE_Image_describer>
      (AKAZE_Image_describer::Params(AKAZE::Params(), AKAZE_MSURF));
  else if (sImage_describer_type == "AKAZE_MLDB")
    image_describer = std::make_shared<AKAZE_Image_describer>
      (AKAZE_Image_describer::Params(AKAZE::Params(), AKAZE_MLDB));
....
 //-- Perform matching -> find Nearest neighbor, filtered with Distance ratio
  matching::IndMatches vec_PutativeMatches;
  matching::DistanceRatioMatch(
    0.8, matching::BRUTE_FORCE_L2,
    *regions_perImage[0].get(),
    *regions_perImage[1].get(),
    vec_PutativeMatches);
```

In your case, since the mother class is already templated you cannot write generic code, or at least you have to consider template parameter everywhere.

So if you want to avoid the cast, just feel free to use directly the SIFT_regions type once and use those pointer later on:
```
const SIFT_Regions* regionsL = dynamic_cast<SIFT_Regions*>(regions_perImage.at(0).get());
const SIFT_Regions* regionsR = dynamic_cast<SIFT_Regions*>(regions_perImage.at(1).get());
// do your stuff
```

As you can see in the rest of the toolchain, the abstract regions type is used for Image collection matching and it's transparent [top class](
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L358) =>  [end calling](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/openMVG/matching/regions_matcher.cpp#L54)


So my conclusion would be there is always compromise between using template or inheritance and I have choose the solution that allow to hide the region type and allow me to test later on the regions type and have some generic code.

But I'm open to any new design and I really like that you take time to illustrate and explain your motivation.
OpenSource is getting better and better since your can iterate and find better design on a large community (So if we find a new design that allow to do more things or allow to have a faster code, I'm open to it!).

**Comment by hugbed** [comment]
Indeed, templating does not seem to be the best solution here.

I thought about it (a lot) and may have found a better solution. 
Since derived classes of Image_describer uses derived class of Regions, there should be a way to abstract the Region at the Image_describer level, while conserving the specific type at the SIFT_Image_describer for example. 

Since the Regions are passed as a parameter to the Describe function, there does not seem to be a trivial solution using this interface to keep specific type information. However, since the regions are theoretically returned by the function, an interface that returned the regions instead of passing them as parameter could have more flexibility in terms of type conservation. The new move semantics of C++11 makes returning local variables inexpensive which is great. Covariant return types could be used to conserve type information.

I have made an example [here](http://coliru.stacked-crooked.com/a/e249c8ce0d7ec567).

So let's simplify the Regions classes for testing purposes:

```cpp
class Regions { 
public:
    virtual void genericFunction() {
        std::cout << "I'm a generic region" << std::endl;   
    } 
};
class SIFT_Regions : public Regions {
public:
    void genericFunction() override {
        std::cout << "I'm a SIFT region" << std::endl;   
    }
    
    void specificFunction() {
        std::cout << "Good job, you found me" << std::endl;   
    }
};
```

We have a genericFunction that is a function that all Regions share (for example GetPositions). And a specific function (e.g., Features or Descriptors).

This is how we could implement the alternative Describe interface while perserving the current interface:

```cpp
class Image_describer {
public:
    // using NVI idiom to wrap covariant return type in a smart pointer
    // only the base class knows about generic regions so this is not virtual
    unique_ptr<Regions> Describe() {
        return unique_ptr<Regions>(doDescribe()); // upcast SIFT_Region type
    }
    
    // the current interface style could also use doDescribe
    virtual bool Describe(unique_ptr<Regions> &regions) {
        regions.reset(doDescribe());   
        return true; // this boolean would be lost though
    }
protected:
    // using covariant return types for specific implementation
    virtual Regions* doDescribe() = 0;
};
```

So there could be a doDescribe function that is virtual and return a pointer of type Regions. This would be the function implemented in the derived classes, which would return specific Regions (e.g., SIFT_Regions). Since covariant return types does not work for smart pointers (sadness), it would be necessary to [wrap the call into a non-virtual function call](https://en.wikipedia.org/wiki/Non-virtual_interface_pattern), which is not so bad since the generic Image_describer would have a generic Describe function and the specific SIFT_Image_describer would have a specific Describe function (that returns unique_ptr<SIFT_Regions>) and the implementation of doDescribe is still enforced. 

So a specific implementation of Image_describer could look like:

```cpp
class SIFT_Image_describer : public Image_describer {
public:
    // use base implementation of bool Describe(unique_ptr<Regions> &regions)
    using Image_describer::Describe;

    // this does not override base class Describe
    // since only this class knows about specific SIFT_Regions
    unique_ptr<SIFT_Regions> Describe() {
        return unique_ptr<SIFT_Regions>(doDescribe());
    }
    
protected:
    // using covariant return types : SIFT_Regions is a Region
    virtual SIFT_Regions* doDescribe() override {
        return new SIFT_Regions;
    }
};
```

A function that takes generic Regions would still work since SIFT_Regions are Regions:

```cpp
// raw pointer means ownership is not transfered
void MatchRegions(Regions* regions) {
    return;   
}

// or

// not really necessary since it does not take ownership of the pointer
void SmartMatchRegions(const unique_ptr<Regions> &regions) {
    return;   
}
```

This is an example of how such interface could work in pair with the current interface:

```cpp
int main() {
    // you can construct a specific or generic image describer
    auto generic_image_describer = unique_ptr<Image_describer>
        (make_unique<SIFT_Image_describer>()); // as before
    auto specific_image_describer = 
        (make_unique<SIFT_Image_describer>());
    
    // if you want to return generic region
    unique_ptr<Regions> genericRegions;
    genericRegions = generic_image_describer->Describe(); // as before
    genericRegions = specific_image_describer->Describe(); // this still works
    
    // if you want to return specific region
    // only works with specific describer
    // but at least you can retrieve the specific type!
    auto specificRegions = specific_image_describer->Describe(); // type is information is preserved here
    
    // current API still works
    generic_image_describer->Describe(genericRegions);
    specific_image_describer->Describe(genericRegions);
    
    // only generic functions are available for generic regions
    genericRegions->genericFunction(); // as before
    
    // specific functions are available without dynamic cast
    // returns SIFT_Regions
    specificRegions->specificFunction(); // can use the preserved specific type
    
    // using generic or specific regions still work
    MatchRegions(genericRegions.get());
    MatchRegions(specificRegions.get());

    // using generic or specific regions still work
    auto genericRegionsUpCasted = unique_ptr<Regions>(move(specificRegions)); // however, loosing type information here
    SmartMatchRegions(genericRegions);
    SmartMatchRegions(genericRegionsUpCasted);

    return 0;
}
```

**Comment by pmoulon** [comment]
Hi @hugbed 
Thank you for your second draft. Really appreciate it

If I'm right your solution will work only if the implementation of an Image_describer is returning only one specific `Regions` type.

So if I take the actual code of the `class AKAZE_Image_describer` that can return various `Regions` type, your design will not work. If I' right, since your `doDescribe` return only one specific region type I will have to create three different new class `class AKAZE_Image_describer_FLOAT`, `class AKAZE_Image_describer_MLDB`, `class AKAZE_Image_describer_LIOP.` Do you confirm that I' right?

You idea is interesting, feel free to start a mockup in a branch in a fork and then we can iterate for an integration into a future version (your branch must start from develop).

**Comment by hugbed** [comment]
Hi, I'm glad you appreciate my input.
 
Yes, you are right. This design will work only if an `Image_describer` returns one specific `Regions`. However, I feel that this would enforce the use of polymorphism in classes derived from `Image_describer` and prevent "switch case" kind of designs which can become hard to maintain after adding some cases that may or may not share similar code. Different Regions types would be handled by different specific derived classes which seems logical (to me at least!). 

With a more polymorphic design, derived class provide specific implementations that still respect the base interface and one can always derive more to handle more specific details while preventing duplicate code for similar feature types. For example, an `AKAZE_Image_describer` interface could use generic `Regions` and contain shared code between specific AKAZE implementations and a more specific `AKAZE_Image_describer_LIOP` could use specific `LIOP_Regions` and would actually implement the doDescribe.

This way, it is possible to choose at which level of the interface you want to work while conserving the specific types, e.g., `Image_describer` to work with generic `Regions`, `SIFT_Image_describer` to work with `SIFT_Regions`. Then you can choose the level of abstraction with the pointer type used to store your `Image_describer`.
 
```cpp
// use generic Features
auto generic_image_describer = unique_ptr<Image_describer>
    (make_unique<SIFT_Image_describer>()); // as before
// use SIFT Features
auto specific_image_describer = unique_ptr<SIFT_Image_describer>
    (make_unique<SIFT_Image_describer>()); // as before
```

I will start a mockup when I'll have the time soon.
Thanks for your support!

**Comment by pmoulon** [comment]
I close the issue since we have merged the new design ;-)
