### ISSUE TITLE
OpenMVG can't do SFM for human face  automatically? But I can detect landmarks on images. 

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#799]
Then how to use OpenMVG code to do SFM?  thanks
SIFT feature detecting and matching did not work for human faces.

**Comment by rperrot** [comment]
It is known to works, but you should be very careful to some points : 
- Face should stable across all view (the current pipeline work for rigid object) ;
- You may have to use higher density of point (use HIGH or ULTRA preset when extracting elements).
 
You can use AKAZE_FLOAT with preset HIGH for testing.

**Comment by wguo68** [comment]
I don't know what are these HIGH or ULTRA or AKAZE_FLOAT ? 
If I can just have  6 landmarks (eye corners ,mouth corners,...)on each facial image and I have about 5 images.  Can I do SFM and how to do using OpenMVG?

**Comment by rperrot** [comment]
BA is not a magic box, SfM in your case must be considered as a whole : feature extraction/matching then SfM reconstruction. 

You may use the SfM pipeline, particularly the incremental one on your specific problem (located in build/software/SfM)

**Comment by pmoulon** [comment]
@wguo68 Please read the introduction tutorial and navigate in the doc
https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

You can also share you dataset on openmvg-team[AT]googlegroups.com and then we can try to make a reconstruction for you.

**Comment by pmoulon** [comment]
Note that every SfM method need some step to work:
- configure intrinsic parameter
- compute features
- compute matches
- compute 3d reconstruction -> camera poses & sparse point cloud (SfM)
- compute dense 3d reconstruction -> dense point cloud or surface plus texture (MVS)

**Comment by pmoulon** [comment]
@wguo68 Any feedback?

**Comment by wguo68** [comment]
Because the openmvg is hard to use ( Its file format and match graph are hard to use). I have give up to use OpenMVG for my task. I will write my own code to do this simple job! Thanks.

**Comment by rperrot** [comment]
Could you explain in precise terms why OpenMVG is hard to use ? 

Did you check the samples ? Did you use the standard python pipelines for your specific need ?

**Comment by pmoulon** [comment]
OpenMVG is a pipeline. As @rperrot said, you can use the python script that will launch the toolchain for you. Face are hard to reconstruct for every photogrammetry solution since by nature a face does not provide a lot of Keypoint with the default SIFT settings.

By saying you want to extract more keypoint (see feature preset in ComputeFeatures) you can be able to obtain something realistic.

As you can see here some users of OpenMVG made nice faces capture
http://arc-team-open-research.blogspot.com/2013/09/scanning-face-in-3d-with-photos.html

**Comment by wguo68** [comment]
The pipeline is a black-box and lt is hard for me  to pass landmarks detected with other libs.I know the camera intrinsic and landmarks.

**Comment by pmoulon** [comment]
1. Since the skin is poor texture, painting on it will help image registration and dense depth map generation a lot.

2. The pipeline is not a black box. Each binary source code is available so you ca dig into.
  1. The sfm_data.json file is generated by the SfMInit_ImageListing binary.
  2. In order to make face reconstruction I advise you to take more images (10 is too few) in a good light environment and try to use a tripod to make your pictures as sharp as possible.
