### ISSUE TITLE
know camera positions

### ISSUE THREAD

**Issue by heikog** [openMVG/openMVG#825]
i wonder if the computing process could benefit from "know camera positions".
For example if I position 4 (or six or eight) Cameras at the corners of the room pointing inwards and so the camera positions are known and stay the same between different shots.
Is  there any benefit to that ?

**Comment by pmoulon** [comment]
For sure you can benefit from known camera position.
In your case if your know the position of your camera you can use the location prior position for a view (as it is used for the GPS XYZ data). And then the BA will ensure to keep your view close to the specified pose.

Can explain more about your camera setup and usage in order to let us be able to provide more feedback and help?

**Comment by heikog** [comment]
thanks for the replay. The idea is to permanently place cameras in the corners of a room ( or on the walls) and at will produce a 3D reconstruction of the room.
And i am wondering now how many cameras you would need and how to point them (probably pretty easy to figure out by testing) and secondly: how can the reconstruction process benefit from the fact that I know where i placed the cameras in the first place (and how and where do i feed this knowledge into the software)
any more thoughts ?

**Comment by pmoulon** [comment]
The idea is that every area you want to recover in 3d must be visible by 3 cameras.

So depending of your FoV (Field of View), the camera resolution, the room size => the number of cameras can change.

 feed this knowledge (known camera position) into the software => I already answered to that:
- You can specify a position prior see [here](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L397),
- Or reuse the previous camera position and only triangulate the corresponding features (tracks).al
