### ISSUE TITLE
Proper documentation?

### ISSUE THREAD

**Issue by MaXL130** [openMVG/openMVG#830]
Hello everyone,
I'm trying to start using openMVG and I managed to set it up correctly. Right now I'm facing the issue, that I am not really sure how to use the library.

Is there any more documentation than the provided "Read the Docs"-Page and the comments in the source code, that I can use and have missed in the past?

Thanks for your help!

**Comment by rperrot** [comment]
We know were lacking a more user friendly documentation with some tutorials, but we try to do our best to remedy to it. BTW, you could find some information at various places (from the high level to the low level view) : 
- use the proposed python pipelines (sequential/global located in your build software/sfm directory) to have a complete reconstruction tool (from images to view/structure) (maybe the best to start with openMVG) ;
 - consult the executables in software/sfm to see what you can do with the library (in a more step by step approach) ;
- have a look at the samples (build it if they are not yet built), they illustrate some specific points of the library ;
- have a look at the unit_tests, they often provide a (minimal) way to use internal structures/functions of openMVG. 

If you don't find your specific information, please tell us what you want to do.

**Comment by MaXL130** [comment]
Thanks for your answer! I will look into those. If I keep getting stuck, I will give you an update.

**Comment by pmoulon** [comment]
Feel free to close the issue when you have the answer to your question.
Feel free also to share any reconstruction results (screenshot) ;-0

**Comment by MaXL130** [comment]
I managed to get some results using the incremental, premade python pipeline and PMVS (see below).

As you can see, only one "half" of the cup was correctly reconstructed, with some minor holes in it. What am I doing wrong? I shot many pictures of the cup, going all around it multiple times in different heights.

![clowncuphalf02](https://cloud.githubusercontent.com/assets/26429337/24359805/b7ebef5c-1305-11e7-86cc-7d228c849d4a.png)
![clowncup01](https://cloud.githubusercontent.com/assets/26429337/24359804/b7e542ec-1305-11e7-8fbf-022bd6b0c869.png)

**Comment by pmoulon** [comment]
Thank for the sharing.

The reconstruction is not complete since the image connection graph must be cut somewhere (certainly less feature for some part of the models).
You can have a look at the logged graph in the matching directory -> svg files (if you have graphviz installed they are exported).

You can try to make the graph denser by using a preset on the feature detector by adding the option `-p HIGH` on the ComputeMatches binary (do it in a new output directory else old feature will be read). 

Or do the same dataset by adding a journal paper below your mug in order to have more texture and so more reliable feature matches from view to view.

**Comment by MaXL130** [comment]
Thanks for the quick answer! Let's see what I can come up with 👍

**Comment by MaXL130** [comment]
I am facing some issues, but for now I am going to close this issue, since the actual question was already answered. I am going to reopen, if there is sth new to report.
