### ISSUE TITLE
[Question] Image registration

### ISSUE THREAD

**Issue by chulminy** [openMVG/openMVG#835]
Dear Experts

I have a question in general.

I constructed a big 3D point cloud model using OpenMVG.  What is the best way to estimate camera matrix (intrinsic and extrinsic) as well as lens distortion parameters for new images? (aka. image registration or localization).

Currently, first, I find the 3D-2D correspondences (3D points in the model and 2D features on the new images) by matching SIFT descriptor. Based on this information, I ran a function of 'solvepnpransac' in OpenCV for pose estimation. Of course, intial intrinsic matrix is computed using EXIF data including principal points and focal lengths. Then, bundle adjustment is implemented to refine all these parameters including intrinsic and extrinsic parameters as well as lens distortion parameters. 

Do you think that I'm doing this in a right way? 

Some issues are 
(1) I can't use "calibrateCamera" in OpenCV because there are lots of spurious 2D-3D correspondences in my application so I need to use RANSAC. There is no RANSAC implementation of "calibrateCamera". 

(2) I don't think it is a good way to find all 2D-2D correspondence to do this because I used more than 5000 images to construct the 3D point cloud model. 

Do you have any suggestion?

Chul Min Yeum

**Comment by pmoulon** [comment]
Dear @chulminy 
So you try to localize and find the internal calibration of your camera (intrinsic).

I understand that you write some code to do that.
Are you aware that there is already an app that can localize picture inside an OpenMVG reconstruction?
https://openmvg.readthedocs.io/en/latest/software/localization/localization/
https://github.com/openMVG/openMVG/blob/master/src/software/Localization/main_SfM_Localization.cpp

Your implementation steps looks good, it is very close to the approach done in the binary I depicted you.

Else if you need to calibrate new camera you can try to perform sone kind of auto-calibration.
You take a lot of picture of a very basic textured object and perform SfM with those images. Since the images will have a lot of overlap and common points the SfM refined parameter will be very good.

Looking forward to continue the discussion.

PS: For very large scale reconstruction I advise you to look to the previous tutorial listed there
https://sites.google.com/view/lsvpr2017/home it shows way to compute the corresponding feature in an optimized way.

**Comment by chulminy** [comment]
Fantastic. Thank you for your kind answer. 
I'm familiar with Matlab so I import SfM data and process them in Matlab. 
I actually wrote a complete code that I mentioned above and obtained a good localization result. 
I would get a confirmation that I did a right way from you or other experts in this github 
As far as I know, there are lots of methods to localize the images in the literature but I would take the simplest way that I can implement in Matlab. 

I don't think people in this Github use Matlab but, if someone needs codes to import SfM data to Matlab, I am willing to share them here. 

Thank you for the link in PS and they are helpful for my research. 

Chul Min Yeum

**Comment by pmoulon** [comment]
I would be curious to see if you can run the Localization tool on your dataset to compare it to your matlab implementation ;-) Must be easy as a command line to launch!

I never ran it on such big dataset but it should run ok ;-)

Regarding your MATLAB SfM_Data import, let see how other person react to it.
I'm pretty sure it can be useful for a lot of person and open new way to use OpenMVG results to the community ;-).

**Comment by chulminy** [comment]
Sure. I will. Thank you for your help. 

Chul Min Yeum
