### ISSUE TITLE
Differing Scales of Reconstruction

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#851]
Hi, I have an dataset of n images, I have run SFM on the dataset with the following combination of parameters, 
1) Incremental_SIFT_High.
2) Incremental_SIFT_Low
3) Incremental_AKAZE_High
4) Incremental_AKAZE_Low

Reconstruction has been successful in each of the case, but what I noticed was that the scale of the object for each of the case was different, could someone please explain why the scale of the objects was different in each case? The fx and fy in the intrinsic matrix is the same for each of the case, so shouldnt I have expected the same scale of size for each of the cases? I would also like to know another small thing, does openMVG assume fx = fy = f in pixels for computation? 

I get a feeling this has something to do with the scaling factor in the homogeneous coordinates, but not very sure how it is useful here. TIA

**Comment by pmoulon** [comment]
SfM will retrieve the reconstruction up to scale of the reality.

This scale is not the same for every run since the initial pair and bundle adjustment will make the scale varies for every try on your settings.

You are right the focal is the same for fx and fy, I assume square pixels.

1. If you want to scale your model you can use a marker with known dimension.
2. If you want to compare various reconstruction you can align them by tweaking a bit https://github.com/openMVG/openMVG/blob/master/src/software/SfM/tools_precisionEvaluationToGt.hpp#L101

**Comment by naveenjafer** [comment]
@pmoulon Could you elaborate a little more on what you mean by use a marker of known dimension? Do you mean use the real world units for something like focal length?

**Comment by pmoulon** [comment]
I mean known dimension of an object in the scene.
