### ISSUE TITLE
Is it possible to limit scene to area smaller than what the default reconstruction provides?

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#863]
Hi, I am trying to reconstruct a scene where the pointcloud has a lot of outliers and would like to limit the scene to the area immediately surrounding the area where I took the photos.  This would greatly aid in continuing the reconstruction with openMVS.

Is there a tool or a method to achieve what I'm thinking?  [This](https://github.com/openMVG/openMVG/issues/857) looks promising but until that is implemented could there be a manual way to define the region of interest?

I've attached some images from [robust_colorized.ply](https://drive.google.com/open?id=0Bwy27kjg_aw5SXVGMEN6ZlY1dUk) to illustrate.

![image](https://cloud.githubusercontent.com/assets/17804207/24831856/469c8022-1c57-11e7-87e5-08fa94ae60d6.png)
![image](https://cloud.githubusercontent.com/assets/17804207/24831858/592a3ab8-1c57-11e7-994d-945cb28d74a8.png)
![image](https://cloud.githubusercontent.com/assets/17804207/24831863/88be01e2-1c57-11e7-83d1-3b2f4522cf1e.png)

This area is all that I'm interested in:
![image](https://cloud.githubusercontent.com/assets/17804207/24831882/c5eb0cd6-1c57-11e7-9529-aac316d68eb1.png)

**Comment by pmoulon** [comment]
Using all the point is interesting for SfM.
I understand that you need a post-processing step in order to limit the area of interest.

I could think about to add a filtering binary that could:

- use a bounding box filter in order to keep only the points that are located in a specified area (but this alternative require to the user to be careful and specify the right value).

- use a filter based on a rule based on the depth of point relative to the camera:
  - a measure like `x * MeanDepth` for all the cameras,
  - a measure like `x * MeanDepth` per camera.
(we can think about using the mean or the median).

How does those ideas sounds to you?

**Comment by jpwhitney** [comment]
HI Pierre, thanks for the thoughtful response.  I agree that all points are interesting, however I only have one small computer and it becomes computationally intensive to the point of being prohibitive to continue with mesh reconstruction. ;-)

The second method you suggest sounds ideal, that is this one:
'''use a filter based on a rule based on the depth of point relative to the camera:

a measure like x * MeanDepth for all the cameras,
a measure like x * MeanDepth per camera.
(we can think about using the mean or the median).'''

What about thinking of some measure that consists of finding the center point of all camera positions and then the farthest extent in each direction to establish two orthogonal vectors to establish a plane and then calculate a rectangle which contained all cameras in that plane plus some buffer x * side length?

I'm on my phone now but when I get to a computer I can draw a diagram if it is unclear what I'm thinking.  I could probably come up with the algorithm to do it as well, but knowing where to put that is beyond my programming ability at the moment.  If there was some filter template perhaps I could figure it out.

**Comment by pmoulon** [comment]
The plane idea + the dilation of this plane to a bounding box is interesting but it will work only on some scene (UAV like acquisition).

I implemented the Depth filter and I can make you test it.

I can help to implement your idea but I don't know when I will be able to perform it.

Here a test on the OpenMVG sample dataset:
**Before**
![before00](https://cloud.githubusercontent.com/assets/3235050/24844966/a203080c-1dae-11e7-8928-851ffabf37fd.png)
**After the filtering step -> one parameter to play with**
![after01](https://cloud.githubusercontent.com/assets/3235050/24844967/a2031306-1dae-11e7-96d8-27b8c5f10bd7.png)

So it's only a start since the parameter is working on depth statistic per camera. We can think to a global depth value used as a threshold rather than a criteria per camera.

See https://github.com/openMVG/openMVG/issues/865 and branch `develop_filtering`

You can use it like that:

1. Export the output to PLY and find the -f ratio by bisection (default value is 5.2)

`./Linux-x86_64-RELEASE/openMVG_main_PointsFiltering -i PATH/sfm_data.bin -o PATH/sfm_data_filtered.ply` // will use a factor -f = 5.2

=> Play by bisection to find the right f value (I'm sure in two or three try you can find the right value)
`./Linux-x86_64-RELEASE/openMVG_main_PointsFiltering -i PATH/sfm_data.bin -o PATH/sfm_data_filtered.ply -f 1.15`

2.  Export the output to bin and use openMVG2X in order to post process the scene with your favorite MVS framework

`./Linux-x86_64-RELEASE/openMVG_main_PointsFiltering -i PATH/sfm_data.bin -o PATH/sfm_data_filtered.bin -f 1.15`


Let's continue the discussion. I'm pretty sure my solution will work for your case

**Comment by jpwhitney** [comment]
This looks very promising.  Yes we are doing UAV like photographs, however in the area there is prohibition on drones so we must do by hand.  Therefore the angle for camera registration gives many points far far away from the study area.  As such I think this filter will be very helpful for our and similar use cases.

I cannot check for at least one week as to how this works.  But I imagine it will work very well.  I will check back in then with the results.

**Comment by naveenjafer** [comment]
@jpwhitney If it is a planar almost circular acquisition( which it is generally in an UAV) you will be able to filter points that lie outside a rough bounding circle of camera poses, this will help quite a lot in your use case.

**Comment by jpwhitney** [comment]
@naveenjafer Are you suggesting finding the center of the cameras and creating a bounding box circular out from that?  That would be interesting to automatically choose the region plus some multiplier x * radius.  Ideally we want a rectangular image so we can convert to a raster.

**Comment by naveenjafer** [comment]
Yes, that was the idea. My bad, wasn't aware of your use case. Would be interesting to come up with something reliable for that on basis of distance statistics

**Comment by pmoulon** [comment]
@naveenjafer The proposed approach already rely on distance statistics (based on depth).
For sure we can improve this first draft and build an alternative based on camera position. Feel free to propose and implement various alternative.

**Comment by pmoulon** [comment]
@jpwhitney Did you made any experiment with the provided code?

**Comment by jpwhitney** [comment]
@pmoulon Sorry for the delay.  I am testing now.

**Comment by pmoulon** [comment]
Hoping it will provide interesting results or feedback.

**Comment by jpwhitney** [comment]
I had some interesting results, but still fine tuning the options.  Thanks for providing this so I can experiment!  I'm interested in the following code snippet:

```
double DepthCleaning
(
  SfM_Data & sfm_data,
  const double k_factor =  5.2,    //5.2 * median ~= X84,
  const IndexT k_min_point_per_pose = 12,  // 6 min
  const IndexT k_min_track_length = 2      // 2 min
)
```

I'm a bit confused by the value of 12 for k_min_point_per_pose.  It seems that a value of 4.5 for k_factor for my case in the example above works well to reduce the most extreme outliers, however it appears that some detail is lost on the far edges of the areas I wish to keep.  I'm not sure how this will propagate forward, but some preliminary tests indicate that if I set the value of k_factor to be too low I ended up with a mesh that was not connected.  Still ironing out the details to get the best combination of results.

Do you think a number other than 12 would be good?  Curious from a theoretical standpoint how the number of points per pose would impact the quality of the final mesh.  I could always run some tests to see, but I'd rather not recompile openMVG each time.  Was thinking of adding a command line option to play around with it.  Maybe will do that and get back to you.  Still interested how you came up with the number 12.

**Comment by pmoulon** [comment]
Determining a absolute pose require (Pinhole camera with unknown intrinsic) at least 6 3D/2D points. So by using 12 I assume that a camera pose is at least verified by 2 * MIN-REQUIRED-POINTS. It means that if a pose have 12 observations, the pose can be trusted.

Regarding the `openMVG_main_openMVG2openMVS` (avoid to copy images):
- we can't do that, since the binary is undistorting the images (see [here](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2openMVS.cpp#L95))
BTW, you will notice that if you have a camera that does not have distortion, the file will just be copied.  If you are in this case (file copy), since you are using rectified images, you can change the file copy to write a symbolic link (will be ok for UNIX systems).

BTW, I'm happy to discuss with you about scene filtering.
