### ISSUE TITLE
[software] update OpenMVS Interface in order to support OpenMVS file format versioning

### ISSUE THREAD

**Issue by cdcseacave** [openMVG/openMVG#869]
@pmoulon when you find some time, please update the Interface.h file with the latest version from OpenMVS cause I added .mvs file versioning. No need to change anything in the code. Thx!

**Comment by pmoulon** [comment]
Thx, I will do it.

**Comment by pmoulon** [comment]
@cdcseacave I tried to update but I'm sorry to say that I can't since the InterfaceMVS.h file does not compile on Linux.
- the file is not self contained. I mean it is using now code from other files.
- `_tcsncmp` is not a portable function
- `Eigen::Default` is not portable => EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION

Can you work a bit on it to make it self contained?

**Comment by cdcseacave** [comment]
@pmoulon thx, I fixed the non-portable function. `Eigen::Default` is portable however, as it is used only for `n==1`.

**Comment by pmoulon** [comment]
Does your new interface will still support the loading of the old .mvs project?

**Comment by cdcseacave** [comment]
yes

**Comment by cdcseacave** [comment]
hope it works now

**Comment by pmoulon** [comment]
Thanks, I will test it soon and keep you in the loop ;-)

**Comment by pmoulon** [comment]
- [ ] need to merge to develop
