### ISSUE TITLE
Question: functional position of pmvs versus DensifyPointCloud ?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#871]
Hello,
i used the standard reconstruction pipeline (global & incremental")  to the cmvs-pmvs.
Few minutes ago, i discovered DensifyPointCloud.

Could you please give few words on the differences between pmvs & DensifyPointCloud ?
Or how you combine them to get better result ?
Thank

**Comment by pmoulon** [comment]
They are using different method for the densification.
I mean PMVS produce a point cloud, CMVS-PMVS is producing a point cloud and then a mesh or a textured mesh.
Note that source of CMVS-PMVS are not released. So I would advise you to use and look to OpenMVS (in which you have the DensifyPointCloud binary)

In better understand the difference in term of densification (point cloud) you can have a look to the paper:

Yasutaka Furukawa and Jean Ponce. Accurate, Dense, and Robust Multi-View Stereopsis.

DensifyPointCLoud is based on:
Patch-Match algorithm: PatchMatch: A Randomized Correspondence Algorithm for Structural Image Editing C. Barnes et al. 2009.

PMVS is based on seed expansion in the set of view, rather than DensifyPointCloud build depth map that are merged and filtered.

**Comment by alvaro562003** [comment]
Thank you.

PMVS produces a point cloud: OK
My view of CMVS-PVMS  was that it produces point cloud only but it divides the image-dataset to run paralell PMVS and then gather all point cloud in one.
Was i wrong ?

Which one of PMVS or DensifyPointCloud does produce best result ?

**Comment by pmoulon** [comment]
I'm sorry I was referring to CMPMVS.

You're right CMVS is a method to divide a scene in a set of clusters on which you can run PMVS.

I cannot tell which one produce the best results, they are very similar. You can run experiments on your side on some dataset and make your own conclusion.
Note also that if you run DensifyPointCloud you can then generate the freespace mesh with ReconstructMesh.

**Comment by alvaro562003** [comment]
Sorry, i ignored the existence of CMPMVS.
Thank you i will look at it .
bye
