### ISSUE TITLE
Can OpenMVG be simpler to use?

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#874]
Although OpenMVG shipped with some utilities such as main_GlobalSfM. But it has limitation such as only accepting data format "SfM_Data" and it asked for image_describer, Features_Provider,and so on. All these make OpenMVG hard to use and lack of flexibility. 

For example, I want to use GlobalSfM and I know the corresponding pairs between images. I think this is enough and need not to do any computation such as image_describer, feature vectors. But I don't know how to use GlobalSfM for this simple case. I think The API of OpenMVG is not good.

**Comment by pmoulon** [comment]
The goal of OpenMVG is to provide accurate implementation of state of the art computer vision algorithms to the community.

On top of that some SfM pipelines are proposed.
Those pipelines use a common interface with abstract object for:
- feature extraction (Image_Describer)
- on disk features reading (Features_Provider)
- on disk matches reading (Matches_Provider)

**The goal of this abstraction is to allow the user to provide their own interface for their own data or to implement new version of the class in order to improve the results (a new image_describer for example).**

So if you have your data on disk (features, matches), just write your own data loader and let GlobalSfM run on that.

**You can say that the API is not good but I would like that you suggest an alternative.**
You sentence is very harsh towards all the OpenMVG contributors and efforts made by the community. 

I mean, if you try to use opensource solution this is because commercial solutions does not allow you to perform the task you need. So you look to open framework that let you the ability to tweak the things that you can't do in other software.

**Comment by alvaro562003** [comment]
@openMVG team & contributor : Thank you very much for your excellent job that set  "PHD level code" accessible to every one.

**Comment by caomw** [comment]
I think openMVG is very excellent Toolkit !
