### ISSUE TITLE
I can't reconstruct a simple apple 

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#881]
```
Hello,

I am trying to reconstruct a simple "apple on a table" as shown in the datasets attached :
[images3.zip](https://github.com/openMVG/openMVG/files/943081/images3.zip)
[image4.zip](https://github.com/openMVG/openMVG/files/943083/image4.zip)
[image5.zip](https://github.com/openMVG/openMVG/files/943080/image5.zip)
[images0.zip](https://github.com/openMVG/openMVG/files/943084/images0.zip)
[images1.zip](https://github.com/openMVG/openMVG/files/943082/images1.zip)

Using the incremental pipeline, the reconstruction is always incomplete
[pmvs_result.zip](https://github.com/openMVG/openMVG/files/943107/pmvs_result.zip).

I try several the following options:
- on openMVG_main_ComputeFeatures: HIGH/ULTRA
- on openMVG_main_ComputeMatches: r=0.5, 0.6 and 0.8
- on openMVG_main_IncrementalSfM: adjust_focal_length [ principal  or adjust_all

I think the issue is coming for the number of poses which is too  low. But i do not understand why.

Here is a part of the python coded used:
`
pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-c", "3"] )
pFeatures = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", os.path.join(matches_dir,"sfm_data.json"), "-o", matches_dir, "-m", "AKAZE_FLOAT", "-f" , "1", "-p", "HIGH" ,"-n",str(psutil.cpu_count(logical=False))], )
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", os.path.join(matches_dir,"sfm_data.json"), "-o", matches_dir, "-r", "0.5", "-g", "f", "-n", "FASTCASCADEHASHINGL2"] )
pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_IncrementalSfM"),  "-i", os.path.join(matches_dir,"sfm_data.json"), "-m", matches_dir, "-o", reconstruction_dir, "-f", "ADJUST_FOCAL_LENGTH|ADJUST_PRINCIPAL_POINT"] )
pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeSfM_DataColor"),  "-i", os.path.join(reconstruction_dir,"sfm_data.bin"), "-o", os.path.join(reconstruction_dir,"colorized.ply")] )
pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeStructureFromKnownPoses"),  "-i", os.path.join(reconstruction_dir,"sfm_data.bin"), "-m", matches_dir, "-f", os.path.join(matches_dir, "matches.f.bin"), "-o", os.path.join(reconstruction_dir,"robust.bin")] )
pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeSfM_DataColor"),  "-i", os.path.join(reconstruction_dir,"robust.bin"), "-o", os.path.join(reconstruction_dir,"robust_colorized.ply")] )
pMVG2PMVS = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_openMVG2PMVS"),  "-i", os.path.join( reconstruction_dir, "robust.bin"), "-o", reconstruction_dir , "-r", "1"] )
pmvs = subprocess.Popen( [ pmvsExec ,  os.path.join( reconstruction_dir, 'PMVS/' ), 'pmvs_options.txt' ])

`
```
Do you have an idea to investigate ?
Thank you

**Comment by rperrot** [comment]
There must be a difficulty regarding scale. 

Here are two captures of your set (using sequential pipeline with -m SIFT -p ULTRA) 
<img width="882" alt="capture d ecran 2017-04-20 a 18 16 07" src="https://cloud.githubusercontent.com/assets/6479700/25241240/8c7c689e-25f5-11e7-896d-2ea143a733c8.png">
<img width="614" alt="capture d ecru 2017-04-20 a 18 16 17" src="https://cloud.githubusercontent.com/assets/6479700/25241241/8c813bc6-25f5-11e7-9c2c-5cb851c04750.png">

as you can see, some images are very close to the apple and the others are far away. I think SIFT descriptors fail to match such huge difference in terms of scale. Maybe you can try to have intermediate images (between your far and close images), to help SIFT descriptor matching. 

I didn't try AKAZE descriptor yet on your set, it is generally known to provide more features, maybe it can help a little bit (try -m AKAZE_FLOAT instead of -m SIFT)

**Comment by alvaro562003** [comment]
I alaready used AKAZE_FLOAT/HIGH....same issue.
Indeed i  walk according 2 concentric circles around this apple. One circle was not enough. 
The best result was with one close circle.

Don't you think the issue is because of the symetry of the apple ?

**Comment by pmoulon** [comment]
It can be to the ambiguity (very similar looking from all the direction).
You can try to put a newspaper below your apple and try again (it will provide texture).

**Comment by alvaro562003** [comment]
Good idea ?
As the closer circle is at atmost 0.75 or 1meter from the apple, don't you think the theoritical focal value is right ?
Maybe 1 meter is too close for having good picture and there are deformation

**Comment by rperrot** [comment]
"Don't you think the issue is because of the symmetry of the apple ?" 

I don't know. Usually with organic subjects like that, there must exist enough dissymmetry, to avoid ambiguous match. 

I also note that in this case, the part of the apple that is not reconstructed is in the shadow (not exactly a shadow but in low light) moreover this region seams to have low texture and I think gradient should be low resulting in a zone with no or very few points. 

"Maybe 1 meter is too close for having good picture and there are deformation"

the issue is more a question of blur at close range (try to have a larger f-stop value in your camera to increase depth of field)

**Comment by alvaro562003** [comment]
@rperrot 
you are right. One half of the apple was exposed to hallogen light, and the other half was behind the curtain of a windows.
Do you think ColHarmonize could be useful ?

i do not understand what does it mean: ry to have a larger f-stop value
I am using an Iphone 6.  How can i do that ?

**Comment by alvaro562003** [comment]
@rperrot : what is your server/pc config...it seems so many time faster than my poor windows laptop?

**Comment by pmoulon** [comment]
1. ColHarmonize will not be useful, since I think some part of the apple is overexposed (we will not recover the apple color from saturated pixels (or from specular reflections))

2. You can try to make your Iphone photo sharper if you put your device on something stable (tripod, chair... the table)

**Comment by rperrot** [comment]
> i do not understand what does it mean: ry to have a larger f-stop value

This corresponds to reducing camera aperture in order to increase the zone where your subject is sharp (see point 3) for an example here : http://www.exposureguide.com/focusing-basics.htm). I don't know if it is possible on an iPhone (sometimes there's a menu or option for that but I don't know if it really corresponds to the true aperture). BTW, the idea is to have the apple in all the sharp zone (remember : the sharper, the better). 

>  One half of the apple was exposed to halogen light, and the other half was behind the curtain of a windows.

There are large difference in term of radiance between sun (even indirectly) and artificial light. Try to have only one kind of light (maybe artificial one is the easier to control). Try to avoid hard shadows (with small point lights or sun) because they may produces holes in your reconstruction, for this purpose maybe you could use a diffuser (even a sheet of paper could be helpful), or a reflector (http://www.wikiwand.com/en/Reflector_(photography)) 

> what is your server/pc config...it seems so many time faster than my poor windows laptop?

a macbook pro. Your set is small enough to be processed quickly.

**Comment by alvaro562003** [comment]
The result is far much better, the result go from 4 poses to 17 poses , i do the changes:
1) Newspaper on the table
2) Only sunlight, no home hallogen light
3) Maintain a greater distance  between apple and iphone (at least 1.5 meter)

I do the ops with AKAZE_FLOAT/HIGHT.

Now i will try with AKAZE_FLOAT/ULTRA.

Thank you again

**Comment by pmoulon** [comment]
You're welcome.
With the newspaper trick even SIFT/NORMAL or SIFT/HIGH must be ok.

On tiny dataset we can add the preset in the loop to have a more consistent set on matches, the overhead is tiny and really help to produce a more consistent point cloud to autocalibrate the distortion.

**Comment by pmoulon** [comment]
Please close the issue when the answer are satisfying.

PS: With AKAZE_FLOAT the ANNL2 matcher provide more accuracy (`-n ANNL2` on main_ComputeMatches).

**Comment by alvaro562003** [comment]
I improved the result by using 3 IPhone features: HDR, focus, exposure.
The main thing to take care was : Light
Thanks again
