### ISSUE TITLE
the reason why sfm cut some image in my image list

### ISSUE THREAD

**Issue by RemoteSensingFrank** [openMVG/openMVG#882]
I'd like to reconstruct my UAV image list, and the image list i used like:

![relative](https://cloud.githubusercontent.com/assets/25923674/25234502/d6211ed0-2614-11e7-8457-3e86972d4814.jpg)

but the final image list contain only:
![final](https://cloud.githubusercontent.com/assets/25923674/25234547/fdcd228a-2614-11e7-8b29-e2c236956a6e.jpg)

I wonder where can I change the parameter so that the final result can constain all images

**Comment by pmoulon** [comment]
Can you tell me which step have you used?
I mean I don't know if you show the graph at matching stage or at SfM stage.

Using more feature per images will allow you to have a denser graph.
Try the option `-p HIGH` on `main_ComputeFeatures`. Use a new directory or use `-f 1` else the previously feature will be read and used.

**Comment by RemoteSensingFrank** [comment]
Thanks for your reply, You mean that the problem due to less feature and 
matches? I try to describe the problem in detail. I wanna reconstruct 
the 3D model from my list of UAV images. And the images contain POS data 
in POS file, so I change the code slightly in my project.  First I list 
the images and compute the features and matches. It shows that two  
images nearby contained more than 1000 match pairs. But when I use 
Global_SfM to bundler adjust, the process remove some of the images. And 
I don't know where is the problem. Besides when I don't use the POS 
data, the result can contain all the images.


在 2017年04月21日 00:06, Pierre Moulon 写道:

**Comment by pmoulon** [comment]
> Thanks for your reply, You mean that the problem due to less feature and
matches?
Yes. I would advise your to compare the graph in the two configuration (normal pipeline and the one in which you add the POS data).

1. Not that GlobalSfM need triplet of images everywhere in the graph to work. In your case there is a weak point in the graph 12-13-14-15 that contains triplet but with less connections that certainly cause the problem.

2. Can you tell me what are the POS data? Do you mean X,Y,Z data. 
It seems like you try to reduce the number of image to matche to keep only the closest one.
If it's the case I would like to suggest you to use this POS data in the GPS field and so use the OpenMVG GPS tools to limit the image pair to matche to only the Xth closest.

See https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst

If you want to use the GPS prior:
1.modify the SfMInit_ImageListing in order to put your POS X,Y,Z data for each view
2. use openMVG_main_ListMatchingPairs to create the match pair file in order to limit the number of pair
3. provide the pair file to main_ComputeMatches
4. run GlobalSfM with the GPS mode

**Comment by RemoteSensingFrank** [comment]
Yeah! I write the GPS data into sfm_data.json and then use the cmd : 
openMVG_main_ComputeFeatures,  openMVG_main_ListMatchingPairs, 
openMVG_main_ComputeMatches, openMVG_main_GlobalSfM surprisingly the 
GlobalSfM works well.
I think there must be some problem in my code, I'll check my code. 
Thanksa lot!

在 2017年04月24日 01:44, Pierre Moulon 写道:

**Comment by pmoulon** [comment]
You can use the ConvertSfMData program to convert your sfm_data.json to a ply file in order to check your GPS position (blue dot). It will certainly help you to see if you made an error in the X,Y,Z data that you have setup.

Else perhaps you openMVG_main_ListMatchingPairs with a parameter -n X with X > 5.
