### ISSUE TITLE
openMVG_test_sfm_data_BA stalls on Travis gcc

### ISSUE THREAD

**Issue by bjornpiltz** [openMVG/openMVG#885]
openMVG_test_sfm_data_BA  should finish in less then a second, but has recently taken minutes when compiled with GCC. Clang and MSVC are unaffected.

https://travis-ci.org/openMVG/openMVG/jobs/224237276
63/69 Test #63: openMVG_test_sfm_data_BA .................................   Passed  112.44 sec

https://travis-ci.org/openMVG/openMVG/jobs/220134803
63/69 Test #63: openMVG_test_sfm_data_BA .................................   Passed  113.17 sec

https://travis-ci.org/openMVG/openMVG/jobs/215126827
62/68 Test #62: openMVG_test_sfm_data_BA .................................   Passed  501.61 sec

If it takes more than 600 seconds it leads to a build failure. That just happened to my PR here: https://travis-ci.org/openMVG/openMVG/jobs/224337239

Apparantly it wasn't the first time: https://github.com/openMVG/openMVG/pull/745#issuecomment-275079800

**Comment by pmoulon** [comment]
It's not related to your PR. It happens from time to time and I don't know why. Perhaps it's due to the travis container or the load on the travis side...

**Comment by bjornpiltz** [comment]
But, it's so specific. It happens only to openMVG_test_sfm_data_BA and only on GCC.

**Comment by pmoulon** [comment]
Perhaps it's due to https://github.com/openMVG/openMVG/blob/master/.travis.yml#L65 `-DSCHUR_SPECIALIZATIONS=OFF` that I use to make the compilation faster on travis.
The other thing is that is does not happens all the time, so it's not reproducible.
Moreover I never got the problem on my gcc even with this compilation option.

**Comment by bjornpiltz** [comment]
I added some diagnostic code: https://github.com/bjornpiltz/openMVG/commit/e329788aa56dfd9f7bc0002bc39254e7a039a7fb and it seems threading is the issue. Clang doesn't support openMP wheras gcc starts the solver with 32 threads.  See [GCC output](https://travis-ci.org/bjornpiltz/openMVG/jobs/228305556#L1636) vs [Clang output](https://travis-ci.org/bjornpiltz/openMVG/jobs/228305557#L1298). This is probably a problem with Ceres+CXSparse.

**Comment by bjornpiltz** [comment]
Confirmed. https://github.com/bjornpiltz/openMVG/commit/a238d32cad1511634e01914b6f2f18b2c07f80d2 fixes this. [GCC](https://travis-ci.org/bjornpiltz/openMVG/jobs/228327302#L936) vs [Clang](https://travis-ci.org/bjornpiltz/openMVG/jobs/228327303#L1124).

**Comment by pmoulon** [comment]
Thanks for the investigation.
Seems like it detects 32 threads on the virtual machine but using all of them is not a good idea since form time to time the VM must block depending of it's charge (I mean it block only from time to time).
Possible fix:
- set only on thread for OpenMP thanks to the command line before launching the unit test.
The pros: test will pass.
The cons: is that we will test only the behavior with one thread.

What is your opinion on it?

**Comment by bjornpiltz** [comment]
Starting 32 threads on the Travis server is a bad idea, no doubt, but there seems to be a bug in CXSparse which causes Ceres to not converge on a solution. Perhaps you should do something similar to  https://github.com/bjornpiltz/openMVG/commit/a238d32cad1511634e01914b6f2f18b2c07f80d2 as a workaround. 

And Adjust() should return false if max_iteration has been reached without convergence.

**Comment by pmoulon** [comment]
There is already a check in order to test if the solution is usable:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L434

Convergence in some case is not reached, but still the solution have been improved. So I would like to keep the actual test `summary.IsSolutionUsable()`

Regarding the thread, the easy temporary solution can be to set the OMP_NUM_THREADS to 1 in the VM command line.
But as you, I understand also that normally it should work and it seems that there is a multithread behavior between ceres and the linear algebra backend.

**Comment by pmoulon** [comment]
Made a test here with this [commit](https://github.com/openMVG/openMVG/commit/3942693b11f468cea9fd18b249d4bf18c72e6be4):
https://travis-ci.org/openMVG/openMVG/jobs/229023563#L1306

Time drop from 100s to 0.07s for the openMVG_test_sfm_data-BA.

Thanks for the investigation. I will merge to develop.

**Comment by bjornpiltz** [comment]
Thanks!
