### ISSUE TITLE
Blending map

### ISSUE THREAD

**Issue by tmac1002** [openMVG/openMVG#891]
Hi, I used some UAV images to generate sparse point. However, the result map seemed blending. I am very confused. I just have no idea why this happened. Could you help me explain this situation or what exactly reasons caused this results. Thank you very much!
![blend_image](https://cloud.githubusercontent.com/assets/11924213/25466119/f5ee296e-2b38-11e7-8d7d-568a73e7801d.JPG)

**Comment by pmoulon** [comment]
This problem is well known.
- It's due to camera translation and distortion that compensate each other.
See ref [1]
[1] Changchang Wu, "Critical Configurations for Radial Distortion Self- Calibration", CVPR 2014.
[paper](http://ccwu.me/file/radial.pdf)
[slides](http://ccwu.me/file/cvpr14_critical_talk.pdf)

If you want to avoid this problem:
- Use the precalibrated distortion (you can do that in OpenMVG by setting your camera intrinsic and then the SfM pipeline will use it)
- Or use a flight path on two different height in order to have more convergent ray in order to estimate the right distortion coefficient.

Please avoid to copy paste the message in different framework:
https://github.com/simonfuhrmann/mve/issues/336
https://github.com/colmap/colmap/issues/112
https://github.com/sweeneychris/TheiaSfM/issues/150

**Comment by tmac1002** [comment]
Thank you very much for your answering. I just want to ask different people to get maybe different kinds of answer. I will later avoid to do this. Thank you again.

**Comment by pmoulon** [comment]
Please close the issue if you have sufficient inputs regarding your questions.
I did not mean to say that it bad to ask at different place, but a single copy paste without citing the software that you have used does not allow us (all the SfM project) to provide you the best solution for your problem.
