### ISSUE TITLE
Sfm with init

### ISSUE THREAD

**Issue by appyhand** [openMVG/openMVG#900]
Hi Pierre,
First, congrats for this great software !
I am trying to use a calibrated camera setup using the steps you mentioned in #412 : 

0 run sequential pipeline on scene#1
1 use SfMInit with the images from scene#2
2 copy paste the intrinsics & extrinsics data from the SfM step of scene#1 inside the sfm_data.json file
do computeFeatures & computeMatches on the sfm_data.json file that you have produced
3 use openMVG_main_ComputeStructureFromKnownPoses on the produced files (matches of the scene scene#2)
It works but I noticed the number of tracks and thus the density of the point cloud is systematically much lower when using known camera poses compared to the same scene (scene#2) when letting openMVG compute the camera poses and refine it using the ComputeStructureFromKnownPoses step in the sequential pipeline.

Result with standard openMVG sequential pipeline on scene#2 :
[SfMStructureFromKnownPoses_Report_sequential.pdf](https://github.com/openMVG/openMVG/files/975410/SfMStructureFromKnownPoses_Report_sequential.pdf)
Result with the same scene (scene#2) when following the steps mentioned in #412 :  
[SfMStructureFromKnownPoses_Report_known_poses.pdf](https://github.com/openMVG/openMVG/files/975417/SfMStructureFromKnownPoses_Report_known_poses.pdf)
The cameras are firmly fixed on a rig so cameras setup is strictly the same between all scenes.

Any clues ?
Thanks !

**Comment by appyhand** [comment]
Could it be due to a slight inaccuracy in the camera poses estimated on scene#1 ?
In this case, what is the best way to tell openMVG pipeline to use the estimated camera poses as a starting point and refine them rather than use them as a fixed input ?
Thanks

**Comment by pmoulon** [comment]
Hi @appyhand,

Here some explanations:
- ComputeStructureFromKnownPoses is performing guided matching and then triangulate only the track that are at least on 3 images (see [here](https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/ComputeStructureFromKnownPoses.rst) for the pseudo code).
- Sequential SfM triangulate even tracks that are on 2 images.

=> That's explains the difference you have noticed.

1. Regarding the refinement of the scene:
- you will notice that if you use the option `-b` on `main_ComputeStructureFromKnowPoses` a BA will be done.

2. I can work on update main_ComputeStructureFromKnowPoses in order to take a matching file and robustly triangulate the tracks. 
- Does it sounds good and interesting for you?
- It was the idea behind this issue https://github.com/openMVG/openMVG/issues/530

**Comment by appyhand** [comment]
Hi Pierre,

Thanks for your prompt answer.
Ok, I understand why there are fewer tracks now, that makes perfectly sense, I missed this difference in the doc.
I've already tried the BA step with -b and also tried to relax the reprojection error criteria with -r, this obviously increases the number of tracks but has other drawbacks of course...

Yes, your proposal would suit my needs, it would be great if you could add this feature.
Thanks a lot !

**Comment by pmoulon** [comment]
@appyhand I found the time to implement your request:
- the feature is available in the branch `develop_ComputeStructureFromKnownPoses_matchfile_triangulation` for testing

Waiting your feedback on it :smile:

**Comment by appyhand** [comment]
@pmoulon : direct triangulation works as expected on reference dataset. Thanks for adding this feature.

**Comment by pmoulon** [comment]
The feature is now integrated in the master branch under the OpenMVG v1.2.

Thank you for your feedback.
