### ISSUE TITLE
Adding variance/covariance matrices

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#904]
Pierre,

I am looking at generating variance/covariance matrices from the adjustment.
1. Produce a-posterior SD's on the pose as a quality assessment
2. Produce a variance/covariance matrix on the intrinsics (then into a correlation matrix.
    This is to to check for any correlation on intrinsic parameters which would indicate that not using the best camera model.

I have made good progress on this but have one question.
1. I have modified the Bundle_Adjustment_Ceres::Adjust function by adding the variance/covariance generation at the end of the adjustment.
2. Unfortunately this gets called after every pass and slows the program down.

Is there anyway to determine when the adjustment has completed its final pass so I only calculate this once ?

I am making good progress in understanding your data structures and work flow. So I am happy to share this code back to your group once it is working (I modified the sfm_data structure to store variance/covariance data). That is if any considers it useful

Alan

**Comment by pmoulon** [comment]
I would suggest two option:
- you can add a boolean option to the BundleAdjustment framework that will enable or disable the computation of the variance/covariance information.
- write a new derived class that will compute variance/covariance data of a sfm_data scene.

In order to know if it's the last BA or not:
- You can write a new binary that will compute the variance/covariance on a existing sfm_data scene. This way you avoid the fact to know or not if your BA is the last one or not
- If you want to do it in the process:
  - Incremental SfM:
    - You can check is there is no longer new view to add, and at this moment configure the variance/covariance computation
  - Global SfM:
   - You know the place where the last BA is performed.

We would be really happy if you cam share back any result and code

**Comment by hcjghr** [comment]
Hi,

if I can add my two cents here. Can I ask @bigakoz which approach are you planning to use to estimate the covariances? And you are just thinking of doing it on poses or also on the structure?

@pmoulon Would it be possible to add into the sfm_data structure the structures for covariance matrices for:
- features 
- poses
- landmarks

I'm asking you this because it would be great to have this unified and done in a way that would  provide compatibility with previous sfm_data structure. It will also make it much easier to then incorporate any development of the uncertainty estimation modules.

Cheers

**Comment by pmoulon** [comment]
Closed due to inactivity.
@hcjghr Feel free to reopen it
