### ISSUE TITLE
OpenMVGConfig.cmake incomplete with Visual studio

### ISSUE THREAD

**Issue by bjornpiltz** [openMVG/openMVG#907]
After building and installing openMVG, I include it in my project like this:
```
find_package(openMVG)
target_link_libraries(myproject ${OPENMVG_LIBRARIES})
```
and I got the following errors:
1: `LINK : fatal error LNK1104: cannot open file 'Threads::Threads.lib'`
It seems https://github.com/openMVG/openMVG/commit/73e990c2b6b7d3dc16a706b92be7c64d7be0984f introduced the dependency Threads::Threads, which is unnecessary, at least on Windows.

2: Missing vl_sift symbols.
There is no line `target_link_libraries(openMVG_features vlsift)`. Is this an oversight, or is there some legal reason for this?

**Comment by pmoulon** [comment]
Hi @bjornpiltz 

1. I'm aware of this and I need to fix it properly.
I think thread will be required (at least on unix system) if you use the brute force nearest neighbor framework (use of thread and future). We have to double check.

2. You're right, I did not include vlsift by default to the openMVG libraries since SIFT is under patent.
Vlsift code must not be necessary by default when using OpenMVG as third party.
If a user want to use it, if have just to include the lib `vlsift` since it is exported as an openMVG-targets lib.
https://github.com/openMVG/openMVG/blob/develop/src/nonFree/sift/CMakeLists.txt#L29

**Comment by bjornpiltz** [comment]
1. Ok, but when you do implement that - you can use `<thread>` and `<future>`, right? Since C++11 is required anyway. I don't see what `find_package(Threads)` is contributing right now. Correct me if I'm wrong. At the very least, we need to remove the line `target_link_libraries(openMVG_matching ... Threads::Threads)` under Windows.
2. I see.

**Comment by pmoulon** [comment]
1. Seems like Linux backend for std::thread implementation is pthread. That's why find_package(Threads) is required.
Seems like gcc and clang are using posix thread model by default:
http://stackoverflow.com/questions/11784153/in-g-is-c-11-thread-model-using-pthreads-in-the-background
See the output of:
`g++ -v`
You will see
`Thread model: posix`

We need to check for windows (Visual Studio).

**Comment by bjornpiltz** [comment]
I see the problem with threads now. OpenMVGTargets.cmake links `openMVG_matching` to `Threads::Threads`, but `find_package(Threads)` hasn't been called when invoking OpenMVGTargets.cmake, so the target `Threads::Threads` is not defined.

A workaround is:
```
find_package(Threads) 
find_package(openMVG)
target_link_libraries(myproject ${OPENMVG_LIBRARIES})
```

It would probably be better if openMVConfig.cmake called find_package(Threads) for you.

**Comment by pmoulon** [comment]
@bjornpiltz 
I made an experiment yesterday (removing pthread link in order to show the different behavior on the CI)

UNIX -> Clang: NOK -> [`undefined reference to pthread_create`](https://travis-ci.org/openMVG/openMVG/jobs/230217845#L1217)
UNIX -> GCC: OK
MacOs -> Apple LLVM version 8.0.0 (clang-800.0.42.1): OK
Windows -> Visual Studio 14 2015 Win64: OK

I think it's safer to include it all the time (since it was working sooner).
But for sure we need to work on a workaround in order to have Threads::Threads defined.
I wonder if we include this lib as PUBLIC if it will still require to make the `find_package(Threads)`

**Comment by bjornpiltz** [comment]
You should definitely keep it on non-Windows platforms, but I don't think you need to keep it on Windows. [Ceres doesn't seem to think so either. ](https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L434-L440) There is no equivalent to pthreads on Windows. Threads and mutexes are part of the standard library.

**Comment by pmoulon** [comment]
Must be solved now.
