### ISSUE TITLE
sample SfM_SequentialPipeline.py fails on SceauxCastle DataSet

### ISSUE THREAD

**Issue by Tooine** [openMVG/openMVG#920]
`python SfM_SequentialPipeline.py /Users/abarrier/Documents/Scolaire/ENS/L3/Cours/Stage/openMVG/src/openMVG_Samples/imageData/ImageDataset_SceauxCastle-master/images /Users/abarrier/Desktop/test`

On MacOS 10.12.5, this command fails with this output: https://pastebin.com/eAfVFv9w

**Comment by pmoulon** [comment]
1. I see that you changed the script in order to use `AKAZE_FLOAT`.

2. When you use AKAZE_FLOAT you will have better result if you use `-n ANNL2` in `main_ComputeMatches`.

=> Can you please update the script to use ANNL2 matcher and launch your experiment again?
- please use a new directory as output to be sure that no previous data will be reloaded.

**Comment by Tooine** [comment]
Well, it is now working ! Thanks !

**Comment by pmoulon** [comment]
Please close the issue since we solved the problem.

PS: CASCADE_HASHING can also work with SURF like descriptor but actually it is tuned to work best for SIFT like descriptors.
