### ISSUE TITLE
why use ROTATION_AVERAGING_L2 as default in global rotation computation

### ISSUE THREAD

**Issue by shuguohui** [openMVG/openMVG#937]
when the image count is large(more than 5000),i found that the global rotation computation use ROTATION_AVERAGING_L2 is very slow,but use ROTATION_AVERAGING_L1 is fast.
so my question is :why use ROTATION_AVERAGING_L2 as default in global rotation computation?is there some weaknesses for ROTATION_AVERAGING_L1?

**Comment by pmoulon** [comment]
Hi @shuguohui 
It's simply because most of the time I observed that the ROTATION_AVERAGING_L2 method was giving me a better initial estimates for the rotation rather than the ROTATION_AVERAGING_L1 (I must admit that I still dislike that the L1 rotation averaging is starting for a MST). Ideally I would prefer having a global optimal minimization....

But since the rotation_averaging method is a command line parameter, feel free to choose the one that fit your needs.

On my side I prefer to consider that this problem "robust large scale rotation averaging" is not yet solved
- K. Wilson, D. Bindel, and N. Snavely, **When is Rotations Averaging Hard?** ECCV 2016. http://www.cs.cornell.edu/~bindel//blurbs/rotavg.html
- Anders Eriksson, Carl Olsson, Fredrik Kahl, Olof Enqvist, Tat-Jun Chin. **Why Rotation Averaging is Easy** 2017 https://arxiv.org/abs/1705.01362

**Comment by shuguohui** [comment]
ROTATION_AVERAGING_L2 can speed up by MKL,(when not use MKL,the cpu use only 10%,and use MKL,the cpu use more than 50%),in 10000 images test,use MKL is speed up 3-4 times

**Comment by pmoulon** [comment]
Using a Sparse Eigen value computation could made the thing faster and less memory hungry. Spectra library -> https://github.com/yixuan/spectra

**Comment by pmoulon** [comment]
@shuguohui Any help to port the L2 code to use Spectra?

**Comment by pmoulon** [comment]
Closed due to inactivity.
@shuguohui Feel free to reopen if you are willing to help
