### ISSUE TITLE
Commercial use?

### ISSUE THREAD

**Issue by mrgloom** [openMVG/openMVG#941]
Can openMVG be used for commercial use? Seems at least SIFT is patented, but maybe it can be replaced with something like FAST etc.

**Comment by pmoulon** [comment]
Yes the project is licensed under the MPL2 that allow commercial usage.
See [here](https://choosealicense.com/licenses/mpl-2.0/)

In order to use OpenMVG in a context free patent you must not use SIFT. Note that OpenMVG already provide an AKAZE implementation, but you can also plug easily any OpenCV feature/descriptor.

You must also ensure that ceres-solver is used without GPL component (some ceres 3rd party library can by GPL) (already done for you in OpenMVG).

**Comment by mrgloom** [comment]
Seems github can strore licence in some more readable format like here:
https://github.com/OpenDroneMap/OpenDroneMap/blob/e827c524ac41e83adda9acb2fbac4a15cfef10f8/LICENSE
https://help.github.com/articles/licensing-a-repository/#disclaimer

**Comment by pmoulon** [comment]
I know, I must update it.
It will be done for the next release.

**Comment by RamadanAhmed** [comment]
Hi,
Is using openMVG as third party can be disclosed or should be open to the public
