### ISSUE TITLE
Given Pipeline: Double estimation of epipolar geometry?

### ISSUE THREAD

**Issue by MaXL130** [openMVG/openMVG#945]
Hi openMVG-team,

I was going through the openMVG pipeline and noticed, that in [main_ComputeMatches](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L388), there is geometric filtering. Basically the epipolar geometry of the image pairs of the putative matches is calculated, so the epipolar constraint can be evaluated. (Am I right?)
Later on, in [main_IncrementalSfM](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_IncrementalSfM.cpp), there is another estimation of the Essential-matrix for the initial pair ([here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L112)), and afterwards there is 2D-3D resection for adding new images ([here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L126)).

My question: Is there a reason that the estimated geometry is not saved? Or is it just because those executables are programmed to also run separately?

Thanks for your help, Max

**Comment by pmoulon** [comment]
Hi,
As you said the binaries can be run separately.
- I don't save the epipolar geometry because they are fast to compute, and since the input matches for some user can be provided by other means I don't want to force them to provide also additional data.

You will note that if you provide the initial pair to the IncrementalSfM pipeline only the Essential-matrix will be estimated for this pair

Moreover, it's not because you found a FMatrix for a pair that the Ematrix will be valid. I mean you can find a Ematrix but then when you check the depth of the points or the relative angle between the image you can detect that the pair is degenerate. That's why I prefer to compute things on the fly.
You will also note that I compute the Essential-matrix only for the pair that have been validated with a Fmatrix (so I do not test all the pair, some filtering have been already done).

Hoping it answer to your question.

**Comment by MaXL130** [comment]
That perfectly answers my question, thank you very much! :)
