### ISSUE TITLE
Implementation of global rotation estimation

### ISSUE THREAD

**Issue by WBigNose** [openMVG/openMVG#950]
For global SfM, the false relative pairwise rotations are detected by verifying triplet of relative rotations. It's not agree with the paper[1] ?

[1] Moulon Pierre, Monasse Pascal and Marlet Renaud. ICCV 2013. Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion.

**Comment by pmoulon** [comment]
Since the bayesian method from " Disambiguating visual relations using loop constraints. CVPR, 2010." does not scale well with complex graph so I decided to implement a simpler scheme for the detection of relative rotation outliers. On many dataset I saw that the triplet filtering was sufficient to deal with the gross outliers.

Feel free to propose help to implement it back if you want it.

**Comment by WBigNose** [comment]
Thanks for your answer.

**Comment by WBigNose** [comment]
Thanks for your answer.
