### ISSUE TITLE
openMVG Query

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#969]
Pierre,

I attended a meeting today and showed them some results I have produced with openMVG. I thought they were impressive.

Anyway the feedback I received was as follows.

Feedback 1.       incremental SfM (as implemented in openMVS) generally produces an inferior AT solution to a simultaneous adjustment model.

My opinion is the model is built incrementally but the BA is actually global (uses all parameters and observations). I believe the results are comparable to other methods. Is my assumption correction ?

Feedback 2. Most SfM solutions will start to become unstable with 200mm focal length lenses.  

Any opinion on that ? I can see why it would become unstable ?

Alan

**Comment by rjanvier** [comment]
Hello,
sorry to hijack the thread
Feedback 1 => are you talking about openMVS or openMVG? I'm afraid to not understand the question correctly. In incremental SfM there were usually local and global BA.
Feedback 2 => http://www.isprs.org/proceedings/XXXVIII/part5/papers/110.pdf. narrow FOV could be an issue with long focal lengths. As a rule of thumb you should always mix long focal length lenses with short focal length lenses on the same scene (no ujsing only long focal length).
Romain

**Comment by bigakoz** [comment]
Openmvg


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Romain Janvier <notifications@github.com> Date: 05/07/2017  21:06  (GMT+08:00) To: openMVG/openMVG <openMVG@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Author <author@noreply.github.com> Subject: Re: [openMVG/openMVG] openMVG Query (#969) 
Hello,

sorry to hijack the thread

Feedback 1 => are you talking about openMVS or openMVG? I'm afraid to not understand the question correctly. In incremental SfM there were usually local and global BA.

Feedback 2 => http://www.isprs.org/proceedings/XXXVIII/part5/papers/110.pdf. narrow FOV could be an issue with long focal lengths. As a rule of thumb you should always mix long focal length lenses with short focal length lenses on the same scene (no ujsing only long focal length).

Romain

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openMVG/openMVG","title":"openMVG/openMVG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openMVG/openMVG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rjanvier in #969: Hello,\r\nsorry to hijack the thread\r\nFeedback 1 =\u003e are you talking about openMVS or openMVG? I'm afraid to not understand the question correctly. In incremental SfM there were usually local and global BA.\r\nFeedback 2 =\u003e http://www.isprs.org/proceedings/XXXVIII/part5/papers/110.pdf. narrow FOV could be an issue with long focal lengths. As a rule of thumb you should always mix long focal length lenses with short focal length lenses on the same scene (no ujsing only long focal length).\r\nRomain"}],"action":{"name":"View Issue","url":"https://github.com/openMVG/openMVG/issues/969#issuecomment-313097360"}}}

**Comment by bigakoz** [comment]
I am not familiar with other Sfm software but assume that they create a model by adding individual bundle adjustments and are therefore subject to drift in the solution.

From my understanding of openMVG. it continually does a full readjustment as views are added which should mean there is no systematic drift in the solution. But I may be wrong.

The solutions I have generated certainly don't have any systematic errors present. I just processed 750 aerial images (10,000' flying height) and checked against ground survey and the results where within 100mm in 3D. This is better  than most commercial photogrammetric software.

I would just like to be able to reply with an intelligent answer. People often make statements that they can't support

**Comment by hcjghr** [comment]
Hi,

a bit of how I understand things. Of course its possible that my reasoning is not right:) 

The SfM in openMVG is either global or sequential (although the binary is called Incremental). 

Global BA:  all the camera poses are estimated followed by the estimation of the 3D points and finally a global BA optimizing all the parameters simultaneously

Sequential BA: Cameras and 3D points are estimated sequentially (not necessary in the order in which the images were acquired) by introducing new set of images to the reconstruction. After each (small) set of images is added (together with newly triangulated points) a global BA over all parameters estimated up to that moment is performed. **Points with high reprojection error are removed.**

This makes the sequential BA in OpenMVG more prone to drift (bending) especially when the dataset consists of long transects and no navigation information is used. 

Why?

As observations (features) are added to the optimization process as they come (when new images are introduced) not all "restrictions" observed by the whole set of images is taken into account at every step of the optimization (which is the case for globalBA). Features themselves sometimes do not give enough information to restrict the reconstruction and "bending effect" can occur. When this happens and we want to introduce a new image to the model, the reprojection error of such bended points might go beyond the limit and such points are removed instead of used with new images to correct the drift ( e.g. loop closure). 

The global BA is for that reason more accurate but requires a lot more connections between the images due to the way the pose of the cameras are computed. If you have datasets where you dont have long transects (next image only sees area from a small set of previous images) then I dont think you will have a big problem with drift even with sequentialBA.

Hope it helps.

**Comment by pmoulon** [comment]
Hi @bigakoz 

> Feedback 1. incremental SfM (as implemented in openMVS) generally produces an inferior AT solution to a simultaneous adjustment model.

Did the people that gave you this comment gave you arguments in order to support their critics?
- it would help to understand what they mean by 'inferior' AT results. (having a 10cm precision according the flight height seems indeed quite good).

As @hcjghr said it, GlobalSfM and Incremental/Sequential SfM can meet some trouble with some specific scene. I would like to say that often if you provide the accurate calibration (focal, pp and distortion) they both work as good (since new points that will be added during the sequential SfM will not be rejected by accident).

Note: In order to get back that potential rejected points you can now use `ComputeStructureFromKnownPoses` in order to triangulate the whole geometric matches and then run a BA.


> Feedback 2. Most SfM solutions will start to become unstable with 200mm focal length lenses. Any opinion on that ? I can see why it would become unstable ?

Large focal length are dangerous since a tiny variation of the parameter can give large impact for the residual error. As @rjanvier said, mixing the dataset with other focal length or using an existing fixed precalibration can help to stabilize the results. You can set the focal as fix and then release it in a final BA performed in `ComputeStructureFromKnownPoses`.

So here my comments:
1. Please ask them some arguments in order to support their critics. Regarding the flight height the accuracy seems really decent.
2.You can use the metaphor about the "
lever arm". The larger the lever arm is, the tiniest change can have a huge impact on the other side ;-). The other thing is that when you are using a large focal length the pinhole camera geometry starts to be close to an orthographic projection (since the flight height is huge and the ground is far away).

**Comment by rjanvier** [comment]
some complementary tricks with long focal lenght. 
as stated by @pmoulon 
> Large focal length are dangerous since a tiny variation of the parameter can give large impact for the residual error

try to avoid grouping into a shared intrinsic long focal length camera if you know some parameters vary across time. For example if you use auto focus (which should not be the case in an aerial survey) it could have a uge impact on your final result. 
With long focal length lenses, you could use less complex distortions models than with short ones (Radial 1 could be ok).

> and checked against ground survey and the results where within 100mm in 3D. This is better than most commercial photogrammetric software.

the big selling points of commercial software are integration and speed optimization. A lot of them use a lot of free lib under the hood (ceres, cgal, opencv, Poisson Reconstruction...) and are not as state of the art than openMVG or other open source SfM libs/software in some of their aspects.

**Comment by bigakoz** [comment]
Thanks Pierre,

This all started because I had an issue with the registration of the model onto the datum.

When I transform the model on to my ground control the results are at the sub 20cm level.

However when I do the registration with the supplied sky control I see a translation and rotation issue. When I look more closely at the sky control residuals the errors are very large (well over a metre).

It was clear to me that I wasn't supplied a post processed GPS file.

However the people I was dealing with called int question my sFm processing !

Thanks for your response as I was able to frame a reasonably intelligent responseto put them back in their boxes.

**Comment by pmoulon** [comment]
Do you think we answered to all of your worries?
If yes, please close the issue ;-)

**Comment by bigakoz** [comment]
Yes thank you


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Pierre Moulon <notifications@github.com> Date: 06/07/2017  14:02  (GMT+08:00) To: openMVG/openMVG <openMVG@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Mention <mention@noreply.github.com> Subject: Re: [openMVG/openMVG] openMVG Query (#969) 
Do you think we answered to all of your worries?

If yes, please close the issue ;-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openMVG/openMVG","title":"openMVG/openMVG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openMVG/openMVG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmoulon in #969: Do you think we answered to all of your worries?\r\nIf yes, please close the issue ;-)"}],"action":{"name":"View Issue","url":"https://github.com/openMVG/openMVG/issues/969#issuecomment-313304002"}}}
