### ISSUE TITLE
Are the datasets in paper all available now ?

### ISSUE THREAD

**Issue by kealennieh** [openMVG/openMVG#972]
Dear authors:
    Are the datasets in your paper all available now? I can only find the Strecha dataset, since its paper was cited in your paper.  What about other datasets? such as, Orangerie dataset, Opera dataset . 

By the way, I'm a little bit confused about the defination of Accuracy in your paper. Can you explain it more.  Thanks in advance !

**Comment by rperrot** [comment]
Could you please tell us what paper are you talking about ?

**Comment by pmoulon** [comment]
Hi @kealennieh 

> Definition of Accuracy in your paper

Comparison of the distance of the computed scene to the GT.
1. 7DoF registration (rigid registration) to the GT of the computed scene
2. Computation of the distance (camera centers, and pointing error (angular errors))

Since OpenMVG is open Source you can see the code by yourself ;-)
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/tools_precisionEvaluationToGt.hpp#L102

> Orangerie dataset, Opera dataset.

Those dataset was captured by myself.
If you want them I can share then, please write a request to: openmvg-team[AT]googlegroups.com

**Comment by pmoulon** [comment]
Closed due to inactivity.
@kealennieh
